### PR TITLE
Appcompat update

### PR DESCRIPTION
**Pull request by vishalduggal**
This PR does a few things
1. Fixes bug reported in [TIMOB-16854](https://jira.appcelerator.org/browse/TIMOB-16854)
2. Updates appcompat module to version 19.1 of support library
3. Overlay now ignores call to take picture if system reports camera is out of focus

### CODE REVIEW

**Comment by alexgbernier** [comment]
On SDK 4.0.0.RC, calling Ti.Media.takePicture() on camera with overlay, and "Unable to focus" event, app becomes unresponsive.

**Comment by ingo** [comment]
@alexgbernier could you please file a ticket for that?

**Comment by alexgbernier** [comment]
Will do. Working on it right now.

**Comment by alexgbernier** [comment]
While making the test case, seems like the "Unable to focus" could have been a red herring. Trying to find some reliable steps to reproduce the ANR on takePicture.

**Pull request merged**
