### PR TITLE
[TIMOB-9680] Fix Android: TextField focus/blur

### PR DESCRIPTION
**Pull request by maggieaxway**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-9680

Expected: to achieve same behaviour as iOS

**Test case:**

````js
var win = Ti.UI.createWindow({backgroundColor : 'gray', layout: 'vertical'});

    tf = Ti.UI.createTextField({
	    value: 'text'});



    btn = Ti.UI.createButton({title: 'focus'});
    btn2 = Ti.UI.createButton({title: 'blur'});


    btn.addEventListener('click', function() {
        tf.focus();
    });

    btn2.addEventListener('click', function() {
            tf.blur();
        });

win.add(tf);

win.add(btn);
win.add(btn2);

win.open();

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

The `focus` & the `blur` method works as expected.

Studio Ver:     4.10.0.201709271713
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.10
Appc CLI:       6.3.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.7
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

**Comment by mukherjee2** [comment]
@garymathews @jquick-axway this PR is ready for CR, can one of you please CR?

**Review by jquick-axway — APPROVED** [review]
CR: Pass

Setting the focus to the root view (which isn't editable) is the best way to go. The focus has to be assigned somewhere.

**Comment by lokeshchdhry** [comment]
@garymathews , @jquick-axway , Can any one of you please resolve the conflict if you have time.

**Comment by jquick-axway** [comment]
Closing since this PR's remote branch appears to have been deleted, which is preventing us from updating and resolving merge conflicts. A new branch was created on my remote repo.

New PR with @maggieaxway and my changes can be found here:  PR #9607

**Pull request closed without merging**
