### PR TITLE
fix(android): fix copying of resources

### PR DESCRIPTION
**Pull request by garymathews**
- Relocate `removeOldFiles` to before new resources are copied over
- Remove unnecessary `setImmediate` call
- Do not symlink a symlink when linking the `appicon.png`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26824)

### CODE REVIEW

**Review by sgtcoolguy — APPROVED** [review]
LGTM, but may want @cb1kenobi to take a peek too?

Sounds like you have confirmed it fixes the issue locally, though.

**Comment by garymathews** [comment]
At the moment, I seem to be the only one that has ran into this issue. I'm not sure if it's exposed due to having a fast SSD. If I delete my `build` folder and build I can consistently reproduce this issue.

**Comment by janvennemann** [comment]
@garymathews These changes are making it hard to implement #10805 for Android. 

The `removeOldFiles` step removes all files in the `lastBuildFiles` map. This map is generated at the beginning by the builder and then the individual steps modify it to control which files to remove. Moving `removeOldFiles` to the top has rendered this logic pretty much useless and almost all files will be deleted now.

**Comment by m1ga** [comment]
I think this PR might be the source for https://jira.appcelerator.org/browse/AC-6360 I see random files not appearing in my resources folder/APK.

**Pull request merged**
