### PR TITLE
feat(android): app-bundle support

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26434

**Summary:**
Building an Android app for "production" will now generate a `*.aab` Android App Bundle file in addition to the `*.apk` file.

**Note:**
An app-bundle cannot be installed/ran on an Android device. It is a "publishing format" only supported by the Google Play app store. When uploaded, Google Play will generate multiple APK files split by CPU architecture and image density.

**Test:**
1. Launch Appcelerator Studio.
2. Create or open an existing Titanium app project.
3. Click on the project in the "Project Explorer" panel in studio.
4. Click on the left-most drop-down box in the toolbar and select "Package".
5. Click on the drop-down box to the right and select "Android Play Store".
6. Click on the left-most [>] run button on the toolbar.
7. A "Distribute" dialog window will appear.
8. Enter a "Distribution Location" the app's release files will be built to.
9. Enter the keystore info to digitally sign the app with.
10. Click on the "Publish" button.
11. When the build finishes, go to the "Distribution Location" directory.
12. Verify that 2 files were created. An `<AppName>.apk` and `<AppName>.aab` file. _(The AAB file is the app-bundle.)_
13. Verify that you can upload the `*.aab` and keystore to Google Play without error.

### CODE REVIEW

**Comment by hansemannn** [comment]
Pull request feedback (to not spam the JIRA ticket and all it's watchers):
- [x] We migrated our whole project to work with Gradle (assets, libraries, manifest)
- [x] We were able to build an AAB file successfully
- [ ] The upload to Google Play failed so far, because the `versionCode` seems to be hard coded

**Comment by jquick-axway** [comment]
Thanks for the feedback @hansemannn. I'll take a look at that in about 2 weeks. On our end, we probably have to remove the `versionCode` from the generated `./build/android/app/build.gradle` file because it sounds like the "AndroidManifest.xml" file's versionCode is not taking priority.

There is an easier work-around. In your app project, create a `./platform/android/build.gradle` file and set `versionCode` there. This will override all of our generated gradle settings.

**Review by garymathews — APPROVED** [review]
LGTM!

**Comment by ssekhri** [comment]
FR Passed. Creating a production build for a project created a .apk and .aab file. The app bundle uploads successfully on play store.
Verified on:
Mac OS: 10.15.1
SDK: 9.0.0.v20200128085643
Appc CLI: 7.1.2
JDK: 11.0.4
Node: 10.16.3
Studio: 6.0.0.201911251516

**Comment by hansemannn** [comment]
Please note that APK builds created with SDK 9 currently fail to be uploaded to common beta distributions like Firebase app distribution, which could lead to an issue.

**Comment by SquirrelMobile** [comment]
@jquick-axway I need to generate an unsigned Android App Bundle. To do this, do i need to add these line : 

```
await gradlew.bundleRelease('app');
this.aabFile = path.join(this.buildDir, 'app', 'build', 'outputs', 'bundle', 'release', 'app.aab');
```

in android/cli/commands/_build.js file in line 3772 here https://github.com/appcelerator/titanium_mobile/pull/11407/files#diff-c5b02bc76af40eccf082f63f6da1ec91R3772 ?

**Pull request merged**
