### PR TITLE
fix(android): autoFocus causing crash on some versions of Android

### PR DESCRIPTION
**Pull request by harnk**
- Refactor `Ti.Media.takePicture` auto-focus callback
- Prevent auto-focus related crashes on older Android verions

##### TEST CASE
```JS
const overlay = Ti.UI.createView({});
const takePicture = Ti.UI.createButton({ title: 'Take Picture' });

takePicture.addEventListener('click', _ => {
    Ti.Media.takePicture();
});
overlay.add(takePicture);

function showCamera(e) {
    Ti.Media.showCamera({
        success: e => {
            if (e.success) {
                console.log('Taken picture successfully!');
            } else {
                console.error(JSON.stringify(e, null, 2));
            }
        },
        saveToPhotoGallery: true,
        autohide: false,
        overlay: overlay,
        mediaTypes: [ Ti.Media.MEDIA_TYPE_PHOTO ]
    });
}

if (Ti.Meda.hasCameraPermissions()) {
    showCamera();
} else {
    Ti.Media.requestCameraPermissions(e => {
        if (e.success) {
            showCamera();
        }
    });
}
```
[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27742)

### CODE REVIEW

**Comment by harnk** [comment]
Crash Details: E/TiExceptionHandler: (main) [55,37938] autoFocus failed
    
        android.hardware.Camera.native_autoFocus(Native Method)
        android.hardware.Camera.autoFocus(Camera.java:1308)
        ti.modules.titanium.media.TiCameraActivity$2.onAutoFocus(TiCameraActivity.java:735)
        android.hardware.Camera$EventHandler.handleMessage(Camera.java:1161)
        android.os.Handler.dispatchMessage(Handler.java:102)
        android.os.Looper.loop(Looper.java:135)
        android.app.ActivityThread.main(ActivityThread.java:5254)
        java.lang.reflect.Method.invoke(Native Method)
        java.lang.reflect.Method.invoke(Method.java:372)
        com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
        com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)

**Comment by garymathews** [comment]
Thanks @harnk! I've pushed a few minor changes to address another similar issue.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Review by ssjsamir — APPROVED** [review]
**FR Passed:** Autofocus no longer causing crashes on a variety of devices/android versions.

**Environment**
```
MacOS Catalina: 10.15.1 beta
Xcode: 11.3
Java Version: 1.8.0_131
Android NDK: 21.1.6273396-beta2
Node.js: 10.16.3
""NPM":"5.0.0-1","CLI":"8.0.0-master.10""
Pixel xl (7.1.1) 
Nexus 60(8.0)
Pixel XL (10)
Samsung Galaxy S4 (5.1)
```

**Pull request merged**
