### PR TITLE
[TIMOB-15443](3_5_X) enable proxies to get window/tabgroup activity lifecycle events

### PR DESCRIPTION
**Pull request by hieupham007**
Testing steps in JIRA

### CODE REVIEW

**Comment by mokesmokes** [comment]
@hieupham007 just note that my PR had another commit to make this complete, see https://github.com/appcelerator/titanium_mobile/pull/6179/commits for the onCreate/PrepareOptionsMenu. Thanks!

**Comment by ingo** [comment]
@mokesmokes thanks! @pingwang2011  can you please review, but DO NOT MERGE to 3.5.X yet?

**Comment by mokesmokes** [comment]
Facebook module users will appreciate this backport... thanks :+1:

**Comment by hieupham007** [comment]
@mokesmokes, hmm I'm not seeing that commit in https://github.com/appcelerator/titanium_mobile/pull/6272. Do you remember which PR has it? Thanks,

**Comment by pingwang2011** [comment]
CR & FR. Passed.

**Comment by hieupham007** [comment]
merging

**Comment by mokesmokes** [comment]
@hieupham007 @ingo this PR seems to be missing from the 3.5.1.RC release notes. It would be helpful to mention the Facebook module https://github.com/mokesmokes/titanium-android-facebook as an example of a module using this feature.

**Pull request merged**
