### PR TITLE
[TIMOB-18905] Android: Update Appcompat to 22.1

### PR DESCRIPTION
**Pull request by ashcoding**
Jira: https://jira.appcelerator.org/browse/TIMOB-18905

To test, run scons and KS.

### CODE REVIEW

**Comment by ashcoding** [comment]
**DO NOT MERGE YET**
Still working on this.

**Comment by ashcoding** [comment]
Note to anyone looking at this in the future, 
http://stackoverflow.com/questions/29784124/java-lang-illegalargumentexception-appcompat-does-not-support-the-current-theme
```xml
<item name="windowNoTitle">true</item>
```
This was needed and added to the various themes in android\templates\build\theme.xml

**Comment by hieupham007** [comment]
Is this a work-in progress, or does it have support for the material themed dialogs we talked about?

**Comment by ashcoding** [comment]
@hieupham007 this is just the Appcompat update. The material themed dialogs will be in another PR.

**Comment by hieupham007** [comment]
code reviewed and functionally tested. Request **accepted**

**Pull request merged**
