### PR TITLE
[TIMOB-20196] iOS: ScrollableView is not possible to change views

### PR DESCRIPTION
**Pull request by AngelkPetkov**
:JIRA:https://jira.appcelerator.org/browse/TIMOB-20196?filter=-1

### CODE REVIEW

**Comment by pec1985** [comment]
Good catch! That also fixes another bug. This PR #7553 is wrong and needs to be corrected. If you could, do these changes:
From
```
#ifndef TI_USE_AUTOLAYOUT
    ENSURE_UI_THREAD(setViews, args)
#endif
```
to 
```
#ifdef TI_USE_AUTOLAYOUT
    ENSURE_UI_THREAD(setViews, args)
#endif
```
And then move this line to the end of the function
```
[self replaceValue:args forKey:@"views" notification:YES];
```
Let me know if you have questions

**Comment by pec1985** [comment]
Fixes https://jira.appcelerator.org/browse/TIMOB-20138 as well

**Comment by AngelkPetkov** [comment]
Thanks! Addressed comments.

**Comment by pec1985** [comment]
Thanks!

**Pull request merged**
