### PR TITLE
[TIMOB-25734] Android: Fix click and touch events for TextField and TextArea

### PR DESCRIPTION
**Pull request by garymathews**
- Fix click and touch events for `TextField` and `TextArea`

###### TEST CASE
```JS
var win = Ti.UI.createWindow({ backgroundColor : 'gray' }),
    tf = Ti.UI.createTextField({
        color : 'black',
        hintText : 'TEXT',
    });

tf.addEventListener('click', function() {
    Ti.API.info('CLICK');
});
tf.addEventListener('dblclick', function() {
    Ti.API.info('CLICK');
});
tf.addEventListener('singletap', function() {
    Ti.API.info('TAP');
});

win.add(tf);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25734)

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

`click`, `focus`,`dblclick`,`singletap` evants works as expected for `textfeild` & `textarea`.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.0.2.v20180130154740
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.11
Appc CLI:       7.0.2-master.7
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.12
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

**Comment by lokeshchdhry** [comment]
@garymathews ,can you please add tests.

**Comment by garymathews** [comment]
No test, this requires user input

**Pull request merged**
