### PR TITLE
[TIMOB-20221] Android: Remove deprecated properties and methods pre-5.0.0

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-20221

**Description:**
Removes nearly all the deprecated code in Android. I left some Geolocation constants, because I was unsure if we really want them removed yet.

One notable change is the removal of TiContext which was used in every single proxy class as an additional constructor arg for extra constructors. I believe removing this may also be a breaking change for native Android modules. Given that we already need to recompile all of them for 6.0.0 due to the V8 update, this seems fine to me.

### CODE REVIEW

**Comment by ashcoding** [comment]
Generally looks okay at a first glance. Are you able to direct me to perhaps a test app, code or test suite to test this?

Test case with emphasis on the classes that has TiContext removed to ensure no regressions.

**Comment by sgtcoolguy** [comment]
_Every_ proxy had a constructor that took TiContext.

**Comment by ashcoding** [comment]
I guess Kitchen Sink would be a good test app. :D

**Comment by ashcoding** [comment]
Functionally tested. Working as per normal. :)

**Comment by ashcoding** [comment]
Found some issues while testing Kitchen Sink but commented it here https://github.com/appcelerator/titanium_mobile/pull/8041#issuecomment-230379452

For the purpose of deprecation, this PR is good to go.

**Comment by sgtcoolguy** [comment]
@ashcoding It seems to work locally for me as well. I'm concerned that the PR build keeps failing with issues where the ti.map recompiled module complains about being unable to find a changed method signature on ProxyFactory class in native code in the SDK. Does Kitchen Sink use the ti.map module? Maybe you can quickly confirm that using some of these recompiled native modules work locally for you as they do for me (and we can chalk it up to some weird build agent setup issue)?

**Pull request merged**
