### PR TITLE
[TIMOB-24538] iOS: Fail gracefully when using reserved bindId identifiers

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24538

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR and FT passed.

**Comment by hansemannn** [comment]
@vijaysingh-axway I think you forgot to the the `in-qe-testing` label. Doing so now.

**Comment by vijaysingh-axway** [comment]
Yeah. Thanks @hansemannn .

**Review by htbryant94 — COMMENTED** [review]
Approved! when using a reserved identifier (i.e. 'badge') for the bindId property of a ListItem an error splash screen detailing the issue is prompted.

iPhone 7 10.2 Device & Simulator
iPhone 5S 9.3.5 SImulator
Mac OS Sierra (10.12.2)
Appc NPM: 4.2.9-1
App CLI: 6.1.0
Xcode 8.2.1
Node v4.6.0

**Review by htbryant94 — APPROVED** [review]

**Pull request merged**
