### PR TITLE
fix(ios): schedule KrollCallback on main thread (8_0_X)

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26673

8_0_X backport of #10556

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by sgtcoolguy** [comment]
@janvennemann ping, this one has merge conflicts that need to be resolved...

**Comment by keerthi1032** [comment]
FR Passed. No freezes, counter increases fine and works as expected. Waiting for resolving  merge conflicts to merge.

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
Node.js
  Node.js Version             = 8.12.0
  npm Version                 = 6.4.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = local sdk 
Device            = iPhone 6s iOS 12 
Simulator       =iPhone 6 iOS 11

**Comment by janvennemann** [comment]
@keerthi1032 merge conflicts resolved!

**Comment by lokeshchdhry** [comment]
Removing `needs test` label as master has `no test`.

**Pull request merged**
