### PR TITLE
[TIMOB-19383] iOS9: Upgrade Facebook module to facebook 4.7.0

### PR DESCRIPTION
**Pull request by cheekiatng**
JIRA: https://jira.appcelerator.org/browse/TIMOB-19383

### CODE REVIEW

**Comment by hansemannn** [comment]
FT and CR passed, PR **approved**. Thank you @cheekiatng !

**Comment by bogdansmc** [comment]
I confirm app crash on iOS.
As well, authorize doesn't work too (version 4.0.5 works well)

**Comment by cheekiatng** [comment]
HI everyone, it'll be great if you could include more details of the environment you are on. Like:
1. Xcode Version.
2. iOS Version.
3. Titanium SDK Version (Has to be 5.0.0 and above).
Also, please make sure you read the changes for replaced methods and make sure to follow the NEW instructions to configure the module.

**Comment by bogdansmc** [comment]
Dear cheekiatng, what new instructions are with using 4.0.5?
I use only simple login functions, there is not changes here!
And as it is described by arnaudm, app crashes after close/reopen without facebook authorize or other functions!

Xcode Version 7.0.1 (7A1001)
ios 8.4, 9.0
Titanium SDK Version 5.0.2.GA

**Comment by bogdansmc** [comment]
The last step-by-step to reproduce:

1. create new mobile app project (Default Alloy Project)
2. install facebook module 5.0.0 into project
3. add var fb = require('facebook'); in controllers/index.js before $.index.open();
4. Run on simulator iphone 4s, ios 8.4
5. After app start press "home" button and run app again. 
App will crash after that!

MacOS 10.11 (15A284)
Appcelerator Studio, build: 4.3.1.201509302304
Xcode Version 7.0.1 (7A1001)
ios 8.4
Titanium SDK Version 5.0.2.GA

**Pull request merged**
