### PR TITLE
[TIMOB-20595] Module Build: Update pre and post compile hooks event name

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/TIMOB-20595

### CODE REVIEW

**Comment by cb1kenobi** [comment]
Looks good, however the `build.pre.construct` events are missing the `module` token.

**Comment by feons** [comment]
What about `build.finalize`?

**Comment by cb1kenobi** [comment]
Especially `build.finalize`. :)

**Comment by cb1kenobi** [comment]
**APPROVED**

**Pull request merged**
