### PR TITLE
feat(ios): expose clearMotionEffects api

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26566

This can only be tested on device and therefore does not include unit-tests.

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by hansemannn** [comment]
Can this please be merged? Such a small change, approved review and all docs in place.

**Comment by janvennemann** [comment]
@hansemannn I guess this ticket fell off the radar since the JIRA ticket status was never update. Master is at 8.2.0 already so i updated the release version in the ticket and put it in QE test so this can finally be resolved.

**Review by ssjsamir — APPROVED** [review]
**FR Passed:** Able to now clear motion effects. Tested with the following test case: 
```
var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var background = Ti.UI.createImageView({
    image: 'http://web-features.net/pb-examples/rainbow-at-sea/bg.jpg',
    horizontalMotionEffect: {
        min: -50,
        max: 50
    },
    verticalMotionEffect: {
        min: -50,
        max: 50
    }
});
win.add(background);
win.addEventListener('click', () => {
    console.log('click click');
    background.clearMotionEffects();
});
win.open();
```
**Test Environment**
```
MacOS Mojave version 10.14.4
Xcode 11 beta 5
Node.js ^8.11.1
iPhone 6s (12.2)
"NPM":"4.2.14","CLI":"7.1.1-master.2"
```

**Pull request merged**
