### PR TITLE
[TIMOB-26963] Remove fields added to iOS required modules

### PR DESCRIPTION
**Pull request by whitfin**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26963

These fields are being injected into iOS modules (in the case of the ticket, a JSON file). These fields seem redundant, so I just removed them. I assume Jenkins will break if they're necessary somehow :) I couldn't find them anywhere else at a glance.

### CODE REVIEW

**Review by janvennemann — COMMENTED** [review]
This looks to be a leftover of our old require implementation which, for some reason, assumed that every module needs to export an `url` and `id` property. I guess it's safe to be removed.

cc @sgtcoolguy to confirm since he did the rework on the require implementation

**Comment by sgtcoolguy** [comment]
Ha I left this around because I had no idea how/if it was used. But hey, the tests all pass and the world didn't end. I'm fine with merging this for 8.2.1...

**Comment by brentonhouse** [comment]
@sgtcoolguy - Is it possible this could get merged into 8.2.0?

**Comment by brentonhouse** [comment]
I believe this PR will fix this issue as well:  https://jira.appcelerator.org/browse/TIMOB-20487

**Comment by cb1kenobi** [comment]
@brentonhouse It's too late to add this to 8.2.0. It'll have to go into 8.2.1.

**Review by sgtcoolguy — APPROVED** [review]

**Comment by ssekhri** [comment]
FR Passed. Appropriate fields available for the required common js module.
Verified on:
Mac OS 10.14.6
Ti SDK: 8.3.0.v20190923144817
Appc CLI: 7.1.1
Node: 10.5.0
JDK: 10.0.2
XCode: 11.0
Studio: 5.1.4.201909061933
Device: iPhone 7Plus(v12.2), iOS simulator (v13.0)

**Pull request merged**
