### PR TITLE
[TIMOB-25459] Android: toImage method needs parity with iOS

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25459

**Description:**
Result from calling toImage is returned directly to the callback function. Should be in a dictionary with "blob" key to match iOS behavior.

**Test case:**
app.js
```
var win = Ti.UI.createWindow();
var view = Ti.UI.createView({backgroundColor: 'green', width: 150, height: 150, top: 100});
var content = Ti.UI.createView({backgroundColor: 'blue', width: 45, height: 45});
var imageView = Ti.UI.createImageView({width: 150, height: 150, top: 300});
view.add(content);
win.add(view);
win.addEventListener('postlayout', function() {
	view.toImage(function(e) {
		imageView.setImage(e.blob);
	});
})
win.add(imageView);
win.open();
```

### CODE REVIEW

**Review by jquick-axway — COMMENTED** [review]
@ypbnv, @hansemannn,

We currently document that the callback argument is `Ti.Blob` here...
http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.View-method-toImage

So, Android was matching the documentation. iOS was not. And Windows does not appear to support this API (have not tried it)...
https://github.com/appcelerator/titanium_mobile_windows/blob/649177875b31712d5bceacd489d4595111648b3f/Source/TitaniumKit/src/UI/ViewLayoutDelegate.cpp#L73

So, which way should we go?
We can either modify iOS to match the docs or take Yordan's change, but it'll require a doc change too.

**Comment by garymathews** [comment]
Windows does support this API, it's implemented [here](https://github.com/appcelerator/titanium_mobile_windows/blob/649177875b31712d5bceacd489d4595111648b3f/Source/UI/src/WindowsViewLayoutDelegate.cpp#L242) and returns a Ti.Blob as documented.

**Comment by ypbnv** [comment]
@jquick-axway, @garymathews, @hansemannn I did not find another callback returning result without dictionary in the docs. so I will update them as well. If we decide to keep it as it is now I will revert the change.

**Comment by jquick-axway** [comment]
@hansemannn, agreed. Going forward, all callbacks we create in the future should provide a dictionary. That way, we can easily extend them with new properties/fields if needed.

**Comment by hansemannn** [comment]
What I am wondering is, why this never popped up before. I'll do the iOS PR later this week, closing this one.

**Pull request closed without merging**
