### PR TITLE
[TIMOB-24351]:iOS Support "editActions" in listview search-results

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-24351

### CODE REVIEW

**Comment by hansemannn** [comment]
This PR depends on the one you published earlier right? We should merge that one first and then rebase this one.

**Comment by vijaysingh-axway** [comment]
Correct.

**Review by ewieberappc — APPROVED** [review]
New FR will happen after dependency PR is merged

**Comment by hansemannn** [comment]
@ewieberappc Can you FT https://github.com/appcelerator/titanium_mobile/pull/9066 before? As soon as that one is merged, Vijay can rebase this PR and we can test the related changes for the edit-actions. Thx!

**Review by hansemannn — CHANGES_REQUESTED** [review]
Blocking until https://github.com/appcelerator/titanium_mobile/pull/9066 is merged.

**Comment by ewieberappc** [comment]
@hansemannn @vijaysingh-axway, #9066 is merged. We can unblock and rebase now.

**Comment by hansemannn** [comment]
@ewieberappc Done!

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@vijaysingh-axway Please revert @fe63d07 and resolve locally. It seems my tries to resolve the merge-conflicts online did not succeed.

**Review by ewieberappc — APPROVED** [review]
FR Passed.
Able to perform edit/delete actions on search results for ListViews and TableViews using searchbars

**Pull request merged**
