### PR TITLE
[TIMOB-24514] Android: Use https for Ti.Geolocation calls

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24514

### CODE REVIEW

**Comment by fmerzadyan** [comment]
@hansemannn, do you have a test case?

**Comment by hansemannn** [comment]
Any `Ti.Geolocation.forwardGeocoder` or `Ti.Geolocation.reverseGeocoder` call should trigger it. Try this:
```js
var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var btn = Ti.UI.createButton({
    title: 'Trigger'
});

btn.addEventListener('click', function() {
    Ti.Geolocation.forwardGeocoder('Berlin, Germany', function(e) {
        alert(e);
    });
});

win.add(btn);
win.open();
```

**Comment by fmerzadyan** [comment]
Thanks, CR && FR PASS.

**Review by ssjsamir — APPROVED** [review]
**FR passed**; was able to trigger the `Ti.Geolocation.forwardGeocoder` from the test case provided above, I also checked the SDK build to ensure changes were actually made to the codebase. 

**Test Steps**
+ Copied the test case from the description above 
+ Pasted the test case in to a titanium project in JIRA
+ Ran the program on and Nexus 6P device running Android 7.1.2
+ Used JD-GUI to decompile the SDK build and verify that `HTTP` was changed to `HTTPS` in the code base in the following location `android/modules/geolocation/src/java/ti/modules/titanium/geolocation/TiLocation.java`

Screenshot of the event being triggered. 
event-triggering

**Environement**
Appcelerator Command-Line Interface, version 6.1.0
Google Nexus 6P (Android 7.1.2)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 4.6.0
npm: 4.2.8
Xcode: 8.2
Appcelerator Studio: 4.8.1.201612050850

**Pull request merged**
