### PR TITLE
[TIMOB-24372] iOS: Expose all missing media item properties

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24372

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway Please review this next week if possible, we just got another request from the customer, thx!

**Review by vijaysingh-axway — COMMENTED** [review]
1. MPMediaItemPropertyHasProtectedAsset  is available with iOS 9_2 and above so macro for same should be there.
2. Any particular reason for deleting  MPMediaItemPropertyPodcastTitle, @"podcastTitle",
and 
 MPMediaItemPropertyPlayCount, @"playCount"
from itemProperties method.

3. In
 +  - name: playCount
+    summary: The  to filter on. Value should be a Number.
should be 

 +  - name: playCount
+    summary: The  playCount to filter on. Value should be a Number.

**Comment by hansemannn** [comment]
1. Added the version check. Will return `NO` on unsupported devices now. Using a mutable dict for this would be overhead.
2. Because they are filterable. They can still be fetched the same way, but now people can also use them to filter queries (e.g. in `Ti.Media.queryMusicLibrary`).
3. Fixed

**Review by vijaysingh-axway — COMMENTED** [review]
Implementation of 
++(BOOL)isIOSVersionOrGreater:(NSString *)version;
missing in TIUtils.m :)

**Review by vijaysingh-axway — COMMENTED** [review]
FT and CR passed.

**Review by htbryant94 — APPROVED** [review]
PR approved! tested with demo code provided in JIRA ticket, including additional exposed media item properties. iOS 10.2 & 9.3.

**Pull request merged**
