### PR TITLE
[TIMOB-25416] Ambiguous certificates trigger development provisioning profiles validation error 6_3_X

### PR DESCRIPTION
**Pull request by feons**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25416

### CODE REVIEW

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@feons Can you resolve the merge conflicts?

**Comment by feons** [comment]
@hansemannn, resolved.

**Comment by ewanharris** [comment]
@feons @hansemannn We shouldn't be using const/let in the build files as we can't safely make the switch to `'use strict';` to keep node 4 compat

**Comment by hansemannn** [comment]
@feons @ewieberappc Either revert or provide another PR for this? This was discovered while fixing iPhone x launch-screens for a customer that used Node 4.

**Pull request merged**
