### PR TITLE
[TIMOB-24579] Android: recognise newer attributes as valid tokens

### PR DESCRIPTION
**Pull request by frankieandone**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24579

#### Test case:
1. Add attribute
2. Run app
3. Check if attribute is in build/android/AndroidManifest.xml. If it is present then test has passed.

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
Approved.

Note: I also verified the spelling of all attributes defined for <application> and <activity>.

**Comment by ssjsamir** [comment]
@fmerzadyan Could you take a look at the merge conflicts?

**Comment by lokeshchdhry** [comment]
FR Passed.

Adding newer tokens to the tiapp.xml adds them succcessfully to the android manifest.
Added few attributes:
```
<android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest>
            <application android:isGame = "true">
                <activity android:configChanges="keyboardHidden"
                    android:label="@string/app_name"
                    android:name=".Timob24971Activity" 
                    android:screenOrientation="portrait"
                	android:supportsPictureInPicture="true"/>
            </application>
        </manifest>
    </android>
```

Studio Ver:     4.9.1.201707130742
SDK Ver:        6.2.0.v20170717103243 from PR
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices: Android 6.0.1, Android 7.0

**Comment by lokeshchdhry** [comment]
@fmerzadyan , Can you please resolve the conflicts so that I can merge. Thanks.

**Pull request merged**
