### PR TITLE
[TIMOB-26308] Update classic splash screens to be reduced in size

### PR DESCRIPTION
**Pull request by Topener**
ticket: https://jira.appcelerator.org/browse/TIMOB-26308

Update classic splash screens to be reduced in size

### CODE REVIEW

**Comment by cb1kenobi** [comment]
Out of curiosity, what software did you use to reduce the size of the images?

**Comment by Topener** [comment]
@cb1kenobi https://tinypng.com.

**Comment by m1ga** [comment]
if you don't want to (or can't) upload images to a server you could also use https://imageoptim.com/mac can drop a whole folder on it and wait 😁

**Review by ewanharris — APPROVED** [review]
Nice @Topener!

Merging

**Pull request merged**
