### PR TITLE
[TIMOB-26370] Android: "Failed to create external storage directory" when download image and save to camera roll

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26370

**Description:**
`WRITE_EXTERNAL_STORAGE` added in Media module where only `READ_EXTERNAL_STORAGE` is requested. This is in order to make up for a fix in Android 8 which no more grants the whole permission group when a single one is requested.

No unit tests for this PR.

**Test case:**
There is a good test code in the JIRA ticket.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
LGTM!

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by keerthi1032** [comment]
FR Passed. Image saved 
Test Environment:
Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  Memory                      = 17179869184
Node.js
  Node.js Version             = 8.12.0
  npm Version                 = 6.4.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = local sdk 8.0.0
Device                           =pixel android 9,samsung s5 android 6
Emulator                       = pixel android 8

**Comment by keerthi1032** [comment]
PR Merged

**Pull request merged**
