### PR TITLE
proper creation of the animation

### PR DESCRIPTION
**Pull request by Topener**

### CODE REVIEW

**Comment by ashcoding** [comment]
@Topener Thanks for the PR. Before we can review it, we would need you to sign the CLA located here: https://cla.appcelerator.com/

**Comment by Topener** [comment]
Done! Forgot about it ;)

**Comment by ashcoding** [comment]
@Topener, thanks for signing!

Just wanna check with you on the changes you made. Both the previous method and the changes you made are valid to create the animation.

Perhaps you could modify the example to have 2 transformations with both styles of initializing the Animation and 2 buttons to do the animation if you want to add that in.

**Comment by Costumelady** [comment]
Hi Thank you for the free app.  However I don't need it on my computer after all.  What name would I find it as in "programs" in control panel?  I can't locate files or the program itself listed as Topener or topener or anything else I found associated with your app.    Personally I can't believe the program survived a "refresh" in windows 8 but it did while all my other apps were removed.  That could be good or bad depending.  In my case I wanted everything wiped.  So I am not a developer just a Wordpress developer so don't answer too complicated for the average joe.  Thank you so much.  Laura thecostumelady

**Comment by Topener** [comment]
I would say this method of creation is more towards guidelines, and more clean. We should be promoting clean code right?

**Comment by hansemannn** [comment]
Hey @Topener, just saw this issue. Can we close it as it is outdated for a while now? The related docs have been creation using a property assignment to make it more easy to understand for beginners. Thanks!

**Comment by Costumelady** [comment]
Yes please close it.
 


     On Thursday, November 12, 2015 11:39 AM, Hans Knoechel <notifications@github.com> wrote:
   

 Hey @Topener, just saw this issue. Can we close it as it is outdated for a while now? The related docs have been creation using a property assignment to make it more easy to understand for beginners. Thanks!—

**Pull request closed without merging**
