### PR TITLE
[TIMOB-24347] Android: Fix URI handling for TiThumbnailRetriever

### PR DESCRIPTION
**Pull request by garymathews**
- Fix handling of external URIs in `TiThumbnailRetriever`
- Resolve path before parsing in `requestThumbnailImagesAtTimes()`
- Add `getNativePath()` into `TitaniumBlob`

###### TEST CASE
- Download [BigBuckBunny_320x180.mp4](http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4) and place into your project `Resources` folder
- Also download on device (Downloads folder), so it appears in your Gallery
```Javascript
var win = Ti.UI.createWindow({
		title: 'TIMOB-24347',
		backgroundColor: 'white',
		layout: 'vertical'
	}),
	bar = Ti.UI.createView({
		backgroundColor: 'gray',
		height: Ti.UI.SIZE,
		layout: 'horizontal',
		bottom: '10dp'
	}),
	bar_intent = Ti.UI.createButton({
		title: 'INTENT',
		width: '50%'
	}),
	bar_url = Ti.UI.createButton({
		title: 'URL',
		width: '50%'
	}),
	vp = Ti.Media.createVideoPlayer({
		backgroundColor: 'black',
		width: '320dp',
		height: '180dp',
		bottom: '10dp',
		mediaControlStyle: Ti.Media.VIDEO_CONTROL_DEFAULT,
		scalingMode: Ti.Media.VIDEO_SCALING_ASPECT_FIT,
		autoplay: false
	}),
	img = Ti.UI.createImageView({
	    backgroundColor: 'gray',
	    width: '320dp',
		height: '180dp',
		bottom: '10dp'
	}),
	slider = Ti.UI.createSlider({
	    backgroundColor: 'gray',
		min: 0,
		max: 100,
		width: '100%',
		visible: false
	}),
	updatingThumbnail = false;

bar_intent.addEventListener("click", function() {
	var intent = Ti.Android.createIntent({
		action: Ti.Android.ACTION_PICK,
		type: "video/*"
	});
	intent.addCategory(Ti.Android.CATEGORY_DEFAULT);
	win.getActivity().startActivityForResult(intent, function(e) {
	    if (e.intent != null) {
            vp.url = e.intent.data;
		}
	});
});

bar_url.addEventListener("click", function() {
	vp.url = 'BigBuckBunny_320x180.mp4';
});

vp.addEventListener("durationavailable", function(e) {
	slider.max = Math.floor(e.duration / 1000);
	slider.show();
});

slider.addEventListener('change', function(e) {
	if (vp && e.value > 0 && !updatingThumbnail) {
	    updatingThumbnail = true;
		vp.requestThumbnailImagesAtTimes([e.value], Ti.Media.VIDEO_TIME_OPTION_NEAREST_KEYFRAME, function(response) {
			img.image = response.image;
			updatingThumbnail = false;
		});
	}
});

bar.add(bar_intent);
bar.add(bar_url);
win.add(bar);

win.add(vp);
win.add(img);
win.add(slider);

win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24347)

### CODE REVIEW

**Review by antw12 — CHANGES_REQUESTED** [review]
After Using the test case to verify code changes here are the  findings:
1) The import for TitaniumBlob didnt not automatically appear when pulling code from PR, please double check as i cannot find it in the PR
relates to file:VideoPlayerProxy.java

however after testing with that change, i can confirm that it works

**Review by antw12 — APPROVED** [review]

**Comment by antw12** [comment]
URL is perfectly working although getting issues with the intent, when click on intent it says theres nothing on the device not sure why as it worked the last time i tested it

**Review by antw12 — CHANGES_REQUESTED** [review]
Intent does not work please look at comment for issue

**Comment by garymathews** [comment]
@antw12 You may have deleted the video from your gallery, download any H.264 MP4 video and try?

**Review by longton95 — APPROVED** [review]
FR passed.

Tested using the test case above and added the permissions for a 6.0+ devices, It now works as expected, spoke to @antw12 about his issue and it is working now.

ENV
```
SDK Version : Local 6.1.0
Mac OS Version : 10.12.3
Appc CLI : 6.1.0
Appc NPM : 4.2.9-1
Node : v4.6.0
Device: Nexus 5x(6.0.1) Pixel XL(7.1.1)
Emulator: (6.0), (4.4.2)
```

**Pull request merged**
