### PR TITLE
fix(android): themes to not use dark status/nav icons on a dark background

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-28577

**Summary:**
If `<application/>` uses Titanium's Solid Light theme (the default as of 10.1.0), then a `Ti.UI.Window` whose "theme" property is set to a dark theme might wrongly show dark status/nav bar icons on a dark background.

**Test:**
1. Set up an Android device to use "Light" mode. (Not dark mode.)
2. Build and run the below code on that device.
3. Tap on the "Theme.Titanium.Dark" button.
4. Verify status/nav bar icon light colored. _(Used to show dark icons.)_
5. Navigate back to parent window.
6. Tap on the "Theme.Titanium.Dark.Solid" button.
7. Verify status/nav bar icons are light colored. _(Used to show dark icons.)_
8. Navigate back to parent window.
9. Tap on the "Theme.Titanium.Light" button.
10. Verify status/nav bar icons are light colored. _(Used to show dark icons.)_
11. Tap on the "Theme.Titanium.Light.Solid" button.
12. Verify status/nav bar icons are **dark** colored on a white background. _(This worked before.)_
13. Set device to "Dark" mode.
14. Repeat steps 3-13. Note that only root window respects device theme, not child windows.

```javascript
const parentWindow = Ti.UI.createWindow({
	title: "Select Child Theme",
	extendSafeArea: false,
});
const tableView = Ti.UI.createTableView({
	data: [
		Ti.UI.createTableViewRow({ title: "Theme.Titanium.Dark" }),
		Ti.UI.createTableViewRow({ title: "Theme.Titanium.Dark.Solid" }),
		Ti.UI.createTableViewRow({ title: "Theme.Titanium.Light" }),
		Ti.UI.createTableViewRow({ title: "Theme.Titanium.Light.Solid" }),
	],
});
tableView.addEventListener("click", (e) => {
	const childWindow = Ti.UI.createWindow({
		title: e.row.title,
		theme: e.row.title,
	});
	const closeButton = Ti.UI.createButton({ title: "Close" });
	closeButton.addEventListener("click", () => {
		childWindow.close();
	});
	childWindow.add(closeButton);
	childWindow.open();
});
parentWindow.add(tableView);
parentWindow.open();
```

### CODE REVIEW

**Comment by hansemannn** [comment]
@m1ga Can you review this? It seems like it fixes a long-standing issue where we needed own dark mode icons for the nav bar (which works automatically on iOS).

**Review by m1ga — APPROVED** [review]

**Comment by hansemannn** [comment]
Does this include icons in the <MenuItem> as well? That would save a lot of app size if it would re-tint automatically. But I guess thats something else.

**Comment by m1ga** [comment]
Which icons? Its tinting the system icons in the statusbar correctly now. Stuff like bottomnavigation icons can be [tinted already](https://github.com/tidev/titanium_mobile/discussions/12568#discussioncomment-483500)

**Comment by hansemannn** [comment]
Oh, I meant the icons in the navigation bar (top right)

**Comment by m1ga** [comment]
navigationbar is to bottom "home, back, app switcher" bar. 

You are talking about the actionbar? In 10.2.0 you can use a custom icon for the `homeAsUpIndicator` https://github.com/tidev/titanium_mobile/pull/13149 (so you can tint it in code and save it).
And for the right icon I just use a drawable:
```
<Menu platform="android">
	<MenuItem id="item1" title="" icon="Titanium.App.Android.R.drawable.cogwheel" showAsAction="Ti.Android.SHOW_AS_ACTION_ALWAYS" onClick="onClickFilter"/>
</Menu>
```
I only use one color for dark/night but it should use the same color as the [actionBarTheme controlColorNormal](https://github.com/m1ga/from_zero_to_app/blob/master/android_theming.md#arrow--menu-item-in-actionbar). So you could change the dark color in your theme.

**Comment by hansemannn** [comment]
Okay, but you still need two drawables (light and dark), right? Because iOS does that automatically (luckily). But nevermind, it's not scope of this PR!

**Review by hansemannn — APPROVED** [review]

**Comment by m1ga** [comment]
> Okay, but you still need two drawables (light and dark), right? Because iOS does that automatically (luckily). But nevermind, it's not scope of this PR!

Still answer it here so it's resolved :smile: 

Screenshot_20220412-133316

1 drawable and tint it with the theme.

https://material.io/components/app-bars-top/android#regular-top-app-bar
at `Action items attributes` you can see `?attr/colorControlNormal (as Drawable tint)`

so in your drawable xml you'll start with:
```
<vector xmlns:android="http://schemas.android.com/apk/res/android"
    android:width="59.999998dp"
    android:height="60.903094dp"
    android:viewportWidth="59.999998"
    android:tint="?attr/colorControlNormal"
    android:viewportHeight="60.903094">
```
and make sure you have `android:tint="?attr/colorControlNormal"` in it. Then you can set `<item name="colorControlNormal">#f00</item>` in your theme later on. I'll add that to my [tutorial later](https://github.com/m1ga/from_zero_to_app/blob/master/android_theming.md)

**Pull request merged**
