### PR TITLE
fix(ios): add workspace workaround

### PR DESCRIPTION
**Pull request by hansemannn**
… until all external SDK dependencies in modules are built

**Important**: There should also be a note about this in the release notes, because native app extensions will also need to specify this setting in their build settings.

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-28303

### CODE REVIEW

**Comment by jasonkneen** [comment]
Can we can this validated and merged? This is a MAJOR breaking issue on Xcode 12.3 on certain projects that means we can't fully upgrade to 12.3 without patching our SDKs.

URGENT!

**Review by sgtcoolguy — APPROVED** [review]
LGTM

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by ssekhri** [comment]
FR Passed.
Verified on:
Mac OS: 10.15.4
SDK: 10.0.0.v20210104110722 
Appc CLI: 8.1.1
JDK: 11.0.6
Node: 12.16.1
Studio: 6.0.0.202005141803
Xcode: 12.3, 12.2
iOS simulator 14.3, 13.4

**Pull request merged**
