### PR TITLE
[TIMOB-20013] Ti.Contacts - Fix relatedNames property causing crash

### PR DESCRIPTION
**Pull request by cheekiatng**
JIRA: https://jira.appcelerator.org/browse/TIMOB-20013

### CODE REVIEW

**Comment by hansemannn** [comment]
Did a CR, unfortunately it's still crashing using the provided example code: 
```
-[__NSCFString countByEnumeratingWithState:objects:count:]: unrecognized selector sent to instance 0x7f91fbc5af40
```

**Comment by cheekiatng** [comment]
@hansemannn is this crash caused in > iOS9.0? Are you referring to the example code in the JIRA ticket? It has to be edited to pass an array into relatedNames. i.e.
```
relatedNames:{
   	  	father: ['baba1','baba2'],
   	  	mother: ['mama'],
   	  	child: ['gaga']
   	  }
```

**Comment by hansemannn** [comment]
Using the array values works in iOS8, but iOS9 crashes using the the property. Also, we should validate the string values inside the array loop to supply a proper error message.

**Comment by hansemannn** [comment]
FT + CR passed, PR approved!

**Pull request merged**
