### PR TITLE
[TIMOB-18853] Android: Custom Fonts for Attributed Strings

### PR DESCRIPTION
**Pull request by ashcoding**

### CODE REVIEW

**Comment by ashcoding** [comment]
Jira: https://jira.appcelerator.org/browse/TIMOB-18853
Test Code:
```
var win = Titanium.UI.createWindow({
	backgroundColor : "#ffffff"
});
 
var scrollView = Ti.UI.createScrollView({
	height : Ti.UI.FILL,
	width : Ti.UI.FILL,
	layout : "vertical"
});
 
win.add(scrollView);
 
win.open();

 
   var font = "Chantelli_Antiqua";
	var text = font;
 
	var attr = Titanium.UI.createAttributedString({
		text : text,
		attributes : [
		{
			type : Ti.UI.ATTRIBUTE_FONT,
			value : {
				font : {
					fontSize : 20,
					fontFamily : font
				}
			},
			range : [0, text.length]
		},
		{
			type : Ti.UI.ATTRIBUTE_FOREGROUND_COLOR,
			value : "#000000",
			range : [0, text.length]
		}]
	});
 
	var label = Titanium.UI.createLabel({
		top : 10,
		left : 10,
		right : 10,
		height : Titanium.UI.SIZE,
		attributedString : attr
	});
 
	scrollView.add(label);

	
	var font1 = "serif";
	var text1 = font1;
 
	var attr1 = Titanium.UI.createAttributedString({
		text : text1,
		attributes : [
		{
			type : Ti.UI.ATTRIBUTE_FONT,
			value : {
				font : {
					fontSize : 20,
					fontFamily : font1
				}
			},
			range : [0, text1.length]
		},
		{
			type : Ti.UI.ATTRIBUTE_FOREGROUND_COLOR,
			value : "#000000",
			range : [0, text1.length]
		}]
	});
 
	var label1 = Titanium.UI.createLabel({
		top : 10,
		left : 10,
		right : 10,
		height : Titanium.UI.SIZE,
		attributedString : attr1
	});
 
	scrollView.add(label1);
	
	var text2 = "Chantelli_Antiqua";
	var label2 = Ti.UI.createLabel({
	top : 20,
	font : {
		fontSize : 50,
		fontFamily : 'Chantelli_Antiqua'
	},
	color : '#d0d',
	text : text2
});
scrollView.add(label2);
```

**Comment by hieupham007** [comment]
Code reviewed and functionally tested. Request **accepted**

**Comment by nuno** [comment]
Nice!

**Comment by alexgbernier** [comment]
Nice, indeed. Thank you, @ashcoding and @hieupham007!

**Comment by ashcoding** [comment]
:thumbsup:

**Pull request merged**
