### PR TITLE
[6_2_X][TIMOB-15910] Android: Implement Ti.UI.Android.DrawerLayout

### PR DESCRIPTION
**Pull request by garymathews**
- Cherry-pick of https://github.com/appcelerator/titanium_mobile/pull/9091

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-15910)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

The drawer layout works as expected. The left, middle & the right views are shown with the appropriate way of unhiding them. Also, different views like imageView, Label, TextView, tableview, listview etc can be successfully added to the left, middle & right drawer views.
The properties & methods seem to work as expected.

Studio Ver: 4.9.1.201707200100
SDK Ver: 6.2.0 Local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.9
Appc CLI: 6.2.3
Ti CLI Ver: 5.0.14
Alloy Ver: 1.9.13
Node Ver: 6.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1
⇨ google Pixel --- Android 7.1.1
Emulator: Android 4.4.2

**Comment by m1ga** [comment]
The example code at http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.Android.DrawerLayout is not showing all the code in the correct style. Looking at other yml files I think an extra line before the actual code is missing

**Comment by hansemannn** [comment]
@m1ga Good catch! Fixed on master and 6_2_X, see [here](https://github.com/appcelerator/titanium_mobile/blob/master/apidoc/Titanium/UI/Android/DrawerLayout.yml).

**Comment by alangumer** [comment]
The background color was hardcoded so was not possible to change the color via theme; also the property android:fitsSystemWindows="true" was added to avoid that the status bar overlaps the App bar; and the elevation was set to 0 which looks nicer especially when using navigation tabs.

https://github.com/appcelerator/titanium_mobile/pull/9439

**Pull request merged**
