### PR TITLE
[TIMOB-24851] Android: Fix Ti.UI.Label.wordWrap behaviour

### PR DESCRIPTION
**Pull request by garymathews**
- `wordWrap` should still allow new-lines when set to `false`

###### TEST CASE
```JS
var win = Ti.UI.createWindow(),
    lbl = Ti.UI.createLabel({
        left: 0,
        text: 'This is some very long test text that should span accross the screen.\nThis is a new line for test text.',
        ellipsize: Titanium.UI.TEXT_ELLIPSIZE_TRUNCATE_NONE,
        wordWrap: false
    });

win.add(lbl);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24851)

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
CR:Pass

**Comment by garymathews** [comment]
Will refactor once https://github.com/appcelerator/titanium_mobile/pull/9161 has been merged.

**Comment by sgtcoolguy** [comment]
@garymathews ping: #9161 has been merged. If this is targeted for 7.0.1, then we'll need a backport/cherry-pick (and the JIRA ticket should have a fixVersion)

**Comment by hansemannn** [comment]
@garymathews Merge conflicts and backport? We have too many open "7.1.0" PR's without backport right now.

**Comment by lokeshchdhry** [comment]
FR Passed.

`newline` is allowed when `wordwrap` is set to `false`.

Studio Ver:     5.1.0.201804230827
SDK Ver:        7.2.0.v20180509085211
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.13
Appc CLI:       7.0.3
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

**Comment by lokeshchdhry** [comment]
@garymathews , Can you please resolve the conflicts.

**Comment by garymathews** [comment]
@lokeshchdhry Resolved

**Comment by sgtcoolguy** [comment]
Looks like these changes already snuck in somehow...

**Comment by jquick-axway** [comment]
The "wordWrap" change isn't in yet.
What happened my PR #9161 refactored the code and moved the `setSingleLine()` method calls to a different place in the code.

I'll create a new PR.

**Pull request closed without merging**
