### PR TITLE
[TIMOB-23715] Android: Fix TiBaseActivity and TiUIView memory leaks

### PR DESCRIPTION
**Pull request by garymathews**
- Fix memory leaks from various object references in `TiListView` `TiBaseActivity` and `TiUIView`

##### TEST CASE
```Javascript
var w = Ti.UI.createWindow({layout: 'vertical'}),
    a = Ti.UI.createButton({title: 'Ti.UI.View', width: '90%'}),
    b = Ti.UI.createButton({title: 'Ti.UI.ListView', width: '90%'}),
    iterations = 5;

a.addEventListener('click', function() {
    for (var i = 0; i < iterations; i++) {
        setTimeout(function () {
            var w = Ti.UI.createWindow(),
                a = Ti.UI.createView({
                    width: Ti.UI.FILL,
                    height: Ti.UI.FILL,
                    backgroundColor: 'red'
                });
            w.addEventListener('open', function() {
                w.close();
            });
            w.add(a);
            w.open();
        }, 250*i);
    }
});

b.addEventListener('click', function() {
    for (var i = 0; i < iterations; i++) {
        setTimeout(function () {
            var w = Ti.UI.createWindow(),
                a = Ti.UI.createListView();
            w.addEventListener('open', function() {
                w.close();
            });
            w.add(a);
            w.open();
        }, 250*i);
    }
});

w.add(a);
w.add(b);
w.open();
```

- Use Android Monitor to execute GC and monitor memory allocation

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23715)

### CODE REVIEW

**Comment by garymathews** [comment]
test this please

**Comment by garymathews** [comment]
test this please

**Comment by fmerzadyan** [comment]
Running your test case and the one reported in the ticket. I still get leaked activities from both test cases. Seems there are still contexts leaking in TiCompositeLayout for one example.

**Comment by garymathews** [comment]
@fmerzadyan Updated PR

**Comment by garymathews** [comment]
test this please

**Comment by fmerzadyan** [comment]
The leaks are whittled down 👍  but a few still remain. Add this snippet to `TiListView.release()`.
```
if (inflater != null) {
    inflater = null;
}
```
After adding this your test case has no leaks but there are leaks in original test case. Maybe populate your list view and inspect list view items and `TiBaseListViewItem`?

**Comment by garymathews** [comment]
The `inflater` is static so that should be fine. If everything else is okay it should be good to merge 👍

**Comment by fmerzadyan** [comment]
Mutable static variables are not garbage collected. Developers must explicitly nullify these variables. Plus it flagged up when profiling Java heap.

**Comment by garymathews** [comment]
You're right, but it's done purposefully to reuse the inflater object again when a new ListView is created.

Which is why this is in the constructor, to not recreate the inflater object again:
```Java
if (inflater == null) {
	inflater = (LayoutInflater)activity.getSystemService(Context.LAYOUT_INFLATER_SERVICE);
}
```

**Comment by fmerzadyan** [comment]
CR && FT PASS

**Pull request merged**
