### PR TITLE
chore: fix Android clipboard test

### PR DESCRIPTION
**Pull request by m1ga**
<strike>The clipboard test won't run in every Android version without an issue so I make this iOS only for now.</strike>

Increased the waiting time in the `clipboard` test. It turns out that the next UI test (ImageView) will remove the focus too quickly and on of the clipboard tests will fail. Increasing the waitingTime will fix it.

That way it's <strike>`5166 Total Tests: 5166 passed, 0 failed, 0 skipped.`</strike> `5167 Total Tests: 5167 passed, 0 failed, 0 skipped.
` again. Should we add a `test action` (not for every commit of course) that will run the test suite again?

### CODE REVIEW

**Comment by hansemannn** [comment]
Do we know *why* they would fail on some Android versions, e.g. only > 11 or only > 13? In that case, we should look into the code

**Comment by m1ga** [comment]
I don't know but it was broken for several months (years) like many other tests so I don't think the tests where used that often :wink: I've tested them but did now that this (and the geo parts) could fail so I ignored them. I rather have it clean so we could add it to the CI again and then add more tests.

It is also only the `should(Ti.UI.Clipboard.hasText()).be.true();` part in the test. All other clipboard tests work fine.

**Comment by m1ga** [comment]
Android 10 worked: https://github.com/tidev/titanium_mobile/pull/13355

**Comment by m1ga** [comment]
It has to do with the current focus.
If I do
```js
Ti.UI.Clipboard.setData('text', "asdf");
console.log(Ti.UI.Clipboard.getData('text'));
```
it will return `null`. But if I add a TextField and use it in the TextField `focus` event with
```js
tf.addEventListener("focus", function(){
	tf.value = Ti.UI.Clipboard.getData('text');
})
```
it does return the correct value and writes it into the TextField. I adjust the test to include a textfield

**Review by hansemannn — APPROVED** [review]

**Pull request merged**
