### PR TITLE
[TIMOB-24264] iOS: Support Images on ListView editAction

### PR DESCRIPTION
**Pull request by xicovarisco**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24264

### CODE REVIEW

**Review by hansemannn — CHANGES_REQUESTED** [review]
Some major issues with this PR:
- Missing docs
- Tons of changed blank-spaces (see the diff)
- Add a test-case
- Add a unit-test in https://github.com/appcelerator/titanium-mobile-mocha-suite

Please use "6.2.0" as the version in the docs and edit files with Xcode. If not known before, you can edit and test changes in the repo (iphone/iphone/Titanium.xcodeproj) with an app.js in `demos/KitchenSink/Resources/app.js`.

**Comment by hansemannn** [comment]
@xicovarisco Ping, will you be able to update the PR? We cannot take it inside the core at this state, especially as we are in between the progress linting the whole core.

**Comment by xicovarisco** [comment]
Hey @hansemannn. I have no time at the moment, sorry. Hope someone else find the time to do it :)

**Comment by hansemannn** [comment]
Closing due to missing support for now.

**Pull request closed without merging**
