### PR TITLE
fix(ios)(8_0_X): Supported tel protocol similar to previous implementation

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-26835

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
This should ideally have at least one unit test defined to confirm the fix/feature.

Is the use case trying to "open" a tel: style url to dial a phone number? Is the issue that it actually would exit out app with no way to return if you invoked it?

**Review by janvennemann — DISMISSED** [review]
Please update the log message to explain that this a iOS only recommendation.

**Comment by janvennemann** [comment]
@sgtcoolguy, to goal is that `tel:` style links will be properly handled and a user is able to dial the number. Currently is doing nothing and just ignoring the link click.

I 'm not sure this can be tested with a unit test since it requires user interaction. Or can we emulate user clicks in a unit test in our suite? cc @vijaysingh-axway to confirm.

**Review by ssjsamir — APPROVED** [review]
FR Passed: Able to get call pop menu from a webView

**Test Environment**
```
iPhone 6 (12.1)
APPC CLI: 7.0.10
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 8.9.1
Xcode 10.1
```

**Pull request merged**
