### PR TITLE
[TIMOB-24460] Android: Fix unwanted change event when change properties

### PR DESCRIPTION
**Pull request by maggieaxway**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24460

Test Case:

````js
var win = Ti.UI.createWindow({backgroundColor : 'gray', layout: 'vertical'}),
    tf = Ti.UI.createTextField({
        value: 'TEXT',
        passwordMask: true

    }),
    btn = Ti.UI.createButton({title: 'TOGGLE passwordMask'});

tf.addEventListener('change', function() {
    alert('TEXT CHANGED');
});

btn.addEventListener('click', function() {
    tf.passwordMask = !tf.passwordMask;
});

win.add(tf);
win.add(btn);

win.open();

### CODE REVIEW

**Review by garymathews — CHANGES_REQUESTED** [review]
There seems to be an issue with the initialisation of `passwordMask`. When set to `true` in the constructor, it's still `undefined`.

##### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor : 'gray', layout: 'vertical'}),
    tf = Ti.UI.createTextField({
        value: 'TEXT',
        passwordMask: true

    }),
    btn = Ti.UI.createButton({title: 'TOGGLE passwordMask'});

tf.addEventListener('change', function() {
    alert('TEXT CHANGED');
});

btn.addEventListener('click', function() {
    Ti.API.info('passwordMask: ' + tf.passwordMask);
    tf.setPasswordMask(!tf.passwordMask);
});

win.add(tf);
win.add(btn);

win.open();
```

**Comment by longton95** [comment]
@garymathews #8983 Has the fix for the initialisation of `passwordMask`

**Review by garymathews — APPROVED** [review]

**Comment by garymathews** [comment]
Addressed that as a separate issue here: https://github.com/appcelerator/titanium_mobile/pull/9005

CR: **PASS**

**Review by longton95 — APPROVED** [review]
FR passed.

Tested using the test case above and a modified version, the change event is not fired when `passwordMask` is changed

ENV
```
SDK Version : Local 6.2.0
Mac OS Version : 10.12.4
Appc CLI : 6.2.0
Appc NPM : 4.2.9
Node : v4.6.0
Device: Nexus 5x(6.0.1) Pixel XL(7.1.2)
Emulator: (6.0), (4.4.2)
```

**Pull request merged**
