### PR TITLE
fix(ios): fix top padding of dim-view in Ti.UI.TableView's search-bar 

### LINKED ISSUE #13303: iOS: dimBackgroundForSearch on TableView has no effect
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

The dimBackgroundForSearch has ne effect on a TableView. The background is dimmed anyway.

Maybe related to https://github.com/tidev/titanium_mobile/issues/13246

### Expected Behavior

The background dimming should not be visible

### Actual behavior

The background dimming is visible when dimBackgroundForSearch=false

### Reproducible sample

```
const win = Ti.UI.createWindow({title: 'Window'});
var newData = Ti.UI.createTableViewRow({title: 'element 1'})
var newData2 = Ti.UI.createTableViewRow({title: 'row 2'})
var newData3 = Ti.UI.createTableViewRow({title: 'item 3'})
const table = Ti.UI.createTableView({
        dimBackgroundForSearch: false,
	search: Ti.UI.createSearchBar(),
	data: [newData, newData2, newData3]
});
win.add(table);
win.open();
``` 

### Steps to reproduce

- Start the example
- search for something

### Platform

iOS

### SDK version you are using

10.1.1.GA

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes #13303

The calculation missed the safe-area-insets that's applied on newer devices.

### CODE REVIEW

**Comment by hansemannn** [comment]
@m1ga @caspahouzer Can you review / test this change?

**Comment by caspahouzer** [comment]
https://github.com/tidev/titanium_mobile/issues/13303 is not related to this?

**Review by caspahouzer — COMMENTED** [review]
On first focus, the insets looks good
Bildschirmfoto 2022-04-04 um 11 37 14


Entering "ann" and delete it back to empty, the insets of the dim-view failed
Bildschirmfoto 2022-04-04 um 11 36 53


https://user-images.githubusercontent.com/1126641/161516984-731ff9f6-55ca-4ed3-8535-895f95549c61.mov

**Comment by hansemannn** [comment]
@caspahouzer Do you have a reproducible test case (in app.js format if possible) for this? I can't reproduce it so far :(

**Comment by caspahouzer** [comment]
Sorry for the delay. Here is an example. Build with 10.1.1.GA and 10.2.0.v20220402181347. After search click on cancel and you see the inset bug

```
var win = Ti.UI.createWindow({title: 'Appcelerator Titanium'});

var navigagtionWindow = Ti.UI.createNavigationWindow({
    window: win
});

var search = Titanium.UI.createSearchBar({
    height: 43
});

Ti.UI.backgroundColor = 'white';

var sectionFruit = Ti.UI.createTableViewSection({headerTitle: 'Fruit'});
sectionFruit.add(Ti.UI.createTableViewRow({title: 'Apples'}));
sectionFruit.add(Ti.UI.createTableViewRow({title: 'Bananas'}));
sectionFruit.add(Ti.UI.createTableViewRow({title: 'Mangos'}));
sectionFruit.add(Ti.UI.createTableViewRow({title: 'Ananas'}));
sectionFruit.add(Ti.UI.createTableViewRow({title: 'Peaches'}));

var sectionVeg = Ti.UI.createTableViewSection({headerTitle: 'Vegetables'});
sectionVeg.add(Ti.UI.createTableViewRow({title: 'Carrots'}));
sectionVeg.add(Ti.UI.createTableViewRow({title: 'Potatoes'}));

var sectionFish = Ti.UI.createTableViewSection({headerTitle: 'Fish'});
sectionFish.add(Ti.UI.createTableViewRow({title: 'Cod'}));
sectionFish.add(Ti.UI.createTableViewRow({title: 'Haddock'}));

var table = Ti.UI.createTableView({
    id: 'tableView',
    search: search,
    dimBackgroundForSearch: true,
    showSearchBarInNavBar: true,
    data: [sectionFruit, sectionVeg, sectionFish]
});

win.add(table);
navigagtionWindow.open();
```

https://user-images.githubusercontent.com/1126641/162887112-e1c05bd7-82da-4b13-822c-8fea465ec925.mov

In this test case not visible, but I found another related issue: https://github.com/tidev/titanium_mobile/issues/13388

**Comment by hansemannn** [comment]
I checked it and can reproduce it. But only with `showSearchBarInNavBar` enabled.

**Comment by hansemannn** [comment]
@caspahouzer Pusher a few other fixes, would you mind to check it this week?

**Review by caspahouzer — APPROVED** [review]
Inset fix works

**Pull request merged**
