### PR TITLE
[TIMOB-13379] Add support for console.time and console.timeEnd

### PR DESCRIPTION
**Pull request by mattapperson**
Added support for iOS & Android for TIMOB-13379

### CODE REVIEW

**Comment by pec1985** [comment]
Bump!

**Comment by caspahouzer** [comment]
bump again

**Comment by mattapperson** [comment]
Sorry, but my and my companies dev efforts are now focused on other efforts

**Comment by caspahouzer** [comment]
So no further Appcelerator dev from you?

- Sebastian

**Comment by mattapperson** [comment]
It's just not our focuse at this time.

**Pull request closed without merging**
