### PR TITLE
fix(android): module build to download ndk with gradle tool 3.5.0+

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-27798

**Note:**
The PR for [TIMOB-27755](https://jira.appcelerator.org/browse/TIMOB-27755) must be merged first. Otherwise, Titanium's build tools will fail to find the downloaded NDK under the side-by-side directory which will break Titanium app builds.

**Summary:**
- After updating Android gradle tool from 3.4.2 to 3.6.0, module builds no longer auto-downloads NDK if missing.
- Issue is on Google's end which default to an "unstable" NDK version and tool does not support downloading unstable versions.

**Test:**
Follow the the test procedure written in PR #11531.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by garymathews** [comment]
##### NOTE: Although the code changes are good, the fallback NDK `21.0.6113669` will exhibit [Bad file descriptor](https://jira.appcelerator.org/browse/TIMOB-27776)

**Comment by jquick-axway** [comment]
@garymathews, I think I should set the NDK version 1 release back to avoid that.

**Comment by ssekhri** [comment]
FR Passed.
1. With no NDK on the system, the module build installs side-by-side NDK
2. When side-by-side NDK (any other version) is already installed the module build does not install the NDK
3. When side-by-side NDK is not installed but another NDK is on the system. "appc ti config" does not have flag for android.ndkPath set then the build for module installs side-by-side NDK.
4. When side-by-side NDK is not installed but another NDK is on the system. "appc ti config"  flag for android.ndkPath is set to the NDK on the system then the module build does not install side-by-side NDK.

Verified on:
Mac OS: 10.15.4
SDK: 9.1.0.v20200413165732
Appc CLI: 8.0.0
JDK: 13.0.2
Node: 10.17.0

**Pull request merged**
