### PR TITLE
Add titanium slack to readme

### PR DESCRIPTION
**Pull request by cdrx**

### CODE REVIEW

**Comment by Topener** [comment]
I approve of this commit

**Comment by ingo** [comment]
I'm fine with the addition, but I'd prefer a more "official" URL. Is there one?

**Comment by Topener** [comment]
@ingo, the official url is http://ti-slack.slack.com. But the URL mentioned is the signup form, since Slack doesn't support that out of the box

**Comment by FokkeZB** [comment]
@Topener you can now change this to tislack.org right?

**Comment by Topener** [comment]
Yes! tislack.org is now to proper url

**Comment by hansemannn** [comment]
Changes look fine now, approved!

**Pull request merged**
