### PR TITLE
[TIMOB-23145] Enable run-on-main-thread by default for new projects

### PR DESCRIPTION
**Pull request by cheekiatng**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23145

### CODE REVIEW

**Comment by hansemannn** [comment]
As we are talking about default values. Do we enabled autolayout in 5.4.0 now or do we need more tim?

**Comment by cheekiatng** [comment]
i think we need more time. Is auto layout necessary to be set on for hyperloop?

**Comment by hansemannn** [comment]
Nope, and currently produces problems in that combination. Let's do further discussions in JIRA.

**Comment by sgtcoolguy** [comment]
LGTM

**Pull request merged**
