### PR TITLE
feat(android)(9_0_X): add "google-services.json" support

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27745

**Cherry-pick of PR:** #11461

### CODE REVIEW

**Comment by m1ga** [comment]
@hansemannn with this PR firebase-auth works.

**Comment by hansemannn** [comment]
Jep, thx! I really hope this makes it into 9.0.1. Can't update to 9.x before this.

**Comment by jquick-axway** [comment]
@hansemannn, @m1ga, are you unable to update your firebase modules until this change makes it in?

**Comment by m1ga** [comment]
@jquick-axway in my tests I can't use the latest versions of the modules because of `string not found` errors. I was able to use firebase-core + firebase-cloud-messaging with a lower version e.g. fcm 20.0.1 so it will work. 
But firebase-auth won't work without the patch. Here is a test version: http://migaweb.de/firebase.auth-android-3.0.0.zip if you just include it inside the tiapp.xml it will crash with a `string not found` error. As soon as I use this PR and put the google-service.json in the right place it works fine.

I didn't try to update the other modules to the latest module versions yet since I have a setup now that works and I don't want to change it :)

**Comment by jquick-axway** [comment]
That's what I was afraid of. For your info, the google-services gradle tool turns the JSON into string xml entry under the "res" folder. So, it's failing to find these string resources.

**Comment by hansemannn** [comment]
Yep, that was exactly our issue. We used a local fork that includes the patch now, so once this is merged, we can go official again!

**Comment by ssekhri** [comment]
FR Passed
Mac OS: 10.15.4
SDK: 9.0.1.v20200413124532
Appc CLI: 8.0.0
JDK: 11.0.4
Node: 10.17.0
Studio: 6.0.0.202003181504
Device: Pixel3(v10.0) emulator

**Pull request merged**
