### PR TITLE
[TIMOB-24344] Android: Fix getDensity() for tvdpi

### PR DESCRIPTION
**Pull request by garymathews**
- Fix `getDensity()` of `213dp`to `tvdpi`

###### TEST CASE
```Javascript
Ti.API.info('density: ' + Ti.Platform.displayCaps.getDensity());
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24344)

### CODE REVIEW

**Comment by hansemannn** [comment]
@garymathews Can you add a tiny test-case / environment for this, so QE can pick it up more quicky?

**Comment by maggieaxway** [comment]
CR passed

**Comment by lokeshchdhry** [comment]
@maggieaxway , I see you have merged the PR, with the new process the QE team merges the PR when they are done with the FR, you would have to just add the `in-qe-testing` label so that we know we can pick the ticket for FR.

**Comment by hansemannn** [comment]
@lokeshchdhry Agree. Should I revert the merge or can you use the merged one for this one?

**Comment by lokeshchdhry** [comment]
@hansemannn, No need to revert, the merged one should be fine.

**Comment by lokeshchdhry** [comment]
FR passed.

Checked by creating an emulator with `tvdpi` & getting the `Ti.Platform.displayCaps.getDensity()` returned `TVDPI` which is correct.

Appc Studio : 4.8.1.201612050850
SDK Version : Locally built for this PR.
Mac OS Version : 10.12.2
Xcode Version : Xcode 8.2.1 Build version 8C1002
Appc CLI AND Appc NPM : {"NPM":"4.2.9-1","CLI":"6.1.0"}
Ti CLI : 5.0.11
Alloy : 1.9.5
Node : v4.6.0

**Comment by maggieaxway** [comment]
@lokeshchdhry @hansemannn Thanks for reminding. I will take note next time

**Pull request merged**
