### PR TITLE
[TIMOB-23395] Android: Improve structure of JSON data for Analytics

### PR DESCRIPTION
**Pull request by ashcoding**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23395

See ticket for testing method.

### CODE REVIEW

**Comment by ashcoding** [comment]
A new `android/titanium/lib/aps-analytics.jar` was placed from https://github.com/appcelerator/aps_sdk/pull/295

**Comment by ashcoding** [comment]
Will be updating this due to new commit in https://github.com/appcelerator/aps_sdk/pull/295

**Comment by ashcoding** [comment]
JAR has been updated with the latest commit changes in https://github.com/appcelerator/aps_sdk/pull/295/commits/50b58bf7be0d2bb893a782f9fa0e8e3f6d6fe686

**Comment by hieupham007** [comment]
Code reviewed and tested. Request **accepted**

**Pull request merged**
