### PR TITLE
[TIMOB-19796] Android: Fixed CardView Layout

### PR DESCRIPTION
**Pull request by ashcoding**
Jira: https://jira.appcelerator.org/browse/TIMOB-19796

Testcode:-

``` javascript
var win = Ti.UI.createWindow({
    backgroundColor: 'white'
});

function createCard(layout, wrap) {

    var card = Ti.UI.Android.createCardView({
        top: 20,
        height: 160,
        layout: layout
    });

    if (wrap) {

        view = Ti.UI.createView({
            layout: layout
        });

        card.add(view);

    } else {
        view = card;
    }

    view.add(Ti.UI.createLabel({
        width: 50,
        height: 100,
        backgroundColor: 'green',
        text: (wrap ? 'reference' : layout) + ' in green',
        color: 'black'
    }));

    view.add(Ti.UI.createLabel({
        top: 10,
        width: 100,
        height: 50,
        backgroundColor: 'red',
        text: (wrap ? 'reference' : layout) + ' in red',
        color: 'black'
    }));

    return card;
}

function createCardWithFill(layout, wrap) {

    var card = Ti.UI.Android.createCardView({
        top: 20,
        width: Ti.UI.FILL,
        height: 160,
        layout: layout
    });

    if (wrap) {

        view = Ti.UI.createView({
            layout: layout
        });

        card.add(view);

    } else {
        view = card;
    }

    view.add(Ti.UI.createLabel({
        width: 50,
        height: 100,
        backgroundColor: 'green',
        text: (wrap ? 'reference' : layout) + ' in green',
        color: 'black'
    }));

    view.add(Ti.UI.createLabel({
        top: 10,
        width: 100,
        height: 50,
        backgroundColor: 'red',
        text: (wrap ? 'reference' : layout) + ' in red',
        color: 'black'
    }));
    return card;
}

function createView(layout, wrap) {

    var card = Ti.UI.createView({
        top: 20,
        width: Ti.UI.FILL,
        height: 160,

        layout: layout
    });

    var view;

    if (wrap) {

        view = Ti.UI.createView({
            layout: layout
        });

        card.add(view);

    } else {
        view = card;
    }

    view.add(Ti.UI.createLabel({
        width: 50,
        height: 100,
        backgroundColor: 'green',
        text: (wrap ? 'reference' : layout) + ' in green',
        color: 'black'
    }));

    view.add(Ti.UI.createLabel({
        top: 10,
        width: 100,
        height: 50,
        backgroundColor: 'red',
        text: (wrap ? 'reference' : layout) + ' in red',
        color: 'black'
    }));

    return card;
}


var scrollView = Ti.UI.createScrollView({
    layout: 'vertical'
});

scrollView.add(createCard('horizontal'));
scrollView.add(createCardWithFill('horizontal'));
scrollView.add(createView('horizontal'));

scrollView.add(createCard('vertical'));
scrollView.add(createCardWithFill('vertical'));
scrollView.add(createView('vertical'));

scrollView.add(createCard('vertical', true));
scrollView.add(createCardWithFill('vertical', true));
scrollView.add(createView('vertical', true));

scrollView.add(createCard('composite'));
scrollView.add(createCardWithFill('composite'));
scrollView.add(createView('composite'));

win.add(scrollView);
win.open();
```

### CODE REVIEW

**Comment by FokkeZB** [comment]
I'm trying to build this PR, but there must be something wrong in my environment because I get:

```
...
    [javac] /Users/fokkezb/dev/forks/titanium_mobile/android/modules/map/src/java/ti/modules/titanium/map/TiMapActivity.java:11: error: package com.google.android.maps does not exist
    [javac] import com.google.android.maps.MapActivity;
    [javac]                               ^
    [javac] /Users/fokkezb/dev/forks/titanium_mobile/android/modules/map/src/java/ti/modules/titanium/map/TiMapActivity.java:13: error: cannot find symbol
    [javac] public class TiMapActivity extends MapActivity
    [javac]                                    ^
    [javac]   symbol: class MapActivity
    [javac] Note: [KrollBindingGen] Generating JSON: file:/Users/fokkezb/dev/forks/titanium_mobile/dist/android/json/org/appcelerator/titanium/bindings/map.json
    [javac] 32 errors

BUILD FAILED
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:592: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:681: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:683: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:660: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:548: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:286: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:228: The following error occurred while executing this line:
/Users/fokkezb/dev/forks/titanium_mobile/android/build/common.xml:174: Compile failed; see the compiler error output for details.

Total time: 11 seconds
```

**Comment by ashcoding** [comment]
Seems like something related with GoogleMaps.

**Comment by FokkeZB** [comment]
haha, yes... I figured out that much ;) Can you send me a build to test?

Btw, for the sake of parity I must say I favoured the `contentView` option. Then you don't need to pass on the view properties (backgroundColor, opacity, layout etc as well).

**Comment by hieupham007** [comment]
Code reviewed and functionally tested. Request **accepted**

**Pull request merged**
