### PR TITLE
chore(android): bump Android minSdkVersion to 19

### PR DESCRIPTION
**Pull request by garymathews**
- Bump `minSdkVersion` from 16 (Android 4.1) to API 19 (Android 4.4)

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26633)

**Test:**
1. Create a new "Classic" Titanium app from template.
2. Build for Android.
3. Go to project folder: `./build/android`
4. Open the "AndroidManifest.xml" file.
5. Verify `<uses-sdk/>` XML attribute "minSdkVersion" is set to `19`.

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by hansemannn** [comment]
Great decision!

**Comment by keerthi1032** [comment]
FR passed. minimum version is set to 19.
Test Environment:
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
  Memory                      = 17179869184
Node.js
  Node.js Version             = 8.12.0
  npm Version                 = 6.4.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = local SDK 8.0.0.v20181206111434
emulator     - nexus 5 android 4.4, pixel xl android 8
Device -     samsung s5

**Comment by keerthi1032** [comment]
PR merged

**Pull request merged**
