### PR TITLE
fix(ios): fix console.log formatting crash on non Apple Silicon devices

### PR DESCRIPTION
**Pull request by hansemannn**
I could not reproduce the initial crash on my device, but this change could fix https://github.com/tidev/titanium_mobile/pull/13738

### CODE REVIEW

**Comment by m1ga** [comment]
same error as before. Just 
```
TitaniumKit                   	       0x103da5dd8 StringFormatCallback + 879
```
is now
```
TitaniumKit                   	       0x103da5dd8 StringFormatCallback + 1026
```

**Comment by hansemannn** [comment]
Weird. Then I am not able to fix it right now, since I don't have any device to test with either :/

**Comment by ottopic** [comment]
Tested SDK 12.2.0.v20230511080743 on Mac Intel but still doesn't work.

**Comment by m1ga** [comment]
any way we can help to get this fixed?

**Comment by hansemannn** [comment]
If someone can get me a non-Apple-Silicon device, I'd love to. Right now, it's super hard to debug without it.

**Comment by ottopic** [comment]
We can organize a remote desktop session

**Comment by m1ga** [comment]
sadly I only have one and need it :smile: 
Perhaps [grover](https://www.grover.com/de-de/computers/laptops?filter=rentalPlan%3D1%26structuredSpecifications%3D%255B%257B%2522name%2522%253A%2522processorBrand%2522%252C%2522values%2522%253A%255B%257B%2522value%2522%253A%2522Intel%25C2%25AE%2522%257D%255D%257D%252C%257B%2522name%2522%253A%2522family%2522%252C%2522values%2522%253A%255B%257B%2522value%2522%253A%2522Macbook%2520Pro%2522%257D%252C%257B%2522value%2522%253A%2522Macbook%2520Air%2522%257D%255D%257D%255D) one for a month?

**Comment by hansemannn** [comment]
@m1ga I just pushed the updated fix that could work. Let me know if it works already!

**Comment by m1ga** [comment]
@hansemannn works fine for me! Well done!

**Comment by hansemannn** [comment]
Nice! 🚀 @ottopic Can you confirm as well?

**Comment by ottopic** [comment]
Yes it works! Thank you @hansemannn

**Pull request merged**
