### PR TITLE
feat(ios): be able to get a list of available system font families

### PR DESCRIPTION
**Pull request by hansemannn**
Maybe Android parity could be added, but it seems like there is no convenient way to do so.

### CODE REVIEW

**Comment by m1ga** [comment]
https://developer.android.com/reference/android/graphics/fonts/SystemFonts#getAvailableFonts()
I can have a look later. But most of the time you only have 3 fonts :smile: Think Samsung phones have more (ugly comic font)

**Comment by hansemannn** [comment]
API 29 😢

**Comment by m1ga** [comment]
https://stackoverflow.com/a/35934857/5193915

```java
	@Kroll.getProperty
	public String[] availableSystemFontFamilies()
	{
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.Q) {
			Set<Font> fonts = SystemFonts.getAvailableFonts();
			String[] list = new String[fonts.size()];
			int count = 0;
			for (Font font: fonts) {
				list[count] = font.getFile().getName().replaceFirst("[.][^.]+$", "");
				count++;
			}
			return list;
		} else {
			String path = "/system/fonts";
			File file = new File(path);
			File[] ff = file.listFiles();
			String[] list = new String[ff.length];
			int count = 0;
			for (File font: ff) {
				list[count] = font.getName().replaceFirst("[.][^.]+$", "");
				count++;
			}
			return list;
		}
	}
```

in UIModule.java

returns
```
[INFO]  [
[INFO]  'NotoSansElbasan-Regular',
[INFO]  'NotoSerif-Italic',
[INFO]  'NotoSansPauCinHau-Regular',
[INFO]  'NotoSansMyanmar-Medium',
[INFO]  'NotoSansMultani-Regular',
[INFO]  'NotoSansInscriptionalParthian-Regular',
[INFO]  'NotoSansAnatolianHieroglyphs-Regular',
[INFO]  'NotoSansTaiViet-Regular',
[INFO]  'NotoSansThaana-Bold',
[INFO]  'NotoSansVai-Regular',
[INFO]  'NotoSansMedefaidrin-VF',
[INFO]  'CutiveMono',
[INFO]  'NotoSansTaiTham-Regular',
[INFO]  'NotoSansBuginese-Regular',
[INFO]  'NotoSansThaiUI-Bold',
...
```
on my Pixel 7. Didn't check an older phone

**Comment by hansemannn** [comment]
Thanks @m1ga!

**Pull request merged**
