### PR TITLE
[TIMOB-24662] Bump to node-titanium-sdk 0.2.2 to get fix for minification using babili

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24662

**Description:**
- need to explicitly specify path to babili in node_modules using require, otherwise babel looked in user's project for it (when minifying user JS)

### CODE REVIEW

**Comment by hansemannn** [comment]
LGTM

**Review by hansemannn — APPROVED** [review]

**Review by mukherjee2 — APPROVED** [review]
Passes FR with this environment:
Node Version: 6.10.1
NPM Version: 3.10.10
Mac OS: 10.12.4
Appc CLI: 6.2.0
Appc CLI NPM: 4.2.9
Titanium SDK version: 6.2.0 PR/9023
XCode 8.3.2

Built with this PR, and project built successfully.

**Comment by mukherjee2** [comment]
@sgtcoolguy FR passed, but "Merge" button is grayed out, and I am unable to merge. What do I need to do?

**Comment by cb1kenobi** [comment]
@mukherjee2 The Jenkins job took a dump while fetching the git repo. According to the job log, it appears the problem is due to https://confluence.atlassian.com/stashkb/git-clone-fails-error-rpc-failed-result-56-http-code-200-693897332.html (bad network). Get a better network.

**Comment by mukherjee2** [comment]
@cb1kenobi @sgtcoolguy @hansemannn  I tried the manual method to merge and it still fails:
To https://github.com/appcelerator/titanium_mobile.git
 ! [remote rejected]       master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/appcelerator/titanium_mobile.git'

I'm on a network that's running at 150 Mb/s, so I don't think it's a network problem. It seems I don't have the right access or something. Can someone just merge it for me? I don't have issues with other PR's, just this one. I am confirming that FR did pass. Thanks.

**Pull request merged**
