### PR TITLE
[TIMOB-26329] Android: Modified build to generate missing "R" classes for libraries added in 7.3.0

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26329

**Test:**
1. Download "hyperloop-examples" project from [here](https://github.com/appcelerator/hyperloop-examples).
2. Build and run on Android.
3. Tap on the "Native Layout (XML)" row in the app.
4. Verify that the app does not crash.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

But we should also remove the duplicate libs located in appcompat and add `design` and `compat` as dependencies of `appcompat`

**Comment by lokeshchdhry** [comment]
FR Passed.

Ran the `Hyperloop-example-master/Native Layout` test & no exception is seen.

Studio Ver:     5.1.0.201808080937
SDK Ver:        7.5.0 local build
OS Ver:         10.13.5
Xcode Ver:      Xcode 9.4.1
Appc NPM:       4.2.13
Appc CLI:       7.0.6-master.5
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.2
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Nexus 6P (Android 8.1.0)

**Comment by lokeshchdhry** [comment]
@jquick-axway , Are we done with this PR ? Also, can you please provide a 7.3.1 backport.

**Comment by jquick-axway** [comment]
I just tested this on Windows and it works. I wanted to make sure that the command line wasn't too long.

@lokeshchdhry, thanks for testing this. I'm going to remove the redundant JAR files Gary found and then back-port it. Stay tuned!

**Comment by jquick-axway** [comment]
Updated PR.

Removed duplicate Google Support JARs.

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Pull request merged**
