### PR TITLE
Update Media.yml

### PR DESCRIPTION
**Pull request by mgkimsal**
Adding note about geo information not available in iOS camera API.

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi @mgkimsal, can you please sign the [cla.appcelerator.com](CLA) and resolve it to work with the latest master? Thank you!

**Comment by hansemannn** [comment]
Closing because of merge conflicts and missing CLA. Feel free to create a new PR based on the master, we would greatly appreciate!

**Comment by mgkimsal** [comment]
When I go to https://developer.appcelerator.com/cla I just get 404 page.

I'd hit this a couple times before, but never get time to come back to this area.  It shouldn't be this hard to get a simple doc patch in.  :/

screen shot 2016-03-23 at 7 25 04 am

**Comment by hansemannn** [comment]
@mgkimsal https://github.com/appcelerator/titanium_mobile/pull/CLA should link you to another page. Will reopen for you to try, thanks :blush:

**Comment by mgkimsal** [comment]
screen shot 2016-03-23 at 7 31 25 am


Maybe I'm just totally unlucky or doing this all wrong, but another 404...

**Comment by hansemannn** [comment]
Seems like github has problem detecting links without http, please try again [here](http://cla.appcelerator.com)

**Comment by hansemannn** [comment]
Closing in favor of https://github.com/appcelerator/titanium_mobile/pull/7964, thank you!

**Pull request closed without merging**
