### PR TITLE
fix(ios): Default background  color of TiRootViewController in framework using shared configuration

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-26557

### CODE REVIEW

**Review by janvennemann — CHANGES_REQUESTED** [review]
Please use property accessors whenever possible, e.g. `UIColor.blackColor` or `TiSharedConfig.defaultConfig.defaultBackgroundColor`

**Comment by vijaysingh-axway** [comment]
For colors, I used property accessor. 'defaultConfig' is a static method.  Setter method is written for defaultBackgroundColor because previous properties  set by using setters, so this will be more aligned with other setters.

**Review by janvennemann — APPROVED** [review]
Thanks, that's a good trade-off for now. Approved!

**Review by ssjsamir — APPROVED** [review]
**FR Passed** Following the instructions mentioned in https://jira.appcelerator.org/browse/TIMOB-26557

**Test Environment** 
```
APPC Studio: 5.1.0.201808080937
iPhone 7 Sim (iOS 12.1)
APPC CLI: 7.0.8
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.1
Node.js Version: 8.9.1
Xcode 10.1
```

**Pull request merged**
