### PR TITLE
[TIMOB-24277] Android: Fix horizontal layout when using 'right' and ‘left’

### PR DESCRIPTION
**Pull request by gimdongwoo**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24277

**Optional Description:**

https://github.com/appcelerator/titanium_mobile/pull/8730 affected to the 'TIMOB-24308' and caused a bug.

Incorrect render occurs when a view have both 'right' and 'left' on horizontal layout.
It's a simple mistake, but it has a big impact because it has complex logic.

I tested this PR on both the ``6_1_X`` branch and the ``Master`` branch, and everything was fine.

I often think that is lack of test cases for changes related to render.
I'm interested in Composite Layout and would like to add me to the reviewer.

[Test Code]
```javascript
var win = Ti.UI.createWindow({
  backgroundColor: '#fff',
  layout: "vertical"
});

/** ************************************************************************
* first row
************************************************************************ */
var view = Ti.UI.createView({
  height: Ti.UI.SIZE,
  width: Ti.UI.FILL,
  layout: "horizontal",
  backgroundColor: "gray"
});

var view1 = Ti.UI.createView({
  width: "25%",
  height: 100,
  backgroundColor: "red"
});

var view2 = Ti.UI.createView({
  width: "25%",
  height: 100,
  backgroundColor: "green"
});

var view3 = Ti.UI.createView({
  width: "25%",
  height: 100,
  backgroundColor: "blue"
});

var view4 = Ti.UI.createView({
  width: "25%",
  height: 100,
  backgroundColor: "yellow"
});

view.add(view1);
view.add(view2);
view.add(view3);
view.add(view4);

/** ************************************************************************
* second row
************************************************************************ */
var v = Ti.UI.createView({
  backgroundColor: 'red',
  width: Ti.UI.FILL,
  height: Ti.UI.SIZE,
  layout: 'horizontal'
});
var n = Ti.UI.createLabel({
  top: 0,
  text: '1.',
  backgroundColor: 'purple'
});
var t = Ti.UI.createLabel({
  text: 'Replenish the Uranium rod with dry ice every 6 hours.',
  width:  Ti.UI.FILL,
  backgroundColor: 'orange'
});

v.add([n, t]);

/** ************************************************************************
* third row
************************************************************************ */
var third = Ti.UI.createView({
  backgroundColor: 'grey',
  left: 20, right: 20,
  width: Ti.UI.FILL,
  height: Ti.UI.SIZE,
  layout: 'horizontal'
});

function createItem(_text) {
  var wrap = Ti.UI.createView({
    backgroundColor:"#ffffff",
    width:Ti.UI.SIZE, height:31,
    left:3, right:3, top:4, bottom: 4,
    borderColor: "#ff5757", borderRadius: 15.5, borderWidth: 1
  });

  var labelWrap = Ti.UI.createView({
    width:Ti.UI.SIZE, height: Ti.UI.SIZE,
    left: 14, right: 14
  });

  var label = Ti.UI.createLabel({
    height : 18,
    width: Ti.UI.SIZE,
    wordWrap:false,
    color:"#ff5757", font: { fontSize: 14, fontWeight: 'regular' },
    textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER, verticalAlign: Ti.UI.TEXT_VERTICAL_ALIGNMENT_CENTER,
    text: _text
  });

  labelWrap.add(label);
  wrap.add(labelWrap);

  return wrap;
}

third.add( createItem('#한자급수') );
third.add( createItem('#자유학기제') );
third.add( createItem('#기반학습') );
third.add( createItem('#많은수업시간') );
third.add( createItem('#레벨시스템') );
third.add( createItem('#담임제도') );

/** ************************************************************************
* foruth row
************************************************************************ */
var template = {
	properties: {
		accessoryType: Ti.UI.LIST_ACCESSORY_TYPE_NONE,
		backgroundColor: 'white',
		height: Ti.UI.SIZE,
		layout: 'horizontal'
	},
	events: {
		click: function(e) {
			alert(e.source.customProperty);
		}
	},
	childTemplates: [
		{
			type: 'Ti.UI.Button',
			bindId: 'bindButton',
			properties: {
				left: 10,
				width: 100,
				height: 40,
				borderRadius: 20,
				borderWidth: 1,
				borderColor: '#dedede',
				backgroundColor: 'green'
			},
		},
		{
			type : 'Ti.UI.Button',
			bindId : 'bindButton2',
			properties : {
				right: 10,
				width: 100,
				height: 40,
				borderRadius: 20,
				borderWidth: 1,
				borderColor: '#dedede',
				backgroundColor: 'red'
			}
		}
	]
};

var listView = Ti.UI.createListView({ templates: { 'template': template } });
var section = Ti.UI.createListSection();

var items = [];
for(var i = 1; i <= 3; i++){
	items.push({
		template: 'template',
		bindButton: {
		   title: 'button a ' + i,
		   customProperty: i
		},
		bindButton2: {
		   title: 'button b ' + i,
		   customProperty: i
		},
		properties: {
		   itemId: i
		}
	});
}

section.setItems(items);
listView.sections = [section];

/** ************************************************************************
* add to win
************************************************************************ */
win.add(view);
win.add(v);
win.add(third);
win.add(listView);

win.open();
```

[Correct]

[Incorrect]

### CODE REVIEW

**Comment by hansemannn** [comment]
Thanks @gimdongwoo! We will review this one and do the backport for you if everything looks good :-).

**Comment by lokeshchdhry** [comment]
FR Passed.

ListView horizontal layout does not ignore `right` & works as expected.

Studio Ver:     4.9.0.201705180402
SDK Ver:        6.2.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.2
Appc NPM:       4.2.9
Appc CLI:       6.2.1
Ti CLI Ver:     5.0.13
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        google Nexus 6 --- Android 6.0.1
Emulator:       Android 4.4.4

**Comment by gimdongwoo** [comment]
This bug also includes 6.1.0.RC, I think it should be merged to the 6_1_X branch too.

Thank you in advance for accepting the PR.

**Comment by hansemannn** [comment]
The Code-Review has not been finished, yet, since @garymathews is on Holiday this week. We will process the final steps asap.

**Comment by gimdongwoo** [comment]
@hansemannn Hans, thanks!
I like Titanium so much.
I am very happy that my tiny commit is included in the Titanium.

**Review by jquick-axway — APPROVED** [review]
CR: Passed

**Comment by hansemannn** [comment]
As FT has been approved earlier we'r ready to merge here and in the backport. @lokeshchdhry Please feel free to close when the build successfully includes the change, thx everyone!

**Pull request merged**
