### PR TITLE
chore: add “Optimize for Mac” option for macOS catalyst builds, add tooltip API

### PR DESCRIPTION
**Pull request by hansemannn**
Enables the "Optimize for Mac" flag like visually in Xcode:

Screenshot 2023-03-02 at 22 11 21

Also adds tooltip support for views and buttons
Screenshot 2023-03-02 at 22 39 55 Screenshot 2023-03-02 at 22 40 52

Example (views):
```js
const win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

const btn = Ti.UI.createView({
    backgroundColor: 'red',
    width: 200,
    height: 100,
    tooltip: 'Click me!'
});

win.add(btn);
win.open();
```

Example (buttons):
```js
const win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

const btn = Ti.UI.createButton({
    title: 'Trigger',
    tooltip: 'Click me!'
});

win.add(btn);
win.open();
```

### CODE REVIEW

**Comment by hansemannn** [comment]
Tested by Cesar, so I assume we can merge this!

**Comment by macCesar** [comment]
In line 3214 of this file:` iphone/cli/commands/_build.js`, you'll also need to check when compiling for the Mac App Store to set the "Optimize for Mac" flag:

```javascript
if (this.target === 'macos' || this.target === 'dist-macappstore') {
  deviceFamily = [...deviceFamily.split(','), '6'].join(',');
}
```

Otherwise, the UI will be at 77% of its original size.

**Comment by hansemannn** [comment]
Interesting. But why would this option only be enabled when deploying for production? I would assume it's a general setting, like recommended by Apple.

**Comment by macCesar** [comment]
But the change I'm suggesting affects both the development and production environments.

Let me explain...

When I tested the production version of my app, I noticed that the entire interface was scaled down, just like before you changed the flag to 'Optimize for Mac'.

After making that change, both versions displayed the interface correctly.

**Pull request merged**
