### PR TITLE
fix(ios): fix leak in TiBlob imageAsCompressed method (7_5_X)

### PR DESCRIPTION
**Pull request by rlustemberg**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26800

The TiBlob.imageAsCompressed method leaks memory as it's not initialising the blob with the page context. For that reason, is not deallocated once it's JS proxy is garbage collected.

### CODE REVIEW

**Comment by garymathews** [comment]
@janvennemann This also needs fixing in `master` and `8_0_X`

**Comment by janvennemann** [comment]
@garymathews master done in #10680 and 8_0_X in #10755

**Review by janvennemann — APPROVED** [review]

**Comment by keerthi1032** [comment]
FR Passed. waiting for resolving Jenkin's failure to merge
Test Environment:
Name = Mac OS X
Version = 10.13.6
Architecture = 64bit
Memory = 17179869184
Node.js
Node.js Version = 8.12.0
npm Version = 6.4.1
Titanium CLI
CLI Version = 5.1.1
Titanium SDK
SDk version =local 7.5 sdk
Studio = 5.1.2.201903111843
Cli =7.0.10
Device =iPhone 6s iOS 12
Simulator = iPhone 6 plus iOS 11.4, iPhone 5s iOS 11

**Comment by keerthi1032** [comment]
FR Passed. Waiting for  fixing Jenkins test failure.
Test Environment:
Name = Mac OS X
Version = 10.13.6
Architecture = 64bit
Memory = 17179869184
Node.js
Node.js Version = 8.12.0
npm Version = 6.4.1
Titanium CLI
CLI Version = 5.1.1
Titanium SDK
SDk version =local 7.5 sdk 
Studio = 5.1.2.201903111843
Cli =7.0.10
Device =iPhone 6s iOS 12
Simulator = iPhone 6 plus iOS 11.4, iPhone 5s iOS 11

**Pull request merged**
