### PR TITLE
[TIMOB-24639] Android: Implement Ti.UI.TextField.hintType

### PR DESCRIPTION
**Pull request by garymathews**
- Implement `Titanium.UI.TextField.hintType` utilizing `android.support.design.InputTextLayout`
- Add test case to `ti.ui.textfield.test.js`

###### TEST CASE
```JS
var win = Ti.UI.createWindow({
        backgroundColor: 'gray',
        layout: 'vertical'
    }),
    a = Ti.UI.createTextField({
        hintText: 'TEXT A',
        width: Ti.UI.FILL
    }),
    b = Ti.UI.createTextField({
        hintText: 'TEXT B',
        hintType: Ti.UI.HINT_TYPE_ANIMATED,
        width: Ti.UI.FILL
    }),
    btn = Ti.UI.createButton({
        title: 'TOGGLE hintType',
        width: Ti.UI.FILL
    });

btn.addEventListener('click', function() {
    a.hintType = (a.hintType === Ti.UI.HINT_TYPE_ANIMATED ? Ti.UI.HINT_TYPE_STATIC : Ti.UI.HINT_TYPE_ANIMATED);
    b.hintType = (b.hintType === Ti.UI.HINT_TYPE_ANIMATED ? Ti.UI.HINT_TYPE_STATIC : Ti.UI.HINT_TYPE_ANIMATED);
});

win.add([a, b, btn]);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24639)

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by ypbnv** [comment]
@garymathews Building a SDK version with the changes found some missing imports. Can you check that. It seems I missed that while merging #9027 
To be more specific:
```
import android.support.design.widget.TextInputLayout;
import android.widget.LinearLayout;
import ti.modules.titanium.ui.UIModule;
```
in TiUiText.java

**Comment by garymathews** [comment]
@ypbnv Updated

**Comment by ypbnv** [comment]
@garymathews Looks good to me!

**Comment by lokeshchdhry** [comment]
FR Passed.

`hintType` works as expected & takes 2 values `Ti.UI.HINT_TYPE_ANIMATED` & `Ti.UI.HINT_TYPE_STATIC`.

Verified it using an alloy & classic app.

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ motorola XT1033 --- Android 4.4.4, Nexus 5 --- Android 6.0.1
Emulator:      Android 7.0

**Comment by lokeshchdhry** [comment]
@garymathews , @ypbnv , Can you guys please resolve the conflict.

**Pull request merged**
