### PR TITLE
fix(android): crash in ListView on API 21

### LINKED ISSUE #13261: Android: crash on API 21 in ListView
### Describe the bug
Application crashed on Android API 21

### App sample
<details>
  <summary>app.js</summary>
   
  ```javascript
        var win = Ti.UI.createWindow({backgroundColor: 'gray'});
        var listView = Ti.UI.createListView({
          separatorStyle: Ti.UI.TABLE_VIEW_SEPARATOR_STYLE_NONE
        });
        var sections = [];
        var fruitDataSet = [
            {properties: { title: 'Apple'}},
            {properties: { title: 'Banana'}},
        ];
        var fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits', items: fruitDataSet});
        sections.push(fruitSection);
        var vegDataSet = [
            {properties: { title: 'Carrots'}},
            {properties: { title: 'Potatoes'}},
        ];
        sections.push(vegSection);
        var vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables', items: vegDataSet});
        listView.sections = sections;
        win.add(listView);
        win.open();
        var fishDataSet = [
            {properties: { title: 'Cod'}},
            {properties: { title: 'Haddock'}},
        ];
        var fishSection = Ti.UI.createListSection({ headerTitle: 'Fish', items: fishDataSet});
        listView.appendSection(fishSection);

  ```
  
</details>

### Environment
Titanium SDK version: 10.1.1.GA

### Logs
<details>
  <summary>Crash log</summary>
  
  ```
(main) [89,111] android.graphics.drawable.NinePatchDrawable cannot be cast to android.graphics.drawable.GradientDrawable

    ti.modules.titanium.ui.widget.TiUIListView.processProperty(TiUIListView.java:230)
    ti.modules.titanium.ui.widget.TiUIListView.processProperties(TiUIListView.java:265)
    org.appcelerator.kroll.KrollProxy.setModelListener(KrollProxy.java:1305)
    org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:491)
    org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:481)
    ti.modules.titanium.ui.widget.listview.ListViewProxy.handleGetView(ListViewProxy.java:526)
    org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:434)
    org.appcelerator.titanium.proxy.TiViewProxy.realizeViews(TiViewProxy.java:498)
    org.appcelerator.titanium.proxy.TiViewProxy.handleGetView(TiViewProxy.java:481)
    org.appcelerator.titanium.proxy.TiViewProxy.getOrCreateView(TiViewProxy.java:434)
    org.appcelerator.titanium.proxy.TiViewProxy.add(TiViewProxy.java:621)
    ti.modules.titanium.ui.WindowProxy.windowCreated(WindowProxy.java:317)
    org.appcelerator.titanium.TiActivityWindows.windowCreated(TiActivityWindows.java:57)
    org.appcelerator.titanium.TiBaseActivity.windowCreated(TiBaseActivity.java:600)
    org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:766)
    org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:47)
    android.app.Activity.performCreate(Activity.java:5937)
    android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
    android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
    android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
    android.app.ActivityThread.access$800(ActivityThread.java:144)
    android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
    android.os.Handler.dispatchMessage(Handler.java:102)
    android.os.Looper.loop(Looper.java:135)
    android.app.ActivityThread.main(ActivityThread.java:5221)
    java.lang.reflect.Method.invoke(Native Method)
    java.lang.reflect.Method.invoke(Method.java:372)
    com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
    com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)  
  ```
  
</details>

### Workarounds

- Always specify `separatorColor`, even with `separatorStyle: Ti.UI.TABLE_VIEW_SEPARATOR_STYLE_NONE`

### PR DESCRIPTION
**Pull request by drauggres**
default `listDivider` on API < 23 is instance of `NinePatchDrawable`, not a `GradientDrawable`.

fix #13261

- [x] fix crash on Android API < 23
- [x] handle `separatorStyle: Ti.UI.TABLE_VIEW_SEPARATOR_STYLE_NONE` on API < 23 (separator souldn't be visible)
- [x] ~handle `separatorStyle: Ti.UI.TABLE_VIEW_SEPARATOR_STYLE_SINGLE_LINE` with non zero `separatorHeight` and no `separatorColor` on Android API 21 (height should be applied)~ Put warning into docs, advise to set `separatorColor` on API < 23

### CODE REVIEW

**Comment by hansemannn** [comment]
@drauggres Thanks for this! It looks quite severe, so I think it should be prioritized. Apart form this PR, is there any workaround for the crash, e.g. setting the separator color?

**Comment by drauggres** [comment]
> @drauggres Thanks for this! It looks quite severe, so I think it should be prioritized. Apart form this PR, is there any workaround for the crash, e.g. setting the separator color?

Yes, you need to always specify a `separatorColor` (even with `separatorStyle: Ti.UI.TABLE_VIEW_SEPARATOR_STYLE_NONE`) to force a non-default separator, which will prevent the exception

**Review by hansemannn — APPROVED** [review]
Tested and working great here! I would wait for @m1ga for another review and then this can be merged! @drauggres Please also rebase this one (if possible, all your open PR's - they are very close to be merged :))

**Comment by drauggres** [comment]
> Please also rebase this one (if possible, all your open PR's - they are very close to be merged :))

Done.

I think [this](
https://docs.github.com/en/repositories/configuring-branches-and-merges-in-your-repository/configuring-pull-request-merges/managing-suggestions-to-update-pull-request-branches#managing-suggestions-to-update-a-pull-request-branch) option was enabled in the appcelerator repo, but it is disabled now.
It adds the `Update branch` button, so maintainers and author can quickly merge `master` into PR source branch.

**Comment by hansemannn** [comment]
cc @cb1kenobi Can you re-enable the `Update Branch` button? It actually was there until last weekend 😇

**Pull request merged**
