### PR TITLE
[TIMOB-24730](6_2_X):iOS Remove old statements (e.g. ![TiUtils isIOS8OrGreater])

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-24730

### CODE REVIEW

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@vijaysingh-axway After approving this, I noticed that the number of changed lines and commits are different to the master PR (#9088). Please validate that to ensure you did not cherry-pick incorrect commits to this branch.

**Review by hansemannn — CHANGES_REQUESTED** [review]
See above

**Comment by vijaysingh-axway** [comment]
@hansemannn While cherry-picking I got some conflict. Due to resolving that number of lines and commit are different. I have verified the changes by comparing, changes in each file. But I would request you to have a second pair of eye on these changes. Thanks.

**Comment by hansemannn** [comment]
Closing in favor of #9316.

**Pull request closed without merging**
