### PR TITLE
[TIMOB-24851] Android: Deprecated Ti.UI.Label "wordWrap" property

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-24851

**Summary:**
- "wordWrap" property now ignored. Will log deprecation warning when attempting to set it.
- This property is not supported on iOS, making it not portable.
- The equivalent of "wordWrap" set to `false` can be done via "maxLines" set to `1`, which is portable on all platforms.
- See ticket for explanations why this should be deprecated.

**Test:**
1. Build and run the below on Android.
2. Verify that top label shows 2 lines and bottom label only shows 1 line with `...` ellipsis.
3. Verify that the following warning was logged.
`Ti.UI.Label property 'wordWrap' is deprecated. If setting false, then set 'maxLines' to 1 instead.`
4. Comment out the 2 "wordWrap" property lines from the below code.
5. Rebuild and run on Android.
6. Verify that top label shows 2 lines and bottom label only shows 1 line with `...` ellipsis.
7. Verify that a "wordWrap" deprecation warning was **NOT** logged.

```javascript
var window = Ti.UI.createWindow();
window.add(Ti.UI.createLabel({
	text: "This is line 1.\nThis is line 2.",
	wordWrap: true,
	top: "25%",
}));
window.add(Ti.UI.createLabel({
	text: "This is line 1.\nThis is line 2.",
	maxLines: 1,
	wordWrap: false,
	top: "75%",
}));
window.open();
```

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by lokeshchdhry** [comment]
FR Passed.

Property is ignored by default now.
Using `wordWrap` property the expected deprecation warning is seen as expected.
Not using `wordWrap` property no warning is seen. 

Studio Ver:     5.1.2.201810301430
SDK Ver:        8.0.0 local build
OS Ver:         10.14
Xcode Ver:      Xcode 10.1
Appc NPM:       4.2.13
Appc CLI:       7.0.8-5
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.4
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Nexus 6P (Android 8.1.0)
Emulator:       ⇨ Android 4.1.2

**Comment by lokeshchdhry** [comment]
@jquick-axway , on Nexus 6P Android 8.1 I get this warning:
```
[WARN] :   [Nexus 6P] StaticLayout: maxLineHeight should not be -1.  maxLines:1 lineCount:1
```

**Comment by jquick-axway** [comment]
@lokeshchdhry, this warning has always been there. It happens when you assign property "maxLines" to a value less than the actual line count. The feature still works, but Google wrongly logs a warning on every layout (it's not updating it's internally cached height and reculates the height on every re-layout instead). It's a false-positive and it hasn't been a big enough priority for me to look into a work-around.

**Pull request merged**
