### PR TITLE
Fix xcodebuild dest, bump min iOS target to 9, disable ONLY_ACTIVE_ARCH for 32-bit sims

### PR DESCRIPTION
**Pull request by cb1kenobi**
* Fixes the xcodebuild dest loop not breaking which fixes https://jira.appcelerator.org/browse/TIMOB-27338
* Fixes the app icon issue https://jira.appcelerator.org/browse/TIMOB-27470.

### CODE REVIEW

**Review by ewanharris — APPROVED** [review]
CR looks good

@cb1kenobi do you think this will fix any issues mentioned in appcelerator/ioslib/pull/101? I think keeping this "just pick a simulator" we're doing in this block of code is causing issues with xcodebuild

**Comment by ssekhri** [comment]
FR Passed.
Verified On:
Mac OS: 10.14.5
SDK: 8.3.0.v20191015071817
Appc CLI: 7.1.1
JDK: 1.8.0_162
Node: 10.5.0
Studio: 5.1.4.201909061933
Xcode: 11.0, 10.3
iOS simulator v13.0, 12.4, 12.2

**Comment by ewanharris** [comment]
@ssekhri @cb1kenobi do we want to push the ioslib@v1.7.15 update into this PR also so that we can fix the issues we're seeing on some Jenkins nodes?

**Comment by cb1kenobi** [comment]
@ewanharris ioslib@1.7.15 has not been published yet. We can hold off on this PR until it is published... hopefully later today.

**Comment by lokeshchdhry** [comment]
@cb1kenobi , Is this PR all goods to get tested ?

**Comment by cb1kenobi** [comment]
@lokeshchdhry No. Ewan found an issue he sent me in DM. Investigating now.

**Comment by cb1kenobi** [comment]
Note: this PR requires this ioslib PR: https://github.com/appcelerator/ioslib/pull/102.

**Comment by ewanharris** [comment]
ioslib PR was good so I published it and updated it here and in #11282

**Comment by ewanharris** [comment]
@lokeshchdhry this is good for testing now. You can find info about the testing I've done so far here https://github.com/appcelerator/ioslib/pull/102#issuecomment-543153990

**Comment by lokeshchdhry** [comment]
FR Passed.

Followed tests here https://github.com/appcelerator/ioslib/pull/102#issuecomment-543153990

SDK: 8.2.1 local build

**Pull request merged**
