### PR TITLE
[TIMOB-19555] HTTPClient fails when no contentType is specified

### PR DESCRIPTION
**Pull request by manojdcoder**
JIRA: https://jira.appcelerator.org/browse/AC-365

Modified cod for null check of contentType

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi Mano, thank you for your PR! Can you check the indentation level to be conform with the rest of the code? Our legacy code often has tabs instead of spaces. Thank you!

**Comment by mano-mykingdom** [comment]
@hansemannn: Hope it meets the indentation level now.

**Comment by ashcoding** [comment]
Jira ticket https://jira.appcelerator.org/browse/TIMOB-19555

**Comment by ashcoding** [comment]
Code reviewed and functionally tested with test code in jira ticket. Working well.
**Approved**

:+1: Thanks @mano-mykingdom

**Pull request merged**
