### PR TITLE
[TIMOB-25661] Android: Fix broken animation behaviour on Android 7.0+

### PR DESCRIPTION
**Pull request by garymathews**
- Disable hardware acceleration for `TiBorderWrapperView` to prevent broken animation behaviour on Android 7.0 and above

###### TEST CASE
```JS
var win = Ti.UI.createWindow({ backgroundColor: 'gray' }),
    base = Ti.UI.createView({
        backgroundColor: 'blue',
        width: 200,
        height: 200,
        borderRadius: 100
    })
    sqr = Ti.UI.createView({
        width: 140,
        height: 140,
        backgroundColor: 'red'
    }),
    animation = Ti.UI.createAnimation({
        duration : 3000,
        transform : Ti.UI.create2DMatrix().rotate(-45)
    });

win.addEventListener('open', function () {
    setTimeout(function () {
        base.animate(animation);
    }, 1000);
});

base.add(sqr);
win.add(base);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25661)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

Animation behavior seems to work as expected.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.1.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.11
Appc CLI:       7.0.1
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel XL --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1
                     google pixel --- Android 7.1.1
Emulator: Android 7.0.0

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by ypbnv** [comment]
@lokeshchdhry That's good to go for merging.

**Comment by lokeshchdhry** [comment]
@garymathews , I see there is a test failure here can you please fix it.

**Pull request merged**
