### PR TITLE
[TIMOB-15249] Android: TableView header and footer cannot be removed or resized dynamically

### PR DESCRIPTION
**Pull request by drauggres**
https://jira.appcelerator.org/browse/TIMOB-15249

[TIMOB-15249] unset headerView and footerView in tableView on android

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

###### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor: 'gray'}),
    headerView = Ti.UI.createView({
        backgroundColor: 'red',
        height: 100,
        width: Ti.UI.FILL
    }),
    footerView = Ti.UI.createView({
        backgroundColor: 'green',
        height: 100,
        width: Ti.UI.FILL
    }),
    table = Ti.UI.createTableView({
        headerView: headerView,
        footerView: footerView,
        data: [
            {title: 'ITEM'}
        ]
    });

setTimeout(function() {
    table.headerView = null;
    table.footerView = null;
}, 3000);

win.add(table);
win.open();
```

**Comment by ssjsamir** [comment]
@garymathews When using the following test case: (https://jira.appcelerator.org/browse/TIMOB-15249)


```
var w = Ti.UI.createWindow({
backgroundColor: 'gray'
});
 
var t = Ti.UI.createTableView({
data: [
{ title: 'One' },
{ title: 'Two' },
{ title: 'Three' },
{ title: 'Four' },
{ title: 'Five' }
]
});
 
var h = Ti.UI.createView({
backgroundColor: 'red',
height: 25,
width: Ti.UI.FILL
});
 
h.addEventListener('click', function () {
h.height = 50;
f.height = 50;
});
 
var f = Ti.UI.createView({
backgroundColor: 'green',
height: 25,
width: Ti.UI.FILL
});
 
f.addEventListener('click', function () {
t.headerView = null;
t.footerView = null;
});
 
t.headerView = h;
t.footerView = f;
 
w.add(t);
w.open();

```
when I try the test case in the ticket I am able to close the headerView and footerView when pressing on green but I am unable to resize it when pressing on red.

**Test Environement**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

**Comment by sgtcoolguy** [comment]
@garymathews @drauggres So it sounds like this PR supports explicitly removing or replacing the header/footer view, but not resizing it? Looking at the changes and the test case @ssjsamir mentions, do we need to hook any sort of listeners to the header/footer view to adjust to changes to some subset of it's properties (as here we adjust the height)?

**Comment by drauggres** [comment]
@sgtcoolguy, PR adds only removing support. I didn't find a way to inform TableView about header/footer height change.

**Comment by lokeshchdhry** [comment]
@garymathews , As this PR just adds support to remove the header & footer view & the ticket says resize as well. Is the PR complete & ready for an FR & closing ?

**Comment by drauggres** [comment]
@hansemannn Actually in latest SDK we can't remove footer and header from tableView ("null
 object reference", this fixed in first commit, but resizing wasn't there when you posted your comment.
Now resizing should be fine too.

**Comment by hansemannn** [comment]
@drauggres You can add the following unit-test and verify if it works already (may be linting/timeout errors on the initial draft):

*tests/ti.ui.tableview.addontest.js*

/*
 * Appcelerator Titanium Mobile
 * Copyright (c) 2015-Present by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
/* eslint-env mocha */
/* global Ti */
/* eslint no-unused-expressions: "off" */
'use strict';
var should = require('./utilities/assertions');

describe('Titanium.UI.TableView', function () {
	it('Add and remove headerView/footerView ', function (finish) {
		var win = Ti.UI.createWindow({ backgroundColor: 'gray' }),
		headerView = Ti.UI.createView({
			backgroundColor: 'red',
			height: 100,
			width: Ti.UI.FILL
		}),
		footerView = Ti.UI.createView({
			backgroundColor: 'green',
			height: 100,
			width: Ti.UI.FILL
		}),
		table = Ti.UI.createTableView({
			headerView: headerView,
			footerView: footerView,
			data: [
				{ title: 'ITEM' }
			]
		});

		win.addEventListener('open', function () {
			table.headerView = null;
			table.footerView = null;

			finish();
		});

		win.add(table);
		win.open();
	});
});
```

*NOTE*: There currently is a addon-test for the table-view already, which I just migrated. Once https://github.com/appcelerator/titanium_mobile/pull/10057 is merged, you can commit your file.

**Comment by drauggres** [comment]
Removing works. I will add your test later (`tests/Resources/ti.ui.tableview.addontest.js` I assume).
Not sure if it's possible to write test on resizing case.

**Comment by jquick-axway** [comment]
@ssjsamir, please re-run the following header/footer resize test to verify that it was fixed. From looking at the posts, it's the only issue that we haven't confirmed fixed yet. Thanks.
https://github.com/appcelerator/titanium_mobile/pull/9193#issuecomment-314890439

**Pull request merged**
