### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by ssx**

### CODE REVIEW

**Comment by cb1kenobi** [comment]
@ssx Thanks much for the PR! Can you please sign the CLA quick and I'll get this merged? https://cla.appcelerator.com. Thanks!

**Comment by ssx** [comment]
@cb1kenobi: done! 👍

**Comment by cb1kenobi** [comment]
**APPROVED**! Waiting for the CI build. Thanks again for the PR! :)

**Comment by ssx** [comment]
No problem, just noticed it as I was reading! :)

**Pull request merged**
