### PR TITLE
[TIMOB-18114] CLI: Android: Enable developers to specify arguments to dex command

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/TIMOB-18114
Original PR : https://github.com/appcelerator/titanium_mobile/pull/5645, pull to 4.0.0 with style fixes.

### CODE REVIEW

**Comment by ingo** [comment]
Please cherry-pick the original commit and create a new commit with the modifications. We want to preserve the original authorship as well as your changes.

**Comment by feons** [comment]
Cherry-picked original commit.

**Comment by ashcoding** [comment]
Code reviewed and functionally tested. It's working.

**Comment by skypanther** [comment]
CR and FR passed, **APPROVED**

**Pull request merged**
