### PR TITLE
impr(android): implement foregroundServiceType parameter

### PR DESCRIPTION
**Pull request by garymathews**
- Implement `foregroundServiceType` parameter into `Ti.Android.Service.foregroundNotify`

##### TEST CASE
**tiapp.xml**
```XML
<android>
  <manifest>
    <uses-permission android:name="android.permission.ACCESS_BACKGROUND_LOCATION"/>
    <uses-permission android:name="android.permission.FOREGROUND_SERVICE"/>
  </manifest>
  <services>
    <service url="locationService.js" android:foregroundServiceType="location"/>
  </services>
</android>
```
**locationService.js**
```JS
console.log(`Background location service started.`);

// Create foreground service.
Ti.Android.currentService.foregroundNotify(
	123,
	Ti.Android.createNotification({
		contentTitle: "Background Location Service",
		contentText: "Obtaining location data...",
		contentIntent: Ti.Android.createPendingIntent({
			intent: Ti.App.Android.launchIntent || Ti.Android.createIntent(),
		})
	}),
	Ti.Android.FOREGROUND_SERVICE_TYPE_LOCATION
);
```
**app.js**
```JS
const win = Ti.UI.createWindow({ backgroundColor: 'gray', layout: 'vertical' });
const backgroundServiceBtn = Ti.UI.createButton({ title: 'START BACKGROUND SERVICE' });
const listView = Ti.UI.createListView();

let count = 1;
let service = null;

// Set accuracy to high
Ti.Geolocation.accuracy = Ti.Geolocation.ACCURACY_HIGH;
 
// Enable manual configuration via location providers.
Ti.Geolocation.Android.manualMode = true;
 
// Define a location provider.
Ti.Geolocation.Android.addLocationProvider(
    Ti.Geolocation.Android.createLocationProvider({
        name: Ti.Geolocation.Android.PROVIDER_GPS,
        minUpdateDistance: 0,
        minUpdateTime: 5000
    })
);
 
function getLocation () {

    // Create location event listener.
    Ti.Geolocation.addEventListener('location', e => {

        // Create new section for location data.
        let section = Ti.UI.createListSection({ headerTitle: `#${count++} - ${new Date().toTimeString()}` });
        if (e.success) {
            if (e.coords) {
                e = e.coords;
            }

            // Insert location data.
            section.setItems([
                { properties: { title: 'LOCATION:\n' + e.latitude + ', ' + e.longitude, color: 'green' } },
                { properties: { title: 'ALTITUDE:\n' + e.altitude, color: 'green' } },
                { properties: { title: 'ACCURACY:\n' + e.accuracy, color: 'green' } }
            ]);

        } else {

            // Oops! Something bad happened.
            section.setItems([
                { properties: { title: 'ERROR:\n' + e.error, color: 'red' } }
            ]);
        }

        // Add section to listView
        listView.appendSection(section);
    });
}
 
win.addEventListener('open', () => {

    // Request location permissions.
    Ti.Geolocation.requestLocationPermissions(Ti.Geolocation.AUTHORIZATION_ALWAYS, e => {
        if (e.success) {
            getLocation();
        } else {
            alert('Could not obtain location permissions.');
        }
    });
});

backgroundServiceBtn.addEventListener('click', () => {
    if (!service) {

        // Create background location service.
        const intent = Ti.Android.createServiceIntent({ url : 'locationService.js' });
        service = Ti.Android.createService(intent);

        console.log('Starting background location service...');

        // Android 10+ request background location permissions.
        if (parseInt(Ti.Platform.version.split('.')[0]) >= 10) {
            Ti.Android.requestPermissions([ 'android.permission.ACCESS_BACKGROUND_LOCATION' ], e => {
                if (e.success) {
                    service.start();
                    backgroundServiceBtn.title = 'STOP BACKGROUND SERVICE';
                } else {
                    alert('Could not obtain background location permissions.');
                }
            });
        } else {
            service.start();
            backgroundServiceBtn.title = 'STOP BACKGROUND SERVICE';
        }

    } else {
        console.log('Stopping background location service...');
        
        service.stop();
        backgroundServiceBtn.title = 'START BACKGROUND SERVICE';
    }
});
 
win.add([backgroundServiceBtn, listView]);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26953)

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by keerthi1032** [comment]
@garymathews  on clicking start background button error throws. [ERROR] :  TiServiceProxy: (main) [14,25829] foregroundServiceType 0x00000008 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file

[ERROR] :  TiServiceProxy: java.lang.IllegalArgumentException: foregroundServiceType 0x00000008 is not a subset of foregroundServiceType attribute 0x00000000 in service element of manifest file

[ERROR] :  TiServiceProxy: at android.os.Parcel.createException(Parcel.java:2075)

[ERROR] :  TiServiceProxy: at android.os.Parcel.readException(Parcel.java:2039)

[ERROR] :  TiServiceProxy: at android.os.Parcel.readException(Parcel.java:1987)

[ERROR] :  TiServiceProxy: at android.app.IActivityManager$Stub$Proxy.setServiceForeground(IActivityManager.java:6136)

[ERROR] :  TiServiceProxy: at android.app.Service.startForeground(Service.java:742)

[ERROR] :  TiServiceProxy: at org.appcelerator.titanium.proxy.ServiceProxy$2.run(ServiceProxy.java:366)

[ERROR] :  TiServiceProxy: at org.appcelerator.kroll.KrollProxy.runWithHandler(KrollProxy.java:454)

[ERROR] :  TiServiceProxy: at org.appcelerator.kroll.KrollProxy.runOnMainThread(KrollProxy.java:426)

[ERROR] :  TiServiceProxy: at org.appcelerator.titanium.proxy.ServiceProxy.updateForegroundState(ServiceProxy.java:261)

[ERROR] :  TiServiceProxy: at org.appcelerator.titanium.proxy.ServiceProxy.foregroundNotify(ServiceProxy.java:152)

[ERROR] :  TiServiceProxy: at org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)

[ERROR] :  TiServiceProxy: at org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:162)

[ERROR] :  TiServiceProxy: at org.appcelerator.kroll.KrollRuntime.runModule(KrollRuntime.java:211)

[ERROR] :  TiServiceProxy: at ti.modules.titanium.android.TiJSService.executeServiceCode(TiJSService.java:74)

[ERROR] :  TiServiceProxy: at ti.modules.titanium.android.TiJSService.start(TiJSService.java:96)

[ERROR] :  TiServiceProxy: at org.appcelerator.titanium.proxy.ServiceProxy.invokeBoundService(ServiceProxy.java:235)

[ERROR] :  TiServiceProxy: at org.appcelerator.titanium.proxy.ServiceProxy$1.onServiceConnected(ServiceProxy.java:188)

[ERROR] :  TiServiceProxy: at android.app.LoadedApk$ServiceDispatcher.doConnected(LoadedApk.java:1948)

[ERROR] :  TiServiceProxy: at android.app.LoadedApk$ServiceDispatcher$RunConnection.run(LoadedApk.java:1980)

[ERROR] :  TiServiceProxy: at android.os.Handler.handleCallback(Handler.java:883)

[ERROR] :  TiServiceProxy: at android.os.Handler.dispatchMessage(Handler.java:100)

[ERROR] :  TiServiceProxy: at android.os.Looper.loop(Looper.java:214)

[ERROR] :  TiServiceProxy: at android.app.ActivityThread.main(ActivityThread.java:7356)

[ERROR] :  TiServiceProxy: at java.lang.reflect.Method.invoke(Native Method)

[ERROR] :  TiServiceProxy: at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)

[ERROR] :  TiServiceProxy: at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)

[ERROR] :  TiServiceProxy: Caused by: android.os.RemoteException: Remote stack trace:

[ERROR] :  TiServiceProxy: at com.android.server.am.ActiveServices.setServiceForegroundInnerLocked(ActiveServices.java:1276)

[ERROR] :  TiServiceProxy: at com.android.server.am.ActiveServices.setServiceForegroundLocked(ActiveServices.java:914)

[ERROR] :  TiServiceProxy: at com.android.server.am.ActivityManagerService.setServiceForeground(ActivityManagerService.java:13968)

[ERROR] :  TiServiceProxy: at android.app.IActivityManager$Stub.onTransact(IActivityManager.java:2784)

[ERROR] :  TiServiceProxy: at com.android.server.am.ActivityManagerService.onTransact(ActivityManagerService.java:2741)

[ERROR] :  TiServiceProxy:

**Comment by garymathews** [comment]
@keerthi1032 Could you re-test this? I forgot to include the `android:foregroundServiceType` tag in my test case:
tiapp.xml
```XML
...
<service url="locationService.js" android:foregroundServiceType="location"/>
...
```

**Review by ssjsamir — APPROVED** [review]
FR Passed: `Service.foregroundNotify()` now supports `"foregroundServiceType"` for Android Q. Tested  with the test case mentioned above.

**Note:** for the test case I changed the `backgroundServiceBtn.addEventListener` to include `service = null` after the final `else`.
```
console.log('Stopping background location service...');

        service.stop();
        backgroundServiceBtn.title = 'START BACKGROUND SERVICE';
        service = null;
```

**Test Environment**
```
MacOS Catalina 10.15 Beta
Node.js ^8.11.1
Android Pixel XL 7.1 Emulator 
"NPM":"4.2.15","CLI":"7.1.1"
Java Version 1.8.0_131
Android NDK:  12.1.2977051
```

**Pull request merged**
