### PR TITLE
fix(ios): also lookup semnantic colors in correct location for classic (8_2_X)

### PR DESCRIPTION
**Pull request by ewanharris**
As it's intended to be cross platform this is the right place for a classic app

Fixes TIMOB-27403

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27403

Backport for #11217

### CODE REVIEW

**Review by ssjsamir — APPROVED** [review]
FR Passed: The look up for semantic lookup now works correctly. Tested with the test steps mentioned in: https://jira.appcelerator.org/browse/TIMOB-27403

**Test Environment**
```
MacOS Mojave version 10.14.4
Xcode 11 beta 5
Node.js ^8.11.1
iPhone 7 (13.0 GM)
"NPM":"4.2.15","CLI":"7.1.1"
```

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by KamalKant-Tech** [comment]
This is still not working for me. Please check this below code snippet and correct me If I am missing something.
```
var colorWindow = Ti.UI.fetchSemanticColor("backgroundColor");


var win = Ti.UI.createWindow({
    title: 'Demo App',
    backgroundColor: colorWindow,
    layout: 'vertical'
});
var view = Ti.UI.createView({
    center: { x: 205, y: 250 },
    height: 400,
    width: 300,
    backgroundColor: colorWindow,
    layout: 'vertical',
    top: '20%'
});

win.add(view);
win.add(top);
win.open();
````

semantic.colors.json file content:
```
{
  "backgroundColor": {
    "light": "#E32121",
    "dark": "#000000"
  }
}
```

App Folder structure:

> Resource > app.js 
> Resource > semantic.colors.json

**Comment by ewanharris** [comment]
@KamalKant-Tech, you code is working fine for me on SDK 9.0.3.GA. This fix shipped in 8.2.1.GA so please make sure you're using the correct SDK

**Comment by KamalKant-Tech** [comment]
Thats working. Sorry I did not update it here.

**Pull request merged**
