### PR TITLE
fix(ios): apply “overrideUserInterfaceStyle” to main app window

### LINKED ISSUE #13328: iOS: Overriding the dark mode / light mode is not applied to modal windows
### Describe the bug
Using `Ti.UI.overrideUserInterfaceStyle`, it is possible to override the system light / dark mode. Unfortunately, this is currently not applied to modal windows.

### To Reproduce
Run the following code:*
```js
Ti.UI.overrideUserInterfaceStyle = Ti.UI.USER_INTERFACE_STYLE_DARK;

const win = Ti.UI.createWindow({
	backgroundColor: 'blue',
	title: 'Main Window'
});
win.add(Ti.UI.createLabel({ top: 100, text: 'Window-Title should be white!' }));

const btn = Ti.UI.createButton({
	title: 'Open Sub-Window'
});

btn.addEventListener('click', () => {
	const window = Ti.UI.createWindow({ title: 'Sub-Window', backgroundColor: 'red' });
	window.add(Ti.UI.createLabel({ top: 100, text: 'Window-Title should be white!' }));
	const nav = Ti.UI.createNavigationWindow({ window });
	nav.open({ modal: true });
});

win.add(btn);

const nav = Ti.UI.createNavigationWindow({ window: win });
nav.open();
```

### Expected behavior
The window title of the modally opened window is white (indicating dark mode, in contrast to the black title on light modes)

### Environment
Titanium SDK version: 10.2.0 (master)
CLI version: 5.4.1

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes #13328

```js
Ti.UI.overrideUserInterfaceStyle = Ti.UI.USER_INTERFACE_STYLE_DARK;

const win = Ti.UI.createWindow({
	backgroundColor: 'blue',
	title: 'Main Window'
});
win.add(Ti.UI.createLabel({ top: 100, text: 'Window-Title should be white!' }));

const btn = Ti.UI.createButton({
	title: 'Open Sub-Window'
});

btn.addEventListener('click', () => {
	const window = Ti.UI.createWindow({ title: 'Sub-Window', backgroundColor: 'red' });
	window.add(Ti.UI.createLabel({ top: 100, text: 'Window-Title should be white!' }));
	const nav = Ti.UI.createNavigationWindow({ window });
	nav.open({ modal: true });
});

win.add(btn);

const nav = Ti.UI.createNavigationWindow({ window: win });
nav.open();
```

### CODE REVIEW

**Comment by hansemannn** [comment]
@mbender74 Can you maybe review this one?

**Comment by hansemannn** [comment]
Anyone else (maybe @caspahouzer) who can test thid?

**Review by caspahouzer — APPROVED** [review]
LGTM
Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-06 at 10 10 33

**Comment by mbender74** [comment]
sorry, late for the party.... I will submit soon another fix for control the background color (in the screen black) to be able to coloring it as wanted....

**Pull request merged**
