### PR TITLE
fix: fix adaptive background gradients

### LINKED ISSUE #13446: iOS: The "backgroundGradient" colors do not change when switching between light-/dark-mode
### Description

On iOS, the "backgroundGradient" colors do not change when switching between light-/dark-mode, even when set to semantic colors.

### Expected Behavior

The colors should be adaptive.

### Actual behavior

The colors are static.

#### semantic.colors.json
```json
{
  "color1": {
    "light": "#ffffff",
    "dark": "#000000"
  },
  "color2": {
    "light": "#cccccc",
    "dark": "#777777"
  }
}
```

#### app.js
```js
const window = Ti.UI.createWindow();
const view = Ti.UI.createView({
	backgroundGradient: {
		type: 'linear',
		colors: [ 'color1', 'color2' ],
		startPoint: { x: '100%', y: 0 },
		endPoint: { x: 0, y: '100%' },
		backFillStart: false
	}
});
window.add(view);
window.open();

```

### Steps to reproduce

1. Add the new files
2. Run the app
3. Switch between light- and dark-mode
4. Notice that the gradients do not change.

### Platform

iOS

### SDK version you are using

10.1.1.GA, 10.2.0 (master)

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes https://github.com/tidev/titanium_mobile/issues/13446

### CODE REVIEW

**Comment by hansemannn** [comment]
@caspahouzer can you please test the fix?

**Comment by caspahouzer** [comment]
I've tested with https://github.com/tidev/titanium_mobile/suites/6507492412/artifacts/241929498

Generally, the colors are switched. But I have to restart the app completely instead of just switching to dark mode. This means, a change on runtime is not possible. Can you confirm that?

https://drive.google.com/file/d/1-26L7ZnAGoB99zcq1PFZPgZ__GHbr3FN/view?usp=sharing

**Comment by hansemannn** [comment]
Okay, thanks! Then I have to refine it. But you definitely checked out my branch / downloaded the PR SDK before?

**Comment by caspahouzer** [comment]
I took the video with the SDK build from this PR and set the SDK in my `tiapp.xml` in my classic test project

```
[INFO]  tiapp.xml <sdk-version> set to 11.0.0.v20220514165830, but current Titanium SDK set to 10.1.1.GA
[INFO]  Forking correct SDK command: "/usr/local/bin/node" "/usr/local/bin/ti" "build" "--sdk" "11.0.0.v20220514165830" "--skip-js-minify" "--liveview" "--config-file" "/Users/sebastianklaus/.titanium/config.json" "--platform" "iphone" "--project-dir" "/Users/sebastianklaus/Documents/Apps/classic" "--log-level" "trace" "--device-id" "BD1BA3C8-BF22-41E1-B064-AFBF6B6185AF" "--target" "simulator"
```

**Comment by hansemannn** [comment]
@caspahouzer Changed!

**Review by caspahouzer — APPROVED** [review]
Tried with [mobilesdk-11.0.0.v20220517063216-osx](https://github.com/tidev/titanium_mobile/suites/6535371507/artifacts/243796275) and it works perfect!

LGTM

**Pull request merged**
