### PR TITLE
[TIMOB-25867] Android: Running an application through CLI flickers it's main activity at launch.

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25867

**Description:**
Bump node-titanium-sdk version dependency.

**Test case:**
Just start an empty application through CLI.

### CODE REVIEW

**Review by hansemannn — APPROVED** [review]
Looks good, but I'd like to know @jquick-axway 's opinion on this first, so we don't miss anything.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by hansemannn** [comment]
@ypbnv I have updated the node-titanium-sdk version to `0.4.11` which includes Josh's latest fixes on the Android launching as well.

**Comment by lokeshchdhry** [comment]
Can anybody please fix the lint errors. Looks like the package.json and package-lock.json as not in sync.

**Comment by hansemannn** [comment]
Closing in favor of https://github.com/appcelerator/titanium_mobile/pull/10092.

**Pull request closed without merging**
