### PR TITLE
[TIMOB-24265] Android: Fix unsupported relaunch for Marshmallow and above

### PR DESCRIPTION
**Pull request by garymathews**
- Let Android handle application restart on Android API 23+
- This should prevent the application from crashing when permissions have been revoked during suspend

###### TEST CASE
- Project on JIRA

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24265)

### CODE REVIEW

**Comment by m1ga** [comment]
Testing this patch produces a libkroll crash from time to time. 
See this jira ticket for a complete log:
https://jira.appcelerator.org/browse/TIMOB-20500?focusedCommentId=407442&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-407442

Happens when trying to close a restarted app

**Comment by maggieaxway** [comment]
CR FT pass

Test case:

Run the app
Grant storage permission
Press Home to send app to background
Open Settings or App Info
Revoke storage permission
Try to go back to the app

**Comment by lokeshchdhry** [comment]
@garymathews @maggieaxway - On a google pixel XL I am seeing the following behaviour:
1.  I run the app & grant permissions.
2. Press home & suspend the app.
3. Open settings & revoke `storagePermissions`.
4. Get back to the app - I could get back to the app but In the logcat I see
```
02-23 13:53:10.890  1036  1120 W WindowManager: Failed looking up window
02-23 13:53:10.890  1036  1120 W WindowManager: java.lang.IllegalArgumentException: Requested window android.view.ViewRootImpl$W@3378f57 does not exist
02-23 13:53:10.890  1036  1120 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9415)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9406)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at com.android.server.wm.WindowManagerService.removeWindow(WindowManagerService.java:2387)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at com.android.server.wm.Session.remove(Session.java:193)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at android.view.ViewRootImpl.dispatchDetachedFromWindow(ViewRootImpl.java:3290)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at android.view.ViewRootImpl.doDie(ViewRootImpl.java:5917)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at android.view.ViewRootImpl$ViewRootHandler.handleMessage(ViewRootImpl.java:3626)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at android.os.Handler.dispatchMessage(Handler.java:102)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at android.os.Looper.loop(Looper.java:154)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at android.os.HandlerThread.run(HandlerThread.java:61)
02-23 13:53:10.890  1036  1120 W WindowManager: 	at com.android.server.ServiceThread.run(ServiceThread.java:46)
```
5. Click on the label & again grant `storagePermissions`.
6. Now close the app using the android back button - I see message that the app has stopped :
```
02-23 13:53:40.286  1036 10133 I ActivityManager: Process com.moovel.storagepermissions.example (pid 29966) has died
02-23 13:53:40.286  1036 10133 D ActivityManager: cleanUpApplicationRecord -- 29966
02-23 13:53:40.293  1036  1401 W InputDispatcher: channel '65c696a com.moovel.storagepermissions.example/org.appcelerator.titanium.TiActivity (server)' ~ Consumer closed input channel or an error occurred.  events=0x9
02-23 13:53:40.293  1036  1401 E InputDispatcher: channel '65c696a com.moovel.storagepermissions.example/org.appcelerator.titanium.TiActivity (server)' ~ Channel is unrecoverably broken and will be disposed!
02-23 13:53:40.294   622   622 I Zygote  : Process 29966 exited due to signal (11)
02-23 13:53:40.301  1036 10133 W InputDispatcher: Attempted to unregister already unregistered input channel '65c696a com.moovel.storagepermissions.example/org.appcelerator.titanium.TiActivity (server)'
02-23 13:53:40.319  1036  1655 W WindowManager: Failed looking up window
02-23 13:53:40.319  1036  1655 W WindowManager: java.lang.IllegalArgumentException: Requested window android.os.BinderProxy@d4b8b55 does not exist
02-23 13:53:40.319  1036  1655 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9415)
02-23 13:53:40.319  1036  1655 W WindowManager: 	at com.android.server.wm.WindowManagerService.windowForClientLocked(WindowManagerService.java:9406)
02-23 13:53:40.319  1036  1655 W WindowManager: 	at com.android.server.wm.WindowState$DeathRecipient.binderDied(WindowState.java:1800)
02-23 13:53:40.319  1036  1655 W WindowManager: 	at android.os.BinderProxy.sendDeathNotice(Binder.java:688)
02-23 13:53:40.319  1036  1655 I WindowManager: WIN DEATH: null
```

**Comment by hansemannn** [comment]
This is not ready for QE testing so far, the comment from @m1ga blocks it. Removing label for now, @garymathews can you check that one? Thx!

**Comment by garymathews** [comment]
@m1ga @lokeshchdhry It seems like some activities were left, I've updated the PR

**Comment by m1ga** [comment]
@garymathews once the app restarts and I close it afterwards with the back button I still get a crash:

```
I/RESTART CHECK(12993): (main) [411,39480] baseActivity stop
W/V8Object(12993): (KrollRuntimeThread) [74,39554] Runtime disposed, cannot fire event 'close'
W/V8Object(12993): (KrollRuntimeThread) [9,39563] Runtime disposed, cannot fire event 'close'
A/DEBUG(3695): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
A/DEBUG(3695): Build fingerprint: 'htc/hiaeuhl_00401/htc_hiaeuhl:6.0.1/MMB29M/684509.81:user/release-keys'
A/DEBUG(3695): Revision: '0'
A/DEBUG(3695): ABI: 'arm'
A/DEBUG(3695): pid: 12993, tid: 13007, name: KrollRuntimeThr  >>> com.miga.app <<<
A/DEBUG(3695): signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
A/DEBUG(3695):     r0 00000000  r1 00000000  r2 00000000  r3 00000001
A/DEBUG(3695):     r4 dcec9d70  r5 dcecdc20  r6 dcecdc8c  r7 f6f10e40
A/DEBUG(3695):     r8 f3a64400  r9 ab4c7870  sl 12f2e1f0  fp 00000000
A/DEBUG(3695):     ip dc6a160d  sp f3a643f0  lr dc6a164b  pc dc77cb44  cpsr 600f0010
A/DEBUG(3695): backtrace:
A/DEBUG(3695):     #00 pc 003aeb44  /data/app/com.miga.app-2/lib/arm/libkroll-v8.so (_ZNK2v85Array6LengthEv+4)
A/DEBUG(3695):     #01 pc 002d3647  /data/app/com.miga.app-2/lib/arm/libkroll-v8.so (Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeDispose+58)
A/DEBUG(3695):     #02 pc 00a080df  /data/app/com.miga.app-2/oat/arm/base.odex (offset 0x68f000)
I/BackgroundTask(12498): writeResults: num written: 10
A/DEBUG(3695): Tombstone written to: /data/tombstones/tombstone_03
E/DEBUG(3695): AM write failed: Broken pipe
I/DEBUG(3695): Write to AM fail, close AM fd
I/BootReceiver(6474): Copying /data/tombstones/tombstone_03 to DropBox (SYSTEM_TOMBSTONE)
E/lowmemorykiller(512): Error writing /proc/12993/oom_score_adj; errno=22
E/InputEventReceiver(7064): Looper::removeFd(39) is failed, result(0), input channel 'ClientState{6335c17 uid 10173 pid 12993} (client)'
```

**Runtime disposed, cannot fire event 'close'** is new compared to the last commit

**Comment by lokeshchdhry** [comment]
@garymathews , @m1ga - I tried to reproduce the crash:
1. I backgrounded lot of apps along with my app.
2. After a while of opening the backgrounded apps & open my app.
3. The app is quick to restart as compared to 6.0.2.GA.
4. I close the app using the back button, the app does not crash.
5. I again open the app & then I see the crash.

```
I System.out: ActivityRecorder: before com.app.zprodcheck.Z_prod_checkActivity@8a3acd9_onCreate(), launchUrl = null
I TiRootActivity: (main) [0,0] checkpoint, on root activity create, savedInstanceState: null
I System.out: ActivityRecorder: before com.app.zprodcheck.Z_prod_checkActivity@8a3acd9_onCreate(), launchUrl = null
I System.out: ActivityRecorder: before com.app.zprodcheck.Z_prod_checkActivity@8a3acd9_onCreate(), launchUrl = null
F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0x0 in tid 4013 (.app.zprodcheck)
F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
F DEBUG   : Build fingerprint: 'google/shamu/shamu:6.0.1/MOB30W/3031100:user/release-keys'
F DEBUG   : Revision: '0'
379 F DEBUG   : ABI: 'arm'
F DEBUG   : pid: 4013, tid: 4013, name: .app.zprodcheck  >>> com.app.zprodcheck <<<
F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0
F DEBUG   :     r0 00000000  r1 ab4aa000  r2 75646f4d  r3 0000656c
F DEBUG   :     r4 00000000  r5 a0997dc8  r6 b4dd6b40  r7 00000000
F DEBUG   :     r8 00000000  r9 a0993d70  sl bec12e14  fp b6d67ec0
F DEBUG   :     ip 9fce9774  sp bec12d60  lr a016f587  pc a0250a70  cpsr a00b0010
F DEBUG   : 
F DEBUG   : backtrace:
F DEBUG   :     #00 pc 003b8a70  /data/app/com.app.zprodcheck-2/lib/arm/libkroll-v8.so (_ZN2v86Object3GetENS_5LocalINS_5ValueEEE+8)
F DEBUG   :     #01 pc 002d7583  /data/app/com.app.zprodcheck-2/lib/arm/libkroll-v8.so (Java_org_appcelerator_kroll_runtime_v8_V8Runtime_nativeRunModule+106)
F DEBUG   :     #02 pc 00aa54d5  /data/app/com.app.zprodcheck-2/oat/arm/base.odex (offset 0x69b000)
W ActivityManager:   Force finishing activity com.app.zprodcheck/.Z_prod_checkActivity
F DEBUG   : 
F DEBUG   : Tombstone written to: /data/tombstones/tombstone_05
E DEBUG   : AM write failed: Broken pipe
I BootReceiver: Copying /data/tombstones/tombstone_05 to DropBox (SYSTEM_TOMBSTONE)
D GraphicsStats: Buffer count: 14
I Zygote  : Process 4013 exited due to signal (11)
I WindowManager: Screenshot max retries 4 of Token{99e7899 ActivityRecord{542ade0 u0 com.app.zprodcheck/.Z_prod_checkActivity t103 f}} appWin=Window{a8c58f8 u0 Starting com.app.zprodcheck} drawState=4
W ActivityManager: Exception thrown during pause
W ActivityManager: android.os.DeadObjectException
W ActivityManager: 	at android.os.BinderProxy.transactNative(Native Method)
W ActivityManager: 	at android.os.BinderProxy.transact(Binder.java:503)
W ActivityManager: 	at android.app.ApplicationThreadProxy.schedulePauseActivity(ApplicationThreadNative.java:727)
W ActivityManager: 	at com.android.server.am.ActivityStack.startPausingLocked(ActivityStack.java:867)
W ActivityManager: 	at com.android.server.am.ActivityStack.finishActivityLocked(ActivityStack.java:2907)
W ActivityManager: 	at com.android.server.am.ActivityStack.finishTopRunningActivityLocked(ActivityStack.java:2763)
W ActivityManager: 	at com.android.server.am.ActivityStackSupervisor.finishTopRunningActivityLocked(ActivityStackSupervisor.java:2760)
W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleAppCrashLocked(ActivityManagerService.java:12042)
W ActivityManager: 	at com.android.server.am.ActivityManagerService.makeAppCrashingLocked(ActivityManagerService.java:11938)
W ActivityManager: 	at com.android.server.am.ActivityManagerService.crashApplication(ActivityManagerService.java:12627)
W ActivityManager: 	at com.android.server.am.ActivityManagerService.handleApplicationCrashInner(ActivityManagerService.java:12134)
W ActivityManager: 	at com.android.server.am.NativeCrashListener$NativeCrashReporter.run(NativeCrashListener.java:86)
E lowmemorykiller: Error opening /proc/4013/oom_score_adj; errno=2
I ActivityManager: Process com.app.zprodcheck (pid 4013) has died
W InputMethodManagerService: Window already focused, ignoring focus gain of: com.android.internal.view.IInputMethodClient$Stub$Proxy@709a141 attribute=null, token = android.os.BinderProxy@773ba64
I OpenGLRenderer: Initialized EGL, version 1.4
D audio_hw_primary: disable_audio_route: reset and update mixer path: low-latency-playback speaker
D audio_hw_primary: disable_snd_device: snd_device(2: speaker)
```

Device: Nexus 6 - android 6.0.1

**Comment by garymathews** [comment]
@lokeshchdhry @m1ga Updated PR.

**Comment by m1ga** [comment]
@garymathews crash when closing a restarted app is gone for me!

This is how a restart for a closed-in-background app looks now: http://migaweb.de/restart.mp4
Not sure if the grey screen before the actual splash screen can be removed but otherwise it looks smoother/faster than before (http://www.migaweb.de/video.mp4 starting at 11sec).

**Comment by angelo0000** [comment]
What is the status of this fix??

**Comment by lokeshchdhry** [comment]
FR done in PR https://github.com/appcelerator/titanium_mobile/issues/8926

**Pull request merged**
