### PR TITLE
[TIMOB-1028] Android: Implement AudioRecorder (Parity)

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-1028

**Description:**
Base implementation of the AudioRecorder. In order to have play/pause functionality on API 22 and below and avoid formats that are not supported on some vendors' Android implementations currently it records uncompressed audio data in WAV format. 

**Basic test code:**
```js
var window = Ti.UI.createWindow();
var recordStart = Ti.UI.createButton({title:'Start', top:10});
var recordPause = Ti.UI.createButton({title:'Pause', top:60});
var recordStop = Ti.UI.createButton({title:'Stop', top:110});
var recordPlay = Ti.UI.createButton({title:'Play', top:160});
var audioRecorder = Ti.Media.createAudioRecorder();
var record;
var audioPlayer;

window.addEventListener('open', function (e) {
    Ti.API.info(Ti.Media.canRecord);
    if (!Ti.Media.hasAudioRecorderPermissions()) {
        Ti.Media.requestAudioRecorderPermissions(function (e) {
                    if (e.success) {
                        window.add(recordStart);
                    }
                });
    } else {
        window.add(recordStart);
    }
});

recordStart.addEventListener('click', function (e) {
    audioRecorder.start();
});

recordPause.addEventListener('click', function (e) {
    if (audioRecorder.getPaused()) {
        recordPause.setTitle('Pause');
        audioRecorder.resume()
    } else {
        recordPause.setTitle('Resume');
        audioRecorder.pause();
    }
});

recordStop.addEventListener('click', function (e) {
    record = audioRecorder.stop();
    Ti.API.info(record.getNativePath());
});

recordPlay.addEventListener('click', function (e) {
    audioPlayer = Ti.Media.createAudioPlayer({url:record.getNativePath()});
    audioPlayer.start();
});

window.add(recordPause);
window.add(recordStop);
window.add(recordPlay);

window.open();
```
**Edit**: Changed permissions methods' names in the test case to match the latest update.

### CODE REVIEW

**Review by hansemannn — CHANGES_REQUESTED** [review]
Please also change the docs to include the `android` platform in the `platforms:` key, where ever an API is available cross-platform now. Also add docs for the Android-only ones. Thank you!

**Comment by ypbnv** [comment]
@hansemannn Changed the docs to include the new methods. Also renamed two of them to match the update from iOS.

**Comment by ypbnv** [comment]
Fixed the names.

**Comment by lokeshchdhry** [comment]
FR Passed.

With proper permissions, the audio recorder's record, pause, play, stop works as expected.
1. Checked by recording audio, stopping & playing it.
2. Recording audio, pausing , recording again , stopping & playing.

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.3-21
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.13
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ motorola XT1033 --- Android 4.4.4 , Nexus 5 -- Android 6.0.0
                ⇨ google Nexus 6P --- Android 7.1.1

**Pull request merged**
