### PR TITLE
[TIMOB-26187] Android: Fix Ti.UI.CardView borderRadius

### PR DESCRIPTION
**Pull request by garymathews**
- `TiUICardView` has its own border, prevent `TiUIView` from creating a border wrapper for our view

##### TEST CASE
```JS
const win = Ti.UI.createWindow({ backgroundColor: 'gray' }),
      card = Ti.UI.Android.createCardView({
          padding: 20,
          backgroundColor: 'white',
          borderRadius: 10
      });

card.add(Ti.UI.createLabel({
    color: 'black',
    text: 'THIS IS A TEST!'
}));

win.add(card);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26187)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

The `cardview` is visible with `borderradius` set.

Studio Ver: 5.1.0.201807090554
OS Ver: 4.2.13
Xcode Ver: 7.0.4
Appc NPM: 1.1.3
Appc CLI: 10.13.5
Daemon Ver: Xcode 9.4.1
Ti CLI Ver: 5.1.1
Alloy Ver: 1.12.0
Node Ver: 8.9.1
NPM Ver: 5.5.1
Java Ver: 1.8.0_131
Devices: ⇨ google Nexus 5 --- Android 6.0.1
⇨ google Nexus 6P --- Android 8.1.0
Emulator: ⇨ Android 4.1.2

**Review by ypbnv — COMMENTED** [review]
Do we not support borders for CardView in general ?

**Comment by garymathews** [comment]
@ypbnv the native CardView component has its own border handling. You can only set the `borderRadius` on a CardView.

**Review by ypbnv — APPROVED** [review]
LGTM!
One minor thing - Can we mark in the docs that only `borderRadius` is supported for CardView?

**Pull request merged**
