### PR TITLE
[TIMOB-18902] Android: HTTPClient, set Content-Type as application/js…

### PR DESCRIPTION
**Pull request by ashcoding**
…on for JSON

Jira: https://jira.appcelerator.org/browse/TIMOB-18902

### CODE REVIEW

**Comment by ashcoding** [comment]
Test app.js:
Note: You can use any file for the fileSend var. I used a simple square.png file.
```javascript

var salesforceAuthToken = "<your auth token>"; 
// Set this postUri to the server and port that is running the node.js script
var postUri = "192.168.0.105:8080"; 
 
var xhr = Ti.Network.createHTTPClient({ 
onload : function() { 
// Do Sth	
}, 
onerror : function(e) { 
Ti.API.info(e); 
Ti.API.info(this.responseText); 
}, 
timeout : 10000 
}); 
 
xhr.open("POST", postUri); 
xhr.setRequestHeader("Authorization", salesforceAuthToken); 
xhr.setRequestHeader('enctype', 'multipart/form-data'); 
 
// Assemble a valid salesforce post body 
var postBody = {}; 
postBody.feedElementType = "FeedItem"; 
postBody.subjectId = "<A valid chatter group id in your salesforce instance>"; 
 
var messageSegments = []; 
var message = { 
type : "text to be here", 
text : "some text" 
}; 
messageSegments.push(message); 
postBody.body = { 
messageSegments : messageSegments 
}; 
 
var fileCapability = { 
content : { 
description : "a file description", 
title : "test.jpg" 
} 
}; 
postBody.capabilities = fileCapability; 
// Assemble end 
var fileSend = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "square.png");
var data2send = { 
//json : JSON.stringify(postBody), 
json : postBody, 
feedElementFileUpload : fileSend
}; 
xhr.send(data2send);
```
Node JS server code:
```javascript

var http = require('http');
http.createServer(function (req, res) {
  var body = "";
  req.on('data', function (chunk) {
    body += chunk;
  });
  req.on('end', function () {
    console.log(body);
  });
}).listen(8080);

```

Instructions to run the test:-
1) Run the node js script
2) Find out your network ip address, (for Mac you can use this on terminal-> ifconfig)
3) Change the ip address in the App.js code to your computer running the node script
4) Run the test code on an Android that is connected to the same network
5) Check the output of the node script once the Android app is running. It should show:-
```
--ztq2DKUqYughaBWtY1D_xFPoee8DoJkAp
Content-Disposition: form-data; name="feedElementFileUpload"; filename="tixhr1589809136.png"
Content-Type: image/png
Content-Transfer-Encoding: binary

�PNG

IHDR��>a��iCCPICC Profile8��U�o�T?�o\�?�����US[������B���*��unS�6��mU��o
                                                                        ����xB
                                                                              �����ISA�$�=t�@h����p��S�]Ƹ��9�w>��5@�W���I`��]5������;V!	�A'�@��{N�\..ƅG��_!��7���suV��$�BlW=}�i���;� �F��)�A��<�.&�Xax��,�38S�(b���׵*�%��31�l
                                                                                    ���#O-���zQv��a�X�OP��5o6Z�z����&�⻏�^w���k�I�/#���&���\%�x/@���{����7�S� މ�j���P�h͔&�mry�>���k�7�=�ߪ�B��#@�fs�_�{덱п0�-L�Z~��%�Gp���ˈ{����YX�f^���+�_s�-�T�>�D���@�קƸ-9��!r[2]3�B��c�����nC������?�>�*��Ԯ��e�D|�%4�`�
                       �:X�2���
�י5Fi�����t���� )�Cd���L�$o��$��rpӶ��b����>4�+��̹�F_��{�Я��k���i+�x�������.��+��B.�{���L<���۩��
����=���UHcnf��<>F��� ^�e||�p�yv��%b�:�iX'���%8�I�ߔ?��
Ic����<�x�x-�������8��ZNxA�-8�m�Ck�K�Ha���Yn1Ĝ�� �{�qHg����u#���L����Q�N�^�d��pY�I�"|#\�����c���z[�2M�^S0���[zI�J/H�H�ȟ�-
h��s �:6��z!�y@}z�g����q�ٺ/�S���4~��\���~Y3M9Py�K=�.�� �� �����-��z$��8��Y7"�t�k���Hևwⳟ\8�7܅��O$~�j���]��n5�����`��f���fs�K��p��Yqx����ID��=@�p��p8~P��(���n�������
��=@�p��p8~P��(���n��
��=@�p��p8~P��(���n��
��=@�p��p8~P��(���n��
��=@�p��p8~P��(���n��
��=@�p��p8~P��(���n��
��=@�p��p8~P��(���n��
��=@�p��p8~P��(����<_���DIEND�B`�
--ztq2DKUqYughaBWtY1D_xFPoee8DoJkAp
Content-Disposition: form-data; name="json"
Content-Type: application/json; charset=UTF-8
Content-Transfer-Encoding: 8bit

{"body":{"messageSegments":[{"text":"some text","type":"text to be here"}]},"feedElementType":"FeedItem","subjectId":"<A valid chatter group id in your salesforce instance>","capabilities":{"content":{"title":"test.jpg","description":"a file description"}}}
--ztq2DKUqYughaBWtY1D_xFPoee8DoJkAp--

```

Check the bottom part for the JSON. Check that it has the `Content-Type` set to `application/json`.

**Comment by hieupham007** [comment]
Where can I obtain a salesforce auth token?

**Comment by ashcoding** [comment]
I don't have one too. I'm currently testing it by running a node.js server to see that the output is as intended. I'll write in the Jira ticket to see if there's a test api with an auth token we can use.

**Comment by hieupham007** [comment]
Hmm, please figure out how to get the token and update the testing steps. Thanks

**Comment by ashcoding** [comment]
Will do.

**Comment by ashcoding** [comment]
@hieupham007 Updated testing steps in Jira: https://jira.appcelerator.org/browse/TIMOB-18902

**Comment by hieupham007** [comment]
Code reviewed and functionally tested. Request **accepted**

**Pull request merged**
