### PR TITLE
docs: fix static links

### PR DESCRIPTION
**Pull request by m1ga**
* fixing appcelerator.com -> titaniumsdk.com links
* saving those files remove some blanks from the line endings (hope it doesn't matter)

**TODO**:
* links in the changelogs files and some other files (409 still left)

### CODE REVIEW

**Review by cb1kenobi — APPROVED** [review]
HUGE thanks for helping with this. **APPROVED**!

**Comment by m1ga** [comment]
no problem :smile: thanks for the quick merge.
Around 340 links are in very old  changelog files ( 1.4 - 5.0 ). Not sure if those need to be changed or can be removed

**Comment by cb1kenobi** [comment]
I'm not worried about changelogs.

**Comment by m1ga** [comment]
yeah, https://github.com/tidev/titanium_mobile/tree/master/apidoc/Titanium/CHANGELOG is not even used anymore. Maybe it can be removed at some point. Its still in the github history if someone is interested what is new in 1.2 :rofl:

**Pull request merged**
