### PR TITLE
[TIMOB-20357] Android: 9-patch padding box area ignored for Button backgroundImage

### PR DESCRIPTION
**Pull request by falkolab**
PR for [JIRA](https://jira.appcelerator.org/browse/TIMOB-20357)

### CODE REVIEW

**Comment by ashcoding** [comment]
Code reviewed and functionally tested by setting 
`button.backgroundImage = "/images/alert_button.png";`

**Accepted**

**Comment by falkolab** [comment]
Sorry just saw your comment. It is wrong test case becouse bug inside `processProperties` but PR is functioning.

**Comment by ashcoding** [comment]
Which test case are you referring to?

**Comment by falkolab** [comment]
`Ti.UI.createButton({backgroundImage:"/images/alert_button.png"})`

But yesterday I tested this patch with other 9-patch image. And I found that button has not paddings defined in right and bottom area of 9-patch image. It have not 0 paddings, but different against defined in 9-patch.

I think need to reopen issue in JIRA.

**Pull request merged**
