### PR TITLE
[TIMOB-25466] iOS: Move iOS 11 guards inside method

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-25466

### CODE REVIEW

**Comment by mukherjee2** [comment]
@hansemannn I'm not able to Merge pull request. There are unit test failures, can you unblock this?

**Comment by hansemannn** [comment]
@mukherjee2 The Android unit-test `hide() and show() change visible property value` fails, I cannot help with that.

**Comment by mukherjee2** [comment]
@garymathews , @jquick-axway per @hansemannn comment, an Android dev needs to merge this ticket, can one of you please merge? cc: @eric34

**Comment by hansemannn** [comment]
@mukherjee2 The Android unit-tests should be fixed or Jenkins should be retriggered. The Android team cannot force-merge, only @ingo and @sgtcoolguy.

**Review by ewieberappc — APPROVED** [review]

**Comment by mukherjee2** [comment]
@eric34 can you please force merge? FR passed, but unable to merge.

**Pull request merged**
