### PR TITLE
[TIMOB-25288]Android: addAnnotations in Ti.Map crashes app

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25288

**Description:**
Bundled module looks for non-existing method. Rebuild against latest sources.
Attached Module archive should be added as a release version.

**Test case:**
In JIRA ticket.

[ti.map-android-3.3.1.zip](https://github.com/appcelerator/titanium_mobile/files/1312220/ti.map-android-3.3.1.zip)

### CODE REVIEW

**Comment by garymathews** [comment]
@ypbnv I added a `3.3.1` pre-release compiled with `6.2.0.GA` to [ti.map](https://github.com/appcelerator-modules/ti.map/releases/tag/android-3.3.1)

This makes the `packages/modules.json` link valid (ttps://github.com/appcelerator-modules/ti.map/releases/download/android-3.3.1/ti.map-android-3.3.1.zip).

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by lokeshchdhry** [comment]
FR Passed.

Ran the test code from the ticket to check if adding annotations outside `createView` does not crash the app.

Studio Ver:     4.9.1.201707200100
SDK Ver:        6.2.0.GA
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.4
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.14
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Map Module: 3.3.1
Devices:        ⇨ google Pixel --- Android 7.1.1
                ⇨ google Nexus 5 --- Android 6.0.1

**Comment by ypbnv** [comment]
@garymathews Thank you!

**Pull request merged**
