### PR TITLE
[TIMOB-24667] Android: Fix LOWER_THAN_JELLYBEAN condition for HW-acceleration

### PR DESCRIPTION
**Pull request by garymathews**
- Fix `LOWER_THAN_JELLYBEAN` condition to disable hardware acceleration for < API 17

##### TEST CASE
```JS
var win = Ti.UI.createWindow({
        backgroundColor: 'white'
    }),
    view = Ti.UI.createView({
        width: 100,
        height: 100,
        borderWidth: 3,
        borderRadius: 50,
        borderColor: 'red',
        backgroundColor: 'pink'
    });

win.add(view);
win.open();
```
- Should display a circle with red border - test on Android `4.1` `4.2` `4.3` and `5.0`

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24667)

### CODE REVIEW

**Comment by hansemannn** [comment]
@garymathews Looks good! Can we get a 6.1.0 backport for this if @eric34 agrees?

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR passed.

Adding a `borderRadius` on a view clips the `backgroundColor` as expected.

Studio Ver:     4.9.0.201704240654
SDK Ver:        6.1.0.v20170509155334
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.2
Appc NPM:       4.2.9
Appc CLI:       6.2.0
Ti CLI Ver:     5.0.12
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        > google Nexus 6 --- Android 6.0.1 > google Nexus 6P --- Android 7.1.1

**Comment by lokeshchdhry** [comment]
FR passed.

Adding a borderRadius on a view clips the backgroundColor as expected.

Studio Ver: 4.9.0.201704240654
SDK Ver: 6.2.0.v20170509154446
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.2
Appc NPM: 4.2.9
Appc CLI: 6.2.0
Ti CLI Ver: 5.0.12
Alloy Ver: 1.9.11
Node Ver: 6.10.1
Java Ver: 1.8.0_101
Emulator: Android 4.4.2, 4.2.2, 6.0

**Pull request merged**
