### PR TITLE
[6_3_X][TIMOB-25423] Android: Ti.UI.Slider on Android 4.x is not working

### PR DESCRIPTION
**Pull request by maggieaxway**
Update TIUISlider.java

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25423

Test case:
````js
var win1 = Titanium.UI.createWindow({
    title:'TIMOB-25423',
    backgroundColor:'#000'
});
var slider = Titanium.UI.createSlider({
     min: 0, max: 100, width: '100%', height: Ti.UI.SIZE, value: 0, splitTrack: 'true'
    });

var label = Ti.UI.createLabel({
    text: slider.value,
    width: Ti.UI.FILL,
    top: 30,
    left: 0,
    textAlign: Ti.UI.TEXT_ALIGNMENT_CENTER
});

slider.addEventListener('change', function(e) {
    label.text = e.value;
});

win1.add(slider);
win1.add(label);
win1.open();

### CODE REVIEW

**Comment by hansemannn** [comment]
@garymathews The following test-case currently fails:
```
  1) #isGooglePlayServicesAvailable()
    {"state":"failed","duration":1,"suite":"Titanium.Map","title":"#isGooglePlayServicesAvailable()","error":{},"stdout":"","stderr":"[WARN] : \b\b \b W/System.err: java.lang.NoClassDefFoundError: Failed resolution of: Lcom/google/android/gms/common/GooglePlayServicesUtil;\n[WARN] : \b\b \b W/System.err: \tat ti.map.MapModule.isGooglePlayServicesAvailable(MapModule.java:106)\n[WARN] : \b\b \b W/System.err: \tat org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)\n[WARN] : \b\b \b W/System.err: \tat org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:57)\n[WARN] : \b\b \b W/System.err: \tat org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:43)\n[WARN] : \b\b \b W/System.err: \tat ti.modules.titanium.TitaniumModule$Timer.run(TitaniumModule.java:147)\n[WARN] : \b\b \b W/System.err: \tat android.os.Handler.handleCallback(Handler.java:739)\n[WARN] : \b\b \b W/System.err: \tat android.os.Handler.dispatchMessage(Handler.java:95)\n[WARN] : \b\b \b W/System.err: \tat android.os.Looper.loop(Looper.java:148)\n[WARN] : \b\b \b W/System.err: \tat android.app.ActivityThread.main(ActivityThread.java:5417)\n[WARN] : \b\b \b W/System.err: \tat java.lang.reflect.Method.invoke(Native Method)\n[WARN] : \b\b \b W/System.err: \tat com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)\n[WARN] : \b\b \b W/System.err: \tat com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)\n[WARN] : \b\b \b W/System.err: Caused by: java.lang.ClassNotFoundException: Didn't find class \"com.google.android.gms.common.GooglePlayServicesUtil\" on path: DexPathList[[zip file \"/data/app/com.appcelerator.testApp.testing-2/base.apk\"],nativeLibraryDirectories=[/data/app/com.appcelerator.testApp.testing-2/lib/x86, /data/app/com.appcelerator.testApp.testing-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]\n[WARN] : \b\b \b W/System.err: \tat dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)\n[WARN] : \b\b \b W/System.err: \tat java.lang.ClassLoader.loadClass(ClassLoader.java:511)\n[WARN] : \b\b \b W/System.err: \tat java.lang.ClassLoader.loadClass(ClassLoader.java:469)\n[WARN] : \b\b \b W/System.err: \t... 12 more\n[WARN] : \b\b \b W/System.err: \tSuppressed: java.lang.ClassNotFoundException: com.google.android.gms.common.GooglePlayServicesUtil\n[WARN] : \b\b \b W/System.err: \t\tat java.lang.Class.classForName(Native Method)\n[WARN] : \b\b \b W/System.err: \t\tat java.lang.BootClassLoader.findClass(ClassLoader.java:781)\n[WARN] : \b\b \b W/System.err: \t\tat java.lang.BootClassLoader.loadClass(ClassLoader.java:841)\n[WARN] : \b\b \b W/System.err: \t\tat java.lang.ClassLoader.loadClass(ClassLoader.java:504)\n[WARN] : \b\b \b W/System.err: \t\t... 13 more\n[WARN] : \b\b \b W/System.err: \tCaused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack trace available\n"}
```
Is this resolved by your PR in #9546 ?

**Comment by jquick-axway** [comment]
@hansemannn, that test failure appears to be some kind of server issue. That is, either there is something wrong with the "ti.map" module installation or with how the build system is failing to merge the library dependencies. A unit test change won't fix it (other than to skip the "ti.map" test). We should talk about it offline with Gary and Chris Williams.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

`Ti.UI.Slider` does not crash on android 4.X.

Studio Ver: 4.10.0.201709271713
SDK Ver:  6.3.0 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.10-2
Appc CLI: 6.3.0-master.15
Ti CLI Ver: 5.0.14
Alloy Ver: 1.10.6
Node Ver: 7.10.1
Java Ver: 1.8.0_101
Devices: Android 4.4.2

**Pull request merged**
