### PR TITLE
feat: add "isTrusted" property to Slider "change" event

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-27977

**Summary:**
Added a "isTrusted" boolean property to `Ti.UI.Slider` object's "change" event. Property will be `true` if change came from the end-user. Will be `false` if change was made programmatically. This is a standard JavaScript event property available to web developers. (In the future, we should apply this property to all events.)
https://developer.mozilla.org/en-US/docs/Web/API/Event/isTrusted

**Test:**
1. Build and run the below for Android.
2. Drag the slider with your finger.
3. In the log, verify change event's `isTrusted` property is set to `true`.
4. Tap on the "Update Slider" button.
5. In the log, verify change event's `isTrusted` property is set to `false`.

```javascript
var window = Ti.UI.createWindow();
var slider = Ti.UI.createSlider({
	min: 0.0,
	max: 1.0,
	value: 0.25,
});
slider.addEventListener("change", function(e) {
	Ti.API.info("@@@ slider value changed: " + e.value + ", isTrusted: " + e.isTrusted);
});
window.add(slider);
var button = Ti.UI.createButton({
	title: "Update Slider Position",
	bottom: "20dp",
});
button.addEventListener("click", function() {
	slider.value = 0.5;
});
window.add(button);
window.open();
```

### CODE REVIEW

**Comment by jquick-axway** [comment]
@m1ga, would you mind if I add changes to this PR?
I'd like to make the same change to iOS and add a unit test.

**Comment by m1ga** [comment]
@jquick-axway no, go ahead!

**Comment by jquick-axway** [comment]
PR updated:
- Added property to iOS for parity.
- Added unit test.
- Updated API docs.

@janvennemann, would you mind reviewing the iOS side? Do you have any objections to this new event property?

**Review by janvennemann — APPROVED** [review]
@jquick-axway iOS change looks good. I'm fine with introducing this now since we already fire the event on programmatic changes. Eventually we should stop firing the `change` event after programmatic changes though, but as already discussed we can deal with that in a separate ticket for an upcoming major release.

**Review by ssjsamir — APPROVED** [review]
**FR Passed** Tested using the test case and instructions mentioned above in the description. 

**Test Environment**
```
MacOS Big Sur: 11.0 Beta
Xcode: 12.0 Beta 
Java Version: 1.8.0_242
Android NDK: 21.3.6528147
Node.js: 12.18.1
""NPM":"5.0.0","CLI":"8.0.0""
iphone 8 Sim (14.0 Beta)
API29 Pixel XL emulator
```

**Comment by ssaddique** [comment]
Fix verified on build 9.1.0.v20200804082025.

**Test environment**
```
OS Ver:         10.15.3
Xcode Ver:      Xcode 11.6
Appc NPM:       5.0.0
Appc CLI:       8.0.0
Node Ver:       10.17.0
Java Ver:       1.8.0_162
Devices:        iPhone 6 (12.1.4), Pixel 3a (11.0)
```

I must note that when clicking the 'Update' button, the value is logged twice:

`[INFO]  @@@ slider value changed: 0.5, isTrusted: false
`
`
[INFO]  @@@ slider value changed: 0.5, isTrusted: false
`

**Pull request merged**
