### PR TITLE
[TIMOB-23830] (6_0_X) Fixed Android modules that have name that begins with a number

### PR DESCRIPTION
**Pull request by cb1kenobi**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23830

Fixed Android modules that have name that begins with a number.

### CODE REVIEW

**Comment by hansemannn** [comment]
> This ticket and PR will NOT go in 6.0.

**Comment by cb1kenobi** [comment]
@hansemannn I said it wasn't going into 6.0.0. I didn't say it wasn't going into 6.1.0.

**Comment by hansemannn** [comment]
Thought that's what https://github.com/appcelerator/titanium_mobile/pull/8273 is for?

**Comment by cb1kenobi** [comment]
#8273 is for master, not 6_0_X. v6.1.0 will come from 6_0_X.

**Comment by hansemannn** [comment]
Sorry, I don't get you. 6.1.0 is master, 6.0.0 is 6_0_X. Whatever ...

**Comment by cb1kenobi** [comment]
@hansemannn Too much work and not enough sleep.

**Pull request closed without merging**
