### PR TITLE
[TIMOB-26580] Android: Fix ListView template support for native modules

### PR DESCRIPTION
**Pull request by garymathews**
- Fix missing assignment to support native modules

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26580)

### CODE REVIEW

**Comment by m1ga** [comment]
This still crashes with `Error: Requested module not found: /alloy/widgets/AvImageview.ImageView/controllers/widget` if you use `<ImageView bindId="image" class="profil_img" ns="AvImageview"/>` . The old listview.js (https://github.com/appcelerator/titanium_mobile/pull/9955/files#diff-d91f84ce1f8aba65f9302707f8d4c438L83) works fine

**Review by ypbnv — APPROVED** [review]
CR: Pass

Sorry for the late review!

**Comment by hansemannn** [comment]
Can this be backported to 7.5.1? I think many apps are currency broken and unable to update to 7.5.0 without this.

**Comment by lokeshchdhry** [comment]
FR Passed.

Use of native modules with listview works fine.

Studio Ver:     5.1.2.201810301430
SDK Ver:        8.0.0 local build
OS Ver:         10.14
Xcode Ver:      Xcode 10.1
Appc NPM:       4.2.13
Appc CLI:       7.0.8
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.4
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Nexus 6P (Android 8.1.0)

**Comment by AhmedMSayed** [comment]
> 
> 
> Can this be backported to 7.5.1? I think many apps are currency broken and unable to update to 7.5.0 without this.

Yes, we can't update to 7.5.0 because of this

**Pull request merged**
