### PR TITLE
[TIMOB 16879] iOS : ScrollableView: Add "insertAt()" method

### PR DESCRIPTION
**Pull request by bduyng**

### CODE REVIEW

**Comment by hansemannn** [comment]
Can you please squash the commits to prevent unrelated commits? Also, please provide a demo on how to use your feature.

**Comment by nuno** [comment]
+1 for the demo

**Comment by bduyng** [comment]
Demo:
```js
var win = Ti.UI.createWindow();

var view1 = Ti.UI.createView({ backgroundColor:'#123' });
var view2 = Ti.UI.createView({ backgroundColor:'#246' });
var view3 = Ti.UI.createView({ backgroundColor:'#48b' });

var scrollableView = Ti.UI.createScrollableView({
  views:[view1,view2,view3],
  showPagingControl:true
});

// insert a view at 1(position)
setTimeout(function(){
  scrollableView.insertAt(1, Ti.UI.createView({ backgroundColor:'yellow' }));
}, 2000);

win.add(scrollableView);
win.open();
```

**Comment by nuno** [comment]
I can confirm works just pretty good, via demo code and more advanced and complex views as code, that envolve api calls.

 Now the "scrollableView" have definitely  infinite scroll working in both directions!

**Comment by bduyng** [comment]
just made another PR [here](https://github.com/appcelerator/titanium_mobile/pull/7764)

**Pull request closed without merging**
