### PR TITLE
[6_3_X][TIMOB-25359] Fix Ti.UI.ScrollView when keyboard is active

### PR DESCRIPTION
**Pull request by garymathews**
- Cherry-pick of https://github.com/appcelerator/titanium_mobile/pull/9502

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25359)

### CODE REVIEW

**Review by ypbnv — CHANGES_REQUESTED** [review]
Missing the following imports:
```
import android.view.Window;
import android.view.WindowManager;
import org.appcelerator.titanium.TiBaseActivity;
```

**Comment by garymathews** [comment]
Updated PR

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

`scrollView` is scrollable when keyboard is up.

Studio Ver: 4.10.0.201709271713
SDK Ver: 7.0.0 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.9
Appc CLI: 6.2.4
Ti CLI Ver: 5.0.14
Alloy Ver: 1.9.14
Node Ver: 7.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1
⇨ google Pixel --- Android 7.1.1

**Pull request merged**
