### PR TITLE
[TIMOB-24949] Android: Remove unnecessary % escapes from logs

### PR DESCRIPTION
**Pull request by garymathews**
- Remove unnecessary escape characters `%%` from logs

###### TEST CASE
```JS
console.log('%');
```
```
%
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24949)

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
QE should also test the following:

```javascript
console.log("%d %f %x %s %%");
```

**Comment by garymathews** [comment]
@jquick-axway We don't (but should) support that [TIMOB-24950](https://jira.appcelerator.org/browse/TIMOB-24950)

**Comment by jquick-axway** [comment]
@garymathews, I was referring to how we log messages internally in Titanium. In this case, I'm expecting the '%' characters to be taken literally. It doesn't hurt to double check.

**Comment by lokeshchdhry** [comment]
FR Passed.

We now see only one `%`.
Checked with `console.log('%');` & `console.log("%d %f %x %s %%");`

Studio Ver:     4.9.0.201705302345
SDK Ver:        6.2.0.v20170712153750 from Jenkins
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1

**Pull request merged**
