### PR TITLE
[TIMOB-25621] Android: Do not delete third-party native libraries

### PR DESCRIPTION
**Pull request by garymathews**
- Do not clean third-party native libraries from Titanium modules
- Caused by the changes in https://github.com/appcelerator/titanium_mobile/pull/9670

###### TEST CASE
- Compile the appcelerator.encrypteddatabase module
- Verify the appropriate *.so libraries are included in the .zip output

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25621)

### CODE REVIEW

**Comment by hansemannn** [comment]
This is not a valid change. The native libraries are recreated during the build by compiling for all architectures specified in the package.json of the Ti-Android project. The encrypted database likely failed because before the change the arm64-v8a was not always created which was caused by not cleaning up the existing libs. Please test this very well in case it should be taken.

**Comment by garymathews** [comment]
@hansemannn This behavior never happened before, the issue is any third-party libraries are deleted during the newly added cleanup phase.

**Comment by garymathews** [comment]
@hansemannn I have updated the PR to only remove the built module `*.so` files and not third-party libraries.

**Comment by lokeshchdhry** [comment]
FR Passed.

The `.so` files are included in the compiled zip in `libs/*` folder.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.1.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11
Appc CLI:       7.0.1
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101

**Comment by hansemannn** [comment]
@garymathews @lokeshchdhry Sorry to step in again, but this ticket should not have been merged. The first reason is that it haven't been CR-tested in any way. The second reason is that the binary that caused the ticket was obviously compiled before 7.0.1 was released. And the last third reason is that this PR will likely introduce a regression for the case that we remove an old architecture again, like in 6.0.0. In that case, the .so will be deleted, but the directory will still be present, which will cause a module build error when verifying the build architectures. Please have this in mind once it pops up.

**Pull request merged**
