### PR TITLE
Fixes switch animation on when programmatically setting value

### PR DESCRIPTION
**Pull request by FokkeZB**
JIRA: https://jira.appcelerator.org/browse/TIMOB-2908

### CODE REVIEW

**Comment by hansemannn** [comment]
@FokkeZB Is this still happening? Would be happy to get this in.

**Comment by FokkeZB** [comment]
Still true, but as you pointed out on Flow you wouldn't always want it not to animate so it would be better if we'd override `setValue(val)` to allow:

```
mySwitch.setValue(true, {
  animated: false
});
```

**Comment by skypanther** [comment]
I commented on the ticket. Simply disabling the animation doesn't fully resolve the current problem with the switch.

**Comment by hansemannn** [comment]
Closed in favor of #7456

**Pull request closed without merging**
