### PR TITLE
[TIMOB-24438] Update Android Support Library to 23.4.0

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24438

**Optional Description:**
Updates the bundled Android Support Library to the latest version for API level 23, which is 23.4.0

### CODE REVIEW

**Comment by hansemannn** [comment]
Niceeeee!

**Comment by hansemannn** [comment]
@janvennemann Quick question: What prevents us from using 25.x again? Our build tools? Can't we update those as well to achieve latest support?

**Review by garymathews — APPROVED** [review]
Approved

**Comment by janvennemann** [comment]
@hansemannn, i tried that but i think there were some issues, can't remember what exactly right now. @garymathews got the SDK to work with API 25 in the meantime so let me double check that again.

**Comment by garymathews** [comment]
@janvennemann Want me to push a PR for that?

**Comment by janvennemann** [comment]
@garymathews sure, if you have the time that could probably be interesting for 6.2.0. I'll leave the Support Libraries at 23.4.0 for know as this is intended for 6.1.0 and we most likely stay on API level 23 there.

**Comment by garymathews** [comment]
@janvennemann Yes, I think this should go into 6.1.0, since it's only a minor bump.

**Comment by lokeshchdhry** [comment]
FR Passed.
Followed steps in https://jira.appcelerator.org/browse/TIMOB-24438?focusedCommentId=419016&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-419016
Did not see any issues.

Studio Ver:     4.9.0.201704240654
SDK Ver:       6.2.0.v20170504083145
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.2
Appc NPM:       4.2.9
Appc CLI:       6.2.0
Ti CLI Ver:     5.0.12
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        > google Nexus 6P --- Android 7.1.1
                > google Nexus 6 --- Android 6.0.1

**Pull request merged**
