### PR TITLE
[TIMOB-17340]  Android: Add LineSpacing for Textfield/Textarea

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-17340

Since it's already implemented in the Label it could be added here, too

linespacing

### CODE REVIEW

**Comment by m1ga** [comment]
But I still want to have https://github.com/appcelerator/titanium_mobile/pull/8558 😄 @kopiro

**Comment by kopiro** [comment]
Ehehe :) Designers wants both.

**Comment by lokeshchdhry** [comment]
@garymathews , @jquick-axway , Can anyone please do a CR for this PR.

**Comment by garymathews** [comment]
Closing, succeeded by https://github.com/appcelerator/titanium_mobile/pull/9564

**Comment by jquick-axway** [comment]
@m1ga, the feature Gary added allows you to apply line spacing via a Titanium [AttributedString](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.AttributedString), which is how it's done on iOS. The idea is that you set up the text formatting via the AttributedString and apply it to the TextField/TextArea [attributedString](http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.TextField-property-attributedString) property. You just need to avoid calling the TextField/TextArea "value" property because it'll blow away your attributed string settings.

**Pull request closed without merging**
