### PR TITLE
fix(ios): check hyperloop availability at runtime

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26671

Hyperloop used to be enabled using a pre-processor define. This is not possible anymore since TitaniumKit is pre-compiled and can't see the pre-processor values during the app build. Move to a runtime check to workaround this limitation.

Related: https://github.com/appcelerator/hyperloop.next/pull/313

### CODE REVIEW

**Comment by vijaysingh-axway** [comment]
Changes looks good.
@janvennemann Please fix formatting  issue.

**Comment by janvennemann** [comment]
@vijaysingh-axway Linting issues fixed

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by sgtcoolguy** [comment]
@ssjsamir @longton95 I've merged this to master/8_0_X and resolved the ticket (but haven't closed it as I didn't see an FR)

**Pull request merged**
