### PR TITLE
fix(android): fix Ti.UI.ListView scroll state restoration

### PR DESCRIPTION
**Pull request by hansemannn**
One note: At least on the Emulator, the list view seems to lose focus after re-rendering the list view. Not sure if thats an Emulator-only issue.

### CODE REVIEW

**Comment by m1ga** [comment]
some kind of test code would be very nice next time to test it. I've quickly created this one:
```js
const win = Ti.UI.createWindow({});
var listView = Ti.UI.createListView({
	templates: {
		test: {
			childTemplates: [{
				type: 'Ti.UI.View',
				childTemplates: [{
					type: 'Ti.UI.Label',
					bindId: 'label',
					properties: {
						color: 'black',
						bindId: 'label',
						bottom: 5
					}
				}],
				properties: {
					width: Ti.UI.FILL,
					height: 100,
					cardUseCompatPadding: true,
					backgroundColor: 'white'
				}
			}]
		}
	},
	defaultItemTemplate: 'test'
});
var section = Ti.UI.createListSection();
var items = [];

function addItems(adding) {
	for (let i = 0; i < 100; i++) {
		var txt = "Row: " + (i + adding);
		items.push({
			label: {
				text: txt
			},
			template: 'test'
		})
	}
	section.setItems(items);
}

listView.sections = [section];
win.add(listView);
win.addEventListener('open', function() {
	addItems(0);

	setTimeout(function(){
		listView.scrollToItem(0,50);
		setTimeout(function(){
			addItems(100)
		}, 2000);
	}, 1000)
})
win.open();
```

Without the PR it will scroll to the top after 3 sec. With the PR it will stay at the same position and just attach the items.

**Review by m1ga — APPROVED** [review]
Looks fine, test code works better with the PR and my existing app still works the same

**Review by caspahouzer — APPROVED** [review]
No scrolling detected with this fix

LGTM

**Comment by hansemannn** [comment]
We have to revert it I think, the PR was not finished so far. The potential open issue with the missing focus needs to be tested on device. Sorry for the missing code @m1ga, I was about to add it this evening. Its already happening when generating a long list of items and setting the sections again (causing the internal `update` method to be called).

**Comment by m1ga** [comment]
@hansemannn I've tested it on a device (Pixel 4, Android 12) and emulator (Android 13).

**Comment by hansemannn** [comment]
Okay, so the view did not lose focus / turn gray? Then it's all good.

**Comment by hansemannn** [comment]
Minimalistic test case:
```js
const window = Ti.UI.createWindow();

const listView = Ti.UI.createListView({
	sections: [
		Ti.UI.createListSection({
			items: generateItems()
		})
	]
});

window.add(listView);
window.open();

setTimeout(() => {
	listView.sections[0].items = generateItems();
}, 3000);

function generateItems() {
	return  Array.from(Array(30).keys()).map(num => ({ properties: { title: `Cell ${num + 1}` } }))
}
```

**Comment by hansemannn** [comment]
I guess we are fine then. Cool!

**Comment by m1ga** [comment]
> Okay, so the view did not lose focus / turn gray? Then it's all good.

not sure what you mean by that :smile: Your example looks the same with 11.0.0.RC and the patched SDK on my device, at start and 3 seconds later :smile: It only fixes the scrolling that my example is showing. Rest looks fine

**Comment by hansemannn** [comment]
In my internal example, we have a text field in the item and after hitting the "Return" key, the list seems to lose focus. But it seems okay.

**Pull request merged**
