### PR TITLE
[TIMOB-24775] iOS 11: Remove Xcode 8 macros, add new macros / utilities, fix Xcode 9 Analyser warnings

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24775

### CODE REVIEW

**Review by vijaysingh-axway — COMMENTED** [review]
For me when I am running this pr on Xcode 8.3, I am getting error - "ld: framework not found IOSurface for architecture arm64". On xcode 9 it is working fine. @hansemannn Is this problem at your end also. I found a link for same as "https://stackoverflow.com/questions/44450673/framework-not-found-iosurface-for-architecture-arm64"

**Comment by hansemannn** [comment]
It's a Beta issue where Xcode 9 will keep derived data although cleaned up I guess. I had the same with the [FileProvider](https://developer.apple.com/documentation/fileprovider) API that is iOS 11+ and did not have **any** references in the titanium_mobile project (even did multiple recursive searches). We can wait until B2 comes out, that should be a very frequent issue right now.

**Comment by vijaysingh-axway** [comment]
@hansemannn,  I tried to run this pr using Xcode 9 beta 3, still same problem. I created a sample app using Xcode 8 , it is running on Xcode 8 and Xcode 9 beta 3 both. I think we should look in this if any problem from our side ?

**Comment by hansemannn** [comment]
@vijaysingh-axway I just resolved all merge conflicts, packaged the SDK locally and made a test-build. All working on my side. Please check with Beta 4.

**Comment by vijaysingh-axway** [comment]
@hansemannn Have you tried with referencing Xcode 8 and iOS 10 ? For me it is still giving problem. If it works for you then it may be some Xcode setup problem at my end, in this case we can pass it to QE.

**Comment by hansemannn** [comment]
@ewieberappc Can you validate this early? We have different outputs here, thx!

**Comment by hansemannn** [comment]
Will open a new PR, this one contains too many iOS 11 unrelated changes by now.

**Pull request closed without merging**
