### PR TITLE
[TIMOB-25533] Android: Fix pending HTTP request status

### PR DESCRIPTION
**Pull request by garymathews**
- Set pending state before callbacks

```JS
var count = 1,
    client = Ti.Network.createHTTPClient({
        onload: (e) => {
            Ti.API.info(e);
            
            // should send 8 requests
            if (count < 8) {
                client.send(JSON.stringify({ payload: 'COUNT #' + ++count }));
            }
        },
        onerror: (e) => {
            Ti.API.error(e);
        }
    });

client.open('POST', 'https://webhook.site/dec4a6ff-c910-4eba-9e63-e24cd23b2a84'); // set this up
client.setRequestHeader('Content-Type', 'application/json; charset=utf8');
client.send(JSON.stringify({ payload: 'COUNT #' + count }));
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25533)

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
**LGTM**

**Comment by sgtcoolguy** [comment]
@garymathews Can we turn your manual test into a mocha test in our httpclient suite? Is the url reliable, or does it go away after some time?

**Comment by garymathews** [comment]
@sgtcoolguy It's only temporary :(

**Comment by sgtcoolguy** [comment]
@garymathews As per the DangerJS comments, this is crashing the iOS mocha tests. 

Looks like we have some state assertions built into our native http client library that are now failing?

The relevant part of the crash log is here:
```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Application Specific Information:
Assertion failed: (self.response.readyState == APSHTTPResponseStateUnsent), function -[APSHTTPRequest send], file /Users/vijaysingh/Documents/TitaniumProject/titanium_mobile_modules/APSHTTPClient/APSHTTPClient/APSHTTPRequest.m, line 69.
 
CoreSimulator 494.13.6 - Device: iPhone 7 Plus - Runtime: iOS 11.0 (15A372) - DeviceType: iPhone 7 Plus

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x000000011ceebd42 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x000000011cf23457 pthread_kill + 90
2   libsystem_c.dylib             	0x000000011cbac107 abort + 127
3   libsystem_c.dylib             	0x000000011cb74798 __assert_rtn + 320
4   com.appcelerator.testApp.testing	0x000000010fe4037a -[APSHTTPRequest send] + 3658
5   com.appcelerator.testApp.testing	0x000000010fca44ec -[TiNetworkHTTPClientProxy send:] + 4780 (TiNetworkHTTPClientProxy.m:242)
6   com.apple.CoreFoundation      	0x00000001181fc56c __invoking___ + 140
7   com.apple.CoreFoundation      	0x00000001181fc440 -[NSInvocation invoke] + 320
8   com.appcelerator.testApp.testing	0x000000010fbb495d -[KrollMethod call:] + 2045
9   com.appcelerator.testApp.testing	0x000000010fbb3231 __KrollCallAsFunction_block_invoke + 49 (KrollMethod.m:53)
10  com.appcelerator.testApp.testing	0x000000010fcb322d TiThreadPerformOnMainThread + 77 (TiBase.m:321)
11  com.appcelerator.testApp.testing	0x000000010fbb2ede KrollCallAsFunction + 702 (KrollMethod.m:52)
12  com.apple.JavaScriptCore      	0x0000000110b64a50 JSC::JSCallbackObject<JSC::JSDestructibleObject>::call(JSC::ExecState*) + 512
13  com.apple.JavaScriptCore      	0x0000000110c6fd01 JSC::LLInt::setUpCall(JSC::ExecState*, JSC::Instruction*, JSC::CodeSpecializationKind, JSC::JSValue, JSC::LLIntCallLinkInfo*) + 577
14  com.apple.JavaScriptCore      	0x0000000110c78f7d llint_entry + 27269
15  com.apple.JavaScriptCore      	0x0000000110c72310 vmEntryToJavaScript + 304
16  com.apple.JavaScriptCore      	0x0000000110b032ef JSC::JITCode::execute(JSC::VM*, JSC::ProtoCallFrame*) + 127
17  com.apple.JavaScriptCore      	0x0000000110ac9981 JSC::Interpreter::executeCall(JSC::ExecState*, JSC::JSObject*, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 433
18  com.apple.JavaScriptCore      	0x00000001107ba9a2 JSC::profiledCall(JSC::ExecState*, JSC::ProfilingReason, JSC::JSValue, JSC::CallType, JSC::CallData const&, JSC::JSValue, JSC::ArgList const&) + 178
19  com.apple.JavaScriptCore      	0x0000000110bc43bd JSObjectCallAsFunction + 461
20  com.appcelerator.testApp.testing	0x000000010fbbc0c8 __65-[KrollObject invokeCallbackForKey:withObject:thisObject:onDone:]_block_invoke + 632 (KrollObject.m:1103)

```

**Comment by garymathews** [comment]
@hansemannn Humm... looks like this needs some re-work on iOS

**Comment by lokeshchdhry** [comment]
FR Passed.

No `HTTP` error seen.

Studio Ver:     5.1.0
SDK Ver:        7.2.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.12
Appc CLI:       7.0.3-master.23
Daemon Ver:     1.0.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       9.0.4
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0

**Comment by lokeshchdhry** [comment]
Will do an FR again once work on this PR is complete.

**Comment by lokeshchdhry** [comment]
@hansemannn , Is anybody working on the IOS part for this ticket. Because we will also need a backport once both platform fixes are in.

**Comment by hansemannn** [comment]
@lokeshchdhry This PR is supposed to include iOS as well, but it seems like its not stable so far. Not sure if I should take it over or not.

**Comment by lokeshchdhry** [comment]
@garymathews, Can you please resolve the conflicts?

**Comment by hansemannn** [comment]
iOS change: https://github.com/appcelerator/APSHTTPClient/pull/46

**Comment by lokeshchdhry** [comment]
FR Passed for Android & IOS.

No HTTP errors seen.

Studio Ver:     5.1.0.201804230827
SDK Ver:        7.2.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.13
Appc CLI:       7.0.3
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1
Emulator:       ⇨ Android 4.1.2
IOS Emulator: Iphone 8 IOS 11.3

**Pull request merged**
