### PR TITLE
[TC-4699] iOS: Fix crash in TiBase : TiThreadProcessPendingMainThreadBlocks

### PR DESCRIPTION
**Pull request by ghost**
We have a recurring error on Crashlytics for iOS platform : 
TiBase.m line 279
__destroy_helper_block_187
Crashed: com.apple.main-thread
EXC_BAD_ACCESS KERN_INVALID_ADDRESS at 0xc0000010
0  libobjc.A.dylib                0x3b2ca7ea objc_release + 9
1  libsystem_blocks.dylib  0x3b7f2ac5 _Block_release + 216
2  MyApp                            0x000dd697 __destroy_helper_block_187 (TiBase.m:279)
3  libsystem_blocks.dylib   0x3b7f2ac5 _Block_release + 216
4  MyApp                            0x000dd839 TiThreadProcessPendingMainThreadBlocks (TiBase.m:366)

To fix this error we use autorelease for "thisAction" and we replace NSAutoreleasePool with new syntax :  @autoreleasepool.  

Do you think this fix is appropriate?

Thanks for your help

### CODE REVIEW

**Comment by alexgbernier** [comment]
We have the same issue with the overwhelming majority of crashes from production coming from this issue. @ingo, can this be looked at again?

**Comment by ingo** [comment]
Can you provide any new information? What SDK, OS?

**Comment by alexgbernier** [comment]
iOS, 3.4.1.GA. We use a background service on iOS. Wondering if that could be related.

**Comment by alexgbernier** [comment]
We've seen the bug since we've had crash reporting, since SDK 3.2.3, so it's not specific to 3.4.1.GA.

**Comment by ingo** [comment]
I would suggest seeing if you can isolate it into any kind of test case. If we can't reproduce it, we can't know if we fixed it.

**Comment by alexgbernier** [comment]
Totally get it. We've never seen the crash. Will let you know if we can pin
it down.

**Comment by alexgbernier** [comment]
@shopmium I'm curious if this reduced the rate of crashes in prod for you? Thank you!

**Comment by hansemannn** [comment]
Closing this PR, since the error hasn't been able to be reproduced since last year.

**Comment by wsliaw** [comment]
We are having this issue too, we are using SDK 5.2.2, getting a lot of this log from Crashlytics. We start getting this since we added background service to our iOS app, but unfortunately we can't reproduce it, it seems occurs randomly. I will keep trying to reproduce it but hopefully you can help us to reinvestigate it, many thanks.

**Pull request closed without merging**
