### PR TITLE
fix(ios): backgroundcolor Ti.UI.backgroundColor fixed on modal windows (#13392)

### LINKED ISSUE #13392: iOS fix for Ti.UI.backgroundColor for modal windows
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

when open a modal window or dialog like the photogallery, the background will be black. The base color set via Ti.UI.backgroundcolor is not respected.

### Solution

I fixed that in **TitaniumKit/TitaniumKit/Sources/API/TiRootViewController.m** with a one liner, so that now the backroundcolor is respected.

Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-13 at 02 03 20
Simulator Screen Shot - iPhone 12 Pro Max - 2022-04-13 at 02 01 20

### Alternatives

_No response_

### Platforms

iOS

### PR DESCRIPTION
**Pull request by mbender74**
Fixed backgroundcolor via Ti.UI.backgroundcolor for iOS on modal windows

### CODE REVIEW

**Review by caspahouzer — DISMISSED** [review]

**Review by caspahouzer — COMMENTED** [review]
I've tested with
```
Ti.UI.backgroundColor = '#000';
var win = Ti.UI.createWindow({title: 'Appcelerator Titanium'});

var navigationWindow = Ti.UI.createNavigationWindow({
    window: win
});
var modalButton = Ti.UI.createButton({
    title: 'Open Modal',
});
modalButton.addEventListener('click', function () {
    var modalNavigationWindow = Ti.UI.createNavigationWindow({
        window: Ti.UI.createWindow({
            title: 'Modal Window',
        })
    });
    modalNavigationWindow.open({
        modal: true
    });
});
win.add(modalButton);
navigationWindow.open();
```
and it results in a modal window with transparent background

https://user-images.githubusercontent.com/1126641/163124572-b47860cf-3f25-4e37-b900-e717d3b640a7.mov

Am I doing it right?

**Comment by mbender74** [comment]
@caspahouzer did you set a backgroundcolor of your window?
I will check your code....

**Comment by caspahouzer** [comment]
@mbender74 No backgroundColor for the window is set

I also tried 
```
Ti.UI.backgroundColor = '#000';
var win = Ti.UI.createWindow({title: 'Appcelerator Titanium'});

var navigationWindow = Ti.UI.createNavigationWindow({
    window: win
});
var modalButton = Ti.UI.createButton({
    title: 'Open Gallery',
});
modalButton.addEventListener('click', function () {
    Ti.Media.openPhotoGallery();
});
win.add(modalButton);
navigationWindow.open();
```
Simulator Screen Shot - iPhone 13 Pro Max - 2022-04-13 at 09 42 14

**Comment by mbender74** [comment]
```
Ti.UI.backgroundColor = 'green';
var win = Ti.UI.createWindow({title: 'Appcelerator Titanium',height:Ti.UI.FILL,width:Ti.UI.FILL,backgroundColor:'red'});

var navigationWindow = Ti.UI.createNavigationWindow({
    window: win
});
var modalButton = Ti.UI.createButton({
    title: 'Open Modal',
});
modalButton.addEventListener('click', function () {
    var modalNavigationWindow = Ti.UI.createNavigationWindow({
        window: Ti.UI.createWindow({
            title: 'Modal Window',
            height:Ti.UI.FILL,
            width:Ti.UI.FILL,
            backgroundColor:'yellow'
        })
    });
    modalNavigationWindow.open({
        modal: true
    });
});
win.add(modalButton);
navigationWindow.open();
```

**Comment by mbender74** [comment]
when you set black color, you will not notice any difference to before....

**Review by caspahouzer — APPROVED** [review]
I now got the exact function of the backgroundColor. It's for the app and not an overwrite for the window. Got it.

LGTM

**Comment by mbender74** [comment]
@caspahouzer BTW, what is the meaning of LGTM?

**Comment by hansemannn** [comment]
@mbender74 Looks Good To Me

**Comment by caspahouzer** [comment]
@mbender74 Let's Get This Merged

**Pull request merged**
