### PR TITLE
[TIMOB-27126] feat(ios): support TiColor for all color-setters

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27126

The SDK side changes to support dark mode (semantic colors). This SDK change does not relate to iOS 13 / Xcode 11 and runs fine on older devices. It just makes sure that all color-related setters can accept a `TiColor` object which does the magic.

For more infos, join the [dark side](https://github.com/hansemannn/titanium-dark-mode)!

### CODE REVIEW

**Comment by hansemannn** [comment]
What's the problem here? The PR should be pretty simple to reproduce / test and is fundamental to support iOS 13 dark mode properly.

**Comment by sgtcoolguy** [comment]
LGTM, but defer to @ewanharris and @vijaysingh-axway for this...

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by hansemannn** [comment]
Ping! Please don't forget this one for 8.2.0. Otherwise all dark mode changes are useless.

**Comment by keerthi1032** [comment]
FR passed. label/text color changes to according to dark/light mode
Test Enviornment:
Operating System
  Name                        = Mac OS X
  Version                     = 10.14.5
  Architecture                = 64bit
Node.js
  Node.js Version             = 10.16.2
  npm Version                 = 6.9.0
Titanium CLI
  CLI Version                 = 5.2.1
Titanium SDK
  SDK Version                 = local sdk 8.2.0.v20190903105127
Device -iPhone XR iOS 13
Simulator -iPhone 8 iOS 13

**Pull request merged**
