### PR TITLE
 Android Webview Photo upload #7949 

### PR DESCRIPTION
**Pull request by NikunjKapupara**
**JIRA:** https://jira.appcelerator.org/browse/AC-3520

Provide a clear PR title prefixed with `AC-3520`
screenshot_2016-04-18-13-23-41
## DESCRIPTION:

In one of the my Appcelerator Project there is one functionality like,

We are showing a remote webpage in webview and in that webpage there is Photo Upload Browse button.

By clicking on that button Option dialog comes that ask to choose photo from Camera or Photo Gallery and we can select the photo.

That functionality is works fine in iOS but in android Titanium SDK has not support to choose and upload a photo from remote web page which is loaded on webview.

Earlier we are using a modified Titanium SDK. Can you please modified latest Titanium SDK(5.2.X Onwards) that support this feature.

**The remote web page has done this code in HTML file and it's working fine in iOS but not working in android.

<input name="sitePlanDocument" id="sitePlanDocument" type="file" accept="image/jpg, image/JPG,image/JPEG, image/jpeg,image/jpeg,image/gif,image/png, application/pdf,image/x-eps, application/msword" error-size="${filesize}" error-extention="${fileextention}" error-failed="${fileerror}"/>**

Modified SDK (https://www.dropbox.com/s/j2csab3dhy6w3u2/4.1.0.GA_For_Correction_Camera_Web_upload.zip?dl=0) which allow to select photo from gallery or camera and this working fine in iOS and Android so the same change I need for latest version of Titanium SDK (5.2.X Onwards)

If you know, what changes we have to do in Titanium SDK to support this feature so can you suggest me in which file of Titanium SDK we need to do changes and what changes we have to write Titanium SDK files ?.
b86327ec-056f-11e6-941c-8e6edf48e923

### CODE REVIEW

**Comment by NikunjKapupara** [comment]
Can you modified any current Titanium 5.2.X version of SDK and send me back as earlier we got the same because I can't wait for next release when it will available and our application is LIVE already. Moreover, I also have to give the support of Android 6.0 and Android 6.0 support can't be possible in 4.1.0GA SDK because it takes TargetSDK 22 and we have uploaded Target SDK 23 on store.

In short I need any of current Titanium 5.2.X version of SDK which allow me to select photo from webview in android as I have mentioned above. (attachment)

It's very urgent so please co-operate me.

**Comment by hansemannn** [comment]
Now you want to merge into `FokkeZB-patch-1` from master. You can always build your own version of the SDK, see [here](http://docs.appcelerator.com/platform/latest/#!/guide/Building_the_Titanium_SDK_From_Source) for more infos.

**Comment by ashcoding** [comment]
@hansemannn With ref to this PR and https://jira.appcelerator.org/browse/AC-3520, I added comments into the ticket with which comment is needed exactly.

**Comment by ashcoding** [comment]
@NikunjKapupara Please see progress in Jira ticket https://jira.appcelerator.org/browse/TIMOB-23229

Closing this PR as it is not required.

**Pull request closed without merging**
