### PR TITLE
[TIMOB-19911] Added support for custom entitlements from the tiapp.xml.

### PR DESCRIPTION
**Pull request by cb1kenobi**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-19911

### CODE REVIEW

**Comment by hansemannn** [comment]
This does not work. I tried this <ios> section:
```xml
<ios>
	<enable-launch-screen-storyboard>true</enable-launch-screen-storyboard>
	<use-app-thinning>true</use-app-thinning>
	<entitlements>
		<key>keychain-access-groups</key>
		<array>
			<string>$(AppIdentifierPrefix)com.appcelerator.titanium</string>
		</array>
	</entitlements>
	<plist>
		<dict>
			<key>UIStatusBarStyle</key>
			<string>UIStatusBarStyleDefault</string>
		</dict>
	</plist>
</ios>
```

The generated entitlements file does not include the keys.

**Comment by cb1kenobi** [comment]
I retested it and it worked as expected. My app name is {{appctest}} and thus the file is {{build/iphone/appctest.entitlements}}:

```
<?xml version="1.0" encoding="UTF-8"?>
<!DOCTYPE plist PUBLIC "-//Apple//DTD PLIST 1.0//EN" "http://www.apple.com/DTDs/PropertyList-1.0.dtd">
<plist version="1.0">
<dict>
	<key>keychain-access-groups</key>
	<array>
		<string>$(AppIdentifierPrefix)com.appcelerator.titanium</string>
	</array>
</dict>
</plist>
```

**Comment by hansemannn** [comment]
Using a packaged 6.1.0 and am able to find the changes you made in the packaged version. Example project attached.
[test_entitlements.zip](https://github.com/appcelerator/titanium_mobile/files/668812/test_entitlements.zip)

**Comment by cb1kenobi** [comment]
@hansemannn Oops. You need to wrap everything in the `<entitlements>` in a `<dict>` tag just like `<plist>`. So, try:

```
<entitlements>
	<dict>
		<key>keychain-access-groups</key>
		<array>
			<string>$(AppIdentifierPrefix)com.appcelerator.titanium</string>
		</array>
	</dict>
</entitlements>
```

**Comment by hansemannn** [comment]
CR + FT approved.

**Pull request merged**
