### PR TITLE
[TIMOB-20247] Regression in android HTTPClient

### PR DESCRIPTION
**Pull request by ypbnv**
Send the headers ready state once they and the status are read

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-20247

### CODE REVIEW

**Review by jquick-axway — CHANGES_REQUESTED** [review]
The code changes look good except for the tabbing inconsistency. Can you change it to use spaces like the rest of the file please?  Either switch to spaces like the rest of the file or change the whole file to use tabs.

Note that our coding standard states that we use tabs. So, you were doing it right. This appears to be a rogue source file that was using spaces by mistake.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by ypbnv** [comment]
@jquick-axway If you could take a look again - I did small change in the charset check.

**Comment by jquick-axway** [comment]
The charset changes look good.
CR: Passed

**Review by ssjsamir — APPROVED** [review]
**FR Passed:** Was able to get a response using the test case provided in https://jira.appcelerator.org/browse/TIMOB-20247 without getting any errors. 

**Test steps**
+ Built the SDK form this PR
+ Copied the test case from the description in https://jira.appcelerator.org/browse/TIMOB-20247
```
var xhr = Titanium.Network.createHTTPClient();
 
xhr.onreadystatechange = function() {
    if (3 == xhr.readyState) {
        console.log(xhr.getResponseHeader('Last-Modified'));
    }
 
};
 
xhr.open('GET', 'http://www.appcelerator.com/assets/The_iPad_App_Wave.pdf');
 
xhr.send();
```
+ Pasted the code in to a titanium project 
+ Ran the program
+ Saw the following response in the console and application showed no errors 
```
[INFO] :   Thu, 04 May 2017 16:24:20 GMT
[INFO] :   Thu, 04 May 2017 16:24:20 GMT
```
**Environment**
Appcelerator Command-Line Interface, version 6.2.0
Samsung Galaxy S4 (Running android 4.4.4)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 4.6.0
npm: 4.2.8
Xcode: 8.2
Appcelerator Studio: 4.8.1.201612050850

**Pull request merged**
