### PR TITLE
[TIMOB-24707] Android: Show images and videos in picker

### PR DESCRIPTION
**Pull request by frankieandone**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24707

**Summary:**
Added `MEDIA_TYPE_VIDEO` support to `Ti.Media.openPhotoGallery()` on Android. Can now select both images and videos with this API, like iOS.
_(Does not support live photos. That is an iOS only feature.)_

**Test 1:**
Re-run test attached to PR #9918.

**Test 2:**
Re-run test attached to PR #9906.
Verify that selecting an image from Google Drive (via the cloud) does not cause a crash.

**Test 3:**
Re-run test attached to PR #9771.
Verify that the screenshot taken via `toImage()` can still be viewed via `previewImage()`.

**Test 4:**
_(You need to take photos and videos using the Android device's camera before starting the below test procedure.)_

1. Build and run the below code on an Android 7.0 or newer device.
2. An alert is displayed upon app launch. Tap the "Photo" button.
3. Select a photo from the gallery.
4. Verify the Titanium app display the selected photo.
5. Back out of the app and re-launch it.
6. An alert is displayed upon app launch. Tap the "Video" button.
7. Select a video from the gallery.
8. Verify the Titanium app plays the selected video.
9. Back out of the app and re-launch it.
10. An alert is displayed upon app launch. Tap the "Both" button.
11. Select a video from the gallery.
12. Verify the Titanium app plays the selected video.
13. Repeat steps 2-12 on an Android 4.1 device.

```javascript
var window = Ti.UI.createWindow();
window.addEventListener("open", function(e) {
	var dialog = Ti.UI.createAlertDialog(
	{
		message: "Which media type do you want to open?",
		buttonNames: ["Photo", "Video", "Both"],
	});
	dialog.addEventListener("click", function(e) {
		var mediaTypes;
		if (e.index === 0) {
			mediaTypes = [Ti.Media.MEDIA_TYPE_PHOTO];
		} else if (e.index === 1) {
			mediaTypes = [Ti.Media.MEDIA_TYPE_VIDEO];
		} else if (e.index === 2) {
			mediaTypes = [Ti.Media.MEDIA_TYPE_PHOTO, Ti.Media.MEDIA_TYPE_VIDEO];
		} else {
			Ti.API.info("@@@ Alert was canceled.");
			return;
		}
		Ti.Media.openPhotoGallery(
		{
			allowMultiple: false,
			allowEditing: false,
			autohide: true,
			mediaTypes: mediaTypes,
			success: function(e) {
				Ti.API.info("@@@ e: " + JSON.stringify(e));
				Ti.API.info("@@@ e.media.file: " + e.media.file);
				Ti.API.info("@@@ e.media.nativePath: " + e.media.nativePath);
				switch (e.mediaType) {
					case Ti.Media.MEDIA_TYPE_PHOTO:
					case Ti.Media.MEDIA_TYPE_LIVEPHOTO:
						window.add(Ti.UI.createImageView(
						{
							image: e.media,
							width: Ti.UI.FILL,
							height: Ti.UI.FILL,
						}));
						break;
					case Ti.Media.MEDIA_TYPE_VIDEO:
						window.add(Ti.Media.createVideoPlayer(
						{
							url: e.media.nativePath,
							autoplay: true,
							mediaControlStyle: Ti.Media.VIDEO_CONTROL_DEFAULT,
							scalingMode: Ti.Media.VIDEO_SCALING_ASPECT_FIT,
							width: Ti.UI.FILL,
							height: Ti.UI.FILL,
						}));
						break;
					default:
						break;
				}
			},
			cancel: function() {
				Ti.API.info("@@@ Photo gallery selection canceled.");
			},
			error: function() {
				Ti.API.info("@@@ Photo gallery selection error.");
			},
		});
	});
	dialog.show();
});
window.open();
```

### CODE REVIEW

**Review by jquick-axway — CHANGES_REQUESTED** [review]
@fmerzadyan, you need to add support for the "mediaType" array argument here...
http://docs.appcelerator.com/platform/latest/#!/api/PhotoGalleryOptionsType-property-mediaTypes

If this array only contains `MEDIA_TYPE_PHOTO` or `MEDIA_TYPE_LIVE_PHOTO`, then the type string should be `"image/*"`.

If this array only contains `MEDIA_TYPE_VIDEO`, then the type should be `"video/*"`.

If the array contains both photo and video types, then it should be set to `"*/*"`.

**Comment by jquick-axway** [comment]
Updated PR:
- Finished code changes to support video selection and playback.
- Updated API documentation.
- Added test code to PR which displays selected photos and plays selected videos.

**Comment by hansemannn** [comment]
@jquick-axway @garymathews Can you resolve the conflicts?

**Comment by lokeshchdhry** [comment]
@jquick-axway , With this fix/improvement when I run the test from https://github.com/appcelerator/titanium_mobile/pull/9906 & select an image from drive I get a runtime error:
```
[ERROR] :  [Nexus 6P] TiExceptionHandler: (main) [31,31] /app.js:4
[ERROR] :  [Nexus 6P] TiExceptionHandler:         Ti.Media.previewImage({ image: e.media });
[ERROR] :  [Nexus 6P] TiExceptionHandler:                  ^
[ERROR] :  [Nexus 6P] TiExceptionHandler: Error: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
[ERROR] :  [Nexus 6P] TiExceptionHandler:     at Media.success (/app.js:4:18)
[ERROR] :  [Nexus 6P] TiExceptionHandler:
[ERROR] :  [Nexus 6P] TiExceptionHandler:     org.appcelerator.titanium.io.TiFileProvider.createUriFrom(TiFileProvider.java:47)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     ti.modules.titanium.media.MediaModule.previewImage(MediaModule.java:1407)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:55)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:41)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Function$1.run(V8Function.java:68)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     android.os.Handler.handleCallback(Handler.java:789)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     android.os.Handler.dispatchMessage(Handler.java:98)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     android.os.Looper.loop(Looper.java:164)
[ERROR] :  [Nexus 6P] TiExceptionHandler:     android.app.ActivityThread.main(ActivityThread.java:6541)
[ERROR] :  [Nexus 6P] V8Exception: Exception occurred at /app.js:4: Uncaught Error: Attempt to invoke virtual method 'java.lang.String java.io.File.getAbsolutePath()' on a null object reference
```

**Comment by jquick-axway** [comment]
@lokeshchdhry, my newest PR update resolves the previewImage() issue.

**Comment by lokeshchdhry** [comment]
FR Passed.

Images , videos or both are properly shown in the picker according to the `mediaTypes` property specified.

Studio Ver:     5.1.0.201804230827
SDK Ver:        7.2.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.13
Appc CLI:       7.0.3
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0
Emulator:       ⇨ Android 4.1.2

**Comment by lokeshchdhry** [comment]
@jquick-axway , Jenkins is complaining about no tests. Can you please take a look.

**Review by jquick-axway — APPROVED** [review]

**Pull request merged**
