### PR TITLE
fix: resolve all project warnings

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27163

This pull request ~~adds full Swift 5 compatibility, in summary:~~
- ~~Update iOS example Swift module to Swift 5~~
- ~~Update iOS Swift module template to Swift 5~~
- Resolve all project warnings (including missing method selectors, nullability flags and strict prototypes). Not removing the deprecations for now, which should be done in a separate ticket

Tested and confirmed to work. Common steps:
- ~~Create a new app and build it~~
- ~~Create a new iOS Swift module and build + import it~~
- Open the Titanium Xcode project template under `iphone/iphone/Titanium.xcodeproj` and build it
- The number of warnings should be reduced compared to building without this PR. Note that #10381 introduced a lot of new deprecation warnings so the total number of warning is still pretty high.

### CODE REVIEW

**Comment by janvennemann** [comment]
@hansemannn i think this one has some merge errors. I see a lot of changes to unrelated files.

**Comment by janvennemann** [comment]
I would like to split this PR up into the Swift version upgrade and fixing the warning messages. For the Swift version upgrade i created #10974. The warnings will be addressed via [TIMOB-27163](https://jira.appcelerator.org/browse/TIMOB-27163) by using the remaining changes of this PR.

**Comment by lokeshchdhry** [comment]
@janvennemann , can you please resolve the conflicts.

**Comment by janvennemann** [comment]
@lokeshchdhry resolved the first merge conflicts. Please do the FR on #10974 first. Merging that will create new conflicts in this PR that i'll resolve again and then you can the FR on this one.

**Review by janvennemann — APPROVED** [review]

**Comment by hansemannn** [comment]
Once this is merged we can directly tackle the next 100+ warnings :P

**Comment by keerthi1032** [comment]
FR Passed. warning reduced.
Test Environment:
 Name                        = Mac OS X
  Version                     = 10.14.5
  Architecture                = 64bit
Node.js
  Node.js Version             = 10.16.2
  npm Version                 = 6.9.0
Titanium CLI
  CLI Version                 = 5.2.1
Titanium SDK
  SDK Version                 = local sdk 8.2.0.v20190902191234
Device -iPhone X iOS 11,iphone xr iOS 13
Simulator -iPhone 8 iOS 12.4

**Comment by janvennemann** [comment]
Most of the new warnings come from our own getter/setter deprecation and will be removed in 9.0.0.

The rest is either:
- from external libraries (APSAnalytics)
- iOS API deprecation notices that will be tackled in another ticket
- value conversion warnings, which can usually be neglected

**Pull request merged**
