### PR TITLE
fix(android): retain isWhatever query methods on MenuItem/Sound, mark deprecated

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-28407

**Optional Description:**
Follow-on to #12677

- Add back, but deprecate:
  - `Ti.Android.MenuItem.isActionViewExpanded`
  - `Ti.Android.MenuItem.isCheckable`
  - `Ti.Android.MenuItem.isChecked`
  - `Ti.Android.MenuItem.isEnabled` 
  - `Ti.Android.MenuItem.isVisible`
  - `Ti.Media.Sound.isLooping` (added back to Android, it's cross-platform now)
  - `Ti.Media.Sound.isPlaying` (added back to Android, it's cross-platform now)
  - `Ti.Media.Sound.isPaused` (added back to Android, it's cross-platform now)

- Deprecate:
  - `Ti.UI.Tab.setWindow`

### CODE REVIEW

**Comment by jquick-axway** [comment]
FYI: I already changed kitchensink-v2 to use `Ti.Media.Sound.is*` properties.
https://github.com/appcelerator/kitchensink-v2/pull/56

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Review by ewanharris — APPROVED** [review]
Looks good to me, I can do an FR tomorrow if needed

**Comment by ewanharris** [comment]
@sgtcoolguy I overlooked that `Ti.UI.Tab.setWindow` is removed on iOS, but exists on Android. So I think the docs need to be amended to state that?

**Comment by sgtcoolguy** [comment]
@ewanharris Good catch! Trying to use `setWindow` on iOS causes an `Error`. I have pushed a fix by implementing it in our common JS extension layer for iOS that would be pretty easy to remove once we kill the method off.

**Pull request merged**
