### PR TITLE
[TIMOB-24484] Exclude .bundle images from xcassets

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24484

### CODE REVIEW

**Comment by cb1kenobi** [comment]
I don't love this solution, but it works. I recognize that `.bundle` paths are iOS resources, but checking the path seems a little lazy.

A more robust way would be to check the actual directory name being walked and passing through the `useAppThinning` flag:

```
var bundleFileRegExp = /^.+\.bundle$/;

function walk(src, dest, useAppThinning, ignore, origSrc, prefix) {
    fs.existsSync(src) && fs.readdirSync(src).forEach(function (name) {
        // <snip>
        if (srcStat.isDirectory()) {
            return walk(from, to, useAppThinning ? !bundleFileRegExp.test(name) : false, null, origSrc || src, prefix);
        }
        // <snip>
    }
}

this.logger.info(__('Analyzing Resources directory'));
walk(path.join(this.projectDir, 'Resources'),           this.xcodeAppDir, useAppThinning, ignorePlatformDirs);
walk(path.join(this.projectDir, 'Resources', 'iphone'), this.xcodeAppDir, useAppThinning);
walk(path.join(this.projectDir, 'Resources', 'ios'), this.xcodeAppDir, useAppThinning);
```

It's gross.

I propose we accept your solution and then we come up with a better way in the unified Titanium build pipeline to ignore app thinning for entire directory structures.

**Comment by hansemannn** [comment]
Agree. I tried to not touch any method signatures. I would still update the regex to yours, I think mine if overkill, by explicitly allowing everything inside the bundle .

**Comment by cb1kenobi** [comment]
Don't use my regex. It is designed for directory names. You could do something as simple as `/.+\.bundle\/.+/`.

**Comment by hansemannn** [comment]
any character before and after the path? Alrighty!

**Comment by hansemannn** [comment]
@cb1kenobi Need this in 6.1.0.

**Comment by cb1kenobi** [comment]
Looks good to me. **APPROVED**

**Review by cb1kenobi — APPROVED** [review]

**Pull request merged**
