### PR TITLE
fix(ios): Supported WKURLSchemeHandler to load custom url scheme

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26860

**Test:**
1. Create a Classic "Default Project" app.
2. Replace the "app.js" code with the below code.
3. Build and run on iOS.
4. Verify that 2 images are displayed (a soccer balls and an appc logo).

```javascript
var htmlText =
		'<!DOCTYPE html>' +
		'<html>' +
		'	<head>' +
		'		<meta name="viewport" content="width=device-width, initial-scale=1.0">' +
		'	</head>' +
		'	<body>' +
		'		<p>Relative Path Test</p>' +
		'		<img src="assets/images/tab1.png"/>' +
		'		<br/>' +
		'		<p>URL Scheme Test</p>' +
		'		<img src="app://Resources/assets/images/tab2.png"/>' +
		'	</body>' +
		'</html>';

var window = Ti.UI.createWindow();
var webView = Ti.UI.createWebView({
	html: htmlText,
});
window.add(webView);
window.open();
```

### CODE REVIEW

**Review by janvennemann — APPROVED** [review]
CR passed

**Review by ssjsamir — APPROVED** [review]
**FR Passed.** HTML assigned to WebView "html" property is now able to access app's local files.

Tested using the following test case: 
```
var htmlText =
		'<!DOCTYPE html>' +
		'<html>' +
		'	<head>' +
		'		<meta name="viewport" content="width=device-width, initial-scale=1.0">' +
		'	</head>' +
		'	<body>' +
		'		<p>Local Image File</p>' +
//		'		<img src="assets/images/tab1.png"/>' +
		'		<img src="app://Resources/assets/images/tab1.png"/>' +
		'	</body>' +
		'</html>';

var window = Ti.UI.createWindow();
var webView = Ti.UI.createWebView({
	html: htmlText,
});
window.add(webView);
window.open();

```

**Test Environment**
```
iPhone 6 (12.1 Sim)
APPC CLI: 7.0.10-17
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 8.9.1
Xcode 10.1
```

**Comment by jquick-axway** [comment]
@ssjsamir , can you uncomment the `` line and test that too please? We want to test both paths `"assets/images/tab1.png"` and `"app://Resources/assets/images/tab1.png"` on iOS, since they both broke in 8.0.0. Thanks.

**Comment by vijaysingh-axway** [comment]
@ssjsamir I have updated PR to fix paths "assets/images/tab1.png"  also. Please verify again.
Thanks @jquick-axway !

**Comment by ssjsamir** [comment]
@jquick-axway @vijaysingh-axway Now able to see the image as well when using `assets/images/tab1.png`

**Pull request merged**
