### PR TITLE
fix(ios): correctly decode device token for ios 13 compatability

### PR DESCRIPTION
**Pull request by ewanharris**
Fixes TIMOB-27386

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27386

Remote notifications cant be tested in the sim so marking `no tests`

### CODE REVIEW

**Comment by vijaysingh-axway** [comment]
@ewanharris  Please update this PR as well, similar to  https://github.com/appcelerator/titanium_mobile/pull/11203

**Comment by ewanharris** [comment]
@vijaysingh-axway updated PR

**Review by sgtcoolguy — APPROVED** [review]
Matches code in #11203 which was approved

**Review by ssjsamir — APPROVED** [review]
**FR Passed** A correct device token can be decoded. Tested with the following test case: 

```
Ti.App.iOS.addEventListener('usernotificationsettings', function registerForPush() {
 
// Remove event listener once registered for push notifications
Ti.App.iOS.removeEventListener('usernotificationsettings', registerForPush);
 
Ti.Network.registerForPushNotifications({
success: deviceTokenSuccess,
error: deviceTokenError,
callback: receivePush
});
});
 
// Register notification types to use
Ti.App.iOS.registerUserNotificationSettings({
types: [
Ti.App.iOS.USER_NOTIFICATION_TYPE_ALERT,
Ti.App.iOS.USER_NOTIFICATION_TYPE_SOUND,
Ti.App.iOS.USER_NOTIFICATION_TYPE_BADGE
]
});
 
// Process incoming push notifications
function receivePush(e) {
alert('Received push: ' + JSON.stringify(e));
}
// Save the device token for subsequent API calls
function deviceTokenSuccess(e) {
console.log('Yay it worked!');
console.log(e);
}
 
function deviceTokenError(e) {
console.log('Failed to register for push notifications! ' + e.error);
console.log(e);
}

```

**Test Environment**
```
MacOS Mojave version 10.14.4
Xcode 11 beta 5
Node.js ^8.11.1
iPhone 7 (13.0 beta 7)
"NPM":"4.2.15","CLI":"7.1.1"

**Pull request merged**
