### PR TITLE
[TIMOB-23313] Fixed packaging of iOS app with watch app.

### PR DESCRIPTION
**Pull request by cb1kenobi**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23313

### CODE REVIEW

**Comment by cheekiatng** [comment]
Looks good!

**Comment by theschnaz** [comment]
Is this fix live?

**Comment by hansemannn** [comment]
@theschnaz Yes, it's included in 6.0.0.GA and later

**Comment by theschnaz** [comment]
@hansemannn I have 6.0.1.GA but I'm still seeing this error. Are there any other known fixes for this?

**Comment by cb1kenobi** [comment]
@theschnaz Can you be more specific? Which error are you still seeing? The SwiftSupport directory missing error? Are you sure you're building with Titanium SDK 6.0.0.GA? Are you building via Appcelerator Studio or the CLI?

**Comment by theschnaz** [comment]
@cb1kenobi I uninstalled Appcelerator Studio and reinstalled it. I built my app via Appcelerator Studio 6.0.1.GA; everything works fine so far and I'm able to send the build to Apple...

...a few moments later, I receive an email from Apple:

"Dear developer,

We have discovered one or more issues with your recent delivery for "APP_NAME". To process your delivery, the following issues must be corrected:

Invalid Swift Support - The SwiftSupport folder is empty. Rebuild your app using the current public (GM) version of Xcode and resubmit it.

Once these issues have been corrected, you can then redeliver the corrected binary.

Regards,

The App Store team"

I have also archived the app via Xcode (7.3.1) with the latest version of MacOS. I still get the same email when I submit my app via Organizer and Application Loader. (I have 9 of these emails now.)

In other tickets, I've seen issues about watch apps; my app is only for iOS.

Best,

Greg

**Comment by cb1kenobi** [comment]
I presume your reference to "APP_NAME" is for anonymity.

Triple check that the `<sdk-version>` in the tiapp.xml is indeed set to `6.0.0.GA`.

When you build your app for the App Store, it should launch Xcode and open the Organizer. You should be able to show the xcarchive in Finder and go into the archive (it's just a directory). Inside the xcarchive should be the SwiftSupport directory. If it's not there, then that's not good, but we'll figure it out.

**Comment by theschnaz** [comment]
Yea, APP_NAME = the name of my app.

I set "<sdk-version>6.0.0.GA</sdk-version>" in my tiapp.xml file, but I get this error:
"[ERROR] :  Invalid selected Titanium SDK "6.0.0.GA"

Using "<sdk-version>6.0.1.GA</sdk-version>" instead...

The app builds fine via Appcelerator Studio...

I can see my build in Organizer, I can open its folder via Finder:

![screen shot 2017-01-19 at 12 38 42 am]
(https://cloud.githubusercontent.com/assets/76787/22095087/0e6a243a-dde0-11e6-9210-4e9210fea31b.png)

There is a SwiftSupport directory, with an iphonesos subdirectory, but it's empty.

**Comment by theschnaz** [comment]
Thanks for your help. I upgraded to Xcode 8 and now it's working.

**Comment by cb1kenobi** [comment]
@theschnaz Ah, great! That's interesting that it didn't work with Xcode 7.x. I don't think I ever tested packaging with Xcode 7. Doh. Anyways, good luck and if you run into more issues, feel free to reach out on https://jira.appcelerator.org or https://ti-slack.slack.com.

**Pull request merged**
