### PR TITLE
fix(android): fix views with border and transparency

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26394

**Description:**
Rework handling the disabling of the HW acceleration for views with transparency and borders. `isHardwareAccelerated()` returns whether the view is attached to a Window with enabled HW acceleration:
https://android.googlesource.com/platform/frameworks/base.git/+/refs/heads/master/core/java/android/view/View.java#20915
So it depends on the view being attached to a Window. Our call of `disableHWAcceleration()` in TiUIView.java happens before the native view is actually attached to a window, so it would require an additional check in order to determine when to disable acceleration for the TiBorderWrapperView. Currently `borderView.isHardwareAccelerated()` will always return false, resulting in skipping our method.
We had a change in 6.3.0.GA for this code in this PR:
https://github.com/appcelerator/titanium_mobile/pull/9410
Ran the test cases from it and it works fine both on Android 19 and Android 29.
This PR also fixes the case described in this JIRA ticket - https://jira.appcelerator.org/browse/TIMOB-26291
During FR I would recommend trying the test cases from all three PRs to avoid regressions.
Note: No unit test, since this is a visual fix.

**Test case:**
_app.js_
```js
var win = Ti.UI.createWindow({
     backgroundColor: '#fff'
});
 
var v1 = Titanium.UI.createView({
     backgroundColor: 'rgba(0,0,0,0.5)',
     height: 100,
     width: Ti.UI.FILL,
     borderRadius: 20
});
win.add(v1);
win.open();


```

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Review by ssjsamir — APPROVED** [review]
FR Passed: Views with borderRadius now show up semi-transparent. Tested with the test case in the description and additional tests from the mentioned PRs above were done.

**Test Environment**
```
MacOS Catalina 10.15 Beta
Node.js ^8.11.1
Android Pixel XL 7.1 Emulator 
"NPM":"4.2.15","CLI":"7.1.1"
Java Version 1.8.0_131
Android NDK:  12.1.2977051
```

**Comment by hansemannn** [comment]
Either this one or https://github.com/appcelerator/titanium_mobile/pull/10637 is causing a regression with Ti.Map which now displays an empty map, after updating to latest master. You can try with our internal project, I think both @garymathews  and @jquick-axway have access to it.

**Comment by jquick-axway** [comment]
@hansemannn, we'll check it out. Thanks.
Question: Do you have a border applied to your map?

**Comment by jquick-axway** [comment]
Okay, I've confirmed that we have a regression on "master". If you apply a border to a VideoView or MapView (something that requires hardware acceleration), then it won't render. I can understand this happening if "borderRadius" was involved (that's buggy on Google's end), but this is happening to rectangular borders now.
```javascript
var window = Ti.UI.createWindow({ fullscreen: true });
var videoView = Ti.Media.createVideoPlayer({
	url: "http://assets.appcelerator.com.s3.amazonaws.com/video/media.m4v",
	autoplay: true,
	borderWidth: "4dp",
	borderColor: "red",
	width: Ti.UI.FILL,
	height: Ti.UI.FILL,
});
window.add(videoView);
window.open();
```

**Comment by jquick-axway** [comment]
The fix for the regression can be found here:
https://github.com/appcelerator/titanium_mobile/pull/11262

It turns out the old code (before this PR) was wrongly "trying" to disabling hardware acceleration when it didn't need to, but failing due to what this PR was fixing. So, this PR merely the old bug to the surface.

**Comment by hansemannn** [comment]
Thanks Josh, that was fast!

**Pull request merged**
