### PR TITLE
[TIMOB-24266] iOS: Expose UIApplicationDelegate to modules / Hyperloop

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24266

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway @janvennemann Ping for the review.

**Review by vijaysingh-axway — APPROVED** [review]
CR and FT passed.

**Comment by hansemannn** [comment]
@janvennemann Your Review?

**Review by janvennemann — APPROVED** [review]
LGTM!

**Pull request merged**
