### PR TITLE
[TIMOB-4790] Android: Worker API

### PR DESCRIPTION
**Pull request by drauggres**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-4790

This PR also includes changes for [TIMOB-24549](https://jira.appcelerator.org/browse/TIMOB-24549) and [TIMOB-26239](https://jira.appcelerator.org/browse/TIMOB-26239).

```javascript
const TAG = 'app.js';

let task = Ti.Worker.createWorker('worker.js', {name: `Worker Thread`});

task.addEventListener('message', function onMessage(event) {
    console.log(TAG, event.type, JSON.stringify(event.data));
});

task.postMessage({string: 'string', array: [1, 'abc', 2, {a: 'b'}]});
```

```javascript
// echo.js 
// `appcelerator-modules/ti.worker` API
worker.addEventListener('message', function(e) {
    console.log('worker.addEventListener', JSON.stringify(e.data));
    worker.postMessage(e.data)
});

// also works
worker.onmessage = function(e) {
    console.log('worker.onmessage', JSON.stringify(e.data));
    worker.postMessage(e.data)
};
```
or
```javascript
// echo.js Web Workers API
onmessage = function(e) {
    console.log('onmessage', JSON.stringify(e.data));
    postMessage(e.data)
};

// also works
addEventListener('message', function(e) {
    console.log('addEventListener', JSON.stringify(e.data));
    postMessage(e.data)
});
```

How it works:
- Added `v8::Locker` for `v8::Isolate`
- All `Isolate` specific templates/objects/functions/etc stored in map by thread id as a key (or `Isolate` itself, where appropriate).
- After `WorkerProxy` creation it creates `V8Worker` instance which spawns a new thread.
- In the new thread `V8Worker` creates new `Isolate` (and `Locker`), context and does "bootstrap", almost as if it was original `V8Runtime`
- `V8Worker` reads scripts content (file name passed as parameter to `WorkerProxy` constructor/factory) and executes it in newly created "environment" (and of course in the new thread)

#### WorkerProxy
```javascript
worker.postMessage(message);
```
`message` - The object to deliver to the worker; this will be in the `data` field in the event delivered to the `onmessage` handler (and listener added with `addEventListener` method). This may be any value or JavaScript object handled **(WITHOUT CYCLES)**.
##### property ~`onmessage`~
NOT IMPLEMENTED use `worker.addEventListener('message', function(e) {...});`
##### event `message`
Fired after call to `postMessage` inside worker. Field `data` contains data sended from worker.
##### event `error`
Fired when file specified at `WorkerProxy` creation can't be found or when it's empty.

##### methods `addEventListener` and `removeEventListener`
Use them with event type `message`
##### event `message`
Fired after call to `postMessage` on `WorkerProxy`. Field `data` contains data sended from main thread.

#### Module `appcelerator-modules/ti.worker` partly API compliance
- `WorkerGlobalScope` exposed as `worker` object on itself
- method `postMessage`
- method `terminate`
- ~method `nextTick`~ (Not implemented. I would recommend to use `Promise.resolve().then(...)`)
- method `addEventListener('message', ...)`
- event `message`
- ~event `terminated`~ (Not implemented)

### TODO:
- [x] `EventTarget` interface on `WorkerGlobalScope` (`addEventListener`/`removeEventListener`...)

### Next steps (maybe some time later):
- Debugger refactoring to support worker threads debugging
- Implement [structured clone algorithm](https://developer.mozilla.org/en-US/docs/Web/Guide/DOM/The_structured_clone_algorithm)

### CODE REVIEW

**Comment by garymathews** [comment]
Thanks for this contribution, this is nice!

We will take a look once you have finished.

**Comment by drauggres** [comment]
It's turned out that we can't create worker with `new Worker('file.js')`, because when there is no `Ti.Worker` string in the application code, build system will not include "worker module" classes in the apk (for "production" builds). So for now `Ti.Worker.createWorker` is the only way to create new worker.

Also fixed `onmessage` handler (was called twice)
Added tests.

**Comment by ffMathy** [comment]
What is the status on this?

**Comment by drauggres** [comment]
@ffMathy If you mean the code: I know at least one person (except me) who uses it. Everything should work as described in the first message. You can build it yourself or grab prebuilt SDK from [here](https://github.com/drauggres/titanium_mobile/releases/tag/8.0.1.WORKER).
Let me know if you'll have any problems with it.

**Pull request closed without merging**
