### PR TITLE
fix(ios): ensure default icon is not flattened during maccatalyst builds to avoid white background

### PR DESCRIPTION
**Pull request by narbs**
When running the Catalyst build, the DefaultIcon-ios.png is used to generate the Mac Catalyst app icon. This message is displayed:
`The default icon "DefaultIcon-ios.png" contains an alpha channel and will be flattened against a white background`
This is in the iOS build in iphone/cli/commands/_build.js:5925
I can get around it by doing:
```
// Do we need to flatten the default icon?
	let osName = this.xcodeTargetOS;
	if (this.target === 'macos' || this.target === 'dist-macappstore') {
		osName = 'maccatalyst';
	}
	if (missingIcons.length !== 0 && defaultIcon && defaultIconChanged && defaultIconHasAlpha && osName !== 'maccatalyst') {
```
This means that the flattening won't happen for catalyst builds.
What would be better is to have a DefaultIcon-catalyst.png or something like that because I now would have to copy an alpha png to DefaultIcon-ios.png for Catalyst builds to differentiate between these and iOS builds.
@hansemannn @m1ga

### CODE REVIEW

**Review by cb1kenobi — APPROVED** [review]
I'm cool with this, though I cannot test it.

**Comment by cb1kenobi** [comment]
@narbs Before we can accept this PR, we need you to sign the CLA. Go to https://github.com/tidev/organization-docs/blob/main/AUTHORIZED_CONTRIBUTORS.md and follow the instructions. You need to ping Josh with your email and he'll send you a CLA link to sign. Sorry for the hassle.

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@narbs Quick check: Have you submitted the CLA to @joshualambert ?

**Comment by narbs** [comment]
@hansemannn Yes I just did that today! CLA submitted...

**Comment by joshualambert** [comment]
We're good to go on this @hansemannn - he completed the e-sign on the TiDev Docusign on August 4th, 2023. I forgot to add that to the AUTHORIZED_CONTRIBUTORS.md file, but this is fixed now. He should be good to go now. See here: https://github.com/tidev/organization-docs/commit/7648b38c9ddd47bf4f6b5ea17782d922aae2c39d

**Pull request merged**
