### PR TITLE
[TIMOB-26060] Move NavigationWindow API to cross-platform Ti.UI namespace (parity)

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26060

```js
var win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

var newNavWindow = Ti.UI.createNavigationWindow({
    window: win
})

Ti.API.warn('API (new) = ' + newNavWindow.apiName);

var btn = Ti.UI.createButton({
    title: 'Open Modal Window'
});

btn.addEventListener('click', function() {
    var button = Ti.UI.createButton({
        title: 'Close'
    });
    var modalWindow = Ti.UI.createWindow({
        title: 'Modal Window',
        backgroundColor: 'red',
        rightNavButton: button
    });
    var oldNavWindow = Ti.UI.iOS.createNavigationWindow({
        window: modalWindow
    });

    Ti.API.warn('API (old) = ' + oldNavWindow.apiName);

    button.addEventListener('click', function() {
        oldNavWindow.close();
    });
    oldNavWindow.open({
        modal: true
    });
});

win.add(btn);
newNavWindow.open();
```

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR and FT passed.

**Comment by hansemannn** [comment]
Looking over it again, I did not do the docs changes so far. Will do over the next few days.

**Comment by vijaysingh-axway** [comment]
Right. Once doc changes done this will be ready for QE testing.

**Comment by sgtcoolguy** [comment]
@hansemannn I pushed a commit attempting to update the docs, you may want to review.

Additionally, it sounds like we need a PR/ticket for updating Alloy and Android?

I think Android is covered by https://jira.appcelerator.org/browse/TIMOB-24582 ?

**Comment by hansemannn** [comment]
Looks good! I will make an Alloy ticket next and link it with the others. Thank you!

**Comment by keerthi1032** [comment]
FR passed and waiting for merge . This has some merge conflicts. Can someone please look into it.

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
Node.js
  Node.js Version             = 8.9.1
  npm Version                 = 5.5.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = local 7.5.0.v20180928014950
Device			      = iPhone 6s -ios 12 
					iPhone 5s -ios 11 simulator

**Pull request merged**
