### PR TITLE
[TIMOB-18495] Pass guid to titanium_prep - update libraries

### PR DESCRIPTION
**Pull request by pec1985**
Epic: https://jira.appcelerator.org/browse/TIMOB-18494
Specific: https://jira.appcelerator.org/browse/TIMOB-18495

### CODE REVIEW

**Comment by pec1985** [comment]
To test on Mac, use this Ti SDK https://www.dropbox.com/s/n2obr15gf7gqpfl/mobilesdk-4.1.0-osx.zip?dl=0

**Comment by pec1985** [comment]
New build
https://www.dropbox.com/s/7eeqdmqf36ynype/Archive.zip?dl=0

**Comment by pec1985** [comment]
Updated SDK https://www.dropbox.com/s/ksvf3gdjzpgzyk2/Archive%202.zip?dl=0

**Comment by cb1kenobi** [comment]
Closing PR. There was an additional fix that I needed to make, so I created #6726.

**Pull request closed without merging**
