### PR TITLE
[TIMOB-17389] Android: Adding fastScroll to ListViews

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-17389

Will change vertical scrollbar to a draggable scrollbar. 

Sorry about the ListView.yml! I've applied clang to it and it removed a lot of blanks. My changes are in line 708

**example**

```javascript
var win = Ti.UI.createWindow({
	fullscreen: true
});
var counter = 0;

function genData() {
	var data = [];
	for (i = 1; i <= 50; i++) {
		data.push({
			properties: {
				title: 'ROW ' + (counter + i)
			}
		})
	}
	return data;
}
var section = Ti.UI.createListSection({
	headerTitle: "test"
});
section.setItems(genData());
var section2 = Ti.UI.createListSection({
	headerTitle: "test"
});
section2.setItems(genData());

var listView = Ti.UI.createListView({
	sections: [section,section2],
	height: Ti.UI.FILL,
	width: Ti.UI.FILL
});
win.add(listView);

var btn = Ti.UI.createButton({
	title: "toggle",
	bottom: 0
});
btn.addEventListener("click", function() {
	console.log("old", listView.fastScroll);
	listView.setFastScroll(!listView.fastScroll);
	console.log("new", listView.fastScroll);
})
win.add(btn);
win.open();
```

_Note:_
It won't add a letter bubble to the scrollview. As far as I read it would need to have the list items sorted. Might be something for another PR

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by lokeshchdhry** [comment]
FR Passed.

`fastScroll` works as expected & brings up a dragbar so that the user can scroll.

Studio Ver:     5.1.2.201810301430
SDK Ver:        8.0.0 local build
OS Ver:         10.14
Xcode Ver:      Xcode 10.1
Appc NPM:       4.2.13
Appc CLI:       7.0.8-master.6
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.4
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Pixel (Android 9)
Emulator:       ⇨ Android 4.1.2

**Comment by lokeshchdhry** [comment]
Can anyone please fix the lint issues. Thanks.

**Comment by lokeshchdhry** [comment]
@garymathews , Can you please fox the lint errors. Thanks !!

**Comment by m1ga** [comment]
@lokeshchdhry sorry, should be fixed now

**Pull request merged**
