### PR TITLE
[TIMOB-26625] Android: Can't open Titanium app through intent (7.5.0 regression)

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26625

**Description:**
Add a guard for SafeAreaMonitor in `onDestroy` method.

**Test case:**
There are two simple apps uploaded in the ticket.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by jquick-axway** [comment]
Right. I discovered this issue as well while refactoring our intent handling for 8.0.0. This is the right solution.

**Comment by lokeshchdhry** [comment]
@ypbnv , On Android 4.1. I am still seeing these exceptions:
```
E/TiExceptionHandler( 3571): (main) [244,244] Unable to destroy activity {com.app.timob26625one/com.app.timob26625one.Timob26625_1Activity}: java.lang.NullPointerException
E/TiExceptionHandler( 3571): 
E/TiExceptionHandler( 3571):     org.appcelerator.titanium.TiBaseActivity.onDestroy(TiBaseActivity.java:1668)
E/TiExceptionHandler( 3571):     org.appcelerator.titanium.TiLaunchActivity.onDestroy(TiLaunchActivity.java:472)
E/TiExceptionHandler( 3571):     org.appcelerator.titanium.TiRootActivity.onDestroy(TiRootActivity.java:217)
E/TiExceptionHandler( 3571):     android.app.Activity.performDestroy(Activity.java:5172)
E/TiExceptionHandler( 3571):     android.app.Instrumentation.callActivityOnDestroy(Instrumentation.java:1109)
E/TiExceptionHandler( 3571):     android.app.ActivityThread.performDestroyActivity(ActivityThread.java:3260)
E/TiExceptionHandler( 3571):     android.app.ActivityThread.handleDestroyActivity(ActivityThread.java:3291)
E/TiExceptionHandler( 3571):     android.app.ActivityThread.access$1200(ActivityThread.java:130)
E/TiExceptionHandler( 3571):     android.app.ActivityThread$H.handleMessage(ActivityThread.java:1248)
E/TiExceptionHandler( 3571):     android.os.Handler.dispatchMessage(Handler.java:99)
E/TiExceptionHandler( 3571):     android.os.Looper.loop(Looper.java:137)
E/TiExceptionHandler( 3571):     android.app.ActivityThread.main(ActivityThread.java:4745)
E/TiExceptionHandler( 3571):     java.lang.reflect.Method.invokeNative(Native Method)
E/TiExceptionHandler( 3571):     java.lang.reflect.Method.invoke(Method.java:511)
E/TiExceptionHandler( 3571):     com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
E/TiExceptionHandler( 3571):     com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
E/TiExceptionHandler( 3571):     dalvik.system.NativeStart.main(Native Method)
```
This is causing the app opened from intent to not respond.

**Comment by ypbnv** [comment]
@lokeshchdhry Can you share any specific details about your target application? I can't reproduce the issues on Android 4.1 emulator (I don't have a device with this API level at hand) with the applications in the ticket.

**Comment by jquick-axway** [comment]
@lokeshchdhry, Titanium 8.0.0 does not support Android 4.1 anymore. The min Android OS version supported has been changed to 4.4. In fact, Google's "adb install" shouldn't allow you to install it unless the `minSdkVersion` in the "AndroidManifest.xml" file is set incorrectly.

Now the Titanium 7.5.1 back-port is different. Lokesh, is this where you're seeing this error?

**Comment by garymathews** [comment]
@lokeshchdhry I think you are running into an issue unrelated to this PR.

```
java.util.Objects
```

Was not included until Android API 19, which is why it cannot find it.

**Comment by lokeshchdhry** [comment]
@garymathews , @jquick-axway , @ypbnv , It seems my local build had some issues. Artifact works fine. Sorry about the confusion.

**Comment by lokeshchdhry** [comment]
FR Passed.

Titanium app can be opened successfully through an intent.

Studio Ver:     5.1.2.201810301430
SDK Ver:        8.0.0local build
OS Ver:         10.14
Xcode Ver:      Xcode 10.1
Appc NPM:       4.2.13
Appc CLI:       7.0.8
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.4
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Pixel (Android 9)
Emulator:       ⇨ Android 4.1.2

**Pull request merged**
