### PR TITLE
[TIMOB-24679] Android: Remove invalid constant definitions

### PR DESCRIPTION
**Pull request by garymathews**
- Remove invalid proxy constant definitions

###### TEST CASE
```JS
var audioPlayer = Ti.Media.createAudioPlayer();

// this will now be `undefined`
Ti.API.info('audioPlayer.STATE_BUFFERING: ' + audioPlayer.STATE_BUFFERING);

// this is the documented way of obtaining the constant
Ti.API.info('Ti.Media.AudioPlayer.STATE_BUFFERING: ' + Ti.Media.AudioPlayer.STATE_BUFFERING);
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24679)

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
LGTM!

**Review by mukherjee2 — APPROVED** [review]
FR Passed with this environment:
Node Version: 6.11.5
NPM Version: 3.10.10
Mac OS: 10.13
Appc CLI: 7.0.0-master.6
Appc CLI NPM: 4.2.11-2
Titanium SDK version: 7.0.0 locally built on PR-9565
Appcelerator Studio vers 4.10.0
Android 7.1.2

**Comment by mukherjee2** [comment]
@garymathews I would like to merge this PR, but there were unit test failures reported, which blocked the merge. Can you please take a look?

**Comment by mukherjee2** [comment]
@eric34 Can you please merge this one?

**Pull request merged**
