### PR TITLE
[7_0_X][TIMOB-25656] Android: getOrCreateView() should always return a View

### PR DESCRIPTION
**Pull request by garymathews**
- Cherry-pick of https://github.com/appcelerator/titanium_mobile/pull/9721

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25656)

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
@garymathews , On Android 8.0 emulator I am getting this runtime error. Strangely, with master I don't see any issues.

```
[ERROR] :  TiExceptionHandler: (main) [13229,13229] ----- Titanium Javascript Runtime Error -----
[ERROR] :  TiExceptionHandler: (main) [1,13230] - In /app.js:49,14
[ERROR] :  TiExceptionHandler: (main) [0,13230] - Message: Uncaught Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
[ERROR] :  TiExceptionHandler: (main) [0,13230] - Source:   drawerView.setRightView(realRight);
[ERROR] :  V8Exception: Exception occurred at /app.js:49: Uncaught Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
[ERROR] :  V8Exception: Attempt to invoke virtual method 'android.content.res.Resources android.content.Context.getResources()' on a null object reference
```

**Comment by garymathews** [comment]
@lokeshchdhry That looks like a a separate issue, there will be a fix merged into `master` that isn't in `7_0_X`

**Comment by lokeshchdhry** [comment]
FR Passed.

`TiViewProxy.getOrCreateView` does not return null & no runtime error is thrown on android 6.0.1 & 7.0.0+.

Studio Ver: 5.0.0.201712081732
SDK Ver: 7.0.2 local build
OS Ver: 10.13.2
Xcode Ver: Xcode 9.2
Appc NPM: 4.2.11
Appc CLI: 7.0.1
Daemon Ver: 1.0.1
Ti CLI Ver: 5.0.14
Alloy Ver: 1.10.10
Node Ver: 8.9.1
NPM Ver: 5.5.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1
⇨ google Pixel --- Android 7.1.1
Emulator: Android 8.0

**Pull request merged**
