### PR TITLE
[TIDOC-2398] generate google closure externs

### PR DESCRIPTION
**Pull request by drauggres**
**JIRA:** https://jira.appcelerator.org/browse/TIDOC-2398

Generated file could be used as replacement for files from https://github.com/navinpeiris/jsca2js

### CODE REVIEW

**Comment by hansemannn** [comment]
@jawa9000 What to do here?

**Comment by drauggres** [comment]
I use generated file only for code completion in webstorm, not as actual closure externs.
Now when TypeScript definitions file generated this ticket is probably obsolete.

**Comment by janvennemann** [comment]
@drauggres The TypeScript definition are available by now. Could you explain why you think that makes this ticket is obsolete?

**Comment by hansemannn** [comment]
Thanks @drauggres, closing this ticket for now! If it becomes necessary again, we can reopen this PR without issues :-).

**Pull request closed without merging**
