### PR TITLE
[TIMOB-26382] Android: Modified "appc run" to dismiss screen-lock before running built app

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26382

**Note 1:**
We partly needs this for our mocha test suite. We will have timeout failures for "postlayout" based tests if the Android emulator's screen is locked. An Android emulator's screen locking timer cannot be disabled. We can only increase its idle timer to 30 minutes (from default of 1 minute).

**Note 2:**
This change cannot dismiss the screen-lock if it requires authorization such as a passkey, swipe gesture, touch id, etc.

**Test:**
1. Turn the Android device's screen off. (But don't power off the device.)
2. Build and run an app to the same device.
3. Verify that screen is automatically turned on and the app is displayed onscreen.

### CODE REVIEW

**Comment by jquick-axway** [comment]
The unit test timeout that happened on this PR is interesting. The APS analytics library was in the middle of a send while that unit test was happening. That can't be a coincidence.
https://jenkins.appcelerator.org/blue/rest/organizations/jenkins/pipelines/titanium-sdk/pipelines/titanium_mobile/branches/PR-10318/runs/1/log/?start=0

The APS http send request is definitely async, but the APS library uses a lot of synchronization blocks that we may want to double-check.

**Comment by lokeshchdhry** [comment]
FR Passed.

Device screen turns on before the app launch.

Studio Ver:     5.1.1.201809051655
SDK Ver:        7.5.0. local build
OS Ver:         10.13.5
Xcode Ver:      Xcode 9.4.1
Appc NPM:       4.2.13
Appc CLI:       7.0.6
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.2
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Pixel (Android 9)

**Comment by lokeshchdhry** [comment]
Waiting for CR to pass.

**Review by sgtcoolguy — APPROVED** [review]
code looks fine to me 👍

**Pull request merged**
