### PR TITLE
[TIMOB-25684] iOS: Adds home-screen like parallax effect to views

### PR DESCRIPTION
**Pull request by chmiiller**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25684

Adds homescreen like parallax effect to views based on Marcel Pociot's module https://github.com/mpociot/TiMotionEffects

### CODE REVIEW

**Comment by hansemannn** [comment]
The unit-tests are missing which will prevent our Danger.js checks from passing. I prepared them for you, please create a file `ti.ui.view.addontest.is` in tests/:
```js
/*
 * Appcelerator Titanium Mobile
 * Copyright (c) 2015-Present by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
/* eslint-env mocha */
/* global Ti */
/* eslint no-unused-expressions: "off" */
'use strict';
var should = require('./utilities/assertions');

describe('Titanium.UI.View', function () {

	it.ios('.horizontalMotionEffect, .verticalMotionEffect', function (finish) {
		var win = Ti.UI.createWindow({
		  backgroundColor: 'blue'
		});

		var view = Ti.UI.createView({
			horizontalMotionEffect: {
				min: -50,
				max: 50
			},
			verticalMotionEffect: {
				min: -50,
				max: 50
			}
		});

		// horizontalMotionEffect
		should(view.horizontalMotionEffect).be.an.Object;
		should(view.horizontalMotionEffect.min).be.a.Number;
		should(view.horizontalMotionEffect.max).be.a.Number;

		// verticalMotionEffect
		should(view.verticalMotionEffect).be.an.Object;
		should(view.verticalMotionEffect.min).be.a.Number;
		should(view.verticalMotionEffect.max).be.a.Number;

		win.add(view);
		win.open();
	});
});
```

**Comment by chmiiller** [comment]
Thanks @hansemannn ! I've just updated tests and added the properties into View's documentation. Is it missing something else?

**Comment by chmiiller** [comment]
`Test suite crashed on iOS simulator. Please see the crash log for more details.` I can't access the crash logs =/

**Review by hansemannn — APPROVED** [review]
CR + FT **approved**. Jenkins currently fails because of unrelated unit-tests that are not subject of this PR.

**Comment by chmiiller** [comment]
Thanks for all the work @hansemannn ! Looking forward to see it on 7.1.0 release 😬

**Pull request merged**
