### PR TITLE
[TIMOB-25046] iOS: Fix peek-and-pop and other analyser warnings

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25046

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR and FT passed.

**Comment by mukherjee2** [comment]
@hansemannn There are some conflicts reported below, can you please resolve?

**Comment by hansemannn** [comment]
@mukherjee2 Done!

**Review by mukherjee2 — APPROVED** [review]
Environment:
Node Version: 6.10.3
NPM Version: 3.10.10
Mac OS: 10.12.4
Appc CLI: 6.2.3
Appc CLI NPM: 4.2.9
Titanium SDK version: 6.2.0.v20170815112142
Appcelerator Studio, build: 4.9.1.201707200100
Xcode 8.3.2

Passed FR. I first checked with 6.0.3.GA and verified that the 3D touch worked as expected. Then I reproduced the bug in 6.1.2.GA. Finally, I checked with the SDK version built on this PR, and validated that the fix works.

**Pull request merged**
