### PR TITLE
[TIMOB-16985] Android: Removed Ti.UI.Window.url

### PR DESCRIPTION
**Pull request by ashcoding**
https://jira.appcelerator.org/browse/TIMOB-16985

### CODE REVIEW

**Comment by ashcoding** [comment]
I believe this is the only part for the ```url``` property to be removed.

**Comment by hansemannn** [comment]
Will wait for the log-warning to be added as discussed.

**Comment by ashcoding** [comment]
I do not see the usage of ```TiC.PROPERTY_URL``` which is the string ```"url"``` for the WindowProxy in Android. For it to have a log-warning, the property still needs to be in. Since it's not in use, I think removing it is fine.

With the documentation for 6.0.0 and all the information informing people about breaking changes, I think this should suffice.

**Comment by hansemannn** [comment]
Alrighty! Approved!

**Pull request merged**
