### PR TITLE
[TIMOB-23649] Bug fix for generated manifest.json

### PR DESCRIPTION
**Pull request by ashcoding**
https://jira.appcelerator.org/browse/TIMOB-23649

Bug fix for the generated `manifest.json`.

### CODE REVIEW

**Comment by ashcoding** [comment]
To test, run scons to build, package and install.
Check the ```manifest.json`` file in the installed sdk.
If it shows:
```
{
  "name": "6.0.0",
  "version": "6.0.0",
  "moduleAPIVersion": {
    "iphone": "2",
    "android": "3",
    "mobileweb": "2",
    "windows": "2"
  },
  "timestamp": "8/4/2016 05:25",
  "githash": "c5cb644",
  "platforms": [
    "android",
    "iphone",
    "mobileweb"
  ]
}
```
This is correct.

The original incorrect ```manifest.json``` was: 
```
{
  "name": "6.0.0",
  "version": "6.0.0",
  "moduleAPIVersion": "[object Object]",
  "timestamp": "8/4/2016 05:17",
  "githash": "6f132a1",
  "platforms": [
    "android",
    "iphone",
    "mobileweb"
  ]
}
```
This prevented Studio from adding Api Version 3 modules for android.

**Comment by ashcoding** [comment]
And added test you can do is, in Studio, use the SDK and try to add a API Version 3 module https://github.com/appcelerator-modules/ti.imagefactory/releases/tag/android-3.0.0

If it appears and selectable, it's working.

**Comment by ashcoding** [comment]
For my own ref: http://www.ecma-international.org/ecma-262/5.1/#sec-15.2.4.2
Reason behind why ```toString()``` is wrong.

**Comment by sgtcoolguy** [comment]
Checked the generated SDK zip's manifest.json and it looks good. Merging.

**Pull request merged**
