### PR TITLE
feat(ios): read status bar height programmatically

### PR DESCRIPTION
**Pull request by hansemannn**
Requested via Slack to have a common solution that's more flexible for newer devices.

### Test Case

```js

const win = Ti.UI.createWindow({
    backgroundColor: '#fff'
});

const view = Ti.UI.createView({ top: 0, height: 0, backgroundColor: 'red' });

const btn = Ti.UI.createButton({
    title: 'Get status bar height'
});

btn.addEventListener('click', () => {
    view.animate({ height: Ti.UI.statusBarHeight });
    console.warn('statusBarHeight = ', Ti.UI.statusBarHeight);
});

win.add([view, btn]);
win.open();
```

### Example

https://user-images.githubusercontent.com/10667698/215262914-e1abb396-cab8-4136-9428-c89056795cc0.mp4

### CODE REVIEW

**Comment by m1ga** [comment]
for Android too? `displayCutout`. I thought I did a PR with that already 🤔  Was doing some tests with it while I added the Rive animation to the statusbar. Will look if I still find it

**Comment by hansemannn** [comment]
I'd add Android as well, but feel free to do so as well.

**Comment by m1ga** [comment]
found my code already. 
```java
@Kroll.method
	public void getCutout()
	{
		if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.P) {
			Window w = TiApplication.getAppCurrentActivity().getWindow();
			if (w == null) return;
			View dv = w.getDecorView();
			if (dv == null) return;
			DisplayCutout dpc = dv.getRootWindowInsets().getDisplayCutout();
			if (dpc == null) return;
			List<Rect> rects = dpc.getBoundingRects();

			int cutouts = rects.size();
			int[] result = new int[cutouts * 4];
			int index = 0;

			for (Rect rect : rects) {
				KrollDict kd = new KrollDict();
				kd.put("left", rect.left);
				kd.put("top", rect.top);
				kd.put("width", rect.width());
				kd.put("height", rect.height());
				fireEvent("cutout", kd);
			}
		}
	}
```

it returned the whole rectangle shape (e.g. a box around the camera cutout).  Will change it to get the height (rect.top + rec.height).

**Comment by m1ga** [comment]
need to clean it up but its running :+1: 
Screenshot_20230128-130704

**Comment by m1ga** [comment]
added it here: https://github.com/tidev/titanium_mobile/pull/13733
I've kept my `cuteoutSize` method so you can get the shape on Android too.

You could add `android` to the apidocs here

**Pull request merged**
