### PR TITLE
fix(android): amend ListView behaviour when search view is defined

### PR DESCRIPTION
**Pull request by garymathews**
- Amend how `ListView` and `TableView` are constructed when a `searchView` is added
  - Prevent rendering issues when a `borderRadius` is applied
- Fix `TableView` row `index` when a search query is applied

##### TEST CASE 1
```JS
const win = Ti.UI.createWindow({
    backgroundColor: 'white'
});
const search = Ti.UI.createSearchBar({
    //borderWidth: 5, // QE: Validate borders are visible.
    //borderColor: 'orange'
});
const sections = [];
for (let i = 0; i < 3; i++) {
    const items = [];
    for (let x = 0; x < 5; x++) {
        const text = `Item #${x}`;
        items.push({
            properties: {
                searchableText: text
            },
            label: {
                text
            }
        });
    }
    sections.push(Ti.UI.createListSection({
        headerTitle: `Section #${i}`,
        items
    }));
}
const listView = Ti.UI.createListView({
    templates: {
        template: {
            properties: {
                backgroundColor: 'transparent'
            },
            childTemplates: [{
                type: 'Ti.UI.Label',
                bindId: 'label',
                properties: {
                    left: 10,
                    color: 'black'
                }
            }]
        }
    },
    backgroundColor: 'blue',
    defaultItemTemplate: 'template',
    borderRadius: 8,
    searchView: search,
    sections
});
const btn = Ti.UI.createButton({
    bottom: 10,
    title: 'Toggle Search'
});
btn.addEventListener('click', e => {
    listView.searchView = listView.searchView ? null : search;
});
win.add([listView, btn]);
win.open();
```
##### TEST CASE 2
```JS
const win = Titanium.UI.createWindow({
	backgroundColor: 'gray'
});
const search = Ti.UI.createSearchBar({
	hintText: 'Search...',
	showCancel: false
});
const btn = Ti.UI.createButton({ bottom: 10, title: 'Toggle Search' });

btn.addEventListener('click', e => {
	tableView.search = tableView.search ? null : search;
});

function createSection(rows, suffix) {
	const section = Ti.UI.createTableViewSection({
		headerTitle: `Section ${suffix}`
	});

	for (let i = 1; i <= rows; i++) {
		section.add(Ti.UI.createTableViewRow({
			title: `Row #${i}`
		}));
	}

	return section;
}

const tableView = Ti.UI.createTableView({
	data: [
		createSection(10, 'A'),
		createSection(10, 'B'),
		createSection(10, 'C')
	],
	search
});

tableView.addEventListener('noresults', e => {
	alert('NO RESULTS!');
});

win.add([ tableView, btn ]);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28406)

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
@garymathews , I am not able to search in `TestCase 1` for Listview.

**Comment by garymathews** [comment]
@lokeshchdhry The test case didn't set the `searchableText` property on the ListItems. I've updated the test case so it's searchable.

**Comment by lokeshchdhry** [comment]
FR Passed.

**Pull request merged**
