### PR TITLE
[TIMOB-24448] iOS: Decouple Ti.Media music-API macros

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24448

### CODE REVIEW

**Review by vijaysingh-axway — CHANGES_REQUESTED** [review]
I think following mentioned macros are of now use. Please remove.
1. Remove  macros from line  of MediaModule.h- 
#if defined(USE_TI_MEDIASYSTEMMUSICPLAYER) || defined (USE_TI_MEDIAAPPMUSICPLAYER)
#import "TiMediaMusicPlayer.h"
#endif

2.Remove macro USE_TI_MEDIAMUSICPLAYER, line no 212, 272  
3.Remove USE_TI_MEDIASYSTEMMUSICPLAYER and USE_TI_MEDIAAPPMUSICPLAYER from 
#if defined(USE_TI_MEDIASYSTEMMUSICPLAYER) || defined (USE_TI_MEDIAAPPMUSICPLAYER)
    RELEASE_TO_NIL(systemMusicPlayer);
    RELEASE_TO_NIL(appMusicPlayer);
#endif

**Comment by hansemannn** [comment]
Updated, thx!

**Review by vijaysingh-axway — COMMENTED** [review]
FT and CR passed.

**Review by ewieberappc — APPROVED** [review]
FR Passed, using:
MacOS 10.12 (16A323)
Studio 4.8.1.201612050850
Ti SDK 6.1.0
Appc NPM 4.2.8
Appc CLI 6.1.0
Alloy 1.9.5
Xcode 8.2.1 (8C1002)

Tested using the provided code in TIMOB-24448 and TIMOB-24449 as well as running the QE Media Test Suite and submitting an app to the store that uses many ti.media methods/properties. All projects compiled and no errors were encountered

**Pull request merged**
