### PR TITLE
[TIMOB-24648] iOS: Fix network-indicator for synced http-requestes

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24648

### CODE REVIEW

**Review by vijaysingh-axway — COMMENTED** [review]
Still network activity indicator is not getting visible.

**Comment by hansemannn** [comment]
@vijaysingh-axway The issue was fixed for kroll-thread. For main-thread, it's something else, see https://jira.appcelerator.org/browse/TIMOB-24649.

**Review by vijaysingh-axway — APPROVED** [review]
FT and CR passed.

**Review by htbryant94 — APPROVED** [review]
Approved! The Network Activity Indicator is now correctly visible for the initial and every subsequent synchronous request when on the Kroll Thread.

Tested On:
iPhone 7 10.2.1 Device & Simulator

**Pull request merged**
