### PR TITLE
fix(android): Improved merge of "tiapp.xml" android manifest settings

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
- https://jira.appcelerator.org/browse/TIMOB-26778
- https://jira.appcelerator.org/browse/TIMOB-26777
- https://jira.appcelerator.org/browse/TIMOB-27067
- https://jira.appcelerator.org/browse/TIMOB-27084

**Summary:**
- [TIMOB-26778](https://jira.appcelerator.org/browse/TIMOB-26778) Fixed bug where overriding an `<activity/>` in "tiapp.xml" caused most "configChanges" values to be lost.
  * Would cause activity window's UI to disappear if a system config change occurred dynamically.
- [TIMOB-26777](https://jira.appcelerator.org/browse/TIMOB-26777) Fixed bug where connecting/disconnecting a physical keyboard to/from device caused UI to disappear.
- [TIMOB-27067](https://jira.appcelerator.org/browse/TIMOB-27067) Fixed bug where UI sometimes disappears on Android 9.0 or higher when battery saver turns on/off.
- [TIMOB-27084](https://jira.appcelerator.org/browse/TIMOB-27084) Fixed issue where "tiapp.xml" was unable to override "AndroidManifest.xml" settings defined in AAR and "timodule.xml".
- Added missing `<activity/>` "configChanges" values to Titanium's template:
  * `keyboard`, `layoutDirection`, `mcc`, `mnc`, `navigation`, `touchscreen`, `uiMode`
- Added new EJS template variable `<%- allActivityConfigChanges %>`.
  * To be used by Titanium's main "AndroidManifest.xml" and "timodule.xml" files.
- Removed last remnants of deprecate `Ti.Map` from build script.
- Removed `TiVideoActivity` and `TiCameraActivity` injection code from build script.
  * There is no downside to always adding these activities to "AndroidManifest.xml". This reduces complexity.
- Removed launchMode "singleTask" from "TiMapActivity" and "TiVideoActivity".
  * Not applicable to child activities. Only applies to root activity.

---
**Test 1:**
1. Follow the test procedure attached to [TIMOB-26778](https://jira.appcelerator.org/browse/TIMOB-26778).
2. Verify that Titanium does not restart when rotating the splash screen window.
3. Verify that the generated "AndroidManifest.xml" file under the "build/android" directory has all of the following "configChanges" values.
```xml
<activity android:configChanges="fontScale|keyboard|keyboardHidden|layoutDirection|locale|mcc|mnc|navigation|orientation|screenLayout|screenSize|smallestScreenSize|touchscreen|uiMode|density"/>
```

---
**Test 2:**
1. Follow the test procedure attached to [TIMOB-26777](https://jira.appcelerator.org/browse/TIMOB-26777).
2. Verify that connecting/disconnecting a bluetooth keyboard does **NOT** cause the UI to disappear.

---
**Test 3:**
1. Follow the test procedure attached to [TIMOB-27067](https://jira.appcelerator.org/browse/TIMOB-27067).
2. Verify that the window UI does not disappear when changing the battery "Charge connection" setting in the Android emulator.

---
**Test 4:**
1. Follow the test procedure attached to [TIMOB-27084](https://jira.appcelerator.org/browse/TIMOB-27084).
2. Verify that the "intent-filter" defined in your "tiapp.xml" appears in the "AndroidManifest.xml" file under the project's `./build/android` directory.

### CODE REVIEW

**Comment by jquick-axway** [comment]
This PR isn't ready yet.

It's adding all "configChanges" values to every module's and AAR's activities as well, which is wrong. It needs to be limited to Titanium's own core activities which do not have an XML layout to inflate from when the configuration changes.

**Comment by jquick-axway** [comment]
Updated PR.

Now correctly injects "configChanges" values to only the activities that need it. Now inserted via new `<%- allActivityConfigChanges %>` EJS template variable.

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
Changed to "work-in-progress". I want to add a fix for the following ticket as well...
https://jira.appcelerator.org/browse/TIMOB-27084

**Comment by jquick-axway** [comment]
Updated PR to resolve issue [TIMOB-27084](https://jira.appcelerator.org/browse/TIMOB-27084)

**Comment by keerthi1032** [comment]
FR Passed. Tested with  the test cases mentioned in TIMOB-26778,TIMOB-26777, TIMOB-27067 and TIMOB-27067
**TIMOB-26778** -ConfigChanges values updated correctly and all settings were shown correctly manifest file
**TIMOB-26777**- No UI issue when bluetooth keyboard connected/disconnected 
**TIMOB-27067** -No UI issue when tested with battery saver turning off/on 
**TIMOB-27067**- NO issues and setting updated correctly in Android manifest xml file when Tiapp.xml file changed.

**Test Environment:**
Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Architecture                = 64bit
Node.js
  Node.js Version             = 8.9.1
  npm Version                 = 5.5.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = LOCAL SDK 8.1.0.v20190517164852
Device = Pixel android 9,samsung s5 android 6
Emulator= Pixel 2XL android 9,Pixel 3xl

**Comment by keerthi1032** [comment]
Jenkin is failing. waiting for resolving jenkin's failure to merge

**Pull request merged**
