### PR TITLE
[TIMOB-10754] CLI: "build" command for Android modules

### PR DESCRIPTION
**Pull request by feons**
https://jira.appcelerator.org/browse/TIMOB-10754

### CODE REVIEW

**Comment by ingo** [comment]
@pinnamur @ashcoding @kolipakakondal can someone please review this?

**Comment by ingo** [comment]
@ashcoding Can you please test this out? Thanks!

**Comment by ashcoding** [comment]
Functionally tested and working. Code reviewed. **Accepted**

**Comment by pinnamur** [comment]
Yay ! :+1:

**Pull request merged**
