### PR TITLE
[TIMOB-23767] Fix tint-color to gray, update label

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23767

### CODE REVIEW

**Comment by ashcoding** [comment]
**Approved**

**Comment by ashcoding** [comment]
The PR for this fixed is fine.
Travis Failed due to another separate issue.

```
Zipping Mobile SDK...
Cleaning previous zipfile and tmp dir...
Writing manifest.json
Zipping packaged modules...
Unzipping /Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/com.appcelerator.urlSession-iphone-2.0.0.zip to /Users/travis/build/appcelerator/titanium_mobile/dist/ziptmp
Unzipping /Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/facebook-android-6.0.1.zip to /Users/travis/build/appcelerator/titanium_mobile/dist/ziptmp
Unzipping /Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/facebook-iphone-5.2.3.zip to /Users/travis/build/appcelerator/titanium_mobile/dist/ziptmp
{ Error: Command failed: unzip -o "/Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/facebook-iphone-5.2.3.zip" -d "/Users/travis/build/appcelerator/titanium_mobile/dist/ziptmp"
  End-of-central-directory signature not found.  Either this file is not
  a zipfile, or it constitutes one disk of a multi-part archive.  In the
  latter case the central directory and zipfile comment will be found on
  the last disk(s) of this archive.
unzip:  cannot find zipfile directory in one of /Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/facebook-iphone-5.2.3.zip or
        /Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/facebook-iphone-5.2.3.zip.zip, and cannot find /Users/travis/build/appcelerator/titanium_mobile/support/module/packaged/facebook-iphone-5.2.3.zip.ZIP, period.
    at ChildProcess.exithandler (child_process.js:202:12)
    at emitTwo (events.js:106:13)
    at ChildProcess.emit (events.js:191:7)
    at maybeClose (internal/child_process.js:850:16)
    at Socket.<anonymous> (internal/child_process.js:323:11)
    at emitOne (events.js:96:13)
    at Socket.emit (events.js:188:7)
    at Pipe._handle.close [as _onclose] (net.js:485:12)
  killed: false,
  code: 9,
  signal: null,
```
Will merge this but this other issue needs to be looked into.
CC: @cheekiatng , @hansemannn

**Comment by ashcoding** [comment]
This error seems to be only in master branch after it has been bumped to 6.1.0.

**Comment by ashcoding** [comment]
@hansemannn did this https://github.com/appcelerator/titanium_mobile/commit/92f288da36642b8122cc9110c04200672630e9a8 cause the issue?

**Comment by hansemannn** [comment]
Fix is uploading, the old binary I uploaded today morning seems to be corrupt during push (during Standup). Will merge and fix in the next 10m.

**Comment by hansemannn** [comment]
Merged.

**Pull request merged**
