### PR TITLE
[6_1_x][TIMOB-24799] Fix issue where theme was being set as its parent

### PR DESCRIPTION
**Pull request by ewanharris**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24799

Backport of #9134

Bad things happen if a theme is a parent of itself, so we should prevent that

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

Setting theme as <application android:theme="@style/Theme.Titanium"/> in the tiapp.xml does not inherit itself & no error seen.

Ran the attached app in the ticket with the fix & no error/crash was seen.
Studio Ver: 4.9.0.201705302345
SDK Ver: 6.1.1 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.9
Appc CLI: 6.2.2
Ti CLI Ver: 5.0.14
Alloy Ver: 1.9.11
Node Ver: 6.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1
⇨ google Pixel --- Android 7.1.1
Emulator: Android 4.4.2

**Comment by lokeshchdhry** [comment]
OOPS, merged accidentally before the CR. @garymathews or @cb1kenobi, can you please do a quick CR. Thanks.

**Comment by hansemannn** [comment]
@lokeshchdhry master passed CR, so I think you are fine 😇.

**Comment by lokeshchdhry** [comment]
@hansemannn , cool.

**Pull request merged**
