### PR TITLE
[TIMOB-24465] Android: Replacing RGB_565 with ARGB_8888

### PR DESCRIPTION
**Pull request by kopiro**
To avoid funny gradients

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24465

### CODE REVIEW

**Comment by hansemannn** [comment]
How about performance: http://stackoverflow.com/a/15178050/5537752 ?

**Comment by garymathews** [comment]
Yep, `ARGB_8888` should be used. It is the default on Android since 4.0 and the recommended configuration for Bitmaps. Decreasing colour banding with increased bits-per-pixel.

**Comment by hansemannn** [comment]
Thanks Gary! @kopiro can you update those files in this PR as well? Should be added to 6.1.0 as well.

**Comment by jquick-axway** [comment]
I agree with Gary. We should always be loading images with 32-bit color. Especially since the 565 color format doesn't support alpha transparency. The days of the low-end 24 MB heap limited Android device is pretty much over.

The 3 other files source files Gary mentioned need to be changed as well.

Note:
This change will cause a merge conflict (but easy to resolve) with another change of mine where I too have updated TiDrawableReference to decode with 32-bit color.
https://jira.appcelerator.org/browse/TIMOB-24528

**Comment by garymathews** [comment]
Close in favour of https://github.com/appcelerator/titanium_mobile/pull/8978

**Pull request closed without merging**
