### PR TITLE
fix(ios): guard source property and removed NSNull if it is nil

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-27354

### CODE REVIEW

**Review by sgtcoolguy — APPROVED** [review]
LGTM

**Comment by Dankyi** [comment]
FR Failed - I had it run for the first time and it worked as it should but when I tried  for a number of times after the first it failed for all the attempts. I followed the steps in the video from the attachment (https://jira.appcelerator.org/browse/TIMOB-27354)

**Test Environment** 
```
Mac OS X 10.14.5
Node.js Version 10.16.3
Xcode 10.3 (build 10G8) - Xcode default
npm Version 6.9.0
Iphone 7 iOS Version 13.0
```

**Comment by lokeshchdhry** [comment]
FR Passed.

Studio Ver:       5.1.4.201909061933
SDK Ver:          8.2.1 local build
OS Ver:           10.14.5
Xcode Ver:        Xcode 11.0
Appc NPM:         4.2.15
Appc CLI:         7.1.1
Daemon Ver:       1.1.3
Ti CLI Ver:       5.2.1
Alloy Ver:        1.14.1
Node Ver:         10.16.1
NPM Ver:          6.9.0
Java Ver:         10.0.2
IOS Simulator: Iphone XR IOS 13, Iphone XR IOS 12.2

**Comment by lokeshchdhry** [comment]
waiting to merge so that issue seen by @Dankyi can be verified.

**Comment by Dankyi** [comment]
FR Passed - "First/Second app on resume from url: undefined" prompt didn't showed up in all the tests I run.

**Test Environment:**

```
Mac OS X 10.14.5
Node.js Version 10.16.3
Xcode 10.3 (build 10G8) - Xcode default
npm Version 6.9.0
Iphone 7 iOS Version 13.0
```

**Pull request merged**
