### PR TITLE
[7_0_X][TIMOB-25597] Android: Fixed bug where multidexed apps crash on startup on Android 4.x

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25597

**Cherry Pick of:** #9694

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by lokeshchdhry** [comment]
@jquick-axway , I get this error on all android versions wj=hen building with the fix.

```
[ERROR] Application Installer abnormal process termination. Process exit value was 1
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Error: Can't read [/Users/lchoudhary/Desktop/android-sdk-macosx/build-tools/27.0.3/lib/shrinkedAndroid.jar] (Can't process class [android/accessibilityservice/AccessibilityService.class] (Unsupported class version number [52.0] (maximum 51.0, Java 1.7)))
```

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.0.2 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.11
Appc CLI:       7.0.1
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
SDK Tools:      26.1.1
Platform Tools: 27.0.1
Build Tools:    27.0.3

**Comment by jquick-axway** [comment]
Updated PR.

**Comment by lokeshchdhry** [comment]
@jquick-axway , Can you please fix the lint issues. Thanks.

**Comment by lokeshchdhry** [comment]
FR Passed.

No crash seen after launch on android 4.X.

Studio Ver: 5.0.0.201712081732
SDK Ver: 7.0.2 local build
OS Ver: 10.13.2
Xcode Ver: Xcode 9.2
Appc NPM: 4.2.11
Appc CLI: 7.0.1
Daemon Ver: 1.0.1
Ti CLI Ver: 5.0.14
Alloy Ver: 1.10.10
Node Ver: 8.9.1
NPM Ver: 5.5.1
Java Ver: 1.8.0_101
Emulator: Android 4.4.2, Android 4.4.4

**Comment by ssjsamir** [comment]
@jquick-axway Using the build from Mac-OS and then installing it to Windows (Like suggested earlier), the application crashed on a Android 4.4.4 Emulator (Application was able to run on the Android 6.0.0 emulator). Granted this may not be the best way to build on windows and the build it self said 7.1.0 although it was from this 7_0_X branch.

**Comment by jquick-axway** [comment]
@ssjsamir, after doing the build on Windows, go to your project's ".\build\android" directory. Do you see files the files "proguard.gradle", "gradlew", and "gradlew.bat"? If not, then it sounds like you're not building with my PR's changes.

**Comment by ssjsamir** [comment]
@jquick-axway Ah, I re-checked my build and noticed my Github desktop was interfering with my QE FR build tool and the wrong branch was getting checked out and then built. Once I addressed this issue I created the correct build from this PR and I was able to run the application on a Android 4.4.4 emulator on Windows (Sorry for any confusion). I Was also able to see files "proguard.gradle", "gradlew", and "gradlew.bat" in the ".\build\android" directory of my application.

**Pull request merged**
