### PR TITLE
[7_1_X][TIMOB-24408] Android: Add support for RequestHeaders for ImageViews

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24408

**Description:**
Backport of: https://github.com/appcelerator/titanium_mobile/pull/9660

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
@ypbnv , Can you please resolve the conflict.

**Comment by lokeshchdhry** [comment]
@ypbnv , I am seeing issues with emulator API 16-21. I am running your test code.

When I click `No Headers` I see:
```
[ERROR] :  TiDownloadManager: (pool-5-thread-1) [13373,13373] Exception downloading http://hans-knoechel.de/test/test.png
[ERROR] :  TiDownloadManager: java.io.FileNotFoundException: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDownloadManager: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
[ERROR] :  TiDownloadManager: 	at org.appcelerator.titanium.util.TiDownloadManager$DownloadJob.run(TiDownloadManager.java:173)
[ERROR] :  TiDownloadManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[ERROR] :  TiDownloadManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[ERROR] :  TiDownloadManager: 	at java.lang.Thread.run(Thread.java:818)
```

When I click `Headers` I see:
```
[ERROR] :  TiDrawableReference: (pool-6-thread-1) [618,18912] Problem opening stream with url http://hans-knoechel.de/test/test.png: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDrawableReference: java.io.FileNotFoundException: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDrawableReference: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiFileHelper.handleNetworkURL(TiFileHelper.java:252)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiFileHelper.openInputStream(TiFileHelper.java:188)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getInputStream(TiDrawableReference.java:895)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:372)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:329)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiLoadImageManager$LoadImageJob.run(TiLoadImageManager.java:132)
[ERROR] :  TiDrawableReference: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[ERROR] :  TiDrawableReference: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[ERROR] :  TiDrawableReference: 	at java.lang.Thread.run(Thread.java:818)
```

Things run fine on API 23 and above.

**Comment by hansemannn** [comment]
Closing backport as decided for 7.2.0.

**Pull request closed without merging**
