### PR TITLE
[TIMOB-26063] iOS: Add "onlink" callback property to WebView, move KrollWrapper to own file

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26063

Test-Case and docs as part of #9459.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
LGTM! 👍

**Comment by vijaysingh-axway** [comment]
@garymathews Can you update doc by including iOS support as welling your PR  #9459.

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by hansemannn** [comment]
@vijaysingh-axway I just updated the PR via https://github.com/appcelerator/titanium_mobile/pull/9459/commits/5b2bcfe31303cada11070523e17b5a7dc8c4bc1b.

**Comment by hansemannn** [comment]
@sgtcoolguy I can't figure out to get a valid build out of this 🙁. Jenkins says
> [exec] xcrun: error: active developer path ("/Applications/Xcode-9.4.1.app/Contents/Developer") does not exist
[exec] Use `sudo xcode-select --switch path/to/Xcode.app` to specify the Xcode that you wish to use for command line developer tools, or use `xcode-select --install` to install the standalone command line developer tools.
     [exec] See `man xcode-select` for more details.
BUILD FAILED
/Users/build/jenkins/workspace/dk_titanium_mobile_PR-10180-6NEH2EVODLMQKGDVPINRLNDJFUHO4DD7AVEYPXZTNV2WASV5UBIQ/android/build/common.xml:636: exec returned: 1

which looks related to the Xcode configuration, but unrelated to this PR.

**Pull request merged**
