### PR TITLE
[TIMOB-24408] iOS: Add requestHeaders to Ti.UI.ImageView

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24408

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway @ewieberappc Merge conflicts resolved

**Comment by sgtcoolguy** [comment]
Is this something we can try and do cross-platform for Android and possibly Windows?

**Comment by sgtcoolguy** [comment]
@vijaysingh-axway ping

**Review by vijaysingh-axway — APPROVED** [review]
CR and FT passed.

**Comment by hansemannn** [comment]
We should. @maggieaxway is this something you can work on?

**Comment by ewieberappc** [comment]
iOS FR Passed. Comments in 7_1_X branch. PR can be merged once Android FR is passed

**Comment by ypbnv** [comment]
@ewieberappc Can you please ping me when this gets merged in order to enable the unit test for iOS as well?

**Comment by hansemannn** [comment]
Closing in favor of a CommonJS solution.

**Pull request closed without merging**
