### PR TITLE
[TIMOB-24808] Implement autofill hints for TextField and TextArea

### PR DESCRIPTION
**Pull request by garymathews**
- Implement `Titanium.UI.TextField` and `Titanium.UI.TextArea` `autofillType` for iOS and Android

###### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor: 'gray', layout: 'vertical'}),
	usr = Ti.UI.createTextField({
		width: Ti.UI.FILL,
		hintText: 'USERNAME',
		autofillType: Titanium.UI.AUTOFILL_TYPE_USERNAME
	}),
	pwd = Ti.UI.createTextField({
		width: Ti.UI.FILL,
		hintText:'PASSWORD',
		autofillType: Titanium.UI.AUTOFILL_TYPE_PASSWORD
	});

win.add(usr);
win.add(pwd);

win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24808)

### CODE REVIEW

**Review by hansemannn — APPROVED** [review]
iOS approved! Will wait for https://github.com/appcelerator/titanium_mobile/pull/9429 to be merged before, otherwise `IS_XCODE_9` will not be available for testing it. Please also do a backport of the latest changes, I've commited one more change.

**Comment by garymathews** [comment]
@hansemannn #9429 has now been merged, are we back porting to `6.3.0` ?

**Comment by hansemannn** [comment]
@garymathews Agreed, we are good to go.

**Comment by lokeshchdhry** [comment]
FR Passed for Android.

After app launch `autofill` prompts to select the google account to use for autofill for the app & autofills the fields.

Studio Ver:     4.10.0.201709271713
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.10-2
Appc CLI:       6.3.0-master.14
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.5
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Devices:        Android 8.0

**Comment by garymathews** [comment]
Humm.. `ios_format` isn't happy:
```
Fatal error: Error: Formatting incorrect on "iphone/Classes/TiUITextWidget.m"
```

**Comment by jquick-axway** [comment]
@lokeshchdhry, can you also test this with an Android 4.x device please? On Android, this feature is only supported on Android 8 and higher, so, this is to verify that this feature no-ops and we properly guard against its usage on older OS versions. Thanks.

**Review by jquick-axway — APPROVED** [review]
CR: Pass for Android

**Comment by hansemannn** [comment]
@garymathews This ticket should be a good candidate for unit-tests to validate the `autofillType` accessors as well as all constants. Can you do that? Otherwise I'll try to do it over the weekend.

**Comment by AppWerft** [comment]
I have added this in `app.js` on a real device (Pie), build with 8.0.0. In system configuration I have selected Google as autofill service:
```
const $ = Ti.UI.createWindow();
$.add(Ti.UI.createTextField({
	height:50,
	top:50,
	width:'90%',
	hintText: 'USERNAME',
	autofillType: Ti.UI.AUTOFILL_TYPE_USERNAME
}));
$.open();
```
Nothing happens. Whats going wrong?

Additional:
Following this instruction: https://developer.android.com/reference/android/view/autofill/AutofillManager.html#notifyViewEntered(android.view.View)
I cannot find `notifyViewEntered` or `requestAutofill` in the entire repo (grep -r requestAutofill *)
Where I can find the binding to autofill service?

**Pull request merged**
