### PR TITLE
[6_1_X][TIMOB-24793] Android: Fix Ti.UI.View.center calculation

### PR DESCRIPTION
**Pull request by garymathews**
- Cherry-pick of https://github.com/appcelerator/titanium_mobile/pull/9125

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24793)

### CODE REVIEW

**Review by jquick-axway — CHANGES_REQUESTED** [review]
This PR's code needs to be updated with the changes made in #9125.

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

```
var window = Ti.UI.createWindow({backgroundColor: 'gray'}),
	a = Ti.UI.createView({backgroundColor: 'red', width: 200, height: 200, center: {x: 0, y: 0}}),
    b = Ti.UI.createView({backgroundColor: 'blue', width: 100, height: 100, center: {x: 0, y: 0}}),
    btnLeft = Ti.UI.createButton({title: 'TOP LEFT', top: 0, left: 0, width: Ti.UI.SIZE});
    btnRight = Ti.UI.createButton({title: 'TOP RIGHT', top: 0, left: '25%', width: Ti.UI.SIZE});
    btnBottomLeft = Ti.UI.createButton({title: 'BOTTOM \nLEFT', top: 0, left: '50%', width: Ti.UI.SIZE});
    btnBottomRight = Ti.UI.createButton({title: 'BOTTOM RIGHT', top: 0, left: '75%', width: Ti.UI.SIZE});
    btnCenter = Ti.UI.createButton({title: 'Center', top: 50, left: '30%', width: Ti.UI.SIZE});
	width = 0,
	height = 0,
	widthWin = 0,
	heightWin= 0;
    
window.addEventListener('postlayout', function(){
	alert(a.getSize());
	width = a.getSize().width;
	height = a.getSize().height;
	widthWin = window.getSize().width;
	heightWin = window.getSize().height;
	a.center = {x: widthWin/2, y: heightWin/2};
});



 
btnLeft.addEventListener('click', function(){
    b.center = {x: 0, y: 0};
});

btnRight.addEventListener('click', function(){
    b.center = {x: width, y: 0};
});
 
btnBottomLeft.addEventListener('click', function(){
    b.center = {x: 0, y: height};
});
  
btnBottomRight.addEventListener('click', function(){
    b.center = {x: width, y: height};
});

btnCenter.addEventListener('click', function(){
    b.center = {x: width/2, y: height/2};
});
 
a.add(b);
window.add([btnLeft, btnRight, btnBottomLeft, btnBottomRight, btnCenter, a]);
window.open();
```

Center is the right center now & is calculated properly.

Studio Ver: 4.9.0.201705302345
SDK Ver: 6.1.1 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.9
Appc CLI: 6.2.2
Ti CLI Ver: 5.0.14
Alloy Ver: 1.9.11
Node Ver: 6.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Pixel --- Android 7.1.1
⇨ google Nexus 5 --- Android 6.0.1

**Pull request merged**
