### PR TITLE
feat(android): Optimized TextField/TextArea handling in TableView

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26862

**Summary:**
- Modified `TableView` to no longer recycle row container view.
  * There is no point in doing this since we always keep all child views in memory. Very little memory savings. (Use `ListView` for this behavior instead.)
  * Changing the parent view for rows containing `TextField` and `TextArea` was causing havoc while the virtual keyboard was shown.
- There is no good way to remove the keyboard warnings caused by changing a `TextField` or `TextArea` value/text programmatically. We have to live with it, but I've confirmed that it doesn't cause performance issues either.

---
**Test TableView with TextAreas/TextFields:**
_This tests the optimization change made._
1. Build and run code `TableOfTextFieldsTest.js` attached to [TIMOB-26862](https://jira.appcelerator.org/browse/TIMOB-26862) on Android 7.0 or higher.
2. Note that the first 10 rows contains `TextAreas` and the remaining rows contain `TextFields`.
3. Scroll to the top of the `TableView`.
4. Tap on row 1's `TextArea`.
5. Verify that all of the text within the `TextArea` is highlight.
6. Type in "abc".
7. Verify that the text is changed to "ABC" as you type it in.
8. Dismiss the virtual keyboard. (ie: Press the "Back" button once.)
9. Scroll to the bottom of the `TableView`.
10. Tap on row 200's `TextField`.
11. Verify that all of the text with the `TextField` is highlighted.
12. Type in "xyz".
13. Verify that the text is changed to "XYZ" as you type it in.
14. Dismiss the virtual keyboard.
15. Scroll to the top of the `TableView`.
16. Verify that row 1 still reads "ABC".
17. Repeat steps 1-16 on Android 4.4.

---
**Test TableView Default Rows:**
_This tests that "default" row template updates/handling still works._
1. Build and run code `TableViewDefaultRowTest.js` attached to [TIMOB-26862](https://jira.appcelerator.org/browse/TIMOB-26862) on Android 7.0 or higher.
2. Verify that row background colors change every 2 second to red, orange, and blue.
3. Verify that each row increments its "Count X" text updates every 2 seconds.
4. Verify that every row's left and right icons cycle between the appc logo to a soccer ball every 2 seconds.
5. Scroll to the bottom of the `TableView`.
6. Verify steps 2-4 above for the bottom rows.
7. Repeat steps 1-6 on Android 4.4.

---
**Test TableView Custom Rows:**
_This tests that row child view changes still works._
1. Build and run code `TableViewCustomRowTest.js` attached to [TIMOB-26862](https://jira.appcelerator.org/browse/TIMOB-26862) on Android 7.0 or higher.
2. Verify that row background colors change every 2 second to red, orange, and blue.
3. Verify that each row increments its "Count X" text updates every 2 seconds.
4. Verify that every row's left and right icons cycle between the appc logo to a soccer ball every 2 seconds.
5. Scroll to the bottom of the `TableView`.
6. Verify steps 2-4 above for the bottom rows.
7. Repeat steps 1-6 on Android 4.4.

### CODE REVIEW

**Comment by hansemannn** [comment]
Unfortunately this does not fix our issue so far. In fact, it breaks other parts of the app now. Log:
```
[WARN]  ActivityThread: handleWindowVisibility: no activity for token android.os.BinderProxy@cd124ba
[DEBUG] Window: Checkpoint: postWindowCreated()
[INFO]  AssistStructure: Flattened final assist data: 4140 bytes, containing 1 windows, 15 views
[INFO]  AssistStructure: Flattened final assist data: 4140 bytes, containing 1 windows, 15 views
[INFO]  AssistStructure: Flattened final assist data: 4140 bytes, containing 1 windows, 15 views
[INFO]  AssistStructure: Flattened final assist data: 4140 bytes, containing 1 windows, 15 views
[WARN]  IInputConnectionWrapper: getTextBeforeCursor on inactive InputConnection
[WARN]  IInputConnectionWrapper: getSelectedText on inactive InputConnection
[WARN]  IInputConnectionWrapper: getTextAfterCursor on inactive InputConnection
[WARN]  IInputConnectionWrapper: beginBatchEdit on inactive InputConnection
[WARN]  IInputConnectionWrapper: endBatchEdit on inactive InputConnection
[WARN]  StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
[INFO]  chatty: uid=10134(io.lambus.app) identical 15 lines
[WARN]  StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
[INFO]  I/io.lambus.app: Background concurrent copying GC freed 156310(7MB) AllocSpace objects, 43(2MB) LOS objects, 49% free, 12MB/25MB, paused 167us total 164.773ms
[WARN]  StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
[INFO]  chatty: uid=10134(io.lambus.app) identical 16 lines
[WARN]  StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
[WARN]  JavaObject: Could not move weak reference to strong, java object has already been collected! (Key: 0)
[INFO]  AssistStructure: Flattened final assist data: 8692 bytes, containing 2 windows, 34 views
[WARN]  StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
[INFO]  chatty: uid=10134(io.lambus.app) identical 16 lines
[WARN]  StaticLayout: maxLineHeight should not be -1.  maxLines:2 lineCount:2
```

**Comment by jquick-axway** [comment]
For everyone's reference, this PR has been changed since @hansemannn's comment above. The new changes resolves the performance issue in a `TableView`.

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by ssjsamir** [comment]
@jquick-axway When testing test case 2 and 3 I get the following errors: 

Test 2: 
```
[ERROR]  TiExceptionHandler: (main) [3,20242] /app.js:18
[ERROR]  TiExceptionHandler: switch (row.backgroundColor) {
[ERROR]  TiExceptionHandler: ^
[ERROR]  TiExceptionHandler: Uncaught Java Exception occurred
[ERROR]  TiExceptionHandler: at updateRow(/app.js:18:15)
[ERROR]  TiExceptionHandler: at (/app.js:57:5)
[ERROR]  TiExceptionHandler:
[ERROR]  TiExceptionHandler:
[ERROR]  TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[ERROR]  TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:55)
[ERROR]  TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:41)
[ERROR]  TiExceptionHandler: ti.modules.titanium.TitaniumModule$Timer.run(TitaniumModule.java:167)
[ERROR]  TiExceptionHandler: android.os.Handler.handleCallback(Handler.java:733)
[ERROR]  TiExceptionHandler: android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR]  TiExceptionHandler: android.os.Looper.loop(Looper.java:136)
[ERROR]  TiExceptionHandler: android.app.ActivityThread.main(ActivityThread.java:5017)
[ERROR]  TiExceptionHandler: java.lang.reflect.Method.invokeNative(Native Method)
[ERROR]  TiExceptionHandler: java.lang.reflect.Method.invoke(Method.java:515)
[ERROR]  V8Exception: Exception occurred at /app.js:18: Uncaught Java Exception occurred
[ERROR]  V8Exception: Java Exception occurred
```

Test 3:
```
[ERROR]  TiExceptionHandler: (main) [4,52377] /app.js:8
[ERROR]  TiExceptionHandler: switch (row.backgroundColor) {
[ERROR]  TiExceptionHandler: ^
[ERROR]  TiExceptionHandler: Uncaught Java Exception occurred
[ERROR]  TiExceptionHandler: at updateRow(/app.js:8:15)
[ERROR]  TiExceptionHandler: at (/app.js:69:5)
[ERROR]  TiExceptionHandler:
[ERROR]  TiExceptionHandler:
[ERROR]  TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Function.nativeInvoke(Native Method)
[ERROR]  TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Function.callSync(V8Function.java:55)
[ERROR]  TiExceptionHandler: org.appcelerator.kroll.runtime.v8.V8Function.call(V8Function.java:41)
[ERROR]  TiExceptionHandler: ti.modules.titanium.TitaniumModule$Timer.run(TitaniumModule.java:167)
[ERROR]  TiExceptionHandler: android.os.Handler.handleCallback(Handler.java:733)
[ERROR]  TiExceptionHandler: android.os.Handler.dispatchMessage(Handler.java:95)
[ERROR]  TiExceptionHandler: android.os.Looper.loop(Looper.java:136)
[ERROR]  TiExceptionHandler: android.app.ActivityThread.main(ActivityThread.java:5017)
[ERROR]  TiExceptionHandler: java.lang.reflect.Method.invokeNative(Native Method)
[ERROR]  TiExceptionHandler: java.lang.reflect.Method.invoke(Method.java:515)
[ERROR]  V8Exception: Exception occurred at /app.js:8: Uncaught Java Exception occurred
[ERROR]  V8Exception: Java Exception occurred
```

**Test Environment:**
```
Pixel XL SIm (7.1.1)
7.0.12
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 10.13.0
```

**Comment by jquick-axway** [comment]
@ssjsamir, those exceptions have nothing to do with this PR. This looks like a recent regression that has been introduced into "master".

**Comment by jquick-axway** [comment]
@ssjsamir, I wrote up a bug report for the issue you found here:
https://jira.appcelerator.org/browse/TIMOB-27231

Once the above issue's PR has been merged, we'll need to "update" this PR and re-test.
Thanks!

**Comment by lokeshchdhry** [comment]
FR Passed.

Studio Ver:     5.1.3.201907112159
SDK Ver:        8.2.0 local build
OS Ver:         10.14.5
Xcode Ver:      Xcode 10.2.1
Appc NPM:       4.2.14-3
Appc CLI:       7.1.0-master.24
Daemon Ver:     1.1.3
Ti CLI Ver:     5.2.1
Alloy Ver:      1.14.0
Node Ver:       10.16.0
NPM Ver:        6.9.0
Java Ver:       10.0.2
Devices:        ⇨ google Pixel (Android 9)
Emulator: Android 4.4.2

**Pull request merged**
