### PR TITLE
chore: remove module verification

### PR DESCRIPTION
**Pull request by garymathews**
- Remove module verification

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-28372)

### CODE REVIEW

**Review by vijaysingh-axway — COMMENTED** [review]
iOS changes looks good.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by sgtcoolguy** [comment]
@garymathews Shouldn't the titanium-verify.jar file go away entirely?

**Comment by garymathews** [comment]
@sgtcoolguy It holds `filterDataInRange()` used by hybrid modules built with TiSDK <9.0.0. Now, I've never seen a hybrid module used in the wild and it would be nice to remove it

**Pull request merged**
