### PR TITLE
[TIMOB-24574] (6_1_X) iOS: Fix picker-selection

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24574

### CODE REVIEW

**Review by vijaysingh-axway — COMMENTED** [review]
1.
-// We're order-dependent on type being set first, so we need to make sure that anything that relies
 -// on whether or not this is a date picker needs to be set AFTER the initial configuration.
 --(void)setSelectionIndicator_:(id)value
 -{
 -	if (picker == nil) {
 -		[[self proxy] replaceValue:value forKey:@"selectionIndicator" notification:NO];
 -	}
 -	else if ([self isDatePicker]==NO)
 -	{
 -		[(UIPickerView*)[self picker] setShowsSelectionIndicator:[TiUtils boolValue:value]];
 -	}
 -}
 -

Rather deleting the method , we should deprecate it by giving message to developers. What you think?

2. 
+        Manually setting the property was deprecated in 6.1.0 and will be ignored by the SDK.

This is deprecated in iOS only. So iOS should be mentioned in above line.

**Comment by hansemannn** [comment]
See notes in the master-PR. Also, please try to format code with 
```
\```objc
Code
\```
```
(Without the \\)

**Review by htbryant94 — APPROVED** [review]
Approved! picker selection indicator is now visible. Tested on iOS 10.2 / 9.3 Devices and Simulators.

**Comment by hansemannn** [comment]
Reverting due to failing unit-tests.

**Pull request merged**
