### PR TITLE
[TIMOB-11856] Fix Android: touchEnabled false on child view bug

### PR DESCRIPTION
**Pull request by maggieaxway**
longpress event to fire when clicked

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-11856

parent view click event should not be fired when child view is touch diabled

Test case:

````js
var win = Ti.UI.createWindow({backgroundColor: 'white', layout: 'vertical'});
 
var parentView = Ti.UI.createView({
   top:10,
   width:'90%',
   height:'90%',
   backgroundColor:'blue',
   layout: 'vertical',
   id: 'parent'
});
parentView.addEventListener('click',function(e){
   alert('parent click: e.source: ' + e.source.id + ', this: ' + this.id);
   Ti.API.info('parent click: e.source: ' + e.source.id + ', this: ' + this.id);
});
parentView.addEventListener('longpress',function(e){
   alert('parent longpress: e.source: ' + e.source.id + ', this: ' + this.id);
   Ti.API.info('parent longpress: e.source: ' + e.source.id + ', this: ' + this.id);
});
 
var childView = Ti.UI.createView({
   top: 50,
   width: '50%',
   height: '50%',
   backgroundColor: 'red',
   id: 'child',
   touchEnabled: false
});
 
parentView.add(childView);
win.add(parentView);
win.open();

### CODE REVIEW

**Comment by hansemannn** [comment]
@maggieaxway Is this ready for review? JIRA says `Open`

**Comment by maggieaxway** [comment]
@hansemannn yes it's ready for review

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Review by ssjsamir — APPROVED** [review]
FR - Passed. Parent view is no longer fired when `touchenabled` is set to `false`.

**Test steps**
+ Downloaded the SDK Build form this PR
+ Created a new Titanium project
+ Copied the the test case from description
+ Ran the application 
+ Clicked on the parent view
+ Saw the following line in the console
`[INFO] :   parent click: e.source: parent, this: parent`
+ Clicked on the child view
+ Nothing was shown in the console 

**Test environment** 
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

**Comment by garymathews** [comment]
- Closing due to `unknown repository`
- Opened new PR https://github.com/appcelerator/titanium_mobile/pull/9143

**Pull request closed without merging**
