### PR TITLE
[TIMOB-16597] iOS Exposing overCurrentContext and overFullScreenContext modal presentation style

### PR DESCRIPTION
**Pull request by AndreaVitale**
**JIRA:** [https://jira.appcelerator.org/browse/TIMOB-16597](https://jira.appcelerator.org/browse/TIMOB-16597)

### CODE REVIEW

**Comment by hansemannn** [comment]
Thanks for the PR @AndreaVitale! Can you also expose [`UIModalPresentationOverFullScreen `](https://developer.apple.com/documentation/uikit/uimodalpresentationstyle/uimodalpresentationoverfullscreen?language=objc), so we have all possible values covered?

**Comment by AndreaVitale** [comment]
Done!

**Review by hansemannn — APPROVED** [review]
CR is looking good, PR **approved**!

**Comment by hansemannn** [comment]
Can you please create a `ti.ui.window.addontest.js` in <titanium_mobile>/tests with the following content:
```js
/*
 * Appcelerator Titanium Mobile
 * Copyright (c) 2011-Present by Appcelerator, Inc. All Rights Reserved.
 * Licensed under the terms of the Apache Public License
 * Please see the LICENSE included with this distribution for details.
 */
/* eslint-env mocha */
/* global Ti */
/* eslint no-unused-expressions: "off" */
'use strict';
var should = require('./utilities/assertions'),
	utilities = require('./utilities/utilities');

describe('Titanium.UI.Window', function () {

	it.ios('modalPresentationStyles', function () {
		should(Ti.UI.iOS.MODAL_PRESENTATION_PAGESHEET).be.a.Number;
		should(Ti.UI.iOS.MODAL_PRESENTATION_FORMSHEET).be.a.Number;
		should(Ti.UI.iOS.MODAL_PRESENTATION_CURRENT_CONTEXT).be.a.Number;
		should(Ti.UI.iOS.MODAL_PRESENTATION_OVER_CURRENT_CONTEXT).be.a.Number;
		should(Ti.UI.iOS.MODAL_PRESENTATION_OVER_CURRENT_FULL_SCREEN).be.a.Number;
	});
});
```
It will be added to the unit tests and validated during CI build.

**Comment by hansemannn** [comment]
Closing in favor of the rebased version in https://github.com/appcelerator/titanium_mobile/pull/10070

**Pull request closed without merging**
