### PR TITLE
fix(ios): remove busy loop and change waitForMemoryPanicCleared to noop since it's always on main thread

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27080

**Description:**
Was previously used in kroll thread entry points to wait for main thread to handle memory warnings.
Now it will just result in an infinite sleep loop because JS runs on main thread.

All credit goes to @janvennemann for finding this, once he pointed it out to me I was able to do a local SDK build with it as a no-op and confirm the fix on @hansemannn 's Lambus app.

### CODE REVIEW

**Comment by janvennemann** [comment]
Instead of making it a noop, can't we just remove the method completely? I don't think it's party of any public API so it shouldn't be an issue to remove it now.

**Comment by hansemannn** [comment]
Still dead-locking / crashing, but now with many more logs:
```
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
[DEBUG] Firing app event: memorywarning
```
Triggered manually via `Debug > Simulate Memory Warning`.

**Review by janvennemann — APPROVED** [review]
Approved! As discussed in Teams we'll keep the function and extern var for now to avoid possible breaking changes.

**Comment by ssekhri** [comment]
Still see the issue with the SDK build fetched from Jenkins for this PR. It consistently crashes when scrolling through the trips (had around 15 trips created and it crashes after scrolling through 8-10 trips). Following logs were shown in console during one of the crash
`
[DEBUG] :  Firing app event: memorywarning
[DEBUG] :  Firing app event: memorywarning
[DEBUG] :  Firing app event: memorywarning
[ERROR] :  The application has crashed with an uncaught exception 'NSGenericException'.
[ERROR] :  Reason:
[ERROR] :  *** Collection <__NSCFDictionary: 0x1754ea40> was mutated while being enumerated.
[ERROR] :  Stack trace:
[ERROR] :  0   CoreFoundation                      0x212ff933 <redacted> + 150
[ERROR] :  1   libobjc.A.dylib                     0x20a9ae17 objc_exception_throw + 38
[ERROR] :  2   CoreFoundation                      0x212ff3a1 <redacted> + 0
[ERROR] :  3   TitaniumKit                         0x01962cc3 -[KrollBridge didReceiveMemoryWarning:] + 196
[ERROR] :  4   CoreFoundation                      0x212b1735 <redacted> + 12
[ERROR] :  5   CoreFoundation                      0x212b113f <redacted> + 390
[ERROR] :  6   CoreFoundation                      0x212b0f1d <redacted> + 40
[ERROR] :  7   CoreFoundation                      0x21307c6b <redacted> + 1334
[ERROR] :  8   CoreFoundation                      0x21211083 _CFXNotificationPost + 486
[ERROR] :  9   Foundation                          0x21a525df <redacted> + 74
[ERROR] :  10  Foundation                          0x21a57113 <redacted> + 30
[ERROR] :  11  UIKit                               0x25b26813 <redacted> + 166
[ERROR] :  12  libdispatch.dylib                   0x20e6d80f <redacted> + 22
[ERROR] :  13  libdispatch.dylib                   0x20e85db3 <redacted> + 2030
[ERROR] :  14  libdispatch.dylib                   0x20e80d19 <redacted> + 712
[ERROR] :  15  libdispatch.dylib                   0x20e7b73f <redacted> + 394
[ERROR] :  16  CoreFoundation                      0x212c1b6d <redacted> + 8
[ERROR] :  17  CoreFoundation                      0x212c0067 <redacted> + 1574
[ERROR] :  18  CoreFoundation                      0x2120f229 CFRunLoopRunSpecific + 520
[ERROR] :  19  CoreFoundation                      0x2120f015 CFRunLoopRunInMode + 108
[ERROR] :  20  GraphicsServices                    0x227ffac9 GSEventRunModal + 160
[ERROR] :  21  UIKit                               0x258e3189 UIApplicationMain + 144
[ERROR] :  22  Lambus                              0x000d0871 Lambus + 51313
[ERROR] :  23  libdyld.dylib                       0x20eb7873 <redacted> + 2
`

Env:
SDK: 8.0.2.v20190522114611, 8.1.0.v20190515121638
Device: iPad mini (v9.3.5)
XCode: 10.2.1
tested using Lambus app versioned 1.2.0.9

**Comment by hansemannn** [comment]
Any update on the merch here? This is a critical pull request for many production apps. I hope postponing it to 8.2.0 was a mistake.

**Comment by sgtcoolguy** [comment]
@hansemannn It's an artifact of our branching off 8_1_X. We expect this fix to be in 8.0.2, master and 8_1_X.

**Comment by ssekhri** [comment]
Couldn't check the master build on the lambus app as there are some errors reported in the app upon launch when using the recent builds.
However the PR on 8_0_X branch was tested and the results updated in the PR.

**Comment by sgtcoolguy** [comment]
merged manually

**Pull request closed without merging**
