### PR TITLE
[TIMOB-18868] Do not overwrite Info.plist keys set by user

### PR DESCRIPTION
**Pull request by FokkeZB**
- Reads `CFBundleVersion` and `CFBundleShortVersionString` from `tiapp.xml`
- Only sets `CFBundleVersion` if target is iTunes or there is no custom value in either `tiapp.xml` or a custom `Info.plist`
- Only sets `CFBundleShortVersionString` if there is no custom value in either `tiapp.xml` or a custom `Info.plist`
- Only generates `CFBundleIconFiles` if there is no custom value in either `tiapp.xml` or a custom `Info.plist`
- Only generates `UILaunchImages` if there is no custom value in either `tiapp.xml` or a custom `Info.plist`, also fixing needing `ti clean` after adding new launch images.
- Only generates `UIAppFonts` if there is no custom value in either `tiapp.xml` or a custom `Info.plist`

### CODE REVIEW

**Comment by astjohn** [comment]
@FokkeZB - Thank you for this. I would love to use it as soon as possible.
:+1:

**Comment by FokkeZB** [comment]
@astjohn https://jira.appcelerator.org/browse/TIMOB-17993 is scheduled for 4.1.0 which is one release after the next minor one.

**Comment by astjohn** [comment]
@FokkeZB. Sounds good. I monkey patched 3.5.0.GA in the mean time and it works great. Thanks again.

**Comment by jasonkneen** [comment]
approve and merge this PLEASE!!!!

**Comment by FokkeZB** [comment]
Re-purposed this PR for https://jira.appcelerator.org/browse/TIMOB-18868
New PR for https://jira.appcelerator.org/browse/TIMOB-17993 is https://github.com/appcelerator/titanium_mobile/pull/6818

**Comment by cb1kenobi** [comment]
Code reviewed and tested. Works as advertised and looks good. **APPROVED**!

**Pull request merged**
