### PR TITLE
[TIDOC-2058] Added GitHub @editurl field to JSDuck generator.

### PR DESCRIPTION
**Pull request by tstatler**
Updated docgen.py to expose a new field on each class that contained the path to the current API file. The jsduck generator was updated to include an @editurl field in each class that pointed to the "Github edit URL". Because different APIs live in different locations, the specific URL needs to be computed based on whether it's a Titanium SDK API, a module API, an Alloy API, or a Tizen API.
- Since some modules are not public, they are 'blacklisted' from their URLs being included in the output.
- Since Alloy docs are passed as-is to JSDuck, it seemed easier just to manually add @editurl tags to Alloy file (see https://github.com/appcelerator/alloy/pull/659).
### Testing steps
1. Run `docgen.py -f jsduck -o ../build/`.
2. View build/titanium.js.

Spot check a few @class tags and make sure each has a corresponding @editurl tag. Copy/paste the @editurl URL into a browser and make sure it opens the expected edit page on Github.

### CODE REVIEW

**Comment by jhaynie** [comment]
this is awesome.

**Comment by bhatfield** [comment]
@tstatler This should be added to the JavaScript version of the scripts too.

**Comment by bhatfield** [comment]
@tstatler 
So it's generating the URLs, but they are not working.  The one's I check look like this:
~~~
/**
     * @class TableViewIndexEntry
     * @typestr Object
     * @pseudo
     * @editurl https://github.com/appcelerator-modules/TableView.yml/edit/master/l
     * <p>A simple object that represents an index entry in a <code>TableView</code>.</p>
     */
~~~

**Comment by tstatler** [comment]
@bhatfield, sorry about that, I've updated the PR with the fix. Please try again.

Also, yes, the JavaScript version is coming shortly.

**Comment by bhatfield** [comment]
@tstatler Link is working now.  Will merge with doctools PR is reviewed.

**Comment by bhatfield** [comment]
**Approved.**

**Pull request merged**
