### PR TITLE
[TIMOB-25424] Wrap music-related API's to prevent the requirement of non-used privacy-keys

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25424

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by ewieberappc** [comment]
FR Passed. Able to play videos and modify play settings on apps with videos. Tested sing the provided test case as well as several apps with video playback in them.

**Comment by sgtcoolguy** [comment]
This PR won't build the test suite app for iOS, so I don't think it's ready for merge.

**Comment by sgtcoolguy** [comment]
manually merged to master

**Pull request closed without merging**
