### PR TITLE
[7_0_X][TIMOB-25599] Android: Fix Java object referencing

### PR DESCRIPTION
**Pull request by garymathews**
- Cherry-pick of https://github.com/appcelerator/titanium_mobile/pull/9675

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25599)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
@garymathews ,
Its crashing for me using the 7.0.2 artifact:
```
01-08 15:51:11.118 13313 13313 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
01-08 15:51:11.118 13313 13313 F DEBUG   : Build fingerprint: 'google/sailfish/sailfish:7.1.1/NMF26O/3514931:user/release-keys'
01-08 15:51:11.118 13313 13313 F DEBUG   : Revision: '0'
01-08 15:51:11.118 13313 13313 F DEBUG   : ABI: 'arm64'
01-08 15:51:11.118 13313 13313 F DEBUG   : pid: 13203, tid: 13203, name: .app.timob25599  >>> com.app.timob25599 <<<
01-08 15:51:11.118 13313 13313 F DEBUG   : signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
01-08 15:51:11.120 13313 13313 F DEBUG   : Abort message: 'art/runtime/java_vm_ext.cc:470] JNI DETECTED ERROR IN APPLICATION: use of invalid jobject 0xcb6260007097b000'
01-08 15:51:11.120 13313 13313 F DEBUG   :     x0   0000000000000000  x1   0000000000003393  x2   0000000000000006  x3   0000000000000008
01-08 15:51:11.120 13313 13313 F DEBUG   :     x4   0000000000000108  x5   0000000000000000  x6   0000000000000000  x7   feff666e6b61686b
01-08 15:51:11.120 13313 13313 F DEBUG   :     x8   0000000000000083  x9   ffffffffffffffdf  x10  0000000000000000  x11  0000000000000001
01-08 15:51:11.120 13313 13313 F DEBUG   :     x12  ffffffffffffffff  x13  ffffffffffffffff  x14  ff00000000000000  x15  ffffffffffffffff
01-08 15:51:11.120 13313 13313 F DEBUG   :     x16  00000070d4e6fee0  x17  00000070d4e19250  x18  0000000000000000  x19  00000070d70f7b40
01-08 15:51:11.120 13313 13313 F DEBUG   :     x20  0000000000000006  x21  00000070d70f7a98  x22  000000000000000b  x23  00000070d3186918
01-08 15:51:11.120 13313 13313 F DEBUG   :     x24  000000000000000a  x25  ffffffffffffffff  x26  00000000000010db  x27  0000007fe8d68c31
01-08 15:51:11.121 13313 13313 F DEBUG   :     x28  00000070d31fc740  x29  0000007fe8d68b30  x30  00000070d4e166f8
01-08 15:51:11.121 13313 13313 F DEBUG   :     sp   0000007fe8d68b10  pc   00000070d4e19258  pstate 0000000060000000
01-08 15:51:11.142 13313 13313 F DEBUG   : 
01-08 15:51:11.142 13313 13313 F DEBUG   : backtrace:
01-08 15:51:11.142 13313 13313 F DEBUG   :     #00 pc 000000000006b258  /system/lib64/libc.so (tgkill+8)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #01 pc 00000000000686f4  /system/lib64/libc.so (pthread_kill+64)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #02 pc 0000000000023ce8  /system/lib64/libc.so (raise+24)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #03 pc 000000000001c76c  /system/lib64/libc.so (abort+52)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #04 pc 00000000004300fc  /system/lib64/libart.so (_ZN3art7Runtime5AbortEPKc+456)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #05 pc 00000000000e5818  /system/lib64/libart.so (_ZN3art10LogMessageD2Ev+1576)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #06 pc 00000000002eee20  /system/lib64/libart.so (_ZN3art9JavaVMExt8JniAbortEPKcS2_+2172)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #07 pc 00000000002ef1e4  /system/lib64/libart.so (_ZN3art9JavaVMExt9JniAbortFEPKcS2_z+184)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #08 pc 00000000004531f0  /system/lib64/libart.so (_ZNK3art6Thread13DecodeJObjectEP8_jobject+404)
01-08 15:51:11.142 13313 13313 F DEBUG   :     #09 pc 00000000004298b4  /system/lib64/libart.so (_ZN3art8ArgArray24BuildArgArrayFromVarArgsERKNS_33ScopedObjectAccessAlreadyRunnableEPNS_6mirror6ObjectESt9__va_list+472)
```
Did not crash with master, but now I doubt it was a fluke.

**Comment by garymathews** [comment]
@lokeshchdhry Interesting, the tests on Jenkins completed successfully: https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile/detail/PR-9675/7/pipeline

I'll take a look

**Comment by lokeshchdhry** [comment]
@garymathews , I still see a crash https://gist.github.com/lokeshchdhry/e8eb50b48e1bee8171b69150ce865ade

**Comment by garymathews** [comment]
Bumped out of `7.0.2`, closing.

**Pull request closed without merging**
