### PR TITLE
[TIMOB-19826] Added error code and moved validation code to Analytics …

### PR DESCRIPTION
**Pull request by ashcoding**
…class
Jira: https://jira.appcelerator.org/browse/TIMOB-19826

### CODE REVIEW

**Comment by ashcoding** [comment]
Code was moved out of TiConvert as it is something that is only used in Analytics. Hence moved to Analytics namespace.

**Comment by zackehh** [comment]
Out of interest, is there any reason the SDK uses `org.json` and `JSONObject` rather than using [Jackson](https://github.com/FasterXML/jackson-core)? Is it just to avoid the external dependency? 

We built a module which is useful for these types of validations for PEM; https://github.com/zackehh/dot-notes-java but it requires Jackson JSON rather than JSONObject.

**Comment by ashcoding** [comment]
You are right. It is to not depend on an external dependency (and prevent bloat in Android).

Android has a 65K Reference Limit (methods) that Titanium is limited by (at the moment).

**Comment by sriks** [comment]
FT Passed.

**Comment by zackehh** [comment]
@ashcoding aw, that's lame. Makes sense though :) thanks.

**Pull request merged**
