### PR TITLE
fix(ios): include shutdownUi() in TitaniumKit

### PR DESCRIPTION
**Pull request by garymathews**
- Since TitaniumKit is precompiled, build time flags should be specified in the headers instead.

##### TEST CASE
```JS
const win = Ti.UI.createWindow();
win.addEventListener('click', () => {
    Ti.App._restart();
});
win.open()
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-26705)

### CODE REVIEW

**Comment by keerthi1032** [comment]
FR passed. No Crash occurs. Waiting for CR to merge 

Operating System
  Name                        = Mac OS X
  Version                     = 10.13.6
  Memory                      = 17179869184
Node.js
  Node.js Version             = 8.12.0
  npm Version                 = 6.4.1
Titanium CLI
  CLI Version                 = 5.1.1
Titanium SDK
  SDK Version                 = local sdk 8.1.0.v20190108111453
 device                          =iPhone 6s iOS 12,

**Review by vijaysingh-axway — CHANGES_REQUESTED** [review]
@garymathews Will removing the wrapping of method from DEBUG macro not affect anything else? cc @janvennemann 
There is one more issue TIMOB-26694 which is happening due to this flag [here](https://github.com/appcelerator/titanium_mobile/blob/5b40485df86758d7fe9c9127136967fc5ad44e24/iphone/TitaniumKit/TitaniumKit/Sources/API/TiBase.h#L525)

**Comment by vijaysingh-axway** [comment]
@garymathews I have fix this issue as part of  [TIMOB-26694](https://jira.appcelerator.org/browse/TIMOB-26694) using a communication in framework via TiSharedConfig. Please review [PR-10593](https://github.com/appcelerator/titanium_mobile/pull/10593)

**Comment by sgtcoolguy** [comment]
closed in favor of #10593

**Pull request closed without merging**
