### PR TITLE
[TIMOB-23486] Android: Added 'canceledOnTouchOutside' property to AlertDialog

### PR DESCRIPTION
**Pull request by ashcoding**
JIRA: https://jira.appcelerator.org/browse/TIMOB-23486

Test Code:

``` javascript
var win = Ti.UI.createWindow({

});

var alertDialog = Ti.UI.createButton({
    title : 'ShowDialog',
    height : Ti.UI.SIZE,
    width : Ti.UI.SIZE,

});

// Listen for click events.
alertDialog.addEventListener('click', function() {
    var dialog = Ti.UI.createAlertDialog({
        message : 'The file has been deleted',
        canceledOnTouchOutside: false,
        cancel : 1,
        buttonNames : ['Confirm', 'Cancel'],
        message : 'Would you like to delete the file?',
        title : 'Delete'

    });
    dialog.show();
    dialog.canceledOnTouchOutside = true;
});

// Add to the parent view.
win.add(alertDialog);

win.open();
```

### CODE REVIEW

**Comment by hansemannn** [comment]
Can we rename it to `canCancelOutside`? Looks a bit more convenient to me.

**Comment by ashcoding** [comment]
There's already another usage of 'canceledOnTouchOutside' else where in our code and the native property is `setCanceledOnTouchOutside`. Thus, I think it's appropriate. Changing it to `canCancelOutside` would mean the other parts of the code in Android would need to change as well and I would like it to be consistent.

What do you think? Is it worth the change? The other usage is in ProgressIndicatorProxy.

**Comment by hansemannn** [comment]
Just thinking about `canEdit`,`canDelete` and `canMove`, your decision!

**Comment by ashcoding** [comment]
For now, `canceledOnTouchOutside` is okay. If there's a requirement to change them in the future, we can revisit this naming convention.

Thanks for the input!

**Comment by hieupham007** [comment]
Code reviewed and functionally tested. Request **accepted**

**Pull request merged**
