### PR TITLE
[TIMOB-18538] Update node-appc; args to spawn must be Array

### PR DESCRIPTION
**Pull request by skypanther**
https://jira.appcelerator.org/browse/TIMOB-18538

### CODE REVIEW

**Comment by cb1kenobi** [comment]
Where node-appc? You need to remove the node-appc in titanium_mobile and update it to 0.2.24.

You should do `rm -rf node_modules/node-appc`, then `npm install --production`. Reset all non-node-appc changes. Commit node-appc changes (should be the changelog, package.json, subprocess.js, and travis file).

**Comment by cb1kenobi** [comment]
Looks better, but needs FR.

**Comment by skypanther** [comment]
Not ready to merge. I'm getting an error in node-ios-device.

**Comment by feons** [comment]
**Approved!**

**Pull request merged**
