### PR TITLE
(5.5.X)Fix wrong ifdef statmenet

### PR DESCRIPTION
**Pull request by AngelkPetkov**
[JIRA](https://jira.appcelerator.org/browse/TIMOB-23824)

### CODE REVIEW

**Comment by hansemannn** [comment]
Needs approval from @eric34  and @cheekiatng before. It basically fixes an issue where the ProgressBarStyle constants could not found unless you define an AnimationStyle constant. @AngelkPetkov please also file a ticket for that asap and link it here.

**Comment by AngelkPetkov** [comment]
Will file a ticket, but its not the only issue it will cause the app to crash too, if you use animationStyle as it would define the progressBar in the m file but the actuall file will not be defined and will crash with null pointer.

**Comment by cheekiatng** [comment]
we want this in 5.5.0. we want a ticket too to track. do asap.

**Comment by hansemannn** [comment]
Approved!

**Pull request merged**
