### PR TITLE
[TIMOB-25517] Android: TableViewProxy unable to create table view row proxy for object

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25517

**Description:**
Fixes TableView insertSectionAfter() method.

**Test case:**
app.js
```
var win = Ti.UI.createWindow();
var table = Ti.UI.createTableView();
win.add(table);
win.open();

var sectionFish = Ti.UI.createTableViewSection({ headerTitle: 'Fish' });
sectionFish.add(Ti.UI.createTableViewRow({ title: 'Cod' }));
sectionFish.add(Ti.UI.createTableViewRow({ title: 'Haddock' }));

table.insertSectionBefore(0, sectionFish);
```

With 6.3.0:
sectionFish is not added and an error is logged:
`Unable to create table view row proxy for object, likely an error in the type of the object passed in...`

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by sgtcoolguy** [comment]
Can we add a test for this? Or maybe just see if Android now passes this one: https://github.com/appcelerator/titanium-mobile-mocha-suite/blob/master/Resources/ti.ui.tableview.test.js#L891

**Comment by ypbnv** [comment]
@sgtcoolguy Both tests (insertSectionBefore and insertSectionAfter) worked on Android device and emulator.

**Comment by sgtcoolguy** [comment]
**NOTE:** This will need to be cherry-picked to 7_0_X after being merged to master.

**Comment by lokeshchdhry** [comment]
FR Passed.

No `Unable to create table view row proxy for object` error seen & `insertSectionBefore` & `insertSectionAfter` works as expected. Also, checked with test app in the ticket.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.1.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11
Appc CLI:       7.0.0
Daemon Ver:     1.0.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

**Pull request merged**
