### PR TITLE
docs(api): remove notes about heavyweight windows

### PR DESCRIPTION
**Pull request by janvennemann**
Removes all the confusing instructions about heavyweigth and leightweight windows which are from pre SDK 3.2.0 era.

I have found not mention about a way to create leightweight windows these days, but just to be sure cc @garymathews @jquick-axway

### CODE REVIEW

**Review by jawa9000 — APPROVED** [review]
Looks good.

**Comment by janvennemann** [comment]
@jquick-axway just to double check, there is no way to create a lightweight window these days, correct?

**Comment by jquick-axway** [comment]
Our current Android code creates either an `Activity` or a tab `Fragment` when opening a `Ti.UI.Window`. Neither of those are lightweight.

Our old `Ti.UI.Window` used to support creating a view within an existing activity. This was considered a lightweight window back then. I can see it in our old 3.x.x code below. We definitely do not support this anymore
https://github.com/appcelerator/titanium_mobile/blob/3_1_X/android/modules/ui/src/java/ti/modules/titanium/ui/WindowProxy.java

**Comment by janvennemann** [comment]
@jquick-axway, perfect, thanks for the clarification. That's exactly what i thought.

@jawa9000 this is good to go!

**Pull request merged**
