### PR TITLE
[TIMOB-23572] iOS/Android: Expose Ti.App.Properties.removeAllProperties()

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23572

I dedicate this PR to @FokkeZB 😉

### CODE REVIEW

**Comment by FokkeZB** [comment]
You 🎸!

**Comment by AngelkPetkov** [comment]
FT on IOS looks good, however cannot compile on android when using scons : 
```
[javac] import org.appcelerator.titanium.TiContext;
    [javac]                                 ^
    [javac]   symbol:   class TiContext
[javac]   location: package org.appcelerator.titanium
[javac] /Users/apetkov/Documents/titanium_mobile/android/modules/app/src/java/ti/modules/titanium/app/properties/PropertiesModule.java:30: error: cannot find symbol
[javac] 	public PropertiesModule(TiContext tiContext)
    [javac] 	                        ^
[javac]   symbol:   class TiContext
    [javac]   location: class PropertiesModule
[javac] 2 errors
```

**Comment by hansemannn** [comment]
I guess it's because of the V8-updates @sgtcoolguy did recently where he removed those constructors. I pulled from master and it's gone, please try again.

**Comment by AngelkPetkov** [comment]
Prettty sure you just merged all the changes into master

**Comment by hansemannn** [comment]
No I didn't. I merged master into the branch.

**Comment by AngelkPetkov** [comment]
Are you sure because i just created a fresh branch pulled from mater and all your changes are there

**Comment by hansemannn** [comment]
Yes, very sure. The [last commits](https://github.com/appcelerator/titanium_mobile/commits/master) have been from you merging my other PR's. You probably mixed up your local fork.

**Comment by AngelkPetkov** [comment]
Approved!

**Pull request merged**
