### PR TITLE
[TIMOB-18662] Bump Titanium SDK Version to 3.5.2

### PR DESCRIPTION
**Pull request by jonalter**
[TIMOB-18662](https://jira.appcelerator.org/browse/TIMOB-18662)

### CODE REVIEW

**Comment by ingo** [comment]
Approved. Merging.

**Comment by jhaynie** [comment]
do we really need to do PR for stuff as simple as this?

**Comment by ingo** [comment]
Yes, because we've forgotten to update both files. The fact we have both files is super-annoying. Once we solve https://jira.appcelerator.org/browse/TIMOB-18508, then no.

**Comment by jhaynie** [comment]
ok, can we just fix that? that seems like a quick fix.

**Comment by ingo** [comment]
Yes--problem is it is reused in a bunch of places. Trying to get to it. I am actively trying to refine as much process as quickly as possible :)

**Comment by jhaynie** [comment]
can't we just put it in the top level build to generate the right value in both places as-is. at least then you don't hard code it in two places.

**Pull request merged**
