### PR TITLE
feat(android): Animate parameter for disableTabNavigation

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/AC-6539

**Optional Description:**

BottomNavBar will animate when removing it:
```
$.tabgroup.disableTabNavigation(false, true);
```
ezgif-3-c99e7f591a6d

```
var win1 = Ti.UI.createWindow({backgroundColor: '#fff'});
win1.add(Ti.UI.createLabel({touchEnabled:false, text: 'Click to hide - animated'}));

var isOpen = true;

win1.addEventListener("click",function(){
	isOpen = !isOpen;
	tabGroup.disableTabNavigation(!isOpen, true); // animate navbar
})

var win2 = Ti.UI.createWindow({backgroundColor: '#fff'});
win2.add(Ti.UI.createLabel({touchEnabled:false,text: 'Click to hide'}));
win2.addEventListener("click",function(){
	isOpen = !isOpen;
	tabGroup.disableTabNavigation(!isOpen); // old behavior
})
var tab1 = Ti.UI.createTab({
    window: win1,
    title: 'Blue'
}),
tab2 = Ti.UI.createTab({
    window: win2,
    title: 'Red'
}),
tabGroup = Ti.UI.createTabGroup({
	style: Ti.UI.Android.TABS_STYLE_BOTTOM_NAVIGATION,
    tabs: [tab1, tab2]
});
tabGroup.open();
```

### CODE REVIEW

**Comment by jquick-axway** [comment]
Oh this is an interesting idea. Kind of reminds me of our iOS-only [hidesBarsOnSwipe](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.NavigationWindow-property-hidesBarsOnSwipe) and [hidesSearchBarWhenScrolling](https://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.NavigationWindow-property-hidesSearchBarWhenScrolling) features, but your solution gives the app dev more direct control of when to hide/show it.

**Question:**
Will the top or bottom tabs slide out of view when using a translucent status bar or navigation bar. I think it will, but would you mind testing it please?
```javascript
Ti.UI.createWindow({
	backgroundColor: '#fff',
	extendSafeArea: true,
	theme: "Theme.AppCompat.NoTitleBar",
	windowFlags: Ti.UI.Android.FLAG_TRANSLUCENT_STATUS | Ti.UI.Android.FLAG_TRANSLUCENT_NAVIGATION,
});
```

**Comment by m1ga** [comment]
Good catch!
```
var win1 = Ti.UI.createWindow({
	backgroundColor: '#fff',
});
win1.add(Ti.UI.createLabel({
	touchEnabled: false,
	text: 'Click to hide - animated'
}));

var isOpen = true;

win1.addEventListener("click", function() {
	isOpen = !isOpen;
	tabGroup.disableTabNavigation(!isOpen, true); // animate navbar
})

var win2 = Ti.UI.createWindow({
	backgroundColor: '#fff'
});
win2.add(Ti.UI.createLabel({
	touchEnabled: false,
	text: 'Click to hide'
}));
win2.addEventListener("click", function() {
	isOpen = !isOpen;
	tabGroup.disableTabNavigation(!isOpen); // old behavior
})
var tab1 = Ti.UI.createTab({
		window: win1,
		title: 'Blue'
	}),
	tab2 = Ti.UI.createTab({
		window: win2,
		title: 'Red'
	}),
	tabGroup = Ti.UI.createTabGroup({
		tabsBackgroundColor: "blue",
		extendSafeArea: true,
		theme: "Theme.AppCompat.NoTitleBar",
		windowFlags: Ti.UI.Android.FLAG_TRANSLUCENT_STATUS | Ti.UI.Android.FLAG_TRANSLUCENT_NAVIGATION,
		style: Ti.UI.Android.TABS_STYLE_BOTTOM_NAVIGATION,
		tabs: [tab1, tab2]
	});
tabGroup.open();
```

will only animate it behind the task switcher bar at the bottom:
Screenshot_20200505-081023
(blue should be gone). I'll check that

**Comment by jquick-axway** [comment]
Right. This is an issue because `mBottomNavigationHeightValue` is the height of the bar from its "resource" file, but the actual height of the bar will be increased via `fitSystemWindows()` insets.

Now I'm actually wondering if there is a pre-existing issue with the `ViewPager` where it will be overlapped by the bottom tab bar when using a translucent nav bar. I'll have to test it out, but I'm thinking it will be an issue and we'll have to relayout the `ViewPager` dynamically since the insets can change dynamically. Especially when rotating between portrait/landscape.

**Comment by m1ga** [comment]
closing in favor of https://github.com/tidev/titanium_mobile/pull/13770

**Pull request closed without merging**
