### PR TITLE
[TIMOB-3797] Tooling: Ignore files listed in tiapp.xml

### PR DESCRIPTION
**Pull request by feons**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-3797

Propose to support adding ignore files in tiapp.xml, eg:
```
  <ignore-files>
    <file>*.tmp</file>
    <file>dist/*</file>
  </ignore-files>
```

### CODE REVIEW

**Comment by cb1kenobi** [comment]
Any particular reason to add this to the `tiapp.xml`? Several tools these days use an "ignore" file such as `.gitignore` or `.npmignore`.

**Comment by hansemannn** [comment]
@cb1kenobi I think the reason was that we want to exclude those file in the Titanium build (e.g. test-files, dev-related JS files).

**Comment by cb1kenobi** [comment]
I'm fine with the "feature". I'm questioning the solution. The tiapp.xml is already overloaded and inconsistent. TIMOB-3797 was created 6 years ago and today is a different day. Maybe putting it in the tiapp is not a great idea, but maybe it's not bad either.

**Comment by cb1kenobi** [comment]
Here's an idea... keep this in the tiapp.xml, but instead of ignoring files, we whitelist files. This is exactly what Xcode projects and Visual Studio projects do. Then we can add additional information PER FILE and specify how files should be handled: encrypted, minified, optimized, copied, not copied, etc.

**Comment by hansemannn** [comment]
I think this PR needs to be reworked and rebased, based on the feedback from Chris. Let's close it for now and revisit the changes as they get requested.

**Pull request closed without merging**
