### PR TITLE
[TIMOB-15091] iOS: Allow using module views in Ti.UI.ListView templates

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-15091

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR and FT passed.

**Comment by hansemannn** [comment]
Moving out of 7.1.0 due to missing Android parity.

**Comment by sgtcoolguy** [comment]
Pushing to 7.4.0 as we should have an Android equivalent merged at the same time.

**Comment by sgtcoolguy** [comment]
@garymathews @jquick-axway I've opened https://jira.appcelerator.org/browse/TIMOB-26138 to address the Android side of this. We shouldn't merge this PR until we have the Android equivalent...

**Comment by hansemannn** [comment]
@sgtcoolguy Let's close this PR and the related ticket. Modules can be used with #10131 by simply returning the view via `getView()` in a module, like:
```js
var map = require('ti.map');
var mapView = map.createView({ /** ... **/ });

exports.getView = () => {
  return mapView;
};
```
so introducing another `module` property is nonsense. Or am I missing something?

**Comment by vijaysingh-axway** [comment]
@sgtcoolguy Should we close this PR as suggested by Hans in above comment?

**Comment by lokeshchdhry** [comment]
@sgtcoolguy , @vijaysingh-axway , What are we doing with this PR ?

**Pull request closed without merging**
