### PR TITLE
[TIMOB-19375]: Check permissions for Android-M

### PR DESCRIPTION
**Pull request by hieupham007**
Android's new permission model. 
Camera test case:

```
function showCamera() {
    Titanium.Media.showCamera({
        success:function(event) {
            // called when media returned from the camera
            Ti.API.debug('Our type was: '+event.mediaType);
            if(event.mediaType == Ti.Media.MEDIA_TYPE_PHOTO) {
                var imageView = Ti.UI.createImageView({
                    width:win.width,
                    height:win.height,
                    image:event.media
                });
                win.add(imageView);
            } else {
                alert("got the wrong type back ="+event.mediaType);
            }
        },
        cancel:function() {
            // called when user cancels taking a picture
        },
        error:function(error) {
            // called when there's an error
            var a = Titanium.UI.createAlertDialog({title:'Camera'});
            a.setMessage(JSON.stringify(error));
            a.show();
        },
        saveToPhotoGallery:true
    });

}

var win = Ti.UI.createWindow();

win.addEventListener("open", function(e) {
   if (Ti.Media.hasCameraPermissions()) {
       showCamera();
   } else { 
       Ti.Media.requestCameraPermissions(function(e) {
                if (e.success === true) {
                    showCamera();
                } else {
                    alert("Access denied, error: " + e.error);
                }
       });
   }

});
win.open();
```

Location test case:

```
var win1 = Titanium.UI.createWindow({
    title : 'Tab 1',
    backgroundColor : '#fff'
});

var latitude = 33.58262112511852;
var longitude = -111.71566843986511;

var locationCallback = function(e) {
    if(!e.success || e.error) {  
        alert('error:' + JSON.stringify(e.error));  
        return;  
    }
    Ti.API.info(JSON.stringify(e));

    var longitude = e.coords.longitude;
    var latitude = e.coords.latitude;

}
win1.addEventListener("open", function(e) {

    if (Ti.Geolocation.hasLocationPermissions()) {
        Ti.Geolocation.preferredProvider = "gps";
        Titanium.Geolocation.addEventListener('location', locationCallback);
    } else {
        Ti.Geolocation.requestLocationPermissions(function(e) {
                    if (e.success === true) {
                        Ti.Geolocation.preferredProvider = "gps";
                        Titanium.Geolocation.addEventListener('location', locationCallback);
                    } else {
                        alert("Access denied, error: " + e.error);
                    }
        });
    }
});

win1.open();
```

Calendar test case:

```
var win = Ti.UI.createWindow();
win.addEventListener("open", function(e) {
    if (Ti.Calendar.hasCalendarPermissions()) {
       Ti.Calendar.getAllCalendars();
    } else {
       Ti.Calendar.requestCalendarPermissions(function(e) {
           if (e.success === true) {
              alert("Access granted");
              Ti.Calendar.getAllCalendars();
           } else {
              alert("Access denied, error: " + e.error);
           }
       });
    }
});
win.open();
```

Contacts example:

```
var win = Ti.UI.createWindow();
win.addEventListener("open", function(e) {
    if (Ti.Contacts.hasContactsPermissions()) {
       Ti.API.info("People: " + JSON.stringify(Ti.Contacts.getAllPeople()));
    } else {
       Ti.Contacts.requestContactsPermissions(function(e) {
           if (e.success === true) {
              alert("Access granted");
              Ti.API.info("People: " + JSON.stringify(Ti.Contacts.getAllPeople()));
           } else {
              alert("Access denied, error: " + e.error);
           }
       });
    }
});
win.open();
```

### CODE REVIEW

**Comment by benbahrenburg** [comment]
@hieupham007 @cheekiatng @ingo this PR looks like it might be missing the location permissions.  

Would be nice to have the ability to 
* Request a location permission
* Determine if a location permission has been requested
* Determine if a location permission has been authorized

Reference Link:
https://developer.android.com/guide/topics/security/permissions.html#normal-dangerous

**Comment by ashcoding** [comment]
Functionally tested.

Tested with Nexus 6 with Android 6.0. Permissions work well.

Just an observation: `Titanium.Geolocation.addEventListener('location', locationCallback);` The callback is not being called on Android 6.0 on the device I'm testing this on. https://github.com/hieupham007/Titanium_Mobile/blob/aef8991208f16ebd7ba746ca6bebd23414b7a771/android/modules/geolocation/src/java/ti/modules/titanium/geolocation/GeolocationModule.java#L543 seems to be null.

**Comment by ashcoding** [comment]
Code reviewed and functionally tested the Permissions. Working well. :+1: 
Waiting for Docs to be added before this is merged.

Only comment is as above regarding Geolocation callback which is not related to the permissions.

**Comment by ashcoding** [comment]
Did a final review. Everything looks good.

**Comment by ashcoding** [comment]
**Accepted** Merging

**Comment by ashcoding** [comment]
Jira link: https://jira.appcelerator.org/browse/TIMOB-19375

**Pull request merged**
