### PR TITLE
[TIMOB-23167] Android: tintColor for Button

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/AC-3470
- adding Ti.UI.Button.tintColor on Android 
- moving tintColor to TiC
- using TiC.tintColor in TiUIImageView too

### CODE REVIEW

**Comment by ashcoding** [comment]
Tested with: 
```javascript
Titanium.UI.setBackgroundColor('#000');
 
var win1 = Titanium.UI.createWindow({
    title:'Tab 1',
    backgroundColor:'white',
    fullscreen: true
});


var button = Titanium.UI.createButton({
	tintColor: '#ff0000',
   title: 'Hello',
   top: 10,
   width: 100,
   height: 50
});


win1.add(button);

var button1 = Titanium.UI.createButton({

   title: 'Hello',
   top: 70,
   width: 100,
   height: 50
});

button1.tintColor = '#ffff00',
win1.add(button1);

var button2 = Titanium.UI.createButton({

   title: 'Hello',
   top: 130,
   width: 100,
   height: 50
});

button2.setTintColor('#ffff00');
win1.add(button2);

win1.open();
```

**Comment by ashcoding** [comment]
Code reviewed and functionally tested.
**Approved**

**Comment by ashcoding** [comment]
@m1ga If there are no more changes that is to be done, I'll merge this. Is that okay?

**Comment by m1ga** [comment]
Feel free to merge it! Thank you

**Comment by ashcoding** [comment]
**Merging**

**Pull request merged**
