### PR TITLE
[TIMOB-24793] Android: Fix Ti.UI.View.center calculation

### PR DESCRIPTION
**Pull request by garymathews**
- Fix `Ti.UI.View.center` property when `{x: 0, y: 0}` is used

###### TEST CASE
```JS
var window = Ti.UI.createWindow({backgroundColor: 'gray'}),
    a = Ti.UI.createView({backgroundColor: 'red', width: 200, height: 200, top: 0, left: 0}),
    b = Ti.UI.createView({backgroundColor: 'blue', width: 100, height: 100, center: {x: 150, y: 150}}),
    btn_a = Ti.UI.createButton({title: 'TOP LEFT', bottom: 0, left: 0, width: '50%'}),
    btn_b = Ti.UI.createButton({title: 'ZERO', bottom: 0, right: 0, width: '50%'});

btn_a.addEventListener('click', function(){
    b.center = {x: 50, y: 50};
});

btn_b.addEventListener('click', function(){
    b.center = {x: 0, y: 0};
});

window.add([btn_a, btn_b, a, b]);
window.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24793)

### CODE REVIEW

**Review by jquick-axway — CHANGES_REQUESTED** [review]
The center point is supposed to be relative to the top-left corner of the parent view. We document it [here](http://docs.appcelerator.com/platform/latest/#!/guide/Layouts,_Positioning,_and_the_View_Hierarchy-section-src-29004895_safe-id-TGF5b3V0cyxQb3NpdGlvbmluZyxhbmR0aGVWaWV3SGllcmFyY2h5LVBvc2l0aW9uaW5nYW5kZGltZW5zaW9uc29mZWxlbWVudHM).

This new code breaks this behavior and makes the center point relative to center of the parent view. This is not correct. Nor does it match iOS (I tested it).

Also, I do see an old bug here (before your change) where a center point of (0,0) is wrongly ignored. (0,0) should position the view in the top-left corner of the parent, which I've confirmed is how it works on iOS.

**Comment by garymathews** [comment]
Thanks for pointing that out, I assumed center of parent due to not having to calculate for zero.

Updated PR

**Comment by jquick-axway** [comment]
No worries! :)
Lokesh and I were confused about what it was supposed to do too. Especially with a center point of (50%,50%) and (0,0) both ending up in the center of the view on Android.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

Used the code below to test:
```
var window = Ti.UI.createWindow({backgroundColor: 'gray'}),
    a = Ti.UI.createView({backgroundColor: 'red', width: 200, height: 200}),
    b = Ti.UI.createView({backgroundColor: 'blue', width: 100, height: 100, center: {x: 0, y: 0}}),
    btnLeft = Ti.UI.createButton({title: 'TOP LEFT', top: 0, left: 0, width: Ti.UI.SIZE});
    btnRight = Ti.UI.createButton({title: 'TOP RIGHT', top: 0, left: '25%', width: Ti.UI.SIZE});
    btnBottomLeft = Ti.UI.createButton({title: 'BOTTOM \nLEFT', top: 0, left: '50%', width: Ti.UI.SIZE});
    btnBottomRight = Ti.UI.createButton({title: 'BOTTOM RIGHT', top: 0, left: '75%', width: Ti.UI.SIZE});
	width = 0,
	height = 0;
    
window.addEventListener('postlayout', function(){
	alert(window.getSize());
	width = window.getSize().width;
	height = window.getSize().height;
});

 
btnLeft.addEventListener('click', function(){
    b.center = {x: 0, y: 0};
});

btnRight.addEventListener('click', function(){
    b.center = {x: width, y: 0};
});
 
btnBottomLeft.addEventListener('click', function(){
    b.center = {x: 0, y: height};
});
  
btnBottomRight.addEventListener('click', function(){
    b.center = {x: width, y: height};
});
 

window.add([btnLeft, btnRight, btnBottomLeft, btnBottomRight, b]);
window.open();
```

Center is the right center now & is calculated properly.

Studio Ver:     4.9.0.201705302345
SDK Ver:        6.2.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel --- Android 7.1.1
                ⇨ google Nexus 5 --- Android 6.0.1

**Pull request merged**
