### PR TITLE
[TIMOB-25560] : iOS extendSafeArea property not behave properly if tabBarHidden = true or navBarHidden = true

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-25560

### CODE REVIEW

**Comment by hansemannn** [comment]
Looks good! Please add unit-tests as well and ensure the sources are linted.

**Comment by hansemannn** [comment]
Faster than our Bot, hahaha!

**Comment by benbahrenburg** [comment]
@hansemannn did a quick test and it fixes the issue I reported earlier

**Review by hansemannn — APPROVED** [review]

**Review by mukherjee2 — APPROVED** [review]
Node Version: 8.9.1
NPM Version: 5.5.1
Mac OS: 10.13.1
Appc CLI: 7.0.0
Appc CLI NPM: 4.2.11
Titanium SDK version: 7.0.0 + artifacts from this PR
Appcelerator Studio vers 5.0.0

Passed FR. I was able to see the text at the top and bottom clearly on iPhone X simulator.

**Pull request merged**
