### PR TITLE
[TIMOB-18767] Android: Add support for xxxhigh to displayCaps.density

### PR DESCRIPTION
**Pull request by FokkeZB**

### CODE REVIEW

**Comment by hieupham007** [comment]
Code reviewed. Looks good

**Comment by hieupham007** [comment]
Functionally tested. The nexus 6 is reporting '560' DPI instead of '640'.

**Comment by FokkeZB** [comment]
@hieupham007, yes and TVs report 213 and because we're having 160/medium as the default that gives odd results. We should do >= instead of ==

**Comment by hieupham007** [comment]
I just submit https://github.com/appcelerator/titanium_mobile/pull/6776, added support for a few densities. I think this should fix our problem

**Comment by cheekiatng** [comment]
Closing PR since TIMOB-18767 is resolved and closed. Thanks!

**Pull request closed without merging**
