### PR TITLE
[TIMOB-25646]: iOS After Listview Search overlay not appearing

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-25646

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway Can you address the linting errors in TiUIListView.m?

**Comment by vijaysingh-axway** [comment]
@hansemannn, I  have already checked on this and couldn't find anything. I ran the clang-format command, but no success. Any suggestion?

**Comment by mukherjee2** [comment]
@vijaysingh-axway I am not able to download the artifact to do FR. Can you please look at the issue with the commit?

**Comment by hansemannn** [comment]
@sgtcoolguy (and Alan, does he has Github?): It looks like a recent change on the clang-format configuration broke some of the iOS validation. It moved some object pointer from `->` to ` -> ` (with a space). This cannot be fixed locally as `clang-format -i -style=file <file>` does not detect it. What do we do here?

**Review by hansemannn — APPROVED** [review]

**Comment by vijaysingh-axway** [comment]
@mukherjee2  The build is failing due to linting issue. Hans has tried to fixed, but still issue is there. As Hans has mentioned, some change on clang-format has broken iOS validation. Let's see what Chris Williams suggest.

**Comment by sgtcoolguy** [comment]
Well... is there any reason you can't fix this manually?

I don't believe there's been any change in clang-format's config recently.

**Comment by sgtcoolguy** [comment]
@mukherjee2 lint issues have been fixed, should be able to grab the SDK to test now.

**Review by mukherjee2 — APPROVED** [review]
Passed FR. Details are in backport PR.

**Pull request merged**
