### PR TITLE
[TIMOB-20275] Updated to node-appc 0.2.35.

### PR DESCRIPTION
**Pull request by cb1kenobi**

### CODE REVIEW

**Comment by cb1kenobi** [comment]
@cheekiatng this PR is ready for your review. Since I only updated node-appc and ioslib and that caused 4,977 files to change (nearly all are NPM dependencies), perhaps I should just update the rest of the NPM modules?

~~~
 archiver             0.16.0  →  0.21.0 
 async                 1.5.0  →   1.5.2 
 buffer-equal          0.0.1  →   1.0.0 
 clean-css             3.4.6  →   3.4.9 
 ejs                   2.3.4  →   2.4.1 
 moment               2.10.6  →  2.11.2 
 node-uuid             1.4.3  →   1.4.7 
 request              2.65.0  →  2.69.0 
 uglify-js             2.5.0  →   2.6.1 
 windowslib            0.3.1  →   0.4.0 
 xcode                 0.8.2  →   0.8.3 
 xmldom               0.1.19  →  0.1.22 
 grunt-contrib-clean  ^0.6.0  →  ^0.7.0 
 should               ~7.1.1  →  ~8.2.2 
~~~

**Comment by cheekiatng** [comment]
yes why not

**Comment by cb1kenobi** [comment]
Updated all NPM deps and switched to NPM 3 "perfect tree" directory structure.

**Comment by FokkeZB** [comment]
O my... @cb1kenobi just wants to end up as number 1 contributor to 5.2 :D

**Comment by cheekiatng** [comment]
APPROVED!

**Pull request merged**
