### PR TITLE
TIMOB-11863: Handle redirect from http to https (vice versa)

### PR DESCRIPTION
**Pull request by hieupham007**
testing steps in JIRA

### CODE REVIEW

**Comment by ashcoding** [comment]
Jira: https://jira.appcelerator.org/browse/TIMOB-11863

**Comment by ashcoding** [comment]
@hieupham007 
Works well with a non 6.0 Android.

On a 6.0 Android, no image loads. Just to be safe, I added the permissions as well. Still doesn't load. Code used for testing:-
```javascript
var win1 = Titanium.UI.createWindow({className:'win1'});
 
var img = Ti.UI.createImageView({
    image:'http://graph.facebook.com/517267866/picture',
    top:40,
    width:200,
    height:200
});
 
win1.add(img);
 


   if (Ti.Media.hasCameraPermissions()) {
      win1.open();
   } else { 
       Ti.Media.requestCameraPermissions(function(e) {
                if (e.success === true) {
                   win1.open();
                } else {
                    alert("Access denied, error: " + e.error);
                }
       });
   }
```

**Comment by hieupham007** [comment]
Ok fixed.

**Comment by ashcoding** [comment]
Code reviewed and functionally tested. **APPROVED**

**Pull request merged**
