### PR TITLE
adding androidback property to showCamera()

### PR DESCRIPTION
**Pull request by AppWerft**
**JIRA:** https://jira.appcelerator.org/browse/AC-5469

**Optional Description:**
 This change request adds a property "androidback" to the camera. Now the user can decide what happens if back button, i.e. hideCamera() (default behaviour). This is useful in AR uses cases.  

```js
Ti.Media.showCamera({
  androidback : function() {
    // go back in stack history etc or
    Ti.Media.hideCamera();
  }
});
```

### CODE REVIEW

**Comment by AppWerft** [comment]
What I have to do?

**Comment by AppWerft** [comment]
How can I sign CLA?

**Comment by hansemannn** [comment]
@AppWerft Reviving your PR! From your local branch, please pull from master and resolve the merge conflict there. Then, you can run `clang-format -style=file -i modules/media/src/java/ti/modules/titanium/media/MediaModule.java` from the `titanium_mobile/android` folder.

**Comment by m1ga** [comment]
I've updated the PR after talking to @AppWerft over here: https://github.com/appcelerator/titanium_mobile/pull/11270
this one can be closed

**Comment by sgtcoolguy** [comment]
Closing in favor of #11270

**Pull request closed without merging**
