### PR TITLE
[TIMOB-24307] Android: Fix Veracode Security scan : Found an Code Qua…

### PR DESCRIPTION
**Pull request by maggieaxway**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24307

### CODE REVIEW

**Comment by maggieaxway** [comment]
Other files no need to change, because the usage of "==" was for primitive type only.

APSAnalyticsHelper.java
TiBlob.java
TiJSService.java
TiMapInfoWindow.java

**Comment by garymathews** [comment]
CR: **PASS**

**Comment by hansemannn** [comment]
@maggieaxway There was one string-compare in `TiMapInfoWindow.java` that should be checked:

```java
if (tag == TiC.PROPERTY_TITLE || tag == TiC.PROPERTY_SUBTITLE)
```

The constants resolve to a string, so they should be compared with `equals()`:
```java
if (tag.equals(TiC.PROPERTY_TITLE) || tag.equals(TiC.PROPERTY_SUBTITLE))
```

All other files look clean. Thx!

**Comment by maggieaxway** [comment]
@hansemannn thanks a lot for pointing out my error. Will update accordingly

**Comment by maggieaxway** [comment]
@garymathews https://github.com/appcelerator-modules/ti.map/pull/197
Can you CR this for me? I can add you or label anything in that repository

**Comment by hansemannn** [comment]
@maggieaxway Sorry, already merged it, saw this comment afterwards. Looks fine, this one as well, thx!

**Pull request merged**
