### PR TITLE
chore: update ti.identity module

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA**
- https://jira.appcelerator.org/browse/MOD-2561
- https://jira.appcelerator.org/browse/MOD-2532

**Description:**
Rolls in fixes from Gary's PR appcelerator-modules/titanium-identity#27
And iOS 13 constants from Hans' PR: appcelerator-modules/titanium-identity#34

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
Note that there is now another update to ti.identity adding some iOS 13 auth policy constants: appcelerator-modules/titanium-identity#34

**Review by garymathews — APPROVED** [review]

**Comment by sgtcoolguy** [comment]
@garymathews is this still valid, or does #11448 make this obsolete?

**Comment by garymathews** [comment]
#11448 makes the Android changes for this PR obsolete

**Comment by garymathews** [comment]
Closing, updated https://github.com/appcelerator/titanium_mobile/pull/11448 to also include latest iOS changes

**Pull request closed without merging**
