### PR TITLE
[TIMOB-20443] Android: Create or Open File in Ti.Database

### PR DESCRIPTION
**Pull request by nitrag**
**Creates** or opens a database in Android. For example, a custom database path such as the applicationDataDirectory you had to pass a file object otherwise Android would tell you "File appdata-private://xyz.db contains a path separator". The following code works after this fix:

```
var file = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory,"xyz.db");
db = Ti.Database.open(file);
```

### CODE REVIEW

**Comment by hansemannn** [comment]
@nitrag Thank you for the PR! Can you please create a [JIRA-ticket](https://jira.appcelerator.org) to help our QE test this issue? /cc @ashcoding

**Comment by nitrag** [comment]
@hansemannn @ashcoding 

Done!
https://jira.appcelerator.org/browse/TC-5819

**Comment by ashcoding** [comment]
@nitrag Thanks!

**Comment by nitrag** [comment]
Still pending! Is that normal?

@ashcoding

**Comment by nitrag** [comment]
Bump

**Comment by ashcoding** [comment]
Thanks for the bump. Will set time aside to complete this as soon as humanly possible.

**Comment by ashcoding** [comment]
Code reviewed. Functionally tested. **Accepted**

**Pull request merged**
