### PR TITLE
[TIMOB-18297] Android: Reset AudioPlayer before in release method

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-18297

This will reset the MediaPlayer when doing a `release()`. The warning (`MediaPlayer: mediaplayer went away with unhandled events`) that appeared before this patch will be gone.

Example:
```
var win = Titanium.UI.createWindow({
	title: 'Audio Test',
	backgroundColor: '#fff',
	layout: 'vertical'
});

var startStopButton = Titanium.UI.createButton({
	title: 'Start/Stop Streaming',
	top: 10,
	width: 200,
	height: 40
});

var pauseResumeButton = Titanium.UI.createButton({
	title: 'Pause/Resume Streaming',
	top: 10,
	width: 200,
	height: 40,
	enabled: false
});

win.add(startStopButton);
win.add(pauseResumeButton);

// allowBackground: true on Android allows the 
// player to keep playing when the app is in the 
// background.
var audioPlayer = Ti.Media.createAudioPlayer({
	url: 'https://ia902508.us.archive.org/5/items/testmp3testfile/mpthreetest.mp3',
	allowBackground: true
});

startStopButton.addEventListener('click', function() {
	// When paused, playing returns false.
	// If both are false, playback is stopped.
	if (audioPlayer.playing || audioPlayer.paused) {
		audioPlayer.stop();
		pauseResumeButton.enabled = false;
		if (Ti.Platform.name === 'android') {
			audioPlayer.release();
		}
	} else {
		audioPlayer.start();
		pauseResumeButton.enabled = true;
	}
});

pauseResumeButton.addEventListener('click', function() {
	if (audioPlayer.paused) {
		audioPlayer.start();
	} else {
		audioPlayer.pause();
	}
});

audioPlayer.addEventListener('progress', function(e) {
	Ti.API.info('Time Played: ' + Math.round(e.progress) + ' milliseconds');
});

audioPlayer.addEventListener('change', function(e) {
	Ti.API.info('State: ' + e.description + ' (' + e.state + ')');
});

win.addEventListener('close', function() {
	audioPlayer.stop();
	if (Ti.Platform.osname === 'android') {
		audioPlayer.release();
	}
});

win.open();
```

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
@m1ga, this just gets rid of the logged warning, right?

I'm pretty sure it won't solve what the ticket is referencing. I'm curious if it's still even an issue. Have you tried it?

**Comment by m1ga** [comment]
@jquick-axway I didn't have a problem starting/stopping the stream before without the patch. A user on tislack had a problem on some devices switching streams or restarting them and he was referring to missing the reset() call.

**Review by caspahouzer — APPROVED** [review]
Everything works now as expected without any issue

**Comment by m1ga** [comment]
@jquick-axway the PR fixes https://jira.appcelerator.org/browse/AC-6300 too

**Comment by ssekhri** [comment]
FR passed. Audio player works fine upon resume or restart. Also no warnings shown.
Mac OS 10.14.6
Ti SDK: 8.3.0.v20190909124628
Appc CLI: 7.1.1
Node: 10.5.0
JDK: 10.0.2
Studio: 5.1.4.201909061933
Device: Nexus 4 (v5.1.1), Nexus 6 emulator (v5.0.0), Nexus 6 emulator (v6.0.0)

**Pull request merged**
