### PR TITLE
fix(android): textfield padding

### PR DESCRIPTION
**Pull request by m1ga**
Partial fix for https://github.com/appcelerator/titanium_mobile/issues/13278

It will apply the padding to the inner TiUITextField and not the outer layout (see screenshots in the issue above):

```js
const window = Ti.UI.createWindow();
window.add(Ti.UI.createTextField({
	top: 20,
	height: 40,
	borderStyle: Ti.UI.INPUT_BORDERSTYLE_ROUNDED,
	hintText: 'Enter value …',
	padding: {
		top: 10,
		bottom: 10
	}
}));
window.open();
```
So you can use a smaller padding yourself if the text is cut of by a fixed height. 
I've kept the default padding for the moment which is too high (48 instead of 28) which looks to be because of the animated hintText option. I'll look into that at some point.

**Before PR (10.1.1.GA):**
the actual textfield is pushed together by the padding:
Screenshot_1648396743
Screenshot_1648396750

**With this PR:**
padding is applied to the actual inner textfield:
Screenshot_1648396695

### CODE REVIEW

**Comment by m1ga** [comment]
added a test and updated the first post with some images.

Happy to get some feedback!

**Review by caspahouzer — APPROVED** [review]
Textfield padding solved great

LGTM

**Comment by hansemannn** [comment]
Unfortunately this caused a very bad regression for our apps, since it's a breaking change inside a minor version update. Therefore, I would revert it for now and merge the PR once the next major version after 11.1.0 is released. Or maybe a glabl opt-in flag to use the new padding behavior. Thoughts?

**Comment by m1ga** [comment]
can you describe the issue you are seeing? It was just "wrong" before how the padding was applied. There wasn't any feedback in https://github.com/tidev/titanium_mobile/issues/13278 or here so I thought it was fine.

Of course we can revert it. Only one person besides you complained about the padding issue before so other people didn't have issues with the current/old way :rofl: The solution for the other person was to use `borderStyle:none` and put it in a view

**Comment by hansemannn** [comment]
Okay, sounds good!

**Comment by jquick-axway** [comment]
I think part of the issue here is that there is more than one padding. Plus the animated hint text complicates things. And if you ever add bottom error text support, which is rendered below the TextField border, then this gets even more "interesting".

There is an outer-padding which is applied outside of the TextField's border. This is what the old code controlled. Correct me if I'm wrong, but doesn't iOS apply the padding outside of its border?

Then there is the inner-padding which is applied within the TextField's border which what this PR is changing it to. (Do you have to worry about the font getting clipped if the padding is too big?)

Maybe the solution is that these should be 2 separate properties?

**Pull request merged**
