### PR TITLE
fix(android): fix reusing a dialog with a new "parent" window

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27256

**Description:**
Reset the Builder instance once the Dialog has been shown in order to allow reusing the proxy with different contexts.
Checking if we can have a reliable unit test for that.

**Test case:**
_app.js_
```js
var dialog = Ti.UI.createAlertDialog({
    title: "Alert Dialog",
    message: "This is the alert message.",
    buttonNames: ["OK", "Cancel"],
    cancel: 1,
});

var window = Ti.UI.createWindow();
var button = Ti.UI.createButton({ title: "Show Alert" });
button.addEventListener("click", function(e) {
    var childWindow = Ti.UI.createWindow({ title: "Child Window" });
    childWindow.addEventListener("open", function() {
        function dialogEventHandler() {
            dialog.removeEventListener("click", dialogEventHandler);
            dialog.removeEventListener("cancel", dialogEventHandler);
            childWindow.close();
        }
        dialog.addEventListener("click", dialogEventHandler);
        dialog.addEventListener("cancel", dialogEventHandler);
        dialog.show();
    });
    childWindow.open();
});
window.add(button);
window.open();

```

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
Ahh... it was a variable scope issue. Thanks @ypbnv.

Issues like this is exactly why devs prefer to prefix member variables with `m_*` or `m*` or `this.*`. It avoids scoping bugs just like this. _(sigh)_

**Comment by ssekhri** [comment]
FR Passed. Dialog re-use works successfully.
Verified on:
Mac OS 10.14.3
Ti SDK: 8.2.0.v20190723012209
Appc CLI: 7.1.0-24
Node: 8.16.0
JDK: 10.0.2
Xcode: 10.2.1
Studio: 5.1.3.201907112159

**Comment by ssekhri** [comment]
@ypbnv kindly back-port to 8_1_X branch

**Pull request merged**
