### PR TITLE
[TIMOB-18976] iOS - Remove KrollThread

### PR DESCRIPTION
**Pull request by pec1985**
Test with this [SDK found here](https://www.dropbox.com/s/gc10hfr424uj6td/mobilesdk-4.1.0-osx.zip?dl=0)
The app will now run on the main thread by default. To disable this option and go back to the old way, just add the following to `tiapp.xml`

```
<ios>
    <run-on-main-thread>false</run-on-main-thread>
    <!-- more iOS stuff here... -->
</ios>
```

### CODE REVIEW

**Comment by vishalduggal** [comment]
:+1:

**Comment by pec1985** [comment]
Test with this [SDK found here](https://www.dropbox.com/s/gc10hfr424uj6td/mobilesdk-4.1.0-osx.zip?dl=0)
The app will now run on the main thread by default. To disable this option and go back to the old way, just add the following to `tiapp.xml`
```
<ios>
	<run-on-main-thread>true</run-on-main-thread>
	<!-- more iOS stuff here... -->
</ios>
```

**Comment by iotashan** [comment]
Just to be clear, the sdk zip is at Titanium SDK, or is it an Appc SDK that requires migrating to Platform?

**Comment by pec1985** [comment]
@iotashan It's a Titanium SDK

**Comment by cheekiatng** [comment]
APPROVED!

**Comment by aviboy2006** [comment]
Its works perfect to solve my issue.

**Pull request merged**
