### PR TITLE
[TIMOB-24409] Android: Improve hasPermission() and requestPermissions() method usability

### PR DESCRIPTION
**Pull request by garymathews**
- Allow a `String` array to be passed into `Titanium.Android.hasPermission()`
- Allow a `String` to be passed into `Titanium.Android.requestPermissions()`
- `Titanium.Android.requestPermissions()` should always respond to callback, with a success state when permissions are already granted.

###### TEST CASE
- Download [BigBuckBunny_320x180.mp4](http://download.blender.org/peach/bigbuckbunny_movies/BigBuckBunny_320x180.mp4)
```Javascript
// this should work on all devices, not just Android 6.0+
Ti.Android.requestPermissions('android.permission.WRITE_EXTERNAL_STORAGE', function(e) {
    if (e.success) {
        var videoFile = Ti.Filesystem.getFile('BigBuckBunny_320x180.mp4');
        Ti.Media.saveToPhotoGallery(videoFile.read(), {
            success : function(e) {
                console.log('SAVED TO GALLERY!');
            },
            error : function(e) {
                console.log('SAVE ERROR: ', e)
            }
        });
    } else {
        Ti.API.info('PERMISSIONS ERROR: ' + e.error);
    }
});
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24409)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
@garymathews , `import org.appcelerator.kroll.KrollDict;` is missing in `AndroidModule.java` due to which build fails scons.

**Comment by lokeshchdhry** [comment]
FR Passed.
1. Checked `Titanium.Android.hasPermission()` with array of permissions. Returned correct boolean value accordingly if permissions were present or not.
2. Checked `Titanium.Android.requestPermissions()` with array of permissions. Showed proper permissions dialog for accepting or declining the permission. Also the callback was fired successfully after the permissions were accepted or declined.

NOTE: permissions should be defined in the tiapp.xml for getting the permissions dialog.

Studio Ver : 4.8.1.201612050850
SDK Ver :    6.2.0 local build
OS Ver :     10.12.3
Xcode Ver :  Xcode 8.3.2
Appc NPM :   4.2.9
Appc CLI :   6.2.0
Ti CLI Ver : 5.0.12
Alloy Ver :  1.9.11
Node Ver :   6.10.1
Java Ver :   1.8.0_101
Devices :    oneplus A0001 --- Android 6.0.1
Emulator: Android 5.1.1, android 7.0

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Comment by hansemannn** [comment]
Removing the `in-qe-testing` label again, this PR was not code-reviewed so far.

**Comment by fmerzadyan** [comment]
CR && FR PASS

**Pull request merged**
