### PR TITLE
[TIMOB-20235] Android: requestStoragePermission is needed for various…

### PR DESCRIPTION
**Pull request by gimdongwoo**
[TIMOB-20235] Android: requestStoragePermission is needed for various use cases

https://jira.appcelerator.org/browse/TIMOB-20235

### CODE REVIEW

**Comment by gimdongwoo** [comment]
https://cla.appcelerator.com/sign
504 Gateway Time-out...

**Comment by gimdongwoo** [comment]
[ERROR] Emulator failed to start in a timely manner
The current timeout is set to 120000 ms
You can increase this timeout by running: titanium config android.emulatorStartTimeout <timeout ms>
Failed to build android project
npm ERR! Test failed.  See above for more details.

**Comment by ashcoding** [comment]
For the cla, please try again at another time to sign.

For the travis build, the emulator in travis timeout sometimes. For this scenario, the travis build just needs to be restarted.

**Comment by gimdongwoo** [comment]
@ashcoding Thank's your advise!!

:+1:

**Comment by yomybaby** [comment]
:+1

**Comment by hansemannn** [comment]
Please also update the docs from "5.1.0" to "6.0.0" since 5.1.0 is already released at the feature would most likely go into 6.0.0 then.

**Comment by gimdongwoo** [comment]
@hansemannn Oh, my mistake. Thank you very much.

**Comment by gimdongwoo** [comment]
Appcelerator-CLA dosen't work...
504 Gateway Time-out...

**Comment by ashcoding** [comment]
@gimdongwoo Could you try another browser and see if it works?

**Comment by gimdongwoo** [comment]
Case 1. Chrome 47.0.2526.111 (OSX 10.10.5)
  - When clicked 'Sign With Github', only refresh scrren but nothing change.
Case 2. Safari 9.0.1 (OSX 10.10.5)
  - When clicked 'Sign With Github', 504 Gateway Timeout.
Case 3. Internet Explorer 11 (Windows 10)
  - When clicked 'Sign With Github', 504 Gateway Timeout.

After, remove authorized application 'Appcelerator CLA' in github (https://github.com/settings/applications) and logout github.
Retry case 1,2,3. Then login & authorizing github, but same result.

Maybe, after authorizing github handling session process in (https://cla.appcelerator.com/sign) has error.

**Comment by hansemannn** [comment]
@gimdongwoo We are working to fix the issue, but sometimes it just works after a few days again. If it still not works today, please be patient for a few more days :-).

**Comment by benbahrenburg** [comment]
@gimdongwoo  @hansemannn    Does it make sense for this make more sense as part of Ti.FileSystem ?  

So @gimdongwoo any chance you could add the check similar to how you did in your awesome module https://github.com/benbahrenburg/Ti-Android-RequestStoragePermission/blob/master/android/src/com/boxoutthinkers/reqstorageperm/TiAndroidRequeststoragepermissionModule.java#L50 ?  Just thinking this would allow for both the check and grant.

**Comment by ashcoding** [comment]
@benbahrenburg I agree with you. It makes more sense to be part of `Ti.Filesystem`

**Comment by gimdongwoo** [comment]
This is a slight variation already existed "requestCameraPermissions" in "MediaModule.java".
And "hasStoragePermission" are already existed, too.
If this code is transferred to "Ti.FileSystem", it duplicated or supposed to be a cross-reference, I don't know whether it was the right thing.

**Comment by gimdongwoo** [comment]
Oh. yeah~

Almostly, I every day and try again.
Today finally, CLA is fixed.

@hansemannn It takes 27 days long, but thank you!

**Comment by gimdongwoo** [comment]
CLA is only work on Safari, but didn't work on Chrome.
I have been also requested this appcelerator support team.

Everybody thank you, have a nice day!!

**Comment by ashcoding** [comment]
:+1: Glad that CLA finally works for you. With regards to this PR, we have a Jira ticket https://jira.appcelerator.org/browse/TIMOB-20251 that has handled this. We needed to fix a few more things beside the permission issue as mentioned in that Jira.

Really appreciated your interest and help in creating a PR and contributing to the discussion of the permissions!

**Comment by ashcoding** [comment]
Thank you!

**Pull request closed without merging**
