### PR TITLE
[TIMOB-25887] Handle hasPlayServices() exceptions

### PR DESCRIPTION
**Pull request by garymathews**
- Handle exceptions from `FusedLocationProvider.hasPlayServices()`

###### TEST CASE
- Do NOT include `ti.playservices`
```JS
var win = Ti.UI.createWindow({ backgroundColor: 'gray' }),
    listView = Ti.UI.createListView(),
    count = 1;

Ti.Geolocation.accuracy = Ti.Geolocation.ACCURACY_HIGH;

function push (e) {
    var section = Ti.UI.createListSection({ headerTitle: '#' + count++ });
    if (e.success) {
        if (e.coords) {
            e = e.coords;
        }
        section.setItems([
            { properties: { title: 'LOCATION:\n' + e.latitude + ', ' + e.longitude, color: 'orange' } },
            { properties: { title: 'ALTITUDE:\n' + e.altitude, color: 'orange' } },
            { properties: { title: 'ACCURACY:\n' + e.accuracy, color: 'orange' } }
        ]);
    } else {
        section.setItems([
            { properties: { title: 'ERROR:\n' + e.error, color: 'red' } }
        ]);
    }
    listView.appendSection(section);
}

function getLocation () {
    Ti.Geolocation.addEventListener('location', push);
    Ti.Geolocation.getCurrentPosition(push);
}

win.addEventListener('open', function () {
    if (Ti.Geolocation.hasLocationPermissions()) {
        getLocation();
    } else {
        Ti.Geolocation.requestLocationPermissions(Ti.Geolocation.AUTHORIZATION_ALWAYS, function (e) {
            if (e.success) {
                getLocation();
            } else {
                alert('could not obtain location permissions');
            }
        });
    }
});

win.add(listView);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25887)

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
LGTM

**Comment by lokeshchdhry** [comment]
@garymathews , I still see the logs on a nexus 6P android 8.0.

**Comment by garymathews** [comment]
@lokeshchdhry Could you paste a snippet of the logs?

**Comment by lokeshchdhry** [comment]
FR Passed.

No unnecessary logs/exceptions seen in the console.

Studio Ver:     5.1.0
SDK Ver:        7.2.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.12
Appc CLI:       7.0.2
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

**Pull request merged**
