### PR TITLE
[TIMOB-19597] Android: Update for previewRect when no overlay is used

### PR DESCRIPTION
**Pull request by m1ga**
See https://jira.appcelerator.org/browse/TIMOB-19597 
When no overlay image is used it will return -1 (width, height)

### CODE REVIEW

**Comment by hansemannn** [comment]
Hey @m1ga, there are a lot of blank spaces that produce a diff change. Can you check and eliminate them? Thanks!

**Comment by sriks** [comment]
@m1ga this PR is taken from your master branch? When you are reworking a fix you should work/fork from the fix branch itself i.e your TIMOB-19597 branch. That way only the required diff is captured. Other wise this PR is capturing a lot of other commits as well.

**Comment by hansemannn** [comment]
Closing in favor of https://github.com/appcelerator/titanium_mobile/pull/7665 and https://github.com/appcelerator/titanium_mobile/pull/7666, thank you!

**Comment by m1ga** [comment]
@hansemannn sorry about all the blanks! 
@sriks yes, it was from master. I thought it would only push my changes (the few lines). Will be more careful next time.

**Pull request closed without merging**
