### PR TITLE
[TIMOB-25728] Android: TableView can crash using setData()

### PR DESCRIPTION
**Pull request by garymathews**
- Improve the validation for selectors in `setRowData()`

###### TEST CASE
```JS
var win = Ti.UI.createWindow({ backgroundColor: 'gray' }),
    data_a = [
        { title: 'Square', backgroundSelectedColor: 'red' },
        { title: 'Circle', backgroundSelectedColor: 'blue' },
        { title: 'Triangle', backgroundSelectedColor: 'purple' }
    ],
    data_b = [
        { title: 'Red', backgroundSelectedColor: 'red' },
        { title: 'Green', backgroundSelectedColor: 'green' },
        { title: 'Blue', backgroundSelectedColor: 'blue' }
    ],
    tv = Ti.UI.createTableView();

tv.data = [];
tv.setData(data_a);
tv.data = [];
tv.setData(data_b);
tv.data = [];
tv.setData(data_a);

win.add(tv);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25728)

### CODE REVIEW

**Review by sgtcoolguy — CHANGES_REQUESTED** [review]
LGTM, but please convert the test case example in your PR comment into an actual mocha test for our suite.

**Review by sgtcoolguy — APPROVED** [review]

**Comment by lokeshchdhry** [comment]
FR Passed.

`setData` on the same data set does not see a crash & this fix seems to have fixed the issue on reporters side as well.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.1.0 local build
OS Ver:         10.13.2
Xcode Ver:      Xcode 9.2
Appc NPM:       4.2.12
Appc CLI:       7.0.2
Daemon Ver:     1.0.1
Ti CLI Ver:     5.0.14
Alloy Ver:      1.11.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

**Comment by lokeshchdhry** [comment]
@garymathews , can you please resolve the conflicts.

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Pull request merged**
