### PR TITLE
[TIMOB-24327]  iOS:  Implement AllowsMultipleSelectionWhenEditing and getSelectedRow in ListView

### PR DESCRIPTION
**Pull request by Brianggalvez**
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-24327

* Added method setAllowsMultipleSelectionDuringEditing
* Added method getSelectedRows
* Added test case

### CODE REVIEW

**Comment by hansemannn** [comment]
@Brianggalvez I really want to get this in, so I've made https://github.com/Brianggalvez/titanium_mobile/pull/1 to add the docs and fix some of the source. As soon as you merge it, we can merge this here as well.

**Review by hansemannn — APPROVED** [review]
LGTM! We need a backport for this to take it for 6.2.0. @Brianggalvez Can you provide that by Monday?

**Comment by Brianggalvez** [comment]
@hansemannn for sure, just tell what I should do, just change the base branch of the PR?

**Comment by hansemannn** [comment]
Correct! Cherry-pick your range of commits to the 6_2_X branch. I am wondering if we have a guide for that already, we should do one at least.

**Comment by hansemannn** [comment]
Shit, now we have the initial PR has no docs, some code issues and test-cases. Let me try to restore it and do the backport, but it may not make it in 6.2.0 anymore.

**Comment by hansemannn** [comment]
@Brianggalvez Updated the PR to fix code-style issues. We need unit-tests for every PR as well, I'll try to set those up for you. If not, it needs to move to 7.1.

**Comment by hansemannn** [comment]
PR handled in https://github.com/appcelerator/titanium_mobile/pull/9557.

**Pull request closed without merging**
