### PR TITLE
[TIMOB-25363] Android: Fix intent URI parsing

### PR DESCRIPTION
**Pull request by garymathews**
- Continuation from https://github.com/appcelerator/titanium_mobile/pull/9500
- Allow non-file URIs
- Fix handling of `putExtraUri()` for files

###### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor: 'gray'}),
    btn = Ti.UI.createButton({
	    title: 'SEND',
    });

btn.addEventListener('click', (e) => {
	var img = 'DefaultIcon.png',
	    src = Ti.Filesystem.getFile(img),
	    dst = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, img), //externalStorageDirectory
        intent = Ti.Android.createIntent({
            action: Ti.Android.ACTION_SEND,
            type: 'image/*'
        });

	dst.write(src, false);

	intent.putExtraUri(Ti.Android.EXTRA_STREAM, dst.nativePath);
	intent = Ti.Android.createIntentChooser(intent, 'Choose');
	Ti.Android.currentActivity.startActivity(intent);
});

win.add(btn);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25363)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

No `Uncaught No Activity found to handle Intent` is thrown.
Also checked with different `action` types & seems to work as expected.

Studio Ver:     4.10.0.201709271713
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.10-2
Appc CLI:       6.3.0-master.15
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.6
Node Ver:       7.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
@lokeshchdhry, please run the sample code attached to [TIMOB-25439](https://jira.appcelerator.org/browse/TIMOB-25439) as well since this PR fixes it too.

**Comment by lokeshchdhry** [comment]
FR passed.

When `data` is not defined the type is set properly & the app list is shown.

Studio Ver: 4.10.0.201709271713
SDK Ver: 7.0.0 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.10-2
Appc CLI: 6.3.0-master.15
Ti CLI Ver: 5.0.14
Alloy Ver: 1.10.6
Node Ver: 7.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1
⇨ google Nexus 6P --- Android 8.0.0

**Comment by garymathews** [comment]
@sgtcoolguy, could you merge this? I can't write unit tests for this change.

**Comment by lokeshchdhry** [comment]
@sgtcoolguy , can you please merge this. @garymathews said in his comment above he can't write unit tests for this PR.

**Pull request merged**
