### PR TITLE
fix flickering while scrolling for webview

### PR DESCRIPTION
**Pull request by extralam**
fix flickering while scrolling for webview

if (Build.VERSION.SDK_INT >= Build.VERSION_CODES.HONEYCOMB) {
            webView.setLayerType(View.LAYER_TYPE_SOFTWARE, null);
        }

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi @extralam, please sign the CLA to get this merged. Thank you! /cc @ashcoding

**Comment by hansemannn** [comment]
@extralam Please sign the CLA in the next 7 days, thank you.

**Comment by hansemannn** [comment]
Approved!

**Comment by Jei** [comment]
I have to agree with @GertjanSmits.
This code was already added in [this commit](https://github.com/appcelerator/titanium_mobile/commit/7862fcaef6e2562ea8fa1c3b2225ff8db195c8e5) to solve [TIMOB-16358](https://jira.appcelerator.org/browse/TIMOB-16358), and then removed in [this revert](https://github.com/appcelerator/titanium_mobile/commit/0cfa35ca922970e97f78bcfe3b093045a5ab5d46).

**Comment by hansemannn** [comment]
Moved the ticket to be investigated for the next release (6.0.0), thanks!

**Pull request merged**
