### PR TITLE
[TIMOB-24270] iOS: Fix autorelease-crash when using kroll-thread

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24270

### CODE REVIEW

**Comment by hansemannn** [comment]
@vijaysingh-axway I'm not feeling save with the `retain + autorelease` solution so far, although it seem to work fine in all my use-cases. I'd love your opinion on this. The retain-cycle of the `media` property is a bit complicated (through different threads and contexts).

**Comment by vijaysingh-axway** [comment]
@hansemannn I was thinking something of using autorelease pool and retaining the image inside  caller function, but I am not very sure.  Let me think in more detail on this and will let you know.

**Review by vijaysingh-axway — COMMENTED** [review]
While verifying with-
//#define TI_USE_KROLL_THREAD
#define USE_JSCORE_FRAMEWORK
I am getting memory leak . 

@hansemannn  Are you sure this solution is working fine .

**Comment by hansemannn** [comment]
I begin to think that the image is not really the problem, but the `TiBlob` is. Otherwise the issue would happen on both JSCore and TiCore.

**Pull request closed without merging**
