### PR TITLE
 [TIMOB-26463] Android: Add accessibility properties to MenuItem

### PR DESCRIPTION
**Pull request by drauggres**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26463

Add accessibilityHint, accessibilityLabel and accessibilityValue properties to MenuItem.

### CODE REVIEW

**Comment by drauggres** [comment]
Confilcts resolved. Commits squashed and rebased on master.

About "needs tests" label: we can't create unit tests to check this feature. For proper testing we need UI tests (and smth. like appium). Same for #10399.

**Comment by drauggres** [comment]
- rebased on `master`
- fixed `since` version in documentation
```javascript
var tabGroup = Ti.UI.createTabGroup();
tabGroup.addTab(createTab("Tab 1", "I am Window 1", "assets/images/tab1.png"));
tabGroup.addTab(createTab("Tab 2", "I am Window 2", "assets/images/tab2.png"));

tabGroup.open();

function createTab(title, message, icon) {
    var win = Ti.UI.createWindow({
        title: title,
        backgroundColor: '#fff'
    });
    var label = Ti.UI.createLabel({
        text: message,
        color: "#333",
        font: {
            fontSize: 20
        }
    });
    win.add(label);
    return Ti.UI.createTab({
        title: title,
        icon: icon,
        window: win
    });
}

tabGroup.addEventListener("open", function() {
    var activity = this.getActivity();
    activity.onCreateOptionsMenu = function(e) {
        var menuItem = e.menu.add({
            title : "Add Task",
            accessibilityHint: 'Hint.',
            accessibilityLabel: 'label,',
            accessibilityValue: 'VALUE;',
            showAsAction : Ti.Android.SHOW_AS_ACTION_ALWAYS,
            icon : "add_icon.png"
        });
        menuItem.addEventListener("click", function(e) {
            //
        });
    };
    activity.invalidateOptionsMenu();
});
```
timob-26463

**Comment by drauggres** [comment]
This should be rewritten In accordance with https://github.com/appcelerator/titanium_mobile/pull/10978

**Comment by sgtcoolguy** [comment]
cc @garymathews What do we need to do to get this PR updated and merged?

**Comment by garymathews** [comment]
Closing, succeeded by https://github.com/appcelerator/titanium_mobile/pull/10978

**Comment by drauggres** [comment]
> Closing, succeeded by #10978

I think there was some kind of mistake.
#10978 does not provide support for a11y properties in MenuItem.
And its predecessor (#10399) was already closed.

**Pull request closed without merging**
