### PR TITLE
fix(android): fixes background color animation with borders (8_3_X)

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27237

**Description:**
Backport of: https://github.com/appcelerator/titanium_mobile/pull/11053

### CODE REVIEW

**Comment by keerthi1032** [comment]
FR passed. Background color animation works as expected on labels.

Test Environment:
Operating System
Name = Mac OS X
Version = 10.14.5
Architecture = 64bit
Node.js
Node.js Version = 10.16.0
npm Version = 6.9.0
Titanium CLI
CLI Version = 5.2.1
Titanium SDK
SDK Version = local sdk 8.3.0.v20190819073617
Device =Samsungs s5 android 6,oneplus 5t andoird 9
Emulator = Pixel xl andorid 9. nexus 6p android 6
Studio -5.1.3.201907112159
CLI -7.1.1-master 2

**Comment by keerthi1032** [comment]
unit tests are failing .not able to merge PR.

**Comment by keerthi1032** [comment]
unit tests are failing .not able to merge PR.

**Comment by sgtcoolguy** [comment]
Closing as #11053 is sufficient to land for 8.3.0 now that master is the branch targeting that release.

**Pull request closed without merging**
