### PR TITLE
[TIMOB-23741] Utilize WindowsOnly folder when generating docs

### PR DESCRIPTION
**Pull request by garymathews**
- Also utilize the [WindowsOnly](https://github.com/appcelerator/titanium_mobile_windows/tree/master/apidoc/WindowsOnly) folder when generating the parity report and documentation

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23741)

### CODE REVIEW

**Comment by hansemannn** [comment]
LGTM, approved!

**Comment by hansemannn** [comment]
@jawa9000 do we need a 5_4_X backport for this in order to make the build-script catch it for the 5.4.0 release? I think it's always using master.

**Comment by cheekiatng** [comment]
I think yes.

**Comment by garymathews** [comment]
@jawa9000 @cheekiatng In `5_4_X` there's no `.js` files in the build folder? https://github.com/appcelerator/titanium_mobile/pull/8071 would also need backporting to `5_4_X`

**Pull request merged**
