### PR TITLE
fix: handle x/y position for touch in dragstart/dragend events on iOS

### PR DESCRIPTION
**Pull request by deckameron**
```js
var win = Ti.UI.createWindow();

var scrollView = Ti.UI.createScrollView({
  showVerticalScrollIndicator: true,
  showHorizontalScrollIndicator: true,
  height: '80%',
  width: '80%'
});
var view = Ti.UI.createView({
  backgroundColor:'#336699',
  borderRadius: 10,
  top: 10,
  height: 2000,
  width: 1000
});
scrollView.add(view);
scrollView.addEventListener("dragstart", function(e){
	console.log(e.x, e.y);
})
scrollView.addEventListener("dragend", function(e){
	console.log(e.x, e.y);
})
win.add(scrollView);
win.open();
 ```

The Android version is this:
https://github.com/tidev/titanium-sdk/pull/14102

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi @deckameron! Thanks for your PR! Can you rename "drag_dict" to "event" or "dict" for better consistency please? We usually don't use snake_case in the code :-) That'd be great! And we need the CLA signed once, you can learn more about it [here](https://titaniumsdk.com/contribute.html). tldr: Contact @joshualambert via TiSlack

**Comment by m1ga** [comment]
you can use https://tidev.io/contribute to automatically sign the CLA

**Comment by hansemannn** [comment]
Thx! I just updated the page

**Comment by deckameron** [comment]
Thanks guys! 
I just signed the CLA and pushed the update you requested. :-)

**Comment by hansemannn** [comment]
Awesome, thank you! Great improvement!

**Comment by m1ga** [comment]
@hansemannn can we merge the Android part of it too: https://github.com/tidev/titanium-sdk/pull/14102 it has the docs for this

**Pull request merged**
