### PR TITLE
[TIMOB-19721] Android: HTTPClient 401 exception

### PR DESCRIPTION
**Pull request by ashcoding**
Fix for HTTPClient throwing exception for a 401 unauthorized error due
to it requesting Username and Password via Authenticator which were
null.

### CODE REVIEW

**Comment by ashcoding** [comment]
Test code App.js:
```
var xhr = Titanium.Network.createHTTPClient({
        timeout : 30000
    });

    xhr.onload = function (response) {
        Ti.API.info("Success");
    };

    xhr.onerror = function (response) {
    	// See http://docs.appcelerator.com/platform/latest/#!/api/Titanium.Network.HTTPClient-property-onerror
    	// http://docs.appcelerator.com/platform/latest/#!/api/FailureResponse
        Ti.API.info("Error");
        Ti.API.info("Response error: " + response.error);
        Ti.API.info("Response success: " + response.success);
        Ti.API.info("Response code: " + response.code);
    };

    xhr.open('GET', 'https://bbms.blackbaud.com/MobilePayWebMethods/MobilePayService.ashx?action=AUTHENTICATE');
    xhr.setRequestHeader('Content-Type', 'application/json');
    xhr.setRequestHeader('Authorization', 'Basic Q0hTOVRPTVNDSDAxXFRvbUJCTVM6dGVzdA==');
    xhr.send();
```

**Comment by ashcoding** [comment]
Jira: https://jira.appcelerator.org/browse/TIMOB-19721

See ticket for test case.

**Comment by hieupham007** [comment]
I'm still seeing a TiHttpClient error: 10-21 16:27:26.117: E/TiHTTPClient(4231): (TiHttpClient-1) [3279,3279] HTTP Error (java.io.IOException): 401 : Unauthorized
10-21 16:27:26.117: E/TiHTTPClient(4231): java.io.IOException: 401 : Unauthorized
10-21 16:27:26.117: E/TiHTTPClient(4231): 	at ti.modules.titanium.network.TiHTTPClient$ClientRunnable.run(TiHTTPClient.java:1216)
10-21 16:27:26.117: E/TiHTTPClient(4231): 	at java.lang.Thread.run(Thread.java:856)

Is this expected?

**Comment by ashcoding** [comment]
That's expected. Also, you should be able to get that on the onError function/listener. Are you able to get it on onerror as well?

**Comment by hieupham007** [comment]
Yea

**Comment by hieupham007** [comment]
Code reviewed and functionally tested. Request **accepted**

**Pull request merged**
