### PR TITLE
fix(ios): delay js object creation to prevent accidental GC (8_0_X)

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26852

8_0_X backport of #10771

### CODE REVIEW

**Comment by mukherjee2** [comment]
@vijaysingh-axway based on the last comment in the JIRA ticket, should this be moved to "Reopen" in JIRA?

**Comment by vijaysingh-axway** [comment]
@mukherjee2 This ticket is not closed yet. I have seen that @janvennemann  has push few commits in  #10771 (which might fix the issue) which need to be back ported here. @janvennemann  Can we mark ticket 'In Progress' as you are still working on this or it is done?

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Review by ssjsamir — APPROVED** [review]
FR Passed, a reduction in crashes can be seen (e.g. against customer applications).

**Test environment** 
```
iPhone 6S plus (12.2 Sim)
APPC CLI: 7.0.11-1
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 8.9.1
Xcode 10.2.1
```

**Pull request merged**
