### PR TITLE
[TIMOB-17595] iOS: The app fails to install on iOS device after a second iOS device is also plugged in

### PR DESCRIPTION
**Pull request by FokkeZB**
**NOTE:** This is not a fix but an improvement of the error message

https://jira.appcelerator.org/browse/TIMOB-17595

### CODE REVIEW

**Comment by hansemannn** [comment]
I think @cb1kenobi is already working on a fix on the CLI side to make this message obsolet.

**Comment by FokkeZB** [comment]
He asked me for a PR (see JIRA) but a full fix is always better ;)

**Comment by hansemannn** [comment]
Great! I would prefer checking against the error code (0xe800007f) rather then the else-case for this. But Chris will review I think.

**Comment by cb1kenobi** [comment]
I'm fine with the messaging. If we don't handle a specific error code, then we have no idea what's up and the only thing we can recommend is to reconnect and try again.

**APPROVED**

@FokkeZB do you have a 5_0_X backport?

**Comment by FokkeZB** [comment]
@cb1kenobi I have now:
https://github.com/appcelerator/titanium_mobile/pull/7143

**Pull request merged**
