### PR TITLE
[TIMOB-17546] ScrollableView paging controls same as in iOS

### PR DESCRIPTION
**Pull request by drauggres**
JIRA: https://jira.appcelerator.org/browse/TIMOB-17546

Probably #10161 should go directly into major release without transitional period.
I've changed default value of `useLegacyControl` to `false`.

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

`IOS` & `Android` scrollableview's paging control now appear to be in parity.

Studio Ver:     5.1.1.201809051655
SDK Ver:        local build
OS Ver:         10.13.5
Xcode Ver:      Xcode 9.4.1
Appc NPM:       4.2.13
Appc CLI:       7.0.6
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.2
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Nexus 6P (Android 8.1.0)
Emulator:       ⇨ Android 4.1.2

**Comment by jquick-axway** [comment]
We need to make sure we can still use a `ScrollableView` as a custom tab group as shown here...
https://jira.appcelerator.org/browse/TIMOB-25535?focusedCommentId=436105&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-436105

That is, set "scrollingEnabled" and "showPagingControl" to `false` so that it can be used to show different UI content. This allows devs to to create their own custom `TabGroup` like layout that they can set up any way that they please. Versus our current `TabGroup` is not as customizable for the sake of keeping it simple.

**Comment by lokeshchdhry** [comment]
@jquick-axway , I tried the code you mentioned above with SDK having this parity fix & I just see the splash screen & no window. Runs fine with out the parity fix.

**Comment by drauggres** [comment]
I'll look into this.

**Comment by lokeshchdhry** [comment]
The build fails with :
```
[javac] /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10316-CNCTKUUPOCDPPENTPG7DBNNEC3RL3N5SLOM2J2EOA3VMTAFCTHIQ/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiArrowPagingControl.java:99: error: cannot find symbol

[javac] 		scrollableView.getContainer().addView(

    [javac] 		              ^

    [javac]   symbol:   method getContainer()

    [javac]   location: variable scrollableView of type TiUIScrollableView

[javac] /Users/build/jenkins/workspace/dk_titanium_mobile_PR-10316-CNCTKUUPOCDPPENTPG7DBNNEC3RL3N5SLOM2J2EOA3VMTAFCTHIQ/android/modules/ui/src/java/ti/modules/titanium/ui/widget/TiDotPagingControl.java:46: error: cannot find symbol

[javac] 		scrollableView.getContainer().addView(mPagerIndicator, params);

    [javac] 		              ^

    [javac]   symbol:   method getContainer()

    [javac]   location: variable scrollableView of type TiUIScrollableView

[javac] Note: Some input files use or override a deprecated API.

[javac] Note: Recompile with -Xlint:deprecation for details.

    [javac] Note: Some input files use unchecked or unsafe operations.

[javac] Note: Recompile with -Xlint:unchecked for details.

[javac] 2 errors

BUILD FAILED
```

**Comment by drauggres** [comment]
Couple of commits are missing after squash. @garymathews

**Comment by lokeshchdhry** [comment]
FR Passed.

`ScrollableView` can be used as a custom `tabgroup`.

Studio Ver:     5.1.1.201809051655
SDK Ver:        8.0.0 local build
OS Ver:         10.13.5
Xcode Ver:      Xcode 9.4.1
Appc NPM:       4.2.13
Appc CLI:       7.0.6
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.2
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_161
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Pixel (Android 9)
Emulator:       ⇨ Android 4.1.2

**Comment by lokeshchdhry** [comment]
Waiting for CR.

**Comment by hansemannn** [comment]
+1 for this PR. We need the paging control as well.

**Comment by drauggres** [comment]
I've restored original commits and rebased them on top of `master` (no changes in code).
**Reminder**: this PR includes breaking changes.

P.S. Also it fixes some broken features (see tests update).

**Pull request closed without merging**
