### PR TITLE
Fix deprecation links

### PR DESCRIPTION
**Pull request by FokkeZB**
JIRA: https://jira.appcelerator.org/browse/AC-3476

### CODE REVIEW

**Comment by hansemannn** [comment]
We need the links. https://github.com/appcelerator/titanium_mobile/pull/7917/files fixes the links like it's done currently. On long-term, we need to adjust the generator to compile `[name](link)` correctly. @AngelkPetkov please check if you cover all links specified here in your PR.

**Comment by FokkeZB** [comment]
The way I fixed it will generate links because it recognizes it as API.

**Comment by hansemannn** [comment]
Did you test the generated html? If that works, please check if you have covered all links Angel added and we merge yours. Thanks! 🚀

**Comment by FokkeZB** [comment]
See http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.iPhone.NavigationGroup where the link works but displays the `< .. >` from the source at https://github.com/appcelerator/titanium_mobile/blob/master/apidoc/Titanium/UI/iPhone/NavigationGroup.yml#L7.

This is how JSDuck works, just mention the API and it wil link it.

**Comment by hansemannn** [comment]
Ok great. So let's write a regex to index all deprecated API's and their `notes` key to fix possibly broken links. @AngelkPetkov or @FokkeZB anyone interested?

**Comment by FokkeZB** [comment]
And/or fix the tooling. As [jsduck_generator.py](https://github.com/appcelerator/titanium_mobile/blob/master/apidoc/generators/jsduck_generator.py#L204) does run `deprecated:notes` through `markdown_to_html`.

**Comment by jawa9000** [comment]
Do we know where to find an alternative image to this one: http://img.skitch.com/20100406-rwe44533tkd94fdnbqqudxynpe.png on http://docs.appcelerator.com/platform/latest/#!/api/Titanium.UI.iPhone.NavigationGroup

We need to stop using EverNote (Skitch) and only reference images from our wiki.

**Comment by FokkeZB** [comment]
I have no idea. I think only Ben used Skitch for images?

You could just create a NavigationGroup and screenshot it?

**Comment by hansemannn** [comment]
Where are we here? If that one image is the only thing preventing us from merging this, anybody can make one quickly, let me know if you need help / example code. This PR should focus on the deprecation links.

**Comment by hansemannn** [comment]
Approved for now, better than broken links. Please keep an eye on possible API's that might cause problems in the future.

**Pull request merged**
