### PR TITLE
[TIMOB-3887] Android: Fix Ti.UI.ImageView autorotation property

### PR DESCRIPTION
**Pull request by garymathews**
- When `autorotate` is defined, images should orient based on `ExifInterface`
- When `saveToPhotoGallery` is defined, save images into a public folder so they are visible from the Gallery (I noticed this on a Samsung S7 device running Android 6.0.1)

##### TEST CASE
```XML
<uses-permission android:name="android.permission.READ_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />
<uses-permission android:name="android.permission.CAMERA" />
<uses-feature android:name="android.hardware.camera" />
<uses-feature android:name="android.hardware.camera.autofocus" />
```
```JS
var win = Titanium.UI.createWindow({title: 'TIMOB-3887', backgroundColor: 'gray', layout: 'vertical'}),
    btn = Ti.UI.createButton({title: 'TAKE PICTURE', width: '100%', height: '40dp'}),
    iv = Ti.UI.createImageView({autorotate: true, width: Ti.UI.FILL, height: Ti.UI.FILL});

function takePicture() {
    Titanium.Media.showCamera({
        success: function(e) {
            iv.image = e.media;
            Ti.Media.hideCamera();
        },
        cancel: function() {
            Ti.API.info('canceled');
        },
        error: function(e) {
            Ti.API.info('error: ' + JSON.stringify(e, null, ' '))
        },
        saveToPhotoGallery: true,
        mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO]
    });
}

btn.addEventListener('click', function(e) {
    var permissions = ['android.permission.CAMERA',
                       'android.permission.WRITE_EXTERNAL_STORAGE',
                       'android.permission.READ_EXTERNAL_STORAGE'];
    for (var permission of permissions) {
        if (!Ti.Android.hasPermission(permission)) {
            Ti.Android.requestPermissions(permissions, function(e) {
                if (e.success) {
                    takePicture();
                }
            });
            return;
        }
    }
    takePicture();
});

win.add(btn);
win.add(iv);
win.open();
```
- Image should display with the same orientation the picture was taken
- Image should display in the Gallery with the same orientation the picture was taken

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-3887)

### CODE REVIEW

**Review by jquick-axway — CHANGES_REQUESTED** [review]
Your code changes look good. It just doesn't handle image mirroring that you'll get from a front-facing camera.

I recommend that you make the following changes to TiImageHelper.getOrientation() method...
```java
switch (exifOrientation) {
	case ExifInterface.ORIENTATION_ROTATE_270:
	case ExifInterface.ORIENTATION_TRANSVERSE:		// Rotated and mirrored.
		orientation = 270;
		break;
	case ExifInterface.ORIENTATION_ROTATE_180:
	case ExifInterface.ORIENTATION_FLIP_VERTICAL:
		orientation = 180;
		break;
	case ExifInterface.ORIENTATION_ROTATE_90:
	case ExifInterface.ORIENTATION_TRANSPOSE:		// Rotated and mirrored.
		orientation = 90;
		break;
}
```

The above won't flip the mirrored image, but it will make sure that it returns a rotation so that mirrored images will not appear upside-down.

Try testing the above with the following images which exercises all of the possible EXIF orientation settings. (I've already done so, but might be good for your info.)
```javascript
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_1.jpg";  // Rotate 0
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_2.jpg";  // Flip Horizontal
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_3.jpg";  // Rotate 180
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_4.jpg";  // Flip Vertical
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_5.jpg";  // Transpose
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_6.jpg";  // Rotate 90
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_7.jpg";  // Transverse
"https://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_8.jpg";  // Rotate 270
```

**Comment by garymathews** [comment]
@jquick-axway Updated PR 👍

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

1. Checked by taking photo with rear camera in portrait mode, landscape left & landscape right. Image obtained in the imageview & the photogallery had the orientation of the picture taken.
2.  Checked by taking photo with front camera in portrait mode, landscape left & landscape right. Image obtained in the imageview & the photogallery had the orientation of the picture taken & was properly mirrored.

Studio Ver:     4.9.0.201705160715
SDK Ver:        6.2.0.v20170516082025
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.2
Appc NPM:       4.2.9
Appc CLI:       6.2.1
Ti CLI Ver:     5.0.13
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        samsung SM-G920T --- Android 6.0.1, Nexus 6 --- Android 6.0.1

**Pull request merged**
