### PR TITLE
[TIMOB-26239] Android: Fix KrollProxy and HTTPClientProxy memory leak

### PR DESCRIPTION
**Pull request by garymathews**
- Release KrollProxy objects and HTTPClient

###### TEST CASE
- Project in JIRA Ticket

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-23269)

### CODE REVIEW

**Comment by fmerzadyan** [comment]
CR and FT PASS

**Comment by lokeshchdhry** [comment]
@garymathews , I saw a crash after like 40 - 45 mi of app use.

```
W/dalvikvm(23382): threadid=38: thread exiting with uncaught exception (group=0x4173fda0)
E/TiApplication(23382): (pool-21-thread-2) [2887,1400907] Sending event: exception on thread: pool-21-thread-2 msg:java.lang.OutOfMemoryError; Titanium 6.1.0,2017/03/08 10:44,undefined
E/TiApplication(23382): java.lang.OutOfMemoryError
E/TiApplication(23382): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/TiApplication(23382): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:709)
E/TiApplication(23382): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:685)
E/TiApplication(23382): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723)
E/TiApplication(23382): 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:388)
E/TiApplication(23382): 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:300)
E/TiApplication(23382): 	at org.appcelerator.titanium.util.TiLoadImageManager$LoadImageJob.run(TiLoadImageManager.java:128)
E/TiApplication(23382): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/TiApplication(23382): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/TiApplication(23382): 	at java.lang.Thread.run(Thread.java:841)
E/AndroidRuntime(23382): FATAL EXCEPTION: pool-21-thread-2
E/AndroidRuntime(23382): Process: com.homes.rentals, PID: 23382
E/AndroidRuntime(23382): java.lang.OutOfMemoryError
E/AndroidRuntime(23382): 	at android.graphics.BitmapFactory.nativeDecodeStream(Native Method)
E/AndroidRuntime(23382): 	at android.graphics.BitmapFactory.decodeStreamInternal(BitmapFactory.java:709)
E/AndroidRuntime(23382): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:685)
E/AndroidRuntime(23382): 	at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:723)
E/AndroidRuntime(23382): 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:388)
E/AndroidRuntime(23382): 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:300)
E/AndroidRuntime(23382): 	at org.appcelerator.titanium.util.TiLoadImageManager$LoadImageJob.run(TiLoadImageManager.java:128)
E/AndroidRuntime(23382): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
E/AndroidRuntime(23382): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
E/AndroidRuntime(23382): 	at java.lang.Thread.run(Thread.java:841)
W/ActivityManager(  719):   Force finishing activity com.homes.rentals/org.appcelerator.titanium.TiTranslucentActivity
W/ContextImpl(  719): Calling a method in the system process without a qualified user: android.app.ContextImpl.sendBroadcast:1509 com.android.server.InputMethodManagerService$4.run:2683 java.lang.Thread.run:841 <bottom of call stack> <bottom of call stack> 
I/dumpstate(29497): begin
D/dalvikvm(  719): GC_FOR_ALLOC freed 3071K, 33% free 24107K/35528K, paused 184ms, total 187ms
V/WindowOrientationListener(  719): WindowOrientationListener disabled
```

I read your comment in the ticket about duplicate annotations, I am not sure if this is fixed or not.

Device: Samsung Galaxy S3 android 4.4.2.

**Comment by kerbooo** [comment]
Hey guys, this issue is fixed or not?

**Comment by garymathews** [comment]
Merging for parity with `6_1_X` branch

**Comment by kerbooo** [comment]
@garymathews  I can't understand what does **Merging for parity with 6_1_X branch** it means fixed? Thank you in advance

**Comment by garymathews** [comment]
@kerbooo Yes, these changes are already part of `6.1.0.GA`

**Pull request merged**
