### PR TITLE
chore: disable analytics in templates

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/AC-6719

**Optional Description:**

Guess it can be removed sooner or later but disabling it already helps when creating a new project 😄

### CODE REVIEW

**Comment by m1ga** [comment]
added the JIRA ticket. Maybe it can be merged in 10.1.0 so there is one less setting to change when creating a new project 😉

**Comment by ewanharris** [comment]
@m1ga, we might look to include this in 10.1.1 or 10.2.0 as we're within 6 months or so of the EoS date.

**Comment by m1ga** [comment]
no rush! Just wanted to include the last missing details

**Comment by m1ga** [comment]
closing in favor of https://github.com/tidev/titanium_mobile/pull/13316

**Pull request closed without merging**
