### PR TITLE
feat(android): Re-added "baseURL" support to WebView.setHtml() method

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26848

**Summary:**
- Re-added `WebView.setHtml()` 2nd argument support to Android which was removed in Titanium 6.0.3.
- 2nd argument supports a "baseURL" setting needed by iframes to load resources, such as a YouTube video.
- Note that iOS already supports this 2nd argument.

---
**IFrame Test:**
1. Acquire an Android device with Internet access.
2. Build and run the below code on that Android device.
3. Tap on the YouTube iframe within the WebView.
4. Verify that the video plays successfully.

```javascript
var htmlText =
		'<!DOCTYPE html>' +
		'<html>' +
		'	<body>' +
		'		<iframe width="560" height="315" src="https://www.youtube.com/embed/dQw4w9WgXcQ" frameborder="0" allow="accelerometer; autoplay; encrypted-media; gyroscope; picture-in-picture" allowfullscreen/>' +
		'	</body>' +
		'</html>';

var window = Ti.UI.createWindow();
var webView = Ti.UI.createWebView();
Ti.API.info("@@@ webView.html: " + webView.html);
//webView.html = htmlText;
webView.setHtml(htmlText, { baseURL: "https://www.youtube.com" });
Ti.API.info("@@@ webView.html: " + webView.html);
window.add(webView);
window.open();
```

---
**Local Base URL Test:**
1. Create a Classic "Default Project" Titanium app.
2. Copy the below code to the project's "app.js".
3. Build and run on Android.
4. Verify that an Appcelerator logo appears within the `WebView`.
5. Comment out `var baseUrl` line under `// Test 1` and uncomment line under `// Test 2`.
6. Rebuild and verify that an Appcelerator logo appears within the `WebView`.
7. Comment out `var baseUrl` line under `// Test 2` and uncomment line under `// Test 3`.
8. Rebuild and verify that an Appcelerator logo appears within the `WebView`.
9. Comment out `var baseUrl` line under `// Test 3` and uncomment line under `// Test 4`.
10. Rebuild and verify that an Appcelerator logo appears within the `WebView`.

```javascript
// Test 1
var baseUrl = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory).nativePath;
// Test 2
//var baseUrl = Ti.Filesystem.applicationDataDirectory;
// Test 3
//var baseUrl = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "assets/images/").nativePath;
// Test 4
//var baseUrl = Ti.Filesystem.resourcesDirectory + "assets/images";

var sourceFile = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory, "assets/images/tab1.png");
var targetFile = Ti.Filesystem.getFile(Ti.Filesystem.applicationDataDirectory, "tab1.png");
sourceFile.copy(targetFile.nativePath);

var htmlText =
		'<!DOCTYPE html>' +
		'<html>' +
		'	<body>' +
		'		<p>Local Image File</p>' +
		'		<img src="tab1.png"/>' +
		'	</body>' +
		'</html>';

var window = Ti.UI.createWindow();
var webView = Ti.UI.createWebView();
webView.setHtml(htmlText, { baseURL: baseUrl });
window.add(webView);
window.open();
```

### CODE REVIEW

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
The unit test failure is a legit issue. I'm looking into it now.

**Comment by jquick-axway** [comment]
I've verified that this PR's newest changes successfully loads local JS files via relative paths and "file://" absolute paths. I think this PR is good to go.

**Comment by lokeshchdhry** [comment]
FR Passed.

Studio Ver:     5.1.2.201903111843
SDK Ver:        8.1.0 local build
OS Ver:         10.14
Xcode Ver:      Xcode 10.1
Appc NPM:       4.2.13
Appc CLI:       7.0.10
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.9
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Pixel (Android 9)

**Pull request merged**
