### PR TITLE
chore(android): changed minSdkVersion to 21 (Android 5.0)

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-28263

**Summary:**
- Changed min OS version supported from Android 4.4 to 5.0.
- Removed backward-compatibility code for OS versions older than 5.0.
- Note that we get multidexing for free on Android 5.0+. We no longer need Google's library for it.
- Note that we need to keep the `NestedScrollView` for `CoordinatorLayout` support.

**Test:**
1. Create a new "Classic" Titanium app from template.
2. Build for Android.
3. Go to project folder: `./build/android/app`
4. Open the "build.gradle" file.
5. Verify `minSdkVersion` is set to `21`.

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
Note that w/ appcelerator/chef-jenkins-node#8, we will now have an android-21-x86 emulator on the build nodes. We may want to consider adding in this PR forking the android tests to run on both `android-30-playstore-x86` and `android-21-x86` emulators in parallel for PRs?

**Comment by jquick-axway** [comment]
@sgtcoolguy , I modified the "Jenkins" file to also test on Android 5.0. What do you think?
https://github.com/appcelerator/titanium_mobile/pull/12316/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8

By the way, our Android 5.0 emulator does not have enough storage space to install the APK. In my opinion, main storage should be at least 3-4 GB _(I set mine to 4 GB)_. The emulator's default storage setting is never enough.

**Review by garymathews — APPROVED** [review]
CR: **PASS**

Just waiting on Jenkins emulator space issues to be resolved.

**Review by ssjsamir — APPROVED** [review]
**FR Passed** MinSDK version now shows 21 instead of 19 when following the test steps mentioned in the PR description. 

**Test Environment**
```
MacOS Big Sur: 11.1 Beta 1
Xcode: 12.2 Beta
Java Version: 1.8.0_242
Android NDK: 21.3.6528147
Node.js: 12.18.1
""NPM":"5.0.0","CLI":"8.1.1""
N3xus 5X API 29 (emulator) 
```

**Pull request merged**
