### PR TITLE
contentSize was missing since property

### PR DESCRIPTION
**Pull request by FokkeZB**
https://jira.appcelerator.org/browse/TIMOB-17247

/cc @jawa9000 @hansemannn

### CODE REVIEW

**Comment by hansemannn** [comment]
Thanks!

**Comment by FokkeZB** [comment]
@jawa9000 can you look into why the docs can't handle since at this place?

**Comment by hansemannn** [comment]
Validation works as soon as https://github.com/appcelerator/titanium_mobile/pull/7776 is merged.

**Comment by hansemannn** [comment]
Validation succeed's now, merging.

**Pull request merged**
