### PR TITLE
[TIMOB-25008] : iOS Remove deprecated Ti.UI.KEYBOARD_* constants in favor of TI.UI.KEYBOARD_TYPE_*

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-25008

### CODE REVIEW

**Review by janvennemann — APPROVED** [review]

**Comment by jquick-axway** [comment]
@vijaysingh-axway, regarding `KEYBOARD_APPEARANCE_ALERT`, you've documented it as removed but it's still in the iOS (and Android) code. Is the plan to delete this constant on all platforms too?

**Comment by janvennemann** [comment]
It was marked to be removed with 7.0.0 already so i would say we delete it.

**Comment by jquick-axway** [comment]
Okay. I've update my PR #10471 to remove the `KEYBOARD_APPEARANCE_ALERT` constant too.

**Comment by vijaysingh-axway** [comment]
> @vijaysingh-axway, regarding `KEYBOARD_APPEARANCE_ALERT`, you've documented it as removed but it's still in the iOS (and Android) code. Is the plan to delete this constant on all platforms too?

@jquick-axway  It was not intended change. So code was not removed. :) I will remove the code as well and update this PR.

**Review by jquick-axway — APPROVED** [review]

**Review by longton95 — APPROVED** [review]
**FR Passed**

`Ti.UI.KEYBOARD_*` shows undefined and the deprecated warnings are removed.

Testcase from PR #10471.

```javascript
var keyboardTypeNames = [
	"Ti.UI.KEYBOARD_APPEARANCE_ALERT",
	"Ti.UI.KEYBOARD_ASCII",
	"Ti.UI.KEYBOARD_DECIMAL_PAD",
	"Ti.UI.KEYBOARD_DEFAULT",
	"Ti.UI.KEYBOARD_EMAIL",
	"Ti.UI.KEYBOARD_NAMEPHONE_PAD",
	"Ti.UI.KEYBOARD_NUMBERS_PUNCTUATION",
	"Ti.UI.KEYBOARD_NUMBER_PAD",
	"Ti.UI.KEYBOARD_PHONE_PAD",
	"Ti.UI.KEYBOARD_WEBSEARCH",
	"Ti.UI.KEYBOARD_TWITTER",
	"Ti.UI.KEYBOARD_URL",
];
for (var index = 0; index < keyboardTypeNames.length; index++) {
	var typeName = keyboardTypeNames[index];
	Ti.API.info(typeName + ": " + eval(typeName));
}
```


**ENV**

```
iPhone 6 (12.0)
iOS simulator (12.1)
Xcode: 10.11
Appc NPM: 4.2.13
Appc CLI: 7.0.7
Ti CLI: 5.1.1
Node: 8.12.0
NPM: 6.4.1
```

**Pull request merged**
