### PR TITLE
[TIMOB-10451] Android: Ellipsis can now be applied to labels based on height.

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:** https://jira.appcelerator.org/browse/10451

**Summary:**
Android used to only apply ellipsis when a Label's "maxLines" property was set. This change allows ellipsis to also be applied when a height other than Ti.UI.SIZE has been assigned to the label, matching iOS' behavior. This is for feature parity.

Note that the "maxLines" property is still respected. Label will still not display more lines than "maxLines". If the height of the label is less than "maxLines", then the ellipsis will be applied based on height instead. This too matches iOS' behavior.

**Test Code:**

Tap the label several times to cycle through various heights.

```javascript
var window = Ti.UI.createWindow(
{
	backgroundColor: "gray",
});
var testLabel = Ti.UI.createLabel(
{
	text: "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry's standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.",
	color: "white",
	backgroundColor: "black",
	width: "80%",
//	maxLines: 3,
});
testLabel.addEventListener("click", function(e)
{
	if (!testLabel.height || (testLabel.height == Ti.UI.SIZE)) {
		testLabel.height = "5%";
	}
	else if (testLabel.height === "5%") {
		testLabel.height = "10%";
	}
	else if (testLabel.height === "10%") {
		testLabel.height = "20%";
	}
	else if (testLabel.height === "20%") {
		testLabel.height = "30%";
	}
	else if (testLabel.height === "30%") {
		testLabel.height = "90%";
	}
	else if (testLabel.height === "90%") {
		testLabel.height = "100%";
	}
	else if (testLabel.height === "100%") {
		testLabel.height = Ti.UI.FILL;
	}
	else {
		testLabel.height = Ti.UI.SIZE;
	}
	if ((Ti.Platform.name === "android") || (Ti.Platform.name === "windows")) {
		var notification = Ti.UI.createNotification(
		{
			message: !testLabel.height ? Ti.UI.SIZE : testLabel.height.toString(),
			duration: Ti.UI.NOTIFICATION_DURATION_SHORT,
		}).show();
	}
});
window.add(testLabel);
window.open();
```

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by jquick-axway** [comment]
I discovered an issue. Ellipsis are not being applied when the height is set to `Ti.UI.FILL`. I'll need to fix this.

**Comment by jquick-axway** [comment]
Fixed ellipsis support for Ti.UI.FILL.

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Review by ssjsamir — APPROVED** [review]
**FR Passed:** Was able to now see ellipsis be applied to labels based on height.

**Test Steps**
+ Downloaded the SDK Build from this PR
+ Created a new Titanium project
+ Copied the test case from description
+ Ran the application 
+ Clicked on the various label lengths and was able to see ellipsis being applied where needed. 

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Samsung Galaxy S5 (4.4.2)
Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

**Pull request merged**
