### PR TITLE
[TIMOB-24920] Android: Allow selecting different stream-types in Ti.Media.Sound

### PR DESCRIPTION
**Pull request by dbankier**
**JIRA**: https://jira.appcelerator.org/browse/TIMOB-24920

### CODE REVIEW

**Comment by hansemannn** [comment]
Hey @dbankier, I've just added the missing docs and fixed some indentation issues for the setter/getter methods. I also noticed that `setAudioStreamType` is deprecated in the native [MediaPlayer](https://developer.android.com/reference/android/media/MediaPlayer.html) API, they recommend to use the [`setAudioAttributes`](https://developer.android.com/reference/android/media/MediaPlayer.html#setAudioAttributes(android.media.AudioAttributes)) method instead. Any thoughts?

**Comment by dbankier** [comment]
`setAudioAttributes` is API 21. I think we are min-sdk 16. So I think we need to stick with `setAudioStreamType` for the moment.

**Comment by hansemannn** [comment]
Gotcha, but then we should still use the newer one for API-level 21 and above. I think we can add it for you if it takes too much time.

**Comment by dbankier** [comment]
Could you please? I'm just in the middle of a project and I'm just flicking you the SDK changes I am making for my project.

**Comment by hansemannn** [comment]
Our Android team will do during review, no worries!

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
We need a backport for this to take it into 6.2.0, I'll try to provide it asap.

**Comment by lokeshchdhry** [comment]
FR Passed.

Different media streams types are selected successfully according to value specified for the `audioType`.

```
var player = Ti.Media.createSound({
	url:"sound.wav",
	audioType: Titanium.Media.Sound.AUDIO_TYPE_ALARM // Can have values AUDIO_TYPE_SIGNALLING, AUDIO_TYPE_MEDIA, AUDIO_TYPE_NOTIFICATION, AUDIO_TYPE_RING
});

player.play();
```
Studio Ver:     4.9.1.201707200100
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.3
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.13
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ motorola XT1033 --- Android 4.4.4
                ⇨ google Pixel --- Android 7.1.1

**Pull request merged**
