### PR TITLE
fix(conditions): Change from ifdef to if due to variable always being defined

### PR DESCRIPTION
**Pull request by Sajoha**
The test for whether or not we're using iOS 13 was using an ifdef condition, but this is always
defined as either true or false in the Titanium_Prefix.pch

https://jira.appcelerator.org/browse/TIMOB-27435

### CODE REVIEW

**Review by sgtcoolguy — APPROVED** [review]
LGTM

**Comment by sgtcoolguy** [comment]
QE: Please just mark as FR passed or not and tag me and I will squash merge this once it's ready (and cherry-pick to master)

**Comment by ssekhri** [comment]
FR Passed.
Project builds successfully on 12.2 and 12.4 simulators with XCode 10.3 and iOS 12.2 and 13.0 simulators with XCode 11.
Verified on:
Mac OS: 10.14.5
SDK: 8.2.1.v20191002063548
Appc CLI: 7.1.1
JDK: 1.8.0_162
Node: 10.5.0
Studio: 5.1.4.201909061933
Xcode: 10.3, 11.0
Device: iOS simulator v12.2, 12.4, 13.0

**Comment by ssekhri** [comment]
@sgtcoolguy Kindly merge the PR and cherry-pick to master

**Comment by vijaysingh-axway** [comment]
> @sgtcoolguy Kindly merge the PR and cherry-pick to master

@ssekhri Here you go  PR #11258

**Pull request merged**
