### PR TITLE
feat(android): support WebAssembly

### PR DESCRIPTION
**Pull request by garymathews**
- Update V8 to `7.9.317.34`
  - Include support for WebAssembly

##### TEST CASE
```JS
const window = Ti.UI.createWindow({ backgroundColor: 'white' });
const label = Ti.UI.createLabel({ color: 'black' });

try {
	if (!WebAssembly) {
		throw Error('WebAssembly not supported.');
	}

	// Engine supports WebAssembly, attempt to run a module export.
	const WASM_BUFFER = new Uint8Array([0,97,115,109,1,0,0,0,1,133,128,128,128,0,1,96,0,1,127,3,130,128,128,128,0,1,0,4,132,128,128,128,0,1,112,0,0,5,131,128,128,128,0,1,0,1,6,129,128,128,128,0,0,7,145,128,128,128,0,2,6,109,101,109,111,114,121,2,0,4,109,97,105,110,0,0,10,138,128,128,128,0,1,132,128,128,128,0,0,65,42,11]);
	const WASM_MODULE = new WebAssembly.Module(WASM_BUFFER);

	const instance = new WebAssembly.Instance(WASM_MODULE).exports;
	label.text = instance.main();
} catch (e) {
	label.color = 'red';
	label.text = e.message;
}

window.add(label);
window.open();
```
- Window should display `42`.

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27887)

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
Something is definitely up here - the Android app is crashing. I logged in manually to re-try and saw this in `adb logcat`:
```
07:03:21.022  5581  5581 F libc    : Fatal signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xdfee4a94 in tid 5581 (testApp.testing), pid 5581 (testApp.testing)
05-28 07:03:21.040  5615  5615 I crash_dump32: obtaining output fd from tombstoned, type: kDebuggerdTombstone
05-28 07:03:21.042  1717  1717 I /system/bin/tombstoned: received crash request for pid 5581
05-28 07:03:21.044  5615  5615 I crash_dump32: performing dump of process 5581 (target tid = 5581)
05-28 07:03:21.048  5615  5615 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
05-28 07:03:21.048  5615  5615 F DEBUG   : Build fingerprint: 'google/sdk_gphone_x86_arm/generic_x86_arm:9/PSR1.180720.117/5875966:user/release-keys'
05-28 07:03:21.048  5615  5615 F DEBUG   : Revision: '0'
05-28 07:03:21.048  5615  5615 F DEBUG   : ABI: 'x86'
05-28 07:03:21.048  5615  5615 F DEBUG   : pid: 5581, tid: 5581, name: testApp.testing  >>> com.appcelerator.testApp.testing <<<
05-28 07:03:21.048  5615  5615 F DEBUG   : signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0xdfee4a94
05-28 07:03:21.048  5615  5615 F DEBUG   :     eax 00000000  ebx d5a3b5b0  ecx dfee4a94  edx 00000000
05-28 07:03:21.048  5615  5615 F DEBUG   :     edi fff9130c  esi fff90830
05-28 07:03:21.048  5615  5615 F DEBUG   :     ebp fff8fa28  esp fff8f990  eip d4e408d1
05-28 07:03:21.051  5615  5615 F DEBUG   : 
05-28 07:03:21.051  5615  5615 F DEBUG   : backtrace:
05-28 07:03:21.052  5615  5615 F DEBUG   :     #00 pc 007ab8d1  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::StandardFrame::IterateCompiledFrame(v8::internal::RootVisitor*) const+433)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #01 pc 007abbce  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::OptimizedFrame::Iterate(v8::internal::RootVisitor*) const+30)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #02 pc 007b3d59  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Isolate::Iterate(v8::internal::RootVisitor*, v8::internal::ThreadLocalTop*)+233)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #03 pc 007b3de6  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Isolate::Iterate(v8::internal::RootVisitor*)+38)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #04 pc 0081127e  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::IterateStrongRoots(v8::internal::RootVisitor*, v8::internal::VisitMode)+126)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #05 pc 00811147  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::IterateRoots(v8::internal::RootVisitor*, v8::internal::VisitMode)+39)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #06 pc 00873971  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::ScavengerCollector::CollectGarbage()+2577)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #07 pc 0080b7cf  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::Scavenge()+543)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #08 pc 00808c60  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::PerformGarbageCollection(v8::internal::GarbageCollector, v8::GCCallbackFlags)+1312)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #09 pc 008070c6  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::CollectGarbage(v8::internal::AllocationSpace, v8::internal::GarbageCollectionReason, v8::GCCallbackFlags)+1046)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #10 pc 00813051  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::AllocateRawWithLightRetrySlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)+81)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #11 pc 00813102  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Heap::AllocateRawWithRetryOrFailSlowPath(int, v8::internal::AllocationType, v8::internal::AllocationOrigin, v8::internal::AllocationAlignment)+50)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #12 pc 007e9ea2  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Factory::NewDescriptorArray(int, int)+98)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #13 pc 009da832  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::DescriptorArray::CopyUpToAddAttributes(v8::internal::Isolate*, v8::internal::Handle<v8::internal::DescriptorArray>, int, v8::internal::PropertyAttributes, int)+66)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #14 pc 009da7d8  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::DescriptorArray::CopyUpTo(v8::internal::Isolate*, v8::internal::Handle<v8::internal::DescriptorArray>, int, int)+56)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #15 pc 009b41b7  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Map::EnsureDescriptorSlack(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, int)+167)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #16 pc 009b680d  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Map::ShareDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::DescriptorArray>, v8::internal::Descriptor*)+301)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #17 pc 009b1b82  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Map::CopyAddDescriptor(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Descriptor*, v8::internal::TransitionFlag)+354)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #18 pc 009b1958  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Map::CopyWithField(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::FieldType>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::Representation, v8::internal::TransitionFlag)+504)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #19 pc 009b86cb  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Map::TransitionToDataProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Map>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::PropertyConstness, v8::internal::StoreOrigin)+923)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #20 pc 009ab59d  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::LookupIterator::PrepareTransitionToDataProperty(v8::internal::Handle<v8::internal::JSReceiver>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::internal::StoreOrigin)+221)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #21 pc 009d6049  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin)+1113)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #22 pc 009d4ef4  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Object::SetProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>)+260)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #23 pc 00af7b6d  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Runtime::SetObjectProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::Handle<v8::internal::Object>, v8::internal::StoreOrigin, v8::Maybe<v8::internal::ShouldThrow>)+301)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #24 pc 00afb1b9  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so (v8::internal::Runtime_SetKeyedProperty(int, unsigned int*, v8::internal::Isolate*)+137)
05-28 07:03:21.052  5615  5615 F DEBUG   :     #25 pc 0100db56  /data/app/com.appcelerator.testApp.testing-nKS6V0xG3KFHgkkalVblFQ==/lib/x86/libkroll-v8.so
05-28 07:03:21.200  1717  1717 E /system/bin/tombstoned: Tombstone written to: /data/tombstones/tombstone_04
```

**Comment by jquick-axway** [comment]
I've never used WebAssemblies before, but I can see references to `wasm32` and `wasm64` on the Internet. Perhaps the binary the test example use is 64-bit? @sgtcoolguy, I can see you're running on an x86 emulator. Perhaps try testing it on an 64-bit device?

If this is the case, it sounds like we should test with a wasm32 binary instead which I would expect to work on 64-bit machines too.

**Comment by sgtcoolguy** [comment]
I double-checked. The test sample above works fine on x86 or x86-64 Android emulators and shows 42, as expected. But if you run the unit test suite it will crash the app. I've been trying to narrow down under what circumstances. Generally it'll crash if you try to run any other tests after the WASM add-on test is loaded. The crashes are generally around GC. But I can't seem to find any common thread. If I skip the WASM tests, it seems to still eventually crash. If they never load, then I think the suite will run fine.

I'll attach a bunch of them.

[crash1.txt](https://github.com/appcelerator/titanium_mobile/files/4725844/crash1.txt)
[crash2.txt](https://github.com/appcelerator/titanium_mobile/files/4725845/crash2.txt)
[crash3.txt](https://github.com/appcelerator/titanium_mobile/files/4725846/crash3.txt)
[crash4.txt](https://github.com/appcelerator/titanium_mobile/files/4725847/crash4.txt)
[crash5.txt](https://github.com/appcelerator/titanium_mobile/files/4725848/crash5.txt)

**Comment by garymathews** [comment]
@sgtcoolguy Yeah, I noticed there's some unreliability here. I'm thinking V8 79 doesn't have a stable WebAssembly implementation, so I'm updating to V8 83 which may fix this issue and also includes other nice performance features.

**Comment by sgtcoolguy** [comment]
I decided to skim the V8 blog to see if I could get any hints. I saw this: https://v8.dev/blog/v8-release-83#faster-arraybuffer-tracking-in-the-garbage-collector

It's possible our ArrayBuffer allocator stuff is bad/outdated. This here:
https://github.com/appcelerator/titanium_mobile/blob/master/android/runtime/v8/src/native/V8Runtime.cpp#L48-L53
and https://github.com/appcelerator/titanium_mobile/blob/master/android/runtime/v8/src/native/V8Runtime.cpp#L228-L230

Looks like V8 provides a default implementation again? https://github.com/nodejs/node/blob/2bdeb88c27b4d8de3a8f6b7a438cf0bcb88fa927/deps/v8/test/fuzzer/fuzzer-support.cc#L26-L28

Node has it's own implementation primarily for optimizations around their Buffer type: https://github.com/nodejs/node/blob/eaa16cd477f671804a46b57bfdfe918a02334f4d/src/node.h#L256-L281

I also see they changed the Allocator API to add a Reallocate method in 8.2 time frame? https://github.com/v8/v8/commit/b5c917ee80cbf33b18a96bfcf67a4c598ea85722

**Pull request closed without merging**
