### PR TITLE
feat(ios): redesigned error view

### PR DESCRIPTION
**Pull request by hansemannn**
We had to revert the previously merged PR, because it errored with the following message:
```
No 'swiftinterface' files found within '/titanium_mobile/iphone/TitaniumKit/build/simulator.xcarchive/Products/Library/Frameworks/TitaniumKit.framework/Modules/TitaniumKit.swiftmodule'.
Error: TitaniumKit build exited with code 70
    at ChildProcess.<anonymous> (/titanium_mobile/build/lib/ios.js:70:18)
```
Once that is fixed (cc @janvennemann), we can merge it again. It seems like it's related to the SwiftUI view that needs to properly generate a .swiftinterface file.

### CODE REVIEW

**Comment by hansemannn** [comment]
@janvennemann Unfortunately this does not compile during the SDK packaging. The displayed error is:
```
Command MergeSwiftModule failed with a nonzero exit code

SwiftCodeGeneration normal arm64 (in target 'TitaniumKit' from project 'TitaniumKit')
    cd /Users/runner/work/titanium_mobile/titanium_mobile/iphone/TitaniumKit
    /Applications/Xcode_13.2.1.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swift-frontend -frontend -c -primary-file /Users/runner/Library/Developer/Xcode/DerivedData/TitaniumKit-drxvhqcdhmjmqcehgqxcxsvstwxu/Build/Intermediates.noindex/ArchiveIntermediates/TitaniumKit/IntermediateBuildFilesPath/TitaniumKit.build/Release-iphoneos/TitaniumKit.build/Objects-normal/arm64/ErrorView.bc -embed-bitcode -target arm64-apple-ios12.0 -Xllvm -aarch64-use-tbi -O -disable-llvm-optzns -module-name TitaniumKit -o /Users/runner/Library/Developer/Xcode/DerivedData/TitaniumKit-drxvhqcdhmjmqcehgqxcxsvstwxu/Build/Intermediates.noindex/ArchiveIntermediates/TitaniumKit/IntermediateBuildFilesPath/TitaniumKit.build/Release-iphoneos/TitaniumKit.build/Objects-normal/arm64/ErrorView.o

error: merge-module command failed with exit code 1 (use -v to see invocation)
```
It would be great if you could check that error!

**Comment by janvennemann** [comment]
@hansemannn I'll take a look!

**Comment by hansemannn** [comment]
@janvennemann All green now. If you're okay with my latest changes, we can merge this.

**Comment by cb1kenobi** [comment]
Whoa, neat! Can't wait to see it!

**Pull request merged**
