### PR TITLE
[TIMOB-24290] Removed Resources/app.js file ref from xcode project.

### PR DESCRIPTION
**Pull request by cb1kenobi**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24290

### CODE REVIEW

**Comment by cb1kenobi** [comment]
**APPROVED**

**Comment by hansemannn** [comment]
Added it there to make it easier to edit the app.js. Did I oversee something?

**Comment by cb1kenobi** [comment]
Yep. You can't do that. The file doesn't exist when building a Titanium app. There's no file for xcode to copy and the build fails.

**Comment by hansemannn** [comment]
Good to know, thx!

**Pull request merged**
