### PR TITLE
[TIMOB-26425] Always use thread-safe access to timers array

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26425

**Optional Description:**
Timers are always started in their own thread. Locking should also be done when running on main thread to make the access to the timers array thread-safe.

### CODE REVIEW

**Review by vijaysingh-axway — CHANGES_REQUESTED** [review]
@janvennemann  Your logic looks good to me. You need to adjust this PR a bit e.g declaration and definition of variable timerLock should be out of TI_USE_KROLL_THREAD macro.
Can you create PR for 7_4_X so we can ask reporter to test? Thanks!

**Comment by janvennemann** [comment]
Addressed the missing declarations and moved them out of the kroll macro.

**Comment by sgtcoolguy** [comment]
[mocha_2018-09-27-000653_morimoto-macos.crash.txt](https://github.com/appcelerator/titanium_mobile/files/2438902/mocha_2018-09-27-000653_morimoto-macos.crash.txt)

**Comment by janvennemann** [comment]
@sgtcoolguy Updated the PR and the Jenkins build is looking good now.

**Pull request merged**
