### PR TITLE
[TIMOB-20229] Android: WebView and Cookie fix

### PR DESCRIPTION
**Pull request by ashcoding**
Jira: https://jira.appcelerator.org/browse/TIMOB-20229

Test code:-

``` javascript
var win = Ti.UI.createWindow({
    layout : 'vertical'
});
var url = 'http://www.appcelerator.com/'; //Or any html file
var reload = Ti.UI.createButton({
    title : 'reload',
    height : 50,
    width : 100,
    top : 5,
});

reload.addEventListener('click', function() {
    web.url = url;
});

win.add(reload);

var web = Ti.UI.createWebView({
    url : url,
    width : Ti.UI.FILL,
    top : 100,
    height : Ti.UI.FILL,

});

win.add(web);
var i = 1;

web.addEventListener('load', function(e) {

    var d = new Date();
    d.setTime(d.getTime() + (2 * 24 * 60 * 60 * 1000));

    var cookie = Ti.Network.createCookie({
        name : 'helloWorld',
        domain : url,
        value : "testCookie",
        expiryDate : d,

    });

    Ti.Network.addSystemCookie(cookie, web);
    Ti.API.info("createCookie -> " + JSON.stringify(cookie));

    var cookies = Ti.Network.getSystemCookies(url,null,null);

    if(cookies != null) {
        Ti.API.info("# of cookies -> " + cookies.length);
        for ( i = 0; i <= cookies.length - 1; i++) {
            Ti.API.info("cookie -> " + cookies[i].name + " - " + cookies[i].value);
        }
    }

});

win.open();
```

### CODE REVIEW

**Comment by ashcoding** [comment]
The domain seems to be the one causing the code not to work in the cookieString. The domain is already used to set the cookieString, thus, there is no need to use it twice.

**Comment by hieupham007** [comment]
Please merge with master

**Comment by ashcoding** [comment]
Master merged.

**Comment by hieupham007** [comment]
Code reviewed and funtionally tested. Looks good

**Pull request merged**
