### PR TITLE
[TIMOB-24903] Android: Allow Ti.UI.View.touchFeedback with border

### PR DESCRIPTION
**Pull request by garymathews**
- Allow `Titanium.UI.View.touchFeedback` to function when a border has been defined

###### TEST CASE
```JS
var win = Ti.UI.createWindow({backgroundColor: '#bebdda'}),
    v = Ti.UI.createView({
        width: 140,
        height: 140,
        backgroundColor: '#becedf',
        touchFeedback: true,
        touchFeedbackColor: '#7d93ab',
        elevation: 20,
        borderColor: '#7d93ab',
        borderWidth: 5,
        borderRadius: 70
    });
win.add(v);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24903)

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

`touchfeedback` works as expected to show the ripple effect.
1. Checked with `borderRadius` & without.
2. Checked with various values of `borderRadius`.

Studio Ver:     4.9.0.201705302345
SDK Ver:        6.2.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel --- Android 7.1.1
                ⇨ google Nexus 5 --- Android 6.0.1

**Comment by lokeshchdhry** [comment]
@garymathews , On Android 5.1.1 emulator I see a crash:
```
[ERROR] :  TiApplication: (main) [167,167] Sending event: exception on thread: main msg:java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.timob24903/org.appcelerator.titanium.TiActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar; Titanium 6.2.0,2017/07/10 11:03,undefined
[ERROR] :  TiApplication: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.app.timob24903/org.appcelerator.titanium.TiActivity}: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
[ERROR] :  TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
[ERROR] :  TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] :  TiApplication: 	at android.os.Looper.loop(Looper.java:135)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5254)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Method.invoke(Method.java:372)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
[ERROR] :  TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
[ERROR] :  TiApplication: Caused by: android.view.InflateException: Binary XML file line #8: Error inflating class android.support.v7.widget.Toolbar
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.createView(LayoutInflater.java:633)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:743)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:806)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.rInflate(LayoutInflater.java:809)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:504)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:414)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.inflate(LayoutInflater.java:365)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7.createSubDecor(AppCompatDelegateImplV7.java:394)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7.ensureSubDecor(AppCompatDelegateImplV7.java:312)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatDelegateImplV7.setContentView(AppCompatDelegateImplV7.java:268)
[ERROR] :  TiApplication: 	at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:145)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.setContentView(TiBaseActivity.java:570)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:694)
[ERROR] :  TiApplication: 	at org.appcelerator.titanium.TiActivity.onCreate(TiActivity.java:21)
[ERROR] :  TiApplication: 	at android.app.Activity.performCreate(Activity.java:5990)
[ERROR] :  TiApplication: 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
[ERROR] :  TiApplication: 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
[ERROR] :  TiApplication: 	... 10 more
[ERROR] :  TiApplication: Caused by: java.lang.reflect.InvocationTargetException
[ERROR] :  TiApplication: 	at java.lang.reflect.Constructor.newInstance(Native Method)
[ERROR] :  TiApplication: 	at java.lang.reflect.Constructor.newInstance(Constructor.java:288)
[ERROR] :  TiApplication: 	at android.view.LayoutInflater.createView(LayoutInflater.java:607)
[ERROR] :  TiApplication: 	... 26 more
[ERROR] :  TiApplication: Caused by: java.lang.NoClassDefFoundError: Failed resolution of: Landroid/support/graphics/drawable/VectorDrawableCompat;
[ERROR] :  TiApplication: 	at android.support.v7.widget.AppCompatDrawableManager$VdcInflateDelegate.createFromXmlInner(AppCompatDrawableManager.java:891)
[ERROR] :  TiApplication: 	at android.support.v7.widget.AppCompatDrawableManager.loadDrawableFromDelegates(AppCompatDrawableManager.java:356)
[ERROR] :  TiApplication: 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:197)
[ERROR] :  TiApplication: 	at android.support.v7.widget.AppCompatDrawableManager.getDrawable(AppCompatDrawableManager.java:192)
[ERROR] :  TiApplication: 	at android.support.v7.widget.TintTypedArray.getDrawable(TintTypedArray.java:60)
[ERROR] :  TiApplication: 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:254)
[ERROR] :  TiApplication: 	at android.support.v7.widget.Toolbar.<init>(Toolbar.java:196)
[ERROR] :  TiApplication: 	... 29 more
[ERROR] :  TiApplication: Caused by: java.lang.ClassNotFoundException: Didn't find class "android.support.graphics.drawable.VectorDrawableCompat" on path: DexPathList[[zip file "/data/app/com.app.timob24903-2/base.apk"],nativeLibraryDirectories=[/data/app/com.app.timob24903-2/lib/x86, /vendor
```

**Comment by lokeshchdhry** [comment]
Verified with @garymathews that the above error is unrelated to this change.

**Pull request merged**
