### PR TITLE
[TIMOB-25580] Android: Prevent EVENT_RETURN firing twice

### PR DESCRIPTION
**Pull request by garymathews**
- Prevent `onEditorAction` firing `EVENT_RETURN`

###### TEST CASE
```Java
var win = Ti.UI.createWindow(),
    text = Ti.UI.createTextArea({
        value: 'TEXT',
        top: 10,
        left: 10,
        right: 10,
        height: 200
    });

text.addEventListener('return', function() {
    alert('return event fired');
});

win.add(text);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25580)

### CODE REVIEW

**Comment by lokeshchdhry** [comment]
FR Passed.

`return` event is fired only once.

Studio Ver:     5.0.0.201711301752
SDK Ver:        7.0.0.v20171130091945
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11-4
Appc CLI:       7.0.0-master.55
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.9
Node Ver:       8.9.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel --- Android 7.1.1

**Review by jquick-axway — CHANGES_REQUESTED** [review]
CR: Pass

@lokeshchdhry, we need to test TextField return key handling too since this code change affects it as well. Particularly when the `RETURN` key has been replaced by `NEXT` or `DONE`, which must fire a `return` event as well.

**Review by jquick-axway — APPROVED** [review]

**Comment by lokeshchdhry** [comment]
@jquick-axway , Thanks for the suggestion.
@garymathews , I see that when I have 3 textfields each with return event listener, the return event is not fired for `next` & `done`.

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Comment by lokeshchdhry** [comment]
FR reviewed & passed.

`return` event is fired after `next` & `done for textfields.

Studio Ver:     5.0.0.201711301752
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11-4
Appc CLI:       7.0.0-master.56
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.9
Node Ver:       8.9.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

**Comment by lokeshchdhry** [comment]
@garymathews , can you please look at this. It says needs tests.

**Comment by garymathews** [comment]
Adding `no tests` as user input is required to test

**Pull request merged**
