### PR TITLE
[TIMOB-19859] Android: Deprecate Ti.Android.R.drawable

### PR DESCRIPTION
**Pull request by sriks**
JIRA https://jira.appcelerator.org/browse/TIMOB-19859?filter=-1

### CODE REVIEW

**Comment by ashcoding** [comment]
@sriks Formatting seems to be off for the code.

**Comment by sriks** [comment]
@ashcoding Applied re-indentation. Please review.

**Comment by ashcoding** [comment]
Tried test code in Jira and didn't observe log messages. Is there something else that I need to do?

**Comment by ashcoding** [comment]
Tested this on a non android 6.0 device. Working well. Seems that the ticket on logs on Android 6.0 needs to be looked into.

**Comment by ashcoding** [comment]
Code reviewed and functionally tested. **Accepted**

**Pull request merged**
