### PR TITLE
feat(android): update gradle

### PR DESCRIPTION
**Pull request by m1ga**
Update Gradle tools (not the plugins! Those still fail to build :disappointed: ) to 7.6

**Features:**
* Java 19 support (only had 20 to test here)

**Tested:**
* Building SDK
* Building module
* Building apps (my app, user app, hyperloop example)
* Module tests:
  * Tested 12.0.0.RC module in PR app
  * Tested PR module in 12.0.0.RC app
  * Tested 11.1.1.GA modules in PR app

**Note:**
Changes are by gradle itself using [this line](https://github.com/tidev/titanium_mobile#upgrade-gradle-and-gradle-plugin). Only [this file](https://github.com/tidev/titanium_mobile/compare/gradleUpdate?expand=1#diff-4c5ffadbdf6016477a1c3768e0b7381cc298bd558b1784871f407cbcb0efacceR3) is changed

### CODE REVIEW

**Comment by cb1kenobi** [comment]
I tested on Windows with both JDK 17.0.5 and 19 and while both work, the app builds fine, and the app runs fine, I see the following error in the log output:

```
[INFO]  [GRADLE] Starting a Gradle Daemon, 2 incompatible Daemons could not be reused, use --status for details
[ERROR] [GRADLE] Warning: This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
[ERROR] [GRADLE] Warning: unexpected element (uri:"", local:"extension-level"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
[ERROR] [GRADLE] Warning: unexpected element (uri:"", local:"base-extension"). Expected elements are <{}codename>,<{}layoutlib>,<{}api-level>
```

Note that these errors do NOT occur with SDK 11.1.0.GA. Is there a way to make Gradle happy?

Side note: Gradle's `java.exe' process eats up a whopping 1GB of memory. That's not good.

image

**Comment by m1ga** [comment]
@cb1kenobi I'm using 12.0.0 for a while now and already used to that "error". It doesn't affect the apps. 
The solution is to update gradle-plugin https://github.com/tidev/titanium_mobile/issues/13579 but I wasn't successful in doing that. Also tried to find someone in the gradle community https://discuss.gradle.org/t/build-order-problem-upgrading-build-tools-from-7-0-4-7-2-2/43850 but that wasn't of any help either :smile: 

Everything from 7.0.x to 7.1.0 or higher breaks the build order as it doesn't have the folders/cpp files ready to continue to build the SDK. But the whole gradle part is not that easy to follow for me as i triggers node stuff and other things. Raising that will fix many warnings and we'll have to do that at some point. For now we can ignore those warnings and I've added flags already that disable Android 33 warnings.

**Comment by m1ga** [comment]
The error tag is internal, for Gradle its a warning `**Warning**: unexpected element (uri:"", local:"extension-level")...`.

**Comment by m1ga** [comment]
> I'm a little concerned with not being able to update the gradle-plugin. Maybe that's something I can take a peek at in the next week or so, but I honestly don't know anything about Gradle.

That would be awesome if someone else could have a look. There are two places to increase the version:
https://github.com/tidev/titanium_mobile/blob/fa604fac971579225c156a51f749011a416b2c74/android/build.gradle#L16 and https://github.com/tidev/titanium_mobile/blob/80ec88188a6254400c7e9569b722bd9570248a10/android/templates/build/root.build.gradle#L10 (for the module builds later on). 

Both have to match otherwise it breaks modules. The module gradle isn't a problem, that works fine. It's just the first one that builds the SDK. `7.3.1` would be the latest stable version but the next iteration `7.1.0` already breaks the builds. Couldn't find anything useful in changelogs. And that there is gradle and "gradle build plugin" doesn't make it easier to search for stuff :smile:

**Comment by cb1kenobi** [comment]
> The error tag is internal, for Gradle its a warning `**Warning**: unexpected element (uri:"", local:"extension-level")...`.

Sorry, I misread the output. You are correct sir!

**Comment by hansemannn** [comment]
I'm definitely for including it, but maybe not in this GA already to ensure we have more time to properly test. I will also discuss this with @janvennemann and @tpretzel to see if we can get the logs fixed.

**Comment by m1ga** [comment]
> I'm definitely for including it, but maybe not in this GA already to ensure we have more time to properly test. 

it's a master PR not for 12.0.0, was supposed to be for the next release  :wink:

**Comment by m1ga** [comment]
@hansemannn @cb1kenobi  added a fix for the warning color:
https://github.com/tidev/titanium/pull/611

**Comment by cb1kenobi** [comment]
I accidentally merged tidev/titanium#611 too quickly and reverted it in https://github.com/tidev/titanium/pull/612.

The correct place to fix the Gradle warning is in the `createReadableDataHandlerUsing()` function: https://github.com/tidev/titanium_mobile/blob/master/android/cli/lib/gradle-wrapper.js#L178-L204

**Comment by m1ga** [comment]
I'll check those places :+1: Sounds like a better way to fix it

**Comment by hansemannn** [comment]
Adding two more logs here to have all at one place:
```
[INFO]  Building app
[TRACE] Found 1 devices, checking if any of them are the emulator...
[TRACE] Emulator is running!
[TRACE] Checking if boot animation has finished...
[TRACE] Emulator is not booted yet; checking again in 2000 ms
[INFO]  [GRADLE] This version only understands SDK XML versions up to 2 but an SDK XML file of version 3 was encountered. This can happen if you use versions of Android Studio and the command-line tools that were released at different times.
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
[INFO]  [GRADLE] Errors limit exceeded. To receive all errors set com.sun.xml.bind logger to FINEST level.
[INFO]  [GRADLE] unexpected element (uri:"", local:"base-extension"). Expected elements are <{}vendor>,<{}codename>,<{}abi>,<{}api-level>,<{}tag>
```
and
```
[INFO]  [GRADLE] Relying on FileTrees for ignoring empty directories when using @SkipWhenEmpty has been deprecated. This is scheduled to be removed in Gradle 8.0. Annotate the property inputFiles with @IgnoreEmptyDirectories or remove @SkipWhenEmpty. Consult the upgrading guide for further information: https://docs.gradle.org/7.4.2/userguide/upgrading_version_7.html#empty_directories_file_tree
```

**Comment by m1ga** [comment]
this PR was fine. We had had issues testing it on Windows.

The problematic one is https://github.com/tidev/titanium-sdk/issues/13579 when updating `com.android.tools.build:gradle` from `7.0.4` to any higher version (7.1.0 is the next one). That will break building the SDK as it won't create the C files before trying to use them.

**Comment by m1ga** [comment]
Tested this PR again:

Fedora Linux, Android 14/Pixel 7

**Java 17** (current max version we support)
* build Android SDK :heavy_check_mark: 
* Ti Android SDK test suite :heavy_check_mark: 
* kitchensink app :heavy_check_mark: 
* hyperloop-examples :heavy_check_mark: 
* two different apps with existing modules :heavy_check_mark: 
* building android modules :heavy_check_mark: 
* build apps with rebuild modules :heavy_check_mark: 
* build apps with 12.2.1.GA + modules that were build with 12.3.0 :heavy_check_mark: 

**Java 20** 
* build Android SDK :heavy_check_mark: 
* Ti Android SDK test suite :heavy_check_mark: 
* kitchensink app :heavy_check_mark: 
* hyperloop-examples :heavy_check_mark: 
* two different apps with existing modules :heavy_check_mark: 
* building android modules :heavy_check_mark: 
* build apps with rebuild modules :heavy_check_mark: 
* build apps with 12.2.1.GA + modules that were build with 12.3.0 :heavy_check_mark:

**Review by cb1kenobi — APPROVED** [review]
Tested on Windows, Java 20, built basic 2-tab app, and everything works!

**Comment by m1ga** [comment]
I'm soooo confused. After working with 12.3.0 (with this PR) and Java 20 the whole day I've tried to build a different PR with Android Studio a few minutes ago and now I'm getting:
```
BUG! exception in phase 'semantic analysis' in source unit '_BuildScript_' Unsupported class file major version 64
```
the whole time. I even switched Java back to 17 and delete the whole `~./gradle` folder, killed all java processes and gradle. Still complaining about major version 64 (which is Java 20) :shrug: What did it break all of the sudden?!

**Comment by cb1kenobi** [comment]
@m1ga I didn't see a problem. You're on Linux, right?

**Comment by m1ga** [comment]
a restart fixed the error! Which is not really helping me to find the source of it. I'll keep investigating and check if the issue appears again. It started once I've opened Android Studio trying to build an old PR. Perhaps that mixed up gradle somehow.

**Pull request merged**
