### PR TITLE
[MOD-2318](5_4_X) iOS/Android: Update ti.cloud packaged module 

### PR DESCRIPTION
**Pull request by AngelkPetkov**
[JIRA](https://jira.appcelerator.org/browse/MOD-2138)

### CODE REVIEW

**Comment by hansemannn** [comment]
Needs to include the changelog specified in https://github.com/appcelerator-modules/ti.cloud/pull/95.

**Comment by hansemannn** [comment]
Needs to include the changelog specified in https://github.com/appcelerator-modules/ti.cloud/pull/95.

**Comment by AngelkPetkov** [comment]
Updated the log and re-packaged

**Comment by hansemannn** [comment]
Approved!

**Pull request merged**
