### PR TITLE
[CLI-1124] Android: Hide non Ti Log

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA**: https://jira.appcelerator.org/browse/CLI-1124

Change regex so it will match string that contains not only characters (e.g. dots)

### CODE REVIEW

**Comment by hansemannn** [comment]
test this please

**Comment by hansemannn** [comment]
@m1ga Can you add an example log with and without this change (e.g. a new created app on startup)?

**Comment by m1ga** [comment]
example added to [JIRA page](https://jira.appcelerator.org/browse/CLI-1124?focusedCommentId=404626&page=com.atlassian.jira.plugin.system.issuetabpanels:comment-tabpanel#comment-404626)

**Comment by feons** [comment]
LGTM. **APPROVED.**

**Comment by skypanther** [comment]
I'm hoping this PR will also address my ticket https://jira.appcelerator.org/browse/TIMOB-23975 Logging on Android has been largely unusable since 5.4.x.

**Comment by hansemannn** [comment]
@skypanther Good point, can you validate this and get back to us? Would be very good to know, since we're currently discussing a possible 6.0.2!

**Comment by skypanther** [comment]
I added a comment on TIMOB-23975. Logging is greatly improved and is again usable. Thanks! There are some extraneous messages but I can certainly live with those.

**Pull request merged**
