### PR TITLE
Possible solution for TIMOB-20320 to be discussed

### PR DESCRIPTION
**Pull request by stgrosshh**
Allow a more generic approach to register permission request result callbacks

### CODE REVIEW

**Comment by hansemannn** [comment]
Hey @stgrosshh, thanks for the PR! Can you give us an example on how your changes would be used in the actual code? Also I notice some "TODO" comments inside your code, whats your progress there? Thanks!

**Comment by stgrosshh** [comment]
Got CLA gateway timeout errors all the time unfortunately

**Comment by stgrosshh** [comment]
Hi Hans,
TODOs are meant as to be discussed with the community.
I can provide some example code next weekend.

**Comment by ashcoding** [comment]
So I guess this PR is more for a discussion? :)

**Comment by stgrosshh** [comment]
Currently implementing a better approach, so I close this PR now.

**Comment by ashcoding** [comment]
:+1: @stgrosshh

**Pull request closed without merging**
