### PR TITLE
fix(android): menu and toolbar icons to use ActionBar style colors

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-28547

**Summary:**
When setting menu/toolbar icons to a resource ID (ie: a vector drawable), the icon should use the theme/style assigned to the ActionBar or Toolbar. Currently, it uses the style colors assigned to the activity window, which won't be the same as the ActionBar if using a DarkActionBar theme.

**Test:**
1. Download https://github.com/appcelerator/kitchensink-v2/pull/59
2. Build and run on Android.
3. Make sure device is using the Light theme.
3. Go to: Views -> ListView (Multi-Select)
4. Verify all top toolbar icons are white. (They used to be gray.)

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**
FT: **PASS**

**Comment by hansemannn** [comment]
I wonder if this change caused the `[ERROR] E/com.example.myapp Invalid ID 0x00000000.` error log. I was able to reproduce it with just these few lines of code:
```xml
<Alloy>
	<Window>
		<Menu platform="android">
			<MenuItem title="Test" />
		</Menu>
	</Window>
</Alloy>
```
cc @m1ga, you may have seen the error log as well.

**Comment by m1ga** [comment]
I'll check that :+1:

**Comment by m1ga** [comment]
@hansemannn it's strange. I can't reproduce it at the moment with 10.2.0. Neither with the demo code nor with my app :thinking: I had this for a long time but now I don't see it anymore. I'll give it another try later today

**Pull request merged**
