### PR TITLE
[DOC] Review Android.yml

### PR DESCRIPTION
**Pull request by ypbnv**
Rewording in a few places ( it sounded a bit better in my head, not sure if it is the proper way ).
Indentation here and there.
Filling in some dots and missing fields.
Move a detailed description to the proper constant.

I noticed a few properties were removed due to being deprecated/removed a long time ago. Are we safe to remove them in the code as well ?
Here they are:
https://github.com/appcelerator/titanium_mobile/pull/10113/files#diff-de28ec13bdb41ca9ccff28d09119a758L787

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
@jawa9000 ping

**Comment by sgtcoolguy** [comment]
cc @garymathews RE: properties removed in docs long ago, but not code(?)

**Comment by hansemannn** [comment]
@jawa9000 @garymathews Can you take a look please? This is a left-over from docs-day.

**Review by jawa9000 — CHANGES_REQUESTED** [review]
For https://github.com/appcelerator/titanium_mobile/pull/10113/files#diff-ef87022d8eb2735f703832e1077f7f58, I would change "Before, a contact can be selected without requiring User permission." to "Previously, a contact can be selected without requiring User permission." Otherwise, it looks good.

**Comment by ypbnv** [comment]
@jawa9000 Updated.

**Pull request merged**
