### PR TITLE
[TIMOB-9111] iOS: Remove Base64Transcoder dependency, fix Base64-parity

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-9111

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
Looks like this now fails the `base64#decode(Ti.Blob)` unit test on iOS.

**Comment by hansemannn** [comment]
@vijaysingh-axway Save to review. @sgtcoolguy I didn't add new unit-tests, because the old ones should persist as they are.

**Review by vijaysingh-axway — APPROVED** [review]
Cr and FT passed.

**Review by mukherjee2 — APPROVED** [review]
Node Version: 8.9.1
NPM Version: 5.5.1
Mac OS: 10.13
Appc CLI: 7.0.0-master.13
Appc CLI NPM: 4.2.11-2
Titanium SDK version: 7.0.0
Appcelerator Studio vers 4.10.0
Xcode 9.1/iOS 11.1 iPhone 7 Plus
Passed FR. I first reproduced with an affected version. I then tried it with the fix version and did not see "NEWLINE" in the alert, as expected.

**Comment by mukherjee2** [comment]
@hansemannn can you look into the unit test failures?

**Pull request merged**
