### PR TITLE
[TIMOB-23310]: Upgrade v8 to 5.0.71.33

### PR DESCRIPTION
**Pull request by hieupham007**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23310
DO NOT MERGE YET

### CODE REVIEW

**Comment by ashcoding** [comment]
@sgtcoolguy @hieupham007 I know this is not ready yet but just want to ask, will there be support for other ABIs? http://developer.android.com/ndk/guides/abis.html Eg. x86_64 ?

Related links: http://stackoverflow.com/questions/36616521/compile-module-for-64-bits-android-devices-with-titanium-appcelerator
https://jira.appcelerator.org/browse/TIMOB-23228

**Comment by sgtcoolguy** [comment]
I don't see why we couldn't. Right now I just built V8 with ARM and ia32(x86) versions. But I think it supports a number of others. See https://android.googlesource.com/platform/external/v8/+/master/Android.mk

They list these arch: arm mips x86 arm64 mips64 x86_64

And here: https://android.googlesource.com/platform/external/v8/+/master/Makefile.android

Basically I think it's more a matter of just generating the v8 libraries for each of those targets we want to support. That would go in appcelerator/v8_titanium repo.

**Comment by sgtcoolguy** [comment]
Looking at the various targets, I think it's also a matter of which platform we compile against.
3+: arm
9+: x86, mips
21+: arm64, x86_64, mips64

I believe we default to building against 9, but a command line arg in the build script for v8_titanium controls that. I'll try and build for all 6 of those...

**Comment by ashcoding** [comment]
That would be awesome!

**Comment by sgtcoolguy** [comment]
Note that Trying this out currently with NDK r11c and Titanium master I see this on startup of the app (during the splash screen):
```
INFO]  TiApplication: (main) [0,0] checkpoint, app created.
[INFO]  TiApplication: (main) [62,62] Titanium 6.0.0 (2016/06/03 15:38 95de999)
[DEBUG] AndroidRuntime: Shutting down VM
[ERROR] TiApplication: (main) [50,112] Sending event: exception on thread: main msg:java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/dfg.df-2/base.apk"],nativeLibraryDirectories=[/data/app/dfg.df-2/lib/x86, /data/app/dfg.df-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libstlport_shared.so"; Titanium 6.0.0,2016/06/03 15:38,95de999
[ERROR] TiApplication: java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/dfg.df-2/base.apk"],nativeLibraryDirectories=[/data/app/dfg.df-2/lib/x86, /data/app/dfg.df-2/base.apk!/lib/x86, /vendor/lib, /system/lib]]] couldn't find "libstlport_shared.so"
[ERROR] TiApplication: 	at java.lang.Runtime.loadLibrary(Runtime.java:367)
[ERROR] TiApplication: 	at java.lang.System.loadLibrary(System.java:1076)
[ERROR] TiApplication: 	at org.appcelerator.kroll.runtime.v8.V8Runtime.initRuntime(V8Runtime.java:59)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.doInit(KrollRuntime.java:205)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime$KrollRuntimeThread.run(KrollRuntime.java:114)
[ERROR] TiApplication: 	at org.appcelerator.kroll.KrollRuntime.init(KrollRuntime.java:136)
[ERROR] TiApplication: 	at dfg.df.ExampleApplication.onCreate(ExampleApplication.java:41)
[ERROR] TiApplication: 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
[ERROR] TiApplication: 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
[ERROR] TiApplication: 	at android.app.ActivityThread.-wrap1(ActivityThread.java)
[ERROR] TiApplication: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
[ERROR] TiApplication: 	at android.os.Handler.dispatchMessage(Handler.java:102)
[ERROR] TiApplication: 	at android.os.Looper.loop(Looper.java:148)
[ERROR] TiApplication: 	at android.app.ActivityThread.main(ActivityThread.java:5417)
[ERROR] TiApplication: 	at java.lang.reflect.Method.invoke(Native Method)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
[ERROR] TiApplication: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
[ERROR] E/NetworkScheduler.SR( 1846): Invalid parameter app
[ERROR] E/NetworkScheduler.SR( 1846): Invalid package name : Perhaps you didn't include a PendingIntent in the extras?
```

Looks like because I had to change our STL from libstlport_shared to libc++_shared, we're not properly using the new shared library and must have some code hard-coded to use libstlport_shared.

Note that I needed to swap to using libc++_shared to get us compiled with new V8, since it looks like stlport_shared doesn't have all the features V8 uses anymore. I chose that library because of https://android.googlesource.com/platform/external/v8/+/master/Android.libv8.mk

**Comment by sgtcoolguy** [comment]
Note that right now even this version of V8 is behind. Once we get this merged we should regularly update. Right now Android stable version is: 5.1.281.57 - see https://omahaproxy.appspot.com

**Comment by sgtcoolguy** [comment]
OK, just pushed the latest that works locally. icons builds fine against Android NDK r11c, and I can run a simple default Titanium app with it (classic two-tab). I can also confirm the new engine fixes TIMOB-23476.

Ready for Review!

**Comment by sgtcoolguy** [comment]
Wait a second... This PR is off of Hieu's branch? OK, so my new commits aren't here. Ugh. I'm going to open the real PR

**Pull request closed without merging**
