### PR TITLE
[TIMOB-25910] Android: Fix Ti.UI.TableView memory leak

### PR DESCRIPTION
**Pull request by garymathews**
- Remove references to TableView rows

###### TEST CASE
```JS
const root = Ti.UI.createWindow({
        backgroundColor: 'gray'
    }),
    btn = Ti.UI.createButton({
        title: 'OPEN TABLE WINDOW'
    });

btn.addEventListener('click', () => {
    const win = Ti.UI.createWindow({
            backgroundColor: 'red'
        }),
        tableView = Ti.UI.createTableView();

    let rows = [];

    for (let i = 0; i < 64; i++) {
        const row = Ti.UI.createTableViewRow();
        const textField = Ti.UI.createTextField();

        row.add(textField);
        rows.push(row);
    }

    tableView.data = rows;

    win.add(tableView);
    win.open();
});

root.add(btn);
root.open();
```
- Open and close `TABLE WINDOW` multiple times
- Observe memory usage to not increase dramatically after GC
- Application should not crash

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25910)

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
I believe this customer has requested the bug fix specifically against the 7.1.0.GA SDK. To help with that I'v generated the `7_1_0-TIMOB-25910` branch specifically to backport this fix onto.

**Comment by lokeshchdhry** [comment]
@garymathews , I am able to get the app to freeze & not respond with the fix.

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Comment by ypbnv** [comment]
@garymathews That way we would not be able to persist the dataset with rows through multiple usage with Table. Here is what I tried:
```
const root = Ti.UI.createWindow({
        backgroundColor: 'gray',
        layout: 'vertical'
    }),
    btn = Ti.UI.createButton({
        title: 'CREATE ROWS'
    }),
    btn2 = Ti.UI.createButton({
    	title: 'OPEN TABLE WITH ROWS'
	});

let rows = [];

btn2.addEventListener('click', () => {

	const win = Ti.UI.createWindow({
		backgroundColor: 'red'
	}),
	tableView = Ti.UI.createTableView();
	tableView.data = rows;

	win.add(tableView);
	win.open();
});

btn.addEventListener('click', () => {

    for (let i = 0; i < 64; i++) {
        const row = Ti.UI.createTableViewRow();
        const textField = Ti.UI.createTextField();

        row.add(textField);
        rows.push(row);
    }

});

root.add(btn);
root.add(btn2);
root.open();
```
After the closing the window and opening it again the app crashes because we have released the proxies for the rows dataset. Are we OK with that?

**Comment by garymathews** [comment]
@ypbnv Good catch! Updated PR 👍 
@lokeshchdhry Could you re-test this PR?

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Review by ssjsamir — COMMENTED** [review]
Although I get no application crashes. When checking Android device monitor after GC I don't see much difference in results from previous versions of the SDK (Not sure if its because of my device or if I need to open and close the window for extended period of time, or if i'm missing something else)

Please could you also take a look @lokeshchdhry or @longton95 

**Test steps**
+ Created a build from this PR
+ Created a titanium app
+ Added the test case above
+ Ran the program
+ Opened and closed `table widows` a few times
+ Application no longer crashed unlike previously
+ Checking Android device monitor shows similar results previously 

**Test Environment**
Nexus 6p 8.1.0
APPC Studio: 5.0.0.201712081732
APPC CLI: 7.0.4-3
Google Pixel (8.1.0)
Operating System Name: Mac OS High Sierra
Operating System Version: 10.13
Node.js Version: 8.9.1
Xcode 9.2

**Comment by sgtcoolguy** [comment]
@garymathews master is now targeting 7.4.0. If this fix is intended to land for 7.3.0, there will need to be a cloned PR (or a cherry-pick of the commit once merged) to `7_3_X`

**Pull request merged**
