### PR TITLE
[TIMOB 16879] ScrollableView: Add "insertViewsAt()" method

### PR DESCRIPTION
**Pull request by bduyng**
JIRA: https://jira.appcelerator.org/browse/TIMOB-16879

### CODE REVIEW

**Comment by bduyng** [comment]
EXAMPLE CODE:
```js
var win = Ti.UI.createWindow();

var view1 = Ti.UI.createView({ backgroundColor:'#123' });
var view2 = Ti.UI.createView({ backgroundColor:'#246' });
var view3 = Ti.UI.createView({ backgroundColor:'#48b' });

var scrollableView = Ti.UI.createScrollableView({
  views:[view1,view2,view3],
  showPagingControl:true
});

// insert a view at 1(position)
setTimeout(function(){
  scrollableView.insertViewsAt(1, Ti.UI.createView({ backgroundColor:'yellow' }));
}, 2000);

// insert many views at 1(position)
setTimeout(function(){
  scrollableView.insertViewsAt(1, [
    Ti.UI.createView({ backgroundColor:'red' }),
    Ti.UI.createView({ backgroundColor:'blue' }),
    Ti.UI.createView({ backgroundColor:'gray' })
  ]);
}, 4000);

win.add(scrollableView);
win.open();
```

**Comment by nuno** [comment]
@bduyng Thanks, is also important   have insertViewsAt() after the window open like:

```javascript

....

win.add(scrollableView);
win.open();

// insert many views at 0(position)
setTimeout(function(){
  scrollableView.insertViewsAt(0, [
    Ti.UI.createView({ backgroundColor:'#FBCA0B' }),
    Ti.UI.createView({ backgroundColor:'#207de5' }),
    Ti.UI.createView({ backgroundColor:'#8155f2' })
  ]);
}, 6000);

```

**Comment by bduyng** [comment]
Thanks @nuno : please test on the Android as well if you want :). I just pushed the Android code. Use the same above example code

**Comment by ashcoding** [comment]
@bduyng Could you Sign the CLA? Thank you!

**Comment by bduyng** [comment]
@ashcoding: I just did. How can we run the test again?  I mean `Some checks were not successful, Appcelerator-CLA — The contributor hasn't signed the CLA`

**Comment by bduyng** [comment]
@ashcoding Hi man, I just did. Seem everything is good to go?

**Comment by zyre91** [comment]
Really looking forward to this change. Thanks @bduyng for your work.

**Comment by bduyng** [comment]
You are welcome @zyre91. I still have no ideas when this pull request will be merged :)

**Comment by ashcoding** [comment]
Thanks for the PR! @hansemannn could you take a look into the iOS portion?

**Comment by hansemannn** [comment]
@bduyng Today we finishing fixing the iOS API for `Ti.UI.ScrollableView`. Can you test your changes with latest master by pulling? After that, we can go on and test / review / merge your PR. Thanks!

**Comment by bduyng** [comment]
@hansemannn: hi Hans. I pulled and tested my changes with latest master then add the dos for `insertViewsAt` as well. Please check if everything is ok.

**Comment by cheekiatng** [comment]
@bduyng appreciate your work on this! 👍 
@hansemannn the code looks good for iOS, and it shouldn't affect auto layout or run on main thread. But please do test those scenarios when reviewing.

**Comment by hansemannn** [comment]
Alright. Review is scheduled for late next week, we're getting there!

**Comment by nuno** [comment]
Oh, is not in this last beta?

**Comment by hansemannn** [comment]
As discussed on Slack, closing this PR in favor of https://github.com/appcelerator/titanium_mobile/pull/7966 to do minor refactoring on adding the views without code-duplications. Very good work @bduyng, thank you! 🚀

**Pull request closed without merging**
