### PR TITLE
[TIMOB-26227] Android: Removed kroll thread support

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-26227

**Summary:**
- The "tiapp.xml" property "run-on-main-thread" is now ignored.
- Titanium's JavaScript runtime can now only run on the main UI thread.

**Test:**
1. Download "kitchensink-v2" project from [here](https://github.com/appcelerator/kitchensink-v2).
2. Build and run on Android.
3. Verify that all UI features in kitchen sink work without issue. _(Note that Google Maps, Facebook, and Twitter features can be skipped since they require an app ID.)_

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
For tracking purposes, the iOS equivalent PR is here: #10196

**Review by garymathews — APPROVED** [review]
CR: **PASS**

NOTE: QE should make sure to test TableView and ListView functionality that isn't included with KitchenSink-V2

**Comment by lokeshchdhry** [comment]
Ran old KS as of now & did not see any issues. KS2 is pending as I am getting error on KS2 startup :
Seems not related to this PR.

```[ERROR] :  [Nexus 5] TiExceptionHandler: Error: Requested module not found: core-js/modules/web.dom.iterable
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module.require (ti:/module.js:303:8)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at require (ti:/module.js:570:15)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at /ti.internal/extensions/Error.js:15:1
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module._runScript (ti:/module.js:613:9)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module.load (ti:/module.js:105:7)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module.loadJavascriptText (ti:/module.js:457:9)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module.loadAsFile (ti:/module.js:512:15)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module.loadAsFileOrDirectory (ti:/module.js:429:20)
[ERROR] :  [Nexus 5] TiExceptionHandler:     at Module.require (ti:/module.js:256:17)
```

**Comment by lokeshchdhry** [comment]
FR Passed.

Ran KS & KS2. Did not find any issues.

Studio Ver:     5.1.2.201810301430
SDK Ver:        8.0.0 local build
OS Ver:         10.14
Xcode Ver:      Xcode 10.1
Appc NPM:       4.2.13
Appc CLI:       7.0.8
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.4
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Pixel (Android 9)

**Pull request merged**
