### PR TITLE
Add progress event to Ti.UI.WebView on Android

### PR DESCRIPTION
**Pull request by arifje**
Add progress event for Ti.UI.WebView on Android.

Ticket: https://jira.appcelerator.org/browse/AC-6456

### CODE REVIEW

**Comment by jquick-axway** [comment]
We need to double check how this works when the webpage contains "iframes" between Android and iOS. The "progress" event should either only apply to (1) the main page or (2) represent all of the web content (main page + iframes). I'm leaning towards option 1 since an iframe can timeout.

**Comment by skoften** [comment]
@jquick-axway agree on option 1, as iframes can been seen as separate/nested webviews with there kwn loading time (and timeouts indeed, because of third party domains), right?

**Review by garymathews — APPROVED** [review]
CR: **PASS**

Can confirm `progress` reaches `100` once page and iframe content has loaded.

**Review by ssjsamir — APPROVED** [review]
**FR Passed** able to see the progress event go from 0-100: 
Using the following test case:
```
var win = Ti.UI.createWindow();
var webview = Ti.UI.createWebView({
    url: 'http://www.google.com'
});
webview.addEventListener('progress', function(e) {
  Ti.API.info(e.progress);
});
win.add(webview);
win.open();
```

**Test Environment**
```
MacOS Catalina: 10.15.5 Beta 
Xcode: 11.4
Java Version: 1.8.0_131
Android NDK: 21.1.6273396-beta2
Node.js: 10.16.3
""NPM":"5.0.0-1","CLI":"8.0.0-master.10""
iphone 8 Sim (13.4)
Pixel Xl (10.0)
```

**Pull request merged**
