### PR TITLE
Fixed a typo.

### PR DESCRIPTION
**Pull request by mackinleysmith**
warpper -> wrapper.

### CODE REVIEW

**Comment by ashcoding** [comment]
Thanks for the PR! Before we can review and accept it, we would need you to sign the CLA. https://cla.appcelerator.com/

**Comment by smit1625** [comment]
Hey there, I’ve been trying to sign it but when I click the “Sign in with Github button”, it just reloads the page and nothing happens.

**Comment by ashcoding** [comment]
Hmmm. I'm not sure what might be the cause of that. Could you try a different web browser and see if it works?

**Comment by smit1625** [comment]
Still no luck ):

**Comment by ashcoding** [comment]
Could you try this workaround of using Private Browsing/Incognito Mode to sign the CLA?

**Comment by smit1625** [comment]
Looks like that worked!  Thanks.

**Comment by ashcoding** [comment]
Reviewed. **Accepted**. Merging.
Thank you! :shipit:

**Pull request merged**
