### PR TITLE
[LAYOUT] First commit on iOS Autolayout

### PR DESCRIPTION
**Pull request by pec1985**
Jira ticket: http://jira.appcelerator.org/browse/TIMOB-19151

### CODE REVIEW

**Comment by pec1985** [comment]
Auto layout is now optional, by editing the `pch` file and adding `#define TI_USE_AUTOLAYOUT`

**Comment by pec1985** [comment]
To test this, add the following tag to the `ios` tag in `tiapp.xml`
```
<use-autolayout>true</use-autolayout>
```

**Comment by cheekiatng** [comment]
APPROVED!

**Comment by jhaynie** [comment]
@pec1985 @cheekiatng i'm getting the following trying to build app from 5_1_X:

```
In file included from /Users/jhaynie/work/proto/libhyperloop/src/utils.m:5:
In file included from /Users/jhaynie/work/proto/libhyperloop/src/utils.h:6:
In file included from /Users/jhaynie/work/proto/libhyperloop/src/define.h:9:
In file included from /Users/jhaynie/work/proto/libhyperloop/titanium/HyperloopViewProxy.h:7:
In file included from /Users/jhaynie/Library/Application Support/Titanium/mobilesdk/osx/5.1.0/iphone/include/TiUIViewProxy.h:8:
In file included from /Users/jhaynie/Library/Application Support/Titanium/mobilesdk/osx/5.1.0/iphone/include/TiViewProxy.h:8:
/Users/jhaynie/Library/Application Support/Titanium/mobilesdk/osx/5.1.0/iphone/include/TiUIView.h:12:9: fatal error: 'TiLayoutView.h' file not
      found
#import "TiLayoutView.h"
        ^
1 error generated.
```

**Comment by jhaynie** [comment]
Putting a guard around the include seems to fix the compile for me in TiUIView.h

#ifdef TI_USE_AUTOLAYOUT
#import "TiLayoutView.h"
#endif

I'm getting the error when i try and compile the hyperloop module and include the headers pointing to this SDK.

**Comment by cheekiatng** [comment]
@jhaynie Thanks. PRs made to address this issue.
https://github.com/appcelerator/titanium_mobile/pull/7287
https://github.com/appcelerator/titanium_mobile/pull/7286

**Pull request merged**
