### PR TITLE
[TIMOB-18913] VideoPlayer fix for Android L

### PR DESCRIPTION
**Pull request by ashcoding**
Jira: https://jira.appcelerator.org/browse/TIMOB-18913

App.js test code:

``` javascript
/*
 * Single Window Application
 */

// This is a single context application
(function() {
    var vidWin = Titanium.UI.createWindow({
      title : 'Video View Demo',
      backgroundColor : '#fff'
  });

  var videoPlayer = Titanium.Media.createVideoPlayer({
      top : 2,
      autoplay : true, // false
      backgroundColor : 'blue',
      height : 300,
      width : 300,
      mediaControlStyle : Titanium.Media.VIDEO_CONTROL_DEFAULT,
      scalingMode : Titanium.Media.VIDEO_SCALING_ASPECT_FIT
  });

  videoPlayer.url = 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4';
  vidWin.add(videoPlayer);
  vidWin.open();
})();
```

### CODE REVIEW

**Comment by hieupham007** [comment]
The test case above works fine, but the url from KS -> Phone -> Play Movie -> Remote doesn't work: 'http://dts.podtrac.com/redirect.mp4/twit.cachefly.net/video/aaa/aaa0033/aaa0033_h264b_640x368_256.mp4'.

**Comment by ashcoding** [comment]
Will look into this.

**Comment by ashcoding** [comment]
Test code updated with more links to try:-
```javascript

var vidWin = Titanium.UI.createWindow({
    title : 'Video View Demo',
    backgroundColor : '#fff'
});
 
var videoPlayer = Titanium.Media.createVideoPlayer({
    top : 2,
    autoplay : true,
    backgroundColor : 'blue',
    height : 300,
    width : 300,
    mediaControlStyle : Titanium.Media.VIDEO_CONTROL_DEFAULT,
    scalingMode : Titanium.Media.VIDEO_SCALING_ASPECT_FIT,
    //url : 'http://s3.amazonaws.com/playbackacp.com/865/challenge_2/865-01-05.mp4'
    //url : 'http://player.vimeo.com/external/121659103.sd.mp4?s=b04ddefe800446e09bd2cdf7e6193aa9'
    //url : 'http://clips.vorwaerts-gmbh.de/big_buck_bunny.mp4'
    //url : 'http://108.59.9.98/big_buck_bunny.mp4'
    url : 'http://dts.podtrac.com/redirect.mp4/twit.cachefly.net/video/aaa/aaa0033/aaa0033_h264b_640x368_256.mp4'
});
 
 
vidWin.add(videoPlayer);
vidWin.open();

```

**Comment by hieupham007** [comment]
Code reviewed and functionally tested on 5.1 emulator. Looks good

**Pull request merged**
