### PR TITLE
feat(ios): add install failed error message

### LINKED ISSUE #13349: iOS: optimize error message if installation fails
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

When you try to install on a device that is not registered in your prov. profiles it will fail with a JS error after "installing app..".
It was pointing to that line: https://github.com/tidev/titanium_mobile/blob/master/iphone/cli/hooks/install.js#L207
but wasn't showing a proper error message.

Tested with 10.1.1.GA and 10.2.0

error message:
```
[ERROR] Error
    at Object.<anonymous> (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/node_modules/node-appc/lib/exception.js:34:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.get (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/node_modules/node-appc/lib/appc.js:62:11)
    at Handle.<anonymous> (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/iphone/cli/hooks/install.js:207:22)
    at Handle.emit (events.js:412:35)
```

test:
* remove device from prov.profile
* build app for device

### Solution

Provide a proper error message "check prov. profiles or device".

### Alternatives

_No response_

### Platforms

iOS

### PR DESCRIPTION
**Pull request by m1ga**
Fixes https://github.com/tidev/titanium_mobile/issues/13349

Adds a new error message `Failed to transfer app to device. Check if your devices is registered in your provisioning profile.` for `0xe800001a` when the build process can't install the iOS app the end. In our case it was not registered in the prov. profile.

**Side note:**
Still have to figure out why the error (or default) error message is not showing but
```
[ERROR] Error
    at Object.<anonymous> (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/node_modules/node-appc/lib/exception.js:34:27)
    at Module._compile (internal/modules/cjs/loader.js:1085:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
    at Module.load (internal/modules/cjs/loader.js:950:32)
    at Function.Module._load (internal/modules/cjs/loader.js:790:12)
    at Module.require (internal/modules/cjs/loader.js:974:19)
    at require (internal/modules/cjs/helpers.js:93:18)
    at Object.get (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/node_modules/node-appc/lib/appc.js:62:11)
    at Handle.<anonymous> (/Users/miga/Library/Application Support/Titanium/mobilesdk/osx/10.2.0.v20220325163249/iphone/cli/hooks/install.js:207:22)
    at Handle.emit (events.js:412:35)
```

Happens with the current GA and 10.2.0. The default `For some reason the app failed to install on the device.` message is not showing up!

### CODE REVIEW

**Comment by hansemannn** [comment]
Try to replace
```js
next(new appc.exception(err, details));
```
with
```js
next(new appc.exception(details));
```

**Comment by m1ga** [comment]
Same error. Easier way to test: detach the device before it installs.
Even the [code in node-appc](https://github.com/tidev/node-appc/blob/master/lib/exception.js#L28-L34) is untouched for a while. Very strange

**Comment by cb1kenobi** [comment]
I'm fine with this change, though the error message is curious. Maybe the `message` is empty?

**Comment by hansemannn** [comment]
Since the error message will not be printed out so far (maybe due to a Node.js breaking change that broke `appc.exception`?). Therefore, I would put the `work in progress` label onto here for now.

**Comment by m1ga** [comment]
https://github.com/tidev/node-appc/blob/master/lib/exception.js#L34
if I change 
```js
AppcException.prototype = new Error();
```

to 
```js
AppcException.prototype = Object.create(Error.prototype);
// or AppcException.prototype = Error.prototype; but that is "bad form" according to the SO article below
```
I'll see the error messages again. Got the hint from https://stackoverflow.com/a/871646/5193915 and it even was like this a loooong time ago: https://github.com/tidev/node-appc/blob/ba568e1bf744f76ac522214ad09c970c392b0d73/lib/exception.js#L32

Perhaps there was a change in nodejs how to handle `new Error()`? Can't believe that is is broken for such a long time

**Comment by hansemannn** [comment]
Makes sense for me. @cb1kenobi Thoughts? The reason it may have worked for years without a code change was likely a behavioral change in a certain Node.js version.

**Comment by caspahouzer** [comment]
I deregistered my device in the provisioning file and tried to install. see the new error message 👍🏻

**Review by caspahouzer — APPROVED** [review]

**Comment by m1ga** [comment]
Removed the `work in progress` tag.  https://github.com/tidev/node-appc/pull/461 got merged so the errors will appear again. This PR will now add another error message for `0xe800001a`

**Comment by hansemannn** [comment]
@m1ga The new version of node-appc should be released and included here as well, then we can merge!

**Comment by m1ga** [comment]
`node-appc` is released with the fix, so this can be merged for the next SDK (just adding another error message to the output) :+1:

**Review by hansemannn — APPROVED** [review]

**Pull request merged**
