### PR TITLE
fix(ios): update aps libraries to fix memory leak (8_0_X)

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26811

8_0_X backport of #10704

### CODE REVIEW

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Comment by ssekhri** [comment]
@janvennemann I tried the sample app as mentioned in corresponding jira and ran it with the SDK 8.0.0.v20190215120515 available from jenkins build for this PR. I still see leaks from the app when i run it on simulator or device.
Just one device iPhone XS (iOS version 12.1.3) i do not see any leaks. That device didnt show me any leaks on 7.5.0.GA as well.
For other devices I still see leaks though they seemed less than 7.5.0.GA.
Check some of the saved instrument trace using the 8.0.0.v20190215120515 SDK. You can get them from https://axwaysoftware-my.sharepoint.com/personal/ssekhri_axway_com/Documents/Leaktest/LeakTestTrace.zip

**Comment by janvennemann** [comment]
@ssekhri please give it another try with the latest [build](https://jenkins.appcelerator.org/blue/organizations/jenkins/titanium-sdk%2Ftitanium_mobile/detail/PR-10705/3/artifacts).

**Comment by ssekhri** [comment]
@janvennemann I tried the latest commit on few devices and simulator. Still see some related leaks though the latest commit is much better than the last one.
You can find the latest leak trace from https://axwaysoftware-my.sharepoint.com/:u:/g/personal/ssekhri_axway_com/ESkrx8p-4INIt2L9wgQcXScBJF0_Hif8nAeOernICt6axQ?e=1UU1wF

**Comment by tristankenney** [comment]
Just confirming, this isn't in the 8_0_X nightly builds yet?

**Comment by ssekhri** [comment]
FR Passed. No more memory leaks seen related to APSHTTP library.
Env:
Mac OS 10.14.3
Ti SDK: 8.0.0.v20190325032239
Appc CLI: 7.0.10
Node: 8.12.0
JDK: 9.0.4
Studio: 5.1.2.201903111843
Xcode: 10.1
Devices: Sim iPhone8(v12.1). Sim iPhone6(v10.0), iPhoneXS(v12.1.3), iPhone7(12.1.1), iPadMini(v9.3.5)

**Comment by janvennemann** [comment]
@tristankenney This just passed QE testing and is available in the 8_0_X nightly builds after this PR has been merged (once the CI build status check passed).

**Comment by ssekhri** [comment]
@janvennemann, the master branch merged successfully. However the Jenkins build is failing for 8_0_X. Can you kindly check.

**Comment by nmuecke** [comment]
Can someone confirm for me that these changes have made their way into the the built 8.0.1.v20190326110553 and later? I've been testing against this build and have not seen a significant reduction in the memory leak. 
Will aim to update https://jira.appcelerator.org/browse/TIMOB-26811 with additional details tomorrow

**Comment by nmuecke** [comment]
Here is a ref to a new ticket that documents our findings
https://jira.appcelerator.org/browse/AC-6190

**Comment by nmuecke** [comment]
Basically the issue that i see is that memory is consumed by the request and 5, 10 minutes later it still not been freed. In contract the 6.30.0.GA frees the memory up after a minute or 2

**Pull request merged**
