### PR TITLE
[TIMOB-25219] Android: FileNotFoundExceptions should not be inside the Titanium log

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25219

**Description:**
This removes passing the exception object to the `Log.e` call, which should avoid printing the full exception stack trace for the exact use case Hans mentioned - when unable to open a file or URL that doesn't exist. 

There's some caveats here:
- It's entirely possible we were unable to load the file/URL input stream for other reasons beyond file not found, and this change would remove the detail to know the underlying cause of failure.
- It's also pretty likely there are lots of other places in the codebase we try to load files/URLs that we may also log the exception stack trace beyond the one Hans provided in his bug report.

### CODE REVIEW

**Comment by hansemannn** [comment]
We log the stacktrace in many places (148x). Maybe we want to hide the 3rd parameter in the default logging-state and show it when using trace-logs? How do others solve this? I am very open and happy to discuss it!

**Review by hansemannn — APPROVED** [review]

**Comment by hansemannn** [comment]
@sgtcoolguy I think this one is save to merge. Other places can be looked into in further use-cases.

**Comment by lokeshchdhry** [comment]
FR Passed.

Studio Ver:     5.1.0.201805150850
SDK Ver:        7.3.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3.1
Appc NPM:       4.2.13
Appc CLI:       7.0.3
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10
Devices:        ⇨ google Nexus 6P --- Android 8.1.0
                ⇨ google Nexus 5 --- Android 6.0.1
Emulator:       ⇨ Android 4.1.2

**Comment by lokeshchdhry** [comment]
@sgtcoolguy , the unit tests are still failing with:
```
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler: 	it.windowsAndAndroidMissing('.refreshControl (in NavigationWindow)', function (finish) {
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     ^
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler: TypeError: it.windowsAndAndroidMissing is not a function
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Suite.<anonymous> (/ti.ui.listview.test.js:872:5)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at context.describe.context.context (/ti-mocha.js:1000:9)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at /ti.ui.listview.test.js:13:1
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Module._runScript (ti:/module.js:613:9)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Module.load (ti:/module.js:105:7)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Module.loadJavascriptText (ti:/module.js:457:9)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Module.loadAsFile (ti:/module.js:512:15)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Module.loadAsFileOrDirectory (ti:/module.js:429:20)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at Module.require (ti:/module.js:256:17)
11:45:04 [android unit tests] [ERROR] :  TiExceptionHandler:     at require (ti:/module.js:570:15)
```
Can you please take a look. Thanks !!

**Comment by hansemannn** [comment]
@lokeshchdhry Addressed in https://github.com/appcelerator/titanium_mobile/pull/10060, but I don't have merge permissions either, so once it turns green, you can merge it.

**Pull request merged**
