### PR TITLE
fix(android): prevent duplicate launch animation

### PR DESCRIPTION
**Pull request by garymathews**
- Prevent duplicate launch animation from occurring on cold-start 

##### TEST CASE
- Launch any Titanium application
- Launch animation should not stutter

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27684)

### CODE REVIEW

**Review by sgtcoolguy — APPROVED** [review]
CR LGTM 👍

**Comment by lokeshchdhry** [comment]
FR Passed.

Studio Ver:       6.0.0.201911251516
SDK Ver:          9.0.0 local build
OS Ver:           10.14.5
Xcode Ver:        Xcode 11.2.1
Appc NPM:         5.0.0-2
Appc CLI:         7.1.2
Daemon Ver:       1.1.3
Ti CLI Ver:       5.2.2
Alloy Ver:        1.14.4
Node Ver:         12.13.1
NPM Ver:          6.12.1
Java Ver:         11.0.1
Android Devices:  ⇨ google Pixel (Android 10)

**Comment by jquick-axway** [comment]
This is really the same issue written here...
https://jira.appcelerator.org/browse/TIMOB-27328

I skirted the issue by switching to a fade-effect. But I think the downside of this PR removing the open animation is that if the app has a long startup time, then no open animation will occur when you open the 1st child window.

@lokeshchdhry, would you mind trying the below code. It blocks on app startup for 4 seconds before opening a window reading "Hello World". Verify that you see that an open-animation between the splash and the child window... because I think this PR has removed that animation.
```javascript
function blockThread() {
	var endTime = new Date();
	endTime.setTime(endTime.getTime() + 4000);
	while (endTime >= new Date()) {}
}
blockThread();

var window = Ti.UI.createWindow();
window.add(Ti.UI.createLabel({ text: "Hello World!" }));
window.open();
```

**Comment by garymathews** [comment]
@jquick-axway This shouldn't affect the animation of `TiActivity` windows. But I figured the fix should live in `TiLaunchActivity` instead (this won't affect the behavior of the fix). But you may want to re-test?

**Comment by lokeshchdhry** [comment]
@garymathews , can you please fix the jenkins error of `can't find symbol`

```
[2019-12-20T00:40:13.940Z] [javac] 		if (TiApplication.firstOnActivityStack()) {
[2019-12-20T00:40:13.940Z]     [javac] 		                 ^
[2019-12-20T00:40:13.940Z]     [javac]   symbol:   method firstOnActivityStack()
[2019-12-20T00:40:13.940Z] [javac]   location: class TiApplication

```

**Comment by sgtcoolguy** [comment]
Looks like the latest force push missed some code or something.

**Pull request merged**
