### PR TITLE
Update Ti.Map and Ti.Facebook releases

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/NOTICKET-0000

Our Ti.Map and Ti.Facebook recently got many bug fixes, mostly on Android. We need to update the modules for the core to reflect these improvements.

> **DO NOT MERGE** so far. The unit-tests uncovered a possible Android issue with the new Ti.Map module (yey) that @ypbnv currently inspects.

### CODE REVIEW

**Comment by hansemannn** [comment]
@ypbnv do you have an update on the Ti.Map issue here?

**Comment by ypbnv** [comment]
@hansemannn Sorry for getting back to you so late? Is the issue you mentioned here the one that we discussed about adding a MapView to a TabGroup ?

**Comment by hansemannn** [comment]
Yes

**Comment by ypbnv** [comment]
I can't reproduce the test failure locally and it seems to be passing on the build machine too now.

**Comment by hansemannn** [comment]
It seems fine now, maybe a temporary issue with Jenkins. The other Ti.Map fixes go into the next Ti.Map version then!

**Pull request merged**
