### PR TITLE
fix(ios): sync wkwebview cookies in shared storage

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-27751

### CODE REVIEW

**Comment by janvennemann** [comment]
@vijaysingh-axway

**Comment by vijaysingh-axway** [comment]
@janvennemann First solution, I tried,  was the same as you have mentioned. But it does not give the cookies.

**Review by janvennemann — APPROVED** [review]
Damn, ok, then we'll have to go with this for now.

**Comment by lokeshchdhry** [comment]
FR Passed.

Checked & I can get the ASP.net cookies as well. With out the fix we used to get only 1 cookie. With the fix we get 3 cookies.

Studio Ver:       6.0.0.202003181504
SDK Ver:          9.1.0 local build
OS Ver:           10.14.5
Xcode Ver:        Xcode 11.3.1
Appc NPM:         5.0.0
Appc CLI:         8.0.0
Daemon Ver:       3.2.0
Ti CLI Ver:       5.2.2
Alloy Ver:        1.14.6
Node Ver:         12.13.1
NPM Ver:          6.12.1
Java Ver:         11.0.1
IOS Devices:      ⇨ iPhone 13.3.1

**Pull request merged**
