### PR TITLE
[6_2_X][TIMOB-1072] Android: Added RefreshControl support to ListView and TableView.

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-1072

**Cherry Pick of:** #9356

### CODE REVIEW

**Comment by hansemannn** [comment]
@jquick-axway Can you sign the [CLA](https://cla.appcelerator.com/) so all tests pass? :-)

**Review by hansemannn — APPROVED** [review]
My FT **passed** (awaiting QE-test as well). 

One side-note: We may want to change [this line](https://github.com/appcelerator/titanium_mobile/pull/9357/files#diff-457b9c419468df9ca1302ebb9ec48236R3) to either link to the native SwipeRefreshLayout as well or just remove the reference. Also, [this line](https://github.com/appcelerator/titanium_mobile/pull/9357/files#diff-457b9c419468df9ca1302ebb9ec48236R6) indicates support for list-, table- and scroll-view. We should put a `(iOS only)` behind the scroll-view phrase.

P.S.: Can you please sign the [CLA](https://cla.appcelerator.com/) so all tests pass? :-)

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Comment by jquick-axway** [comment]
Updated PR based on @hansemannn and @ypbnv 's feedback. Thanks guys!

**Comment by lokeshchdhry** [comment]
FR Passed.

`RefreshControl` works as expected with `tableView`, `listView`. On `scrollView` it shows a message `Ti.UI.ScrollView does not support a RefreshControl on Android, yet.`

Studio Ver: 4.9.1.201707200100
SDK Ver: 6.2.0 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.9
Appc CLI: 6.2.3
Ti CLI Ver: 5.0.14
Alloy Ver: 1.9.13
Node Ver: 6.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1
               ⇨ google Pixel --- Android 7.1.1
Emulator: Android 4.4.2

**Pull request merged**
