### PR TITLE
[TIMOB-25526] Android: Listview when showing image with defaultImage causing inconsistency on image

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25526

**Description:**
Add `image` property to the list to be set when a view is recycled.
Fix a typo in a comment.

**Test case:**
In the JIRA ticket.

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by ypbnv** [comment]
@garymathews, @jquick-axway I was not able to get some reliable unit tests. Any suggestions?

**Comment by lokeshchdhry** [comment]
FR Passed.

The`image` is refreshed successfully when the `listview` is scrolled.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.0.0 local build
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.11
Appc CLI:       7.0.0
Ti CLI Ver:     5.0.14
Alloy Ver:      1.10.10
Node Ver:       8.9.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Pixel --- Android 7.1.1
                ⇨ google Nexus 5 --- Android 6.0.1

**Comment by jquick-axway** [comment]
@ypbnv, @sgtcoolguy,

I don't think we can do a unit test for this on the JavaScript side. Our ListView does not provide APIs that give direct access to its views on purpose (so that they can be recycled for performance reasons). This should be tested manually by taking a screenshot of the results and then measure the image's pixel dimensions via Apple "Preview" or MS Paint.

**Comment by lokeshchdhry** [comment]
@sgtcoolguy , I think we can merge this as according to @ypbnv & @jquick-axway there can't be unit tests for this.

**Comment by sgtcoolguy** [comment]
ok, well it's complaining about formatting of one file, and a unit test failed. At least the formatting should be fixed as per the instructions in the comment from danger.

**Pull request merged**
