### PR TITLE
[TIMOB-23788][TIMOB-23710] Updated aps-analytics

### PR DESCRIPTION
**Pull request by ashcoding**
https://jira.appcelerator.org/browse/TIMOB-23788

### CODE REVIEW

**Comment by ashcoding** [comment]
**Do not merge yet**
Checking if the issue https://jira.appcelerator.org/browse/TIMOB-23710 occurs for this.

**Comment by ashcoding** [comment]
It does occur.
```
[ERROR] :  Failed to run dexer:
[ERROR] :  
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CritterCallback;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CritterRateMyAppButtons;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CritterUserData;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CritterUserDataRequest;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CritterUserDataRequest$1;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/Crittercism;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CrittercismConfig;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/CrittercismNDK;
[ERROR] :  Uncaught translation error: java.lang.IllegalArgumentException: already added: Lcom/crittercism/app/Transaction;
[ERROR] :  
[ERROR] :  UNEXPECTED TOP-LEVEL EXCEPTION:
[ERROR] :  java.lang.RuntimeException: Translation has been interrupted
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:613)
[ERROR] :  	at com.android.dx.command.dexer.Main.runMultiDex(Main.java:366)
[ERROR] :  	at com.android.dx.command.dexer.Main.run(Main.java:275)
[ERROR] :  	at com.android.dx.command.dexer.Main.main(Main.java:245)
[ERROR] :  	at com.android.dx.command.Main.main(Main.java:106)
[ERROR] :  Caused by: java.lang.InterruptedException: Too many errors
[ERROR] :  	at com.android.dx.command.dexer.Main.processAllFiles(Main.java:605)
[ERROR] :  	... 4 more
```

**Comment by ashcoding** [comment]
Took the changes from https://jira.appcelerator.org/browse/TIMOB-23710 and https://github.com/appcelerator/titanium_mobile/pull/8203/files for this PR.

**Comment by cheekiatng** [comment]
APPROVED!

**Pull request merged**
