### PR TITLE
[TIMOB-24408] Android: Add support for RequestHeaders for ImageViews

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24408

**Description:**
Add support for `requestHeaders` property in ImageView.
Remove requirement of having granted READ_EXTERNAL_STORAGE to use ResponseCache.

Note: I have some concerns about using the ResponseCache on lower API levels (16-21) and interaction with external memory permissions. Will update once I have tested on broader range of devices.

**Test case:**
app.js
```
var win = Ti.UI.createWindow({backgroundColor: '#fff'}),
	buttonHeaders = Ti.UI.createButton({title: 'Headers', top: 10, left: 60}),
	buttonNoHeaders = Ti.UI.createButton({title: 'No Headers', top: 10, left: 160});

buttonHeaders.addEventListener('click', function () {
	createImage({'Authorization' : 'Basic ' + Ti.Utils.base64encode('hans:test')}, 80);
});

buttonNoHeaders.addEventListener('click', function () {
	createImage(null, 150);
});

function createImage(headers, top) {
	var imageView = Ti.UI.createImageView({
		top: top,
		image: 'http://hans-knoechel.de/test/test.png',
		requestHeaders: headers
	});
	win.add(imageView);
}

win.add(buttonHeaders);
win.add(buttonNoHeaders);
win.open();
```
Once the image is successfully loaded in the response cache it won't need the request headers property to load it again.

### CODE REVIEW

**Comment by drauggres** [comment]
> Remove requirement of having granted READ_EXTERNAL_STORAGE to use ResponseCache.

[TIMOB-25507](9596)

**Comment by jquick-axway** [comment]
@ypbnv, the `TiDrawableReference.getBitmap()` method also downloads images too and you're not setting the request headers there. This part of the code gets executed when the given URL receives a "redirect" response (ie: HTTP status code of 3xx) when redirecting between HTTP->HTTPS or vice-versa. The Java `HttpURLConnection.setInstanceFollowRedirects(true)` does not automatically redirect when switching between HTTP<->HTTPS.

Note that I don't agree with this download code being under `getBitmap()`. The redirect support between HTTP/HTTPS should be in `TiDownloadManager` and `TiFileHelper`, but to keep it simple for the moment, perhaps just add the request headers to `getBitmap()` for now and we can refactor the rest of the code later. _(I'm sitting on 6 month old code that does refactor it, but it's unmergeable now.)_

**Comment by jquick-axway** [comment]
Or perhaps we should not implement request headers in `TiFileHelper` and `TiDrawableReference`. 

Since this new HTTP request headers feature is only supported by `ImageView.image` and `TiUIImageView` does an async download itself via `TiDownloadManager`, you can keep the feature constrained between the `TiUIImageView` and `TiDownloadManager` Java classes.

I say this because I know for a fact that setting `View.backgroundImage` to a URL will cause a crash on Android (`HttpUrlConnection` throws a `NetworkOnMainThreadException`) because it'll attempt to do a blocking download on the UI thread in `TiFileHelper`. The download code in `TiDrawableReference.getBitmap()` has the same issue.

**Review by jquick-axway — CHANGES_REQUESTED** [review]
See my earlier comments.

**Comment by ypbnv** [comment]
@jquick-axway Updated the PR. Removed the unnecessary reguestHeaders property from TiFileHelper and TiDrawableReference. Also update the test case to take advantage of the ResponseCache.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
@ypbnv , I am seeing issues with emulator API 16-21. I am running your test code.

When I click `Headers` I see:
```
[ERROR] :  TiDownloadManager: (pool-5-thread-1) [13373,13373] Exception downloading http://hans-knoechel.de/test/test.png
[ERROR] :  TiDownloadManager: java.io.FileNotFoundException: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDownloadManager: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
[ERROR] :  TiDownloadManager: 	at org.appcelerator.titanium.util.TiDownloadManager$DownloadJob.run(TiDownloadManager.java:173)
[ERROR] :  TiDownloadManager: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[ERROR] :  TiDownloadManager: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[ERROR] :  TiDownloadManager: 	at java.lang.Thread.run(Thread.java:818)
[ERROR] :  TiDrawableReference: (pool-6-thread-1) [4107,17480] Problem opening stream with url http://hans-knoechel.de/test/test.png: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDrawableReference: java.io.FileNotFoundException: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDrawableReference: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiFileHelper.handleNetworkURL(TiFileHelper.java:252)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiFileHelper.openInputStream(TiFileHelper.java:188)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getInputStream(TiDrawableReference.java:895)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:345)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:329)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiLoadImageManager$LoadImageJob.run(TiLoadImageManager.java:132)
[ERROR] :  TiDrawableReference: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[ERROR] :  TiDrawableReference: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[ERROR] :  TiDrawableReference: 	at java.lang.Thread.run(Thread.java:818)
```

When I click `No Headers` I see:
```
[ERROR] :  TiDrawableReference: (pool-6-thread-1) [618,18912] Problem opening stream with url http://hans-knoechel.de/test/test.png: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDrawableReference: java.io.FileNotFoundException: http://hans-knoechel.de/test/test.png
[ERROR] :  TiDrawableReference: 	at com.android.okhttp.internal.http.HttpURLConnectionImpl.getInputStream(HttpURLConnectionImpl.java:206)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiFileHelper.handleNetworkURL(TiFileHelper.java:252)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiFileHelper.openInputStream(TiFileHelper.java:188)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getInputStream(TiDrawableReference.java:895)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:372)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.view.TiDrawableReference.getBitmap(TiDrawableReference.java:329)
[ERROR] :  TiDrawableReference: 	at org.appcelerator.titanium.util.TiLoadImageManager$LoadImageJob.run(TiLoadImageManager.java:132)
[ERROR] :  TiDrawableReference: 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
[ERROR] :  TiDrawableReference: 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
[ERROR] :  TiDrawableReference: 	at java.lang.Thread.run(Thread.java:818)
```

Things run fine on API 23 and above.

**Comment by jquick-axway** [comment]
@lokeshchdhry, try entering the below URL into your web browser. When it asks for your username and password, enter "hans" and "test" respectively. Does an image file get download after doing this?
http://hans-knoechel.de/test/test.png

**Comment by lokeshchdhry** [comment]
@jquick-axway , Yes it works fine in a browser. It asks for username & password. Entering the credentials downloads the image file.

**Comment by jquick-axway** [comment]
This does not appear to be an issue with using a high API Level call. I'm thinking that the newer Android OS versions (the versions that are working) is automatically adding a header to the request which is allowing the download to succeed. Such as an "Accept" or "Content-Type" header. I know iOS will do this.

@lokeshchdhry, try adding the following headers to the following request (ie: in addition to the authorization header).
`Accept: */*`
`Accept-Encoding: identity`

Setting the "Accept-Encoding" to "identity" tells the web server not to gzip the file in the response. I know that old versions of the Android OS do not automatically decompress gzip responses, but I don't remember which OS versions they changed this.

**Comment by lokeshchdhry** [comment]
@jquick-axway , that didn't work either.

**Comment by ypbnv** [comment]
@jquick-axway @lokeshchdhry My bad here. Adding the `requestHeaders` as a property to a `TiDrawableReference` was to workaround lower API level not caching the response in ResponseCache. I didn't take that into account when I removed them and I tested on a device with newer Android version. I didn't find anything confirming why `ResponseCahce` does not work with `URLConnection` for API 16-21 though.
I tried to somehow get it working and keep the headers only between the DownloadManager and the TiUIImageView, but without any success. With some refactoring I believe I can put together our own caching that works across the Android levels, but that would need a more significant chunk of time.

**Comment by hansemannn** [comment]
We decided to go with a CommonJS module for this to handle the networking code with existing cross-platform technologies. Details in the JIRA ticket!

**Pull request closed without merging**
