### PR TITLE
impr(android): allow gradle to automatically download missing dependencies

### PR DESCRIPTION
**Pull request by garymathews**
- Allow Gradle to automatically download and install missing dependencies (Android SDK, Build-tools etc..)
- These changes will offload SDK validation to Gradle

##### TEST CASE \#1
- Remove `Android SDK Platform 29`
- Attempt to build Titanium application
- Gradle should download and install `Android SDK Platform 29` and build successfully

##### TEST CASE \#2
- Remove `Android SDK Build-Tools`
- Attempt to build Titanium application
- Gradle should download and install `Android SDK Build-Tools` and build successfully

##### TEST CASE \#3
- Remove `Android SDK Platform-Tools`
- Attempt to build Titanium application
- Gradle should download and install `Android SDK Platform-Tools` and build successfully

##### TEST CASE \#4
- Remove `Android SDK Tools`
- Attempt to build Titanium application
- Gradle should download and install `Android SDK Tools` and build successfully

#### Repeat test cases for Titanium native module

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-27686)

### CODE REVIEW

**Comment by jquick-axway** [comment]
I think an app build will still fail if you set the `--no-prompt` flag.
```
appc run -p android --no-prompt --build-only
```

Our `_build.js` script's `cli:pre-validate` event listener is still asserting when tools are missing, such as for `ANDROID_SDK_MISSING_PROGRAMS`.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Review by ssjsamir — COMMENTED** [review]
@garymathews When following the instructions mentioned in the description and building using `appc run -p android --no-prompt --build-only` I get the following error for Step 3 and Step 4 [`ERROR] Missing required option: --device-id <name>`

**Test Steps:**
1. Created a new Titanium application 
2. Removed `Android SDK Platform 29`
3. Built application
4. Able to build to build using the instructions mentioned in step one. 
**Note:** It will not download system images needed for emulators just the `Android SDK Platform 29` which is needed for building. If you try to build to an emulator the below is error is shown. 
```
[ERROR]  Emulator exited with error: 1

[ERROR]  PANIC: Broken AVD system path. Check your ANDROID_SDK_ROOT value [/Users/Samir/Library/Android/sdk]!

Build failed. Process exited with code 1.
```
5. Removed Android SDK Build-Tools
6. Attempted to build Titanium application
7. Application built without any issues and SDK Builds-Tools were installed
8. Removed Android SDK Platform-tools
9. Attempted to build Titanium application
10. **_Following error is shown_**
```
[ERROR] Missing required option: --device-id <name>
```
11. Removed Android SDK Tools
12. Attempted to build Titanium application
13. **_Following error is shown_**
```
[ERROR] Missing required option: --device-id <name>
```
**Test Environment**
```
MacOS Catalina: 10.15.1 beta
Xcode: 11.3
Java Version: 1.8.0_131
Android NDK: 18.1.5063045
Node.js: 10.16.3
"NPM":"4.2.15-1","CLI":"7.1.2-7"
Pixel xl (7.1.1) Emulator
```

**Comment by garymathews** [comment]
@ssjsamir Thanks for finding that, I've updated the PR.

**Comment by ssjsamir** [comment]
@garymathews For the first three test cases everything seems fine but for number 4 when I try to build without the tools folder, the application builds without downloading/installing anything to the `Library/Android/sdk` location. And when I try to run the application normally (to an Android emulator) I get the following error: 
```
[WARN]   Unable to find any emulators, possibily due to missing dependencies.
Continuing with build... (will attempt to install missing dependencies)
2020-01-29T14:21:19.740Z | ERROR | An uncaught exception was thrown!
Cannot read property 'once' of undefined
2020-01-29T14:21:19.741Z | ERROR | Cannot read property 'once' of undefined
Build failed. Process exited with code 1.
```

**Comment by garymathews** [comment]
@ssjsamir I'm having trouble reproducing that issue, what are the steps your doing for 4?

The app builds fine when I remove `Android SDK Tools` or delete the `tools` folder from `../Android/sdk`.
```
[INFO]  Building for target: emulator
[INFO]  Performing build only
...
[INFO]  [GRADLE] BUILD SUCCESSFUL in 12s
[INFO]  [GRADLE] 45 actionable tasks: 45 executed
[INFO]  Writing build manifest: /Users/gmathews/projects/classicTest/build/android/build-manifest.json
[INFO]  Performed build only, skipping installing of the application
[INFO]  Project built successfully in 15s 124ms
```

**Comment by ssjsamir** [comment]
@garymathews The app is building fine but Tools is not actually being downloaded/installed in the SDK location for me unlike the others.

**Comment by garymathews** [comment]
It will only download the dependencies it needs to build the app, so if the apps building fine then it won't download additional dependencies. I think this behaviour is fine then?

**Comment by ssjsamir** [comment]
@garymathews That seems fine with me. To get the above error I ran to an emulator after removing the `tools` folder rather than doing a `build-only`.

**Review by ssjsamir — APPROVED** [review]
**FR Passed** able to build with the following missing dependencies `Android SDK Platform 29`, `Android SDK Build-Tools` , `Android SDK Platform-Tools` and `Android SDK Tools. 
`
**Test Environment**
```
MacOS Catalina: 10.15.1 beta
Xcode: 11.3
Java Version: 1.8.0_131
Android NDK: 18.1.5063045
Node.js: 10.16.3
"NPM":"4.2.15-1","CLI":"7.1.2-7"
Pixel xl (7.1.1) Emulator
```

**Pull request merged**
