### PR TITLE
[TIMOB-25359] Android: Fix Ti.UI.ScrollView when keyboard is active

### PR DESCRIPTION
**Pull request by garymathews**
- Allow `Titanium.UI.ScrollView` to scroll by default when the keyboard is active

###### TEST CASE
```JS
var win = Ti.UI.createWindow({
        backgroundColor: 'white',
        windowSoftInputMode: Ti.UI.Android.SOFT_INPUT_STATE_HIDDEN
    }),
    scrollView = Ti.UI.createScrollView({
        layout: 'vertical'
    }),
    userField = Ti.UI.createTextField({
        hintText: 'USERNAME',
        hintTextColor: 'grey',
        top: '250dp',
        left: '10%', right: '10%',
        backgroundColor: 'transparent',
        width: Titanium.UI.FILL
    }),
    passwordField = Ti.UI.createTextField({
        hintText: 'PASSWORD',
        hintTextColor: 'grey',
        passwordMask: true,
        left: '10%', right: '10%',
        backgroundColor: 'transparent',
        width: Titanium.UI.FILL
    }),
    loginButton = Ti.UI.createButton({
        width: '80%',
        title: 'LOGIN'
    });

scrollView.add([userField, passwordField, loginButton]);

win.add(scrollView);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-25359)

### CODE REVIEW

**Review by ypbnv — CHANGES_REQUESTED** [review]
Missing the following imports:
```
import android.view.Window;
import android.view.WindowManager;
import org.appcelerator.titanium.TiBaseActivity;
```

**Comment by garymathews** [comment]
@lokeshchdhry Updated PR

**Comment by lokeshchdhry** [comment]
FR Passed.

`scrollView` is scrollable when keyboard is up.

Studio Ver: 4.10.0.201709271713
SDK Ver: 7.0.0 local build
OS Ver: 10.12.3
Xcode Ver: Xcode 8.3.3
Appc NPM: 4.2.9
Appc CLI: 6.2.4
Ti CLI Ver: 5.0.14
Alloy Ver: 1.9.14
Node Ver: 7.10.1
Java Ver: 1.8.0_101
Devices: ⇨ google Nexus 5 --- Android 6.0.1

**Review by ypbnv — APPROVED** [review]
CR: Pass

**Pull request merged**
