### PR TITLE
iOS : Add ability to detect permission for camera

### PR DESCRIPTION
**Pull request by ghost**
Sample JS :

```
Ti.Media.requestCameraAuthorization(function(e) {
    if (e.success) {
      // You have camera access
    } else {
      // Denied camera access
    }
});
```

### CODE REVIEW

**Comment by itsbrnrd** [comment]
Hi there,
Thanks a lot for the PR, I'd love to see this feature in the Titanium SDK :)
I wanted to try it before it was merged and (hopefully) officially released. Here is the code I used in my `app.js` in order to test it:
``` javascript
Ti.Media.requestCameraAuthorization(function(e) {
    if (e.success) {
    	Ti.API.info('ACCEPTED');
    } else {
    	Ti.API.info('DENIED');
    }
});
```
The problem is that when the request popup appears, the callback is immediately fired and shows `ACCEPTED` in the console before I even accept or refuse the camera.

Is this the behavior you intended ? I thought that the callback would be fired when the user clicks on a button of the request popup and that `e.success` would be `true` when he accepts the camera.

Cheers

**Comment by itsbrnrd** [comment]
_Disclamer: I'm not an iOS / Objective-C developper_

I did some research and found a nice StackOverflow post about the subject : http://stackoverflow.com/questions/25803217/presenting-camera-permission-dialog-in-ios-8

I modified your code as follow: 

``` objective-c
-(void)requestCameraAuthorization:(id)args
{
  ENSURE_SINGLE_ARG(args, KrollCallback);
  KrollCallback * callback = args;

  TiThreadPerformOnMainThread(^(){
    [AVCaptureDevice requestAccessForMediaType:AVMediaTypeVideo completionHandler:^(BOOL granted) {
        KrollEvent * invocationEvent = [[KrollEvent alloc] initWithCallback:callback
	      eventObject:[TiUtils dictionaryWithCode:(granted ? 0 : 1) message:nil]
	      thisObject:self];
	    [[callback context] enqueue:invocationEvent];
	    RELEASE_TO_NIL(invocationEvent);
    }];
  }, NO);
}
```

and it worked !

Here are the scenarios I tested:
- When the user install the app for the first time, he's prompted the request dialog and the callback is called *only* when he accepts or denies the camera request.
- When the user has already denied or accepted the camera, it fires the callback and correctly sets the `success` value according to the current camera authorisation.

**If an iOS developper / engineer could answer this:**
In the SO post (see above link), OP mentions something about iOS6 specificity about camera authorisation. Is this still needed ?

**Comment by ingo** [comment]
@jonalter, thoughts?

**Comment by shopmium** [comment]
@itsbrnrd Thanks for your help :+1: 
I will update my pull request with your contribution !

I'm not absolutely sure but i think the authorization to access photos / camera is only for iOS 7 & 8

**Comment by pec1985** [comment]
Code looks good. It's missing documentation, if you could [add it here](https://github.com/appcelerator/titanium_mobile/blob/master/apidoc/Titanium/Media/Media.yml), we'll test it and merge it

**Comment by hansemannn** [comment]
Am i allowed to finish the documentation files? If so, we could accelerate the merge process.

**Comment by ingo** [comment]
@hansemannn sure, go ahead.

**Comment by hansemannn** [comment]
@ingo what version should be used in the "since" section?

**Comment by ingo** [comment]
The "since" relates to when it's available in Titanium SDK, so in this context, it would be 4.1.0. Your proposal for renaming sounds good...except, perhaps we should have a single method and pass a parameter specifying what we are requisition permissions for? I worry there will be something else we'll need permissions to do in the future.

**Comment by hansemannn** [comment]
We could create constants like:

- `Ti.UI.Media.AUTHORIZATION_AUDIO`
- `Ti.UI.Media.AUTHORIZATION_CAMERA`

and use them as the first parameter:

```
Ti.Media.requestAuthorization(Ti.UI.Media.AUTHORIZATION_CAMERA, function(e) {
    if (e.success) {
        Ti.API.info('ACCEPTED');
    } else {
        Ti.API.info('DENIED');
    }
});
```

but i must confess, that i'm not that into the Obj-C development, yet to perform these changes. Anyway, i could help to complete the documentation.

**Comment by hansemannn** [comment]
Closing in favor of #7271

**Pull request closed without merging**
