### PR TITLE
fix(android): hide/show progress dialog back-to-back puts it in bad state as if 8.1.1

### PR DESCRIPTION
**Pull request by jquick-axway**
**JIRA:**
https://jira.appcelerator.org/browse/TIMOB-27573

**Summary:**
Calling progress dialog's `hide()` and then immediately `show()` back-to-back prevents the dialog from ever being hidden again. Caused by the Java `onDismiss()` listener for previous dialog being invoked just after `show()` method call for the new dialog.

**Test 1:**
_(Verifies the above ticket's fix.)_
1. Build and run the code attached to [TIMOB-27573](https://jira.appcelerator.org/browse/TIMOB-27573) on Android.
2. Tap on the "Show Progress Dialog" button.
3. Verify that dialog is shown.
4. Verify that dialog is quickly hidden/shown 3 seconds later.
5. Verify that dialog is hidden 2 seconds. _(This used to fail.)_

---
**Test 2:**
_(Verifies progress dialog can be re-shown after auto-closed.)_
1. Build and run the code attached to [TIMOB-27309](https://jira.appcelerator.org/browse/TIMOB-27309) on Android.
2. Tap on the "Show Progress Dialog" button.
3. Wait 2 seconds for the progress dialog and its window to close.
4. Tap on the "Show Progress Dialog" button again.
5. Verify that the progress dialog is re-shown.

### CODE REVIEW

**Comment by hansemannn** [comment]
Can this be a 9.0.2 candidate as it seems to be a regression? We may run into this as well.

**Comment by jquick-axway** [comment]
@hansemannn, the team doesn't want to add anymore tickets to 9.0.2 unless it's a show-stopper issue, because we plan on doing a release soon.

But you shouldn't be running into this issue unless you do exactly this...
```javascript
const window = Ti.UI.createWindow();
const progressIndicator = Ti.UI.Android.createProgressIndicator({
	message: "Loading...",
	location: Ti.UI.Android.PROGRESS_INDICATOR_DIALOG,
	cancelable: true,
});
window.addEventListener("open", () => {
	progressIndicator.show();
	setTimeout(() => {
		// Calling hide/show back-to-back prevents it from being hidden.
		progressIndicator.hide();
		progressIndicator.show();
	}, 1000);
});
window.open();
```

**Comment by hansemannn** [comment]
Yep, thats exactly what we do - showing concurring loaders. But with different instances. Does it not happen then? Then we're fine!

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Comment by ssekhri** [comment]
FR Passed.

Verified on:
Mac OS: 10.15.4
SDK: 9.1.0.v20200511102344
Appc CLI: 8.0.0
JDK: 11.0.4
Node: 10.16.3
Studio: 6.0.0.202005071607
Device: Nexus4(v5.1.1) device, Pixel3(v10.0) emulator

**Pull request merged**
