### PR TITLE
feat(android): ImageView scaleType

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24313

revive https://github.com/appcelerator/titanium_mobile/pull/8755 and make it more customizable.
Adding three modes (https://thoughtbot.com/blog/android-imageview-scaletype-a-visual-guide)
`Ti.Media.IMAGE_SCALING_CENTER, Ti.Media.IMAGE_SCALING_CENTER_CROP, Ti.Media.IMAGE_SCALING_CENTER_INSIDE`

`Ti.Media.IMAGE_SCALING_DEFAULT` is the current mode.

**Example:**

```javascript
var win = Ti.UI.createWindow({
	title: "img",
	backgroundColor: '#fff'
});

var scaleType = 0;
var scaleTypes = [
	Ti.Media.IMAGE_SCALING_DEFAULT,
	Ti.Media.IMAGE_SCALING_CENTER,
	Ti.Media.IMAGE_SCALING_CENTER_CROP,
	Ti.Media.IMAGE_SCALING_CENTER_INSIDE
]
var img = Ti.UI.createImageView({
	image: "./appicon.png",
	width: 400,
	height: 200,
	borderWidth: 1,
	borderColor: "#000",
	scaleType: scaleTypes[scaleType]
});

var btn = Ti.UI.createButton({
	title: "change",
    bottom: 20
});

btn.addEventListener("click", function() {
	scaleType++;
	if (scaleType == 4) {
		scaleType = 0;
	}
    console.log("ScaleType: ", scaleTypes[scaleType]);
	img.scaleType = scaleTypes[scaleType];
})

win.add(img);
win.add(btn)
win.open();
```

someone else need to make the iOS part.

### CODE REVIEW

**Comment by jquick-axway** [comment]
@m1ga , the only problem with this is that the EXIF orientation will be ignored. Odds are most devs will use scale type when displaying camera photos which almost always have EXIF applied. The only way to do both (that I know of) is to do the matrix math yourself.

The ideal solution would be for us to refactor our image loading code so that it always decodes JPEGs in the upright position like iOS, which would then make features like this trivial. It always come back to that. _(sigh)_

**Comment by m1ga** [comment]
I understand, I hate exif on Android too :smile:  I've tested it with: 
```ExifFlipHorizontal.jpg
ExifFlipVertical.jpg
ExifRotate90.jpg
ExifRotate180.jpg
ExifRotate270.jpg
ExifTranspose.jpg
ExifTransverse.jpg
```
from the test folder. The images are not rotated with 9.2.2.GA, too. So this PR will just add new modes and if you want to use it with local images (correct exif) it will be very helpful.

**Comment by jquick-axway** [comment]
@m1ga , PR #12753 handles Android EXIF orientation/mirroring while simultaneously supporting scale modes. It also adds support on iOS for parity.

**Comment by m1ga** [comment]
awesome! Center should be fine for most cases too. I'll close this one.

**Pull request closed without merging**
