### PR TITLE
[TIMOB-24866] (6_2_X) Android: Fix textAlign with padding

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24866

### CODE REVIEW

**Comment by hansemannn** [comment]
@m1ga Cool! PR against master as well? :)

**Comment by m1ga** [comment]
Already done ;)

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Review by ssjsamir — APPROVED** [review]
**FR Passed:** Alignment of text no longer changes when padding is set. 

**Test Steps**
+ Downloaded the SDK Build from this PR
+ Created a new Titanium project
+ Copied the test case from description https://jira.appcelerator.org/browse/TIMOB-24866
+ Ran the application 
+ Saw the text in correct positions
screen shot 2017-07-26 at 9 51 01 am

+ Pressed "Set Padding"
+ Padding was set without the text changing alignment
screen shot 2017-07-26 at 9 52 27 am


**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

**Pull request merged**
