### PR TITLE
fix(ios): guard source property and removed NSNull if it is nil

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-27354

### CODE REVIEW

**Review by sgtcoolguy — APPROVED** [review]
LGTM

**Comment by expergefactor** [comment]
**FR Failed** undefined still showing as before

Tested using the test apps (First and Second) and test steps mentioned [here](https://jira.appcelerator.org/browse/TIMOB-27354)

**See screenshot below**

Screenshot 2019-10-02 at 15 52 56

**Test Environment**

MacOS Mojave 10.14.6
Xcode 11
Node 10.16.3
iPhone 11 Pro Sim(13.0)
{"NPM":"4.2.15","CLI":"7.1.1"}

**Comment by lokeshchdhry** [comment]
@expergefactor , Did you use :
```
Ti.App.iOS.addEventListener("handleurl", function () {
	alert("Second app on resume from url : " + Ti.App.getArguments().url);
});
```
In your alloy.js in both apps ?

**Comment by expergefactor** [comment]
> @expergefactor , Did you use :
> 
> ```
> Ti.App.iOS.addEventListener("handleurl", function () {
> 	alert("Second app on resume from url : " + Ti.App.getArguments().url);
> });
> ```
> 
> In your alloy.js in both apps ?



> @expergefactor , Did you use :
> 
> ```
> Ti.App.iOS.addEventListener("handleurl", function () {
> 	alert("Second app on resume from url : " + Ti.App.getArguments().url);
> });
> ```
> 
> In your alloy.js in both apps ?

I have used the updated code in both apps. I can confirm that the updated code works.

**FR Passed**

**Comment by Dankyi** [comment]
FR Passed - "First/Second app on resume from url: undefined" prompt didn't showed up in all the tests I run.

**Test Environment:**
```
Mac OS X 10.14.5
Node.js Version 10.16.3
Xcode 10.3 (build 10G8) - Xcode default
npm Version 6.9.0
Iphone 7 iOS Version 13.0
```

**Pull request merged**
