### PR TITLE
[TIMOB-23141] iOS: Apply Ti.Filesystem.File.remoteBackup settings recursively

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23141

### CODE REVIEW

**Comment by hansemannn** [comment]
test this please

**Comment by hansemannn** [comment]
test this please

**Comment by hansemannn** [comment]
test this please

**Comment by hansemannn** [comment]
test this please

**Comment by cheekiatng** [comment]
CR and FT passed. APPROVED.

**Pull request merged**
