### PR TITLE
fix(ios): Added missing flag to code sign TitaniumKit so device builds work again.

### PR DESCRIPTION
**Pull request by cb1kenobi**
Added missing flag to code sign TitaniumKit so device builds work again.

Fixes TIMOB-26520.

**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26520

Note: this regression was introduced when PR #10218 (TIMOB-25927) landed.

### CODE REVIEW

**Comment by janvennemann** [comment]
@cb1kenobi can you fix the linting issues? Is this ready to be merged or are more changes required?

**Comment by cb1kenobi** [comment]
@janvennemann As stated in the description and in standup, I'm still working on this.

**Comment by cb1kenobi** [comment]
@janvennemann This PR is now ready for test.

**Review by janvennemann — APPROVED** [review]
LGTM, CR passed

**Review by ssjsamir — APPROVED** [review]
**FR Passed:** Able to build to iOS devices

**Test Environment** 
```
APPC Studio: 5.1.0.201808080937
iPhone 6 plus (iOS 12.1)
APPC CLI: 7.0.8
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.1
Node.js Version: 8.9.1
Xcode 10.1
```

**Comment by PietroGranati** [comment]
A jira bug (https://jira.appcelerator.org/browse/TIMOB-26520) send me there, I still figure the problem when building with SDK 8

**Pull request merged**
