### PR TITLE
fix(ios): Use correct path for modules having incorrect template

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-26591

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**

This fixed my issue when compiling the ACA module 👍

**Comment by keerthi1032** [comment]
@vijaysingh-axway ,with the fix ti.barcode module  built sucessufully and works fine. but when i built ti.coremotion module im seeing the following error. im getting the same error on 7.5.GA for ti .coremotion module . Can you please look at it

  "[ERROR] [xcode-sim] ** BUILD FAILED **
[ERROR] [xcode-sim] The following build commands failed:
[ERROR] [xcode-sim] 	CompileC build/ti.coremotion.build/Release-iphonesimulator/ti.coremotion.build/Objects-normal/i386/TiCoremotionMotionActivityProxy.o Classes/TiCoremotionMotionActivityProxy.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] [xcode-sim] 	CompileC build/ti.coremotion.build/Release-iphonesimulator/ti.coremotion.build/Objects-normal/i386/TiCoremotionMagnetometerProxy.o Classes/TiCoremotionMagnetometerProxy.m normal i386 objective-c com.apple.compilers.llvm.clang.1_0.compiler
[ERROR] [xcode-sim] (2 failures)"

**Comment by vijaysingh-axway** [comment]
@keerthi1032 Have you changed 
TITANIUM_SDK_VERSION = 7.5.0.GA 
in titanium.xcconfig of module?

**Review by longton95 — APPROVED** [review]
**FR Passed**

Verified by building ti.barcode, ti.coremotion and the ACA module, the modules all built succesfully the titanium version needed to be updated on the ACA module and the ti.coremotion module.

**ENV**

```
macOS Mojave (10.14.1)
Appc NPM: 4.2.13
Appc CLI: 7.0.8
Ti CLI: 5.1.1
Node: 8.12.0
NPM: 6.4.1
```

**Pull request merged**
