### PR TITLE
[TIMOB-20116] [TIMOB-23134] Android: IndexOutOfBoundsException in ScrollableView removeView()

### PR DESCRIPTION
**Pull request by falkolab**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-20116, https://jira.appcelerator.org/browse/TIMOB-23134

### CODE REVIEW

**Comment by hansemannn** [comment]
Can you check your Atom editor settings before? It produces white spaces. Thanks!

**Comment by falkolab** [comment]
Where you find it? Studio produces tabs in blank lines and trailing spaces but not Atom.

**Comment by falkolab** [comment]
This is white spaces specs http://www.oracle.com/technetwork/java/javase/documentation/codeconventions-141388.html#475
What wrong with my PR?

**Comment by m1ga** [comment]
@falkolab about the whitespace problem: https://discuss.atom.io/t/atom-changes-lines-that-i-havent-touched-so-git-finds-changes-that-arent-really-changes/11224 

e.g. line 47 has no code change but it shows a diff.

**Comment by falkolab** [comment]
I added whitespaces but don't know what are they needed for and I can't find any specifications about. =)

**Comment by hansemannn** [comment]
It's fine for now, thank you @falkolab!

**Comment by ashcoding** [comment]
Code reviewed and functionally tested with https://jira.appcelerator.org/browse/TIMOB-23134 and https://jira.appcelerator.org/browse/TIMOB-20116.
**Approved** Merging.

**Pull request merged**
