### PR TITLE
feat(ios): update ti.coremotion to 2.1.0

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/MOD-2544

### CODE REVIEW

**Review by sgtcoolguy — APPROVED** [review]

**Comment by sgtcoolguy** [comment]
@mukherjee2 We should consider rolling this and #11244 into 9.0.0 (basically any core modules that have new versions should ship in 9.0.0 if we can)

**Comment by sgtcoolguy** [comment]
Relates to #11390

**Comment by ssekhri** [comment]
FR passed.

**Comment by vijaysingh-axway** [comment]
Closing in favor of PR #11502

**Pull request closed without merging**
