### PR TITLE
fix(iOS)(9_0_X): Search Bar color property does not work with showCancel property in  iOS 10

### PR DESCRIPTION
**Pull request by vijaysingh-axway**
https://jira.appcelerator.org/browse/TIMOB-27820

### CODE REVIEW

**Review by janvennemann — APPROVED** [review]

**Review by ssjsamir — COMMENTED** [review]
@vijaysingh-axway I am unable to see the changes on iOS 13.4 (iphone 8 simulator) but with the master PR I am able to (https://github.com/appcelerator/titanium_mobile/pull/11572)

**Comment by vijaysingh-axway** [comment]
> @vijaysingh-axway I am unable to see the changes on iOS 13.4 (iphone 8 simulator) but with the master PR I am able to (#11572)

This change fix issue in iOS 10. DO you mean the behavior is not expected in iOS 13.4?

**Comment by vijaysingh-axway** [comment]
@ssjsamir  PR https://github.com/appcelerator/titanium_mobile/pull/11566 fixes the iOS 13 issue, which is not merged yet.

**Review by ssjsamir — APPROVED** [review]
**FR passed** Now that https://github.com/appcelerator/titanium_mobile/pull/11566 is merged. Tested using the following test case: 

```
var win = Ti.UI.createWindow({
backgroundColor: '#fff'
});
 
var searchBar = Ti.UI.createSearchBar({
color: 'red',
barColor: 'gray',
showCancel: 'true',
hintTextColor: 'red',
hintText: 'Enter Value',
height: 43,
top: 100
});
 
win.add(searchBar);
win.open();
```


**Environment**
```
MacOS Catalina: 10.15.5 Beta 
Xcode: 11.4
Java Version: 1.8.0_131
Android NDK: 21.1.6273396-beta2
Node.js: 10.16.3
""NPM":"5.0.0-1","CLI":"8.0.0-master.10""
iphone 8 Sim (10.3)
```

**Pull request merged**
