### PR TITLE
[TIMOB-26297] Android: Fix MD5-hashing for Android 9

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:**
- https://jira.appcelerator.org/browse/TIMOB-26297
- https://jira.appcelerator.org/browse/TIMOB-26376

---
**Hashing Test:**
1. Set up the "tiapp.xml" file to target API Level 28 as shown below.
2. Build and run the below "app.js" code on an Android P device.
3. Verify that the app launch successfully without crashing.
4. Verify in the log that MD5 is: `098f6bcd4621d373cade4e832627b4f6`
5. Verify in the log that SHA1 is: `a94a8fe5ccb19ba61c4c0873d391e987982fbbd3`
6. Verify in the log that SHA256 is: `9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08`
7. Repeat steps 2-6 on an Android 4.x device.

tiapp.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
	<android xmlns:android="http://schemas.android.com/apk/res/android">
		<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="28"/>
	</android>
</ti:app>
```

app.js
```javascript
var message = "test";
var md5Result = "MD5('" + message +"') = " + Ti.Utils.md5HexDigest(message);
var sha1Result = "SHA1('" + message +"') = " + Ti.Utils.sha1(message);
var sha256Result = "SHA256('" + message +"') = " + Ti.Utils.sha256(message);
Ti.API.info(md5Result);
Ti.API.info(sha1Result);
Ti.API.info(sha256Result);

var window = Ti.UI.createWindow();
window.add(Ti.UI.createLabel({
	text: md5Result,
	top: "25%",
}));
window.add(Ti.UI.createLabel({
	text: sha1Result,
	top: "50%",
}));
window.add(Ti.UI.createLabel({
	text: sha256Result,
	top: "75%",
}));
window.open();
```

---
**Image Download Test:**
1. Set up the "tiapp.xml" file to target API Level 28 as shown below.
2. Acquire an Android P device and ensure it has Internet access.
3. Build and run the below "app.js" code on the above Android device.
4. Verify that the app has successfully downloaded and displayed an image on startup.
5. Repeat steps 2-4 with an Android 4.x device.

tiapp.xml
```xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
	<android xmlns:android="http://schemas.android.com/apk/res/android">
		<uses-sdk android:minSdkVersion="16" android:targetSdkVersion="28"/>
	</android>
</ti:app>
```

app.js
```javascript
var window = Ti.UI.createWindow();
var imageView = Ti.UI.createImageView({
	image: "http://raw.githubusercontent.com/recurser/exif-orientation-examples/master/Portrait_1.jpg",
});
window.add(imageView);
window.open();
```

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS** 👍

**Comment by jquick-axway** [comment]
I've confirmed that this is only an issue when targeting API Level 28, which Titanium 7.3.0 does not support. When targeting API Level 27 (the default), I've confirmed that an Android P device will correctly load "res" images and the `Ti.Utils.md5HexDigest()` method works. So, Titanium apps are currently backward compatible on Android P.

**Comment by jquick-axway** [comment]
@garymathews, @hansemannn,

I'm thinking for Titanium 8.0.0, we should dump the "commons-codec.jar" (335 kb) and use the Java [MessageDigest](https://developer.android.com/reference/java/security/MessageDigest) class instead. The built-in Android class involves a bit more code, but we can wrap it with out own `TiDigestUtils` class equivalent. What do you think?

**Comment by hansemannn** [comment]
@jquick-axway Something is borked here. The tests keep failing although Jenkins in general is quite stable right now.

**Comment by jquick-axway** [comment]
@hansemannn, I'll double check the Android emulator settings with Alan. I suspect an emulator is putting the display/screen to sleep during the unit test, which would cause a unit test failure. (We might have a misconfigured Jenkins node.)

**Comment by jquick-axway** [comment]
Uh-oh. I've discovered a crash with this PR.

The `Ti.Utils.sha1()` method now crashes on Android 7.x and older OS versions, regardless of which API Level you are targeting. The SHA1 function will work on Android 8.0 if targeting API Level 28, but will crash on Android 8.0 if targeting API Level 27 or older. The MD5 and SHA256 functions work on all Android OS versions.
```javascript
var message = "test";
var window = Ti.UI.createWindow();
window.add(Ti.UI.createLabel({
	text: "MD5('" + message +"') = " + Ti.Utils.md5HexDigest(message),
	top: "25%",
}));
window.add(Ti.UI.createLabel({
	text: "SHA1('" + message +"') = " + Ti.Utils.sha1(message),
	top: "50%",
}));
window.add(Ti.UI.createLabel({
	text: "SHA256('" + message +"') = " + Ti.Utils.sha256(message),
	top: "75%",
}));
window.open();
```

The error output for the above is...
```
[ERROR] :  TiExceptionHandler: Error: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
[ERROR] :  TiExceptionHandler:     at /HashingTest.js:9:47
[ERROR] :  TiExceptionHandler:     at Module._runScript (ti:/module.js:613:9)
[ERROR] :  TiExceptionHandler:     at Module.load (ti:/module.js:105:7)
[ERROR] :  TiExceptionHandler:     at Module.loadJavascriptText (ti:/module.js:457:9)
[ERROR] :  TiExceptionHandler:     at Module.loadAsFile (ti:/module.js:512:15)
[ERROR] :  TiExceptionHandler:     at Module.loadAsFileOrDirectory (ti:/module.js:429:20)
[ERROR] :  TiExceptionHandler:     at Module.require (ti:/module.js:296:17)
[ERROR] :  TiExceptionHandler:     at require (ti:/module.js:570:15)
[ERROR] :  TiExceptionHandler:     at /app.js:43:1
[ERROR] :  TiExceptionHandler:     at Module._runScript (ti:/module.js:596:17)
[ERROR] :  TiExceptionHandler:
[ERROR] :  TiExceptionHandler:     org.apache.commons.codec.digest.DigestUtils.sha1Hex(DigestUtils.java:503)
[ERROR] :  TiExceptionHandler:     org.apache.commons.codec.digest.DigestUtils.shaHex(DigestUtils.java:824)
[ERROR] :  TiExceptionHandler:     ti.modules.titanium.utils.UtilsModule.sha1(UtilsModule.java:102)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Runtime.nativeRunModule(Native Method)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.runtime.v8.V8Runtime.doRunModule(V8Runtime.java:180)
[ERROR] :  TiExceptionHandler:     org.appcelerator.kroll.KrollRuntime.runModule(KrollRuntime.java:247)
[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiLaunchActivity.loadActivityScript(TiLaunchActivity.java:135)
[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiLaunchActivity.windowCreated(TiLaunchActivity.java:190)
[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiRootActivity.windowCreated(TiRootActivity.java:171)
[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiBaseActivity.onCreate(TiBaseActivity.java:675)
[ERROR] :  V8Exception: Exception occurred at /HashingTest.js:9: Uncaught Error: No static method encodeHexString([B)Ljava/lang/String; in class Lorg/apache/commons/codec/binary/Hex; or its super classes (declaration of 'org.apache.commons.codec.binary.Hex' appears in /system/framework/org.apache.http.legacy.boot.jar)
```

Apparently, this is a common problem (see link below) and the "theory" is that the Android OS loads its own older version of the core Apache JAR that supersedes the one we're including. It sounds like we have to work-around this using the same `encodeHex()` solution that @hansemannn used for MD5.
https://stackoverflow.com/questions/9126567/method-not-found-using-digestutils-in-android

**Comment by hansemannn** [comment]
@jquick-axway Thanks, no thats great! 🙏

**Comment by lokeshchdhry** [comment]
@jquick-axway , I do get the error below when I am testing this PR.

```
[ERROR] :  TiExceptionHandler: (main) [1,5000]
[ERROR] :  TiExceptionHandler:     dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:134)
[ERROR] :  TiExceptionHandler:     java.lang.ClassLoader.loadClass(ClassLoader.java:379)
[ERROR] :  TiExceptionHandler:     java.lang.ClassLoader.loadClass(ClassLoader.java:312)
[ERROR] :  TiExceptionHandler:     org.appcelerator.titanium.TiVerify.run(Unknown Source:47)
[ERROR] :  TiExceptionHandler:     java.util.TimerThread.mainLoop(Timer.java:562)
[ERROR] :  TiExceptionHandler:     java.util.TimerThread.run(Timer.java:512)
```
I do have modules in my app.

**Comment by jquick-axway** [comment]
Oh bummer. "ti.verify" is using the apache hashing functions too. I'll have to fix that.
Note that this will happen if you include a native module.

**Comment by jquick-axway** [comment]
Updated PR:
- Removed all Apache JARs.
- Replaced Apache hashing `DigestUtils` class with new `TiDigestUtils` class.
- Updated "titanium-verify.jar" by:
  * Also removed its Apache JARs. (Was causing version conflicts.)
  * Replaced deprecated Apache HTTP class usage with Android's `HttpUrlConnection`.
  * Added support for TLS 1.1 and higher.

@garymathews, can you review this please?

**Review by garymathews — APPROVED** [review]
CR: **PASS**

**Pull request merged**
