### PR TITLE
[TIMOB-24988] (6_2_X) Android: Add Ti.Network.Cookie isValid()

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24988

### CODE REVIEW

**Comment by sgtcoolguy** [comment]
@m1ga Thanks for the PR! I see that you added a manual test case into he JIRA ticket. It'd be great if we could add an automated unit test for this too!

Since we have no tests for Ti.Network.Cookie, the steps would be:
- Copy https://raw.githubusercontent.com/appcelerator/titanium-mobile-mocha-suite/master/Resources/app.js to `titanium_mobile/tests/Resources/app.js`
- Add a `require('./ti.network.cookie.test');` at line 50
- Copy an existing test file like https://raw.githubusercontent.com/appcelerator/titanium-mobile-mocha-suite/master/Resources/ti.network.httpclient.test.js into  `titanium_mobile/tests/Resources/ti.network.cookie.test.js`
- Modify line 10 to be `describe('Titanium.Network.Cookie', function () {`
- Remove all the tests except `apiName` one, update it to test the right string value.
- copy that and create an `#isValid` test that did what your manual test did:
```javascript
var cookie1 = Ti.Network.createCookie({
  domain: 'example.com',
  name: 'test_cookie',
  value: '12',
  path: '/'
});
 
var cookie2 = Ti.Network.createCookie({
  name: 'test_cookie',
  value: '12',
  path: '/'
});

should(cookie1.isValid()).be.true;
should(cookie2.isValid()).false;

```

**Comment by m1ga** [comment]
@sgtcoolguy do I make a PR agains titanium-mobile-mocha-suite at the end?

**Comment by hansemannn** [comment]
Tests merged! @m1ga Usually, you can also copy the test-files to `titanium_mobile/tests` to test locally. See [this chapter](https://github.com/appcelerator/titanium_mobile#unit-tests) of the readme. Removing `needtests` label.

**Comment by hansemannn** [comment]
Closing this one as #9262 includes the changes already.

**Pull request closed without merging**
