### PR TITLE
[TIMOB-24329] iOS: setting additional request header disallows POST form requests

### PR DESCRIPTION
**Pull request by chreck**
TiUiWebView: shouldStartLoadWithRequest - reset lastValidLoad earlier

Making a POST request including the additional headers does not notice the change of the navigationType.
And the second page load to the same url with POST information does not fire a 'load' event.

JIRA: https://jira.appcelerator.org/browse/TIMOB-24329

### CODE REVIEW

**Comment by hansemannn** [comment]
Hah, I was just working on it. My solution would be [this one here](https://github.com/appcelerator/titanium_mobile/compare/master...hansemannn:TIMOB-24329?expand=1).

**Comment by sgtcoolguy** [comment]
ok to test

**Comment by hansemannn** [comment]
It's fine to take yours, I like it! CR + FT *pass*, handling over to QE. Thanks @chreck!

**Review by hansemannn — APPROVED** [review]

**Comment by htbryant94** [comment]
**FR approved!** Ran an app with the provided demo code firstly with an affected 6.1.X build to confirm that the error is reproducible in my environment. Subsequently built the app with a 6.1.X build containing PR #8765 and was able to receive the expected behaviour. Tested with:
- iPhone 7 (10.2) Device & Simulator
- iPhone 6S (9.3) Simulator 
- iPhone 5S (9.3) Device

**Review by htbryant94 — APPROVED** [review]

**Pull request merged**
