### PR TITLE
[TIMOB-24148] iOS: Add note for CommonJS modules colliding with Ti namespaces

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24148

### CODE REVIEW

**Comment by cb1kenobi** [comment]
+1

**Comment by sgtcoolguy** [comment]
I'd tweak this a little bit. The wording seems to indicate that there was a failure and to always use the './' prefix.

What we want the user to know is that there is a clash between a native module with the given id and a JS file with the module id as it's base name - and that we're giving preference to the native module. If they intended to address the JS file, they should use the prefix to make it explicit.

**Comment by hansemannn** [comment]
> What we want the user to know is that there is a clash between a native module with the given id and a JS file with the module id as it's base name - and that we're giving preference to the native module. If they intended to address the JS file, they should use the prefix to make it explicit.

I have to confess that it's hard for me to find the correct wording on this. As the use-case only effects a very specific kind of local CommonJS modules with *no* sub-directories *and* clashing names with core-modules, the suggested `./` prefix would always make sense for that kind of file. 

> I'd also worry that even if they fix their usage but have a JS file whose base name matches a native module id they'll keep seeing this message - and we don't spell out for them that to avoid the message they need to effectively rename the js file 

Native modules won't have a JS file in the app like CommonJS modules have, so the won't collide. I can setup a separate test-case for that if you want

> (Which may be another reason why we'd want this at a WARNING level instead of ERROR)

Agree, I'll change it to `[WARN]`

**Comment by sgtcoolguy** [comment]
Merged manually by copying the changes and tweaking wording some (and bumping down to WARN).

**Pull request closed without merging**
