### PR TITLE
[6_1_X][TIMOB-24809] Android: HTTPClient - "onload" not dispatched.

### PR DESCRIPTION
**Pull request by ypbnv**
Backport of: https://github.com/appcelerator/titanium_mobile/pull/9139

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
CR: **PASS**
FT: **PASS**

**Comment by ypbnv** [comment]
@garymathews Would you take a look at the guarding change?

**Comment by ssjsamir** [comment]
**FR Passed:** Error is no longer shown when a request is finished. 

**Test Steps:**
+ Downloaded the SDK Build form this PR
+ Created a new Titanium project
+ Copied the the test case from description
+ Ran the application 
+ Pressed `Get Photos`
+ Saw the Response 
+ Pressed the `upload` button 
+ Error was not shown 

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

**Review by ssjsamir — APPROVED** [review]

**Review by garymathews — CHANGES_REQUESTED** [review]
CR: **FAIL**

**Review by garymathews — APPROVED** [review]
CR: **PASS**

👍

**Comment by ssjsamir** [comment]
FR Passed following the earlier steps. However I did change the requestbin link as the link had expired. 
```
var window = Ti.UI.createWindow();
var buttonUpload = Ti.UI.createButton({title:"Upload", top:50});
var buttonGetPhotos = Ti.UI.createButton({title:"Get Photos", top: 110});
var xhr = Titanium.Network.createHTTPClient({timeout:5000});
 
var tempF = Ti.Filesystem.getFile(Ti.Filesystem.resourcesDirectory,"simpleTest.png");
Ti.API.info(tempF);
 
buttonUpload.addEventListener('click', function (e) {
    xhr.open("POST","https://requestb.in/16ixvgy1");
 
    var data_to_send = {
        "file": tempF.read(),
    };
 
    xhr.onload = function () {(alert(this.responseText))};
    xhr.send(data_to_send);
});
 
buttonGetPhotos.addEventListener('click', function (e) {    
    xhr.open("POST","https://requestb.in/16ixvgy1");
 
    var params = {
            id:46
    };
 
    xhr.onload = function (e) {alert(this.responseText)};
    xhr.send(params);
});
 
window.add(buttonGetPhotos);
window.add(buttonUpload);
window.open();
```

**Test Steps:**
+ Downloaded the SDK Build form this PR
+ Created a new Titanium project
+ Copied the the test case from description
+ Ran the application 
+ Pressed `Get Photos`
+ Saw the Response 
+ Pressed the `upload` button 
+ Error was not shown 

**Test Environment**
Appcelerator Command-Line Interface, version 6.2.2
Google Nexus 6P (7.1.1)
Operating System Name: Mac OS X El Capitan
Operating System Version: 10.11.6
Node.js Version: 6.10.1
Xcode: 8.2
Appcelerator Studio: 4.9.0.201705251638

**Pull request merged**
