### PR TITLE
fix(ios): properly fire close event for iOS 13+ modal windows

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27332

### CODE REVIEW

**Comment by hansemannn** [comment]
It seems like this crashes with the test suite but I cannot access the logs. I thought that no  Xcode 11 guards are required since it's only a new delegate function which part of an existing delegate and won't be called on earlier versions, but it may does cause issues!

**Review by vijaysingh-axway — CHANGES_REQUESTED** [review]
@hansemannn It is crashing when opening and closing window multiple times. See PR https://github.com/appcelerator/titanium_mobile/pull/11057. In this PR, this issue is already fixed.

**Comment by hansemannn** [comment]
@vijaysingh-axway Is that really the same thing? Your PR is for configuring whether or not a modal window should be swipeable, this one is a bugfix for windows that don't trigger a `close` event, causing huge glitches in depending apps. I see you introduced a new flag for it, so if it works for this one as well, feel free to cherry-pick and integrate my changes into your PR.

**Comment by vijaysingh-axway** [comment]
> @vijaysingh-axway Is that really the same thing? Your PR is for configuring whether or not a modal window should be swipeable, this one is a bugfix for windows that don't trigger a `close` event, causing huge glitches in depending apps. I see you introduced a new flag for it, so if it works for this one as well, feel free to cherry-pick and integrate my changes into your PR.

@hansemannn  What I mean was, In my PR https://github.com/appcelerator/titanium_mobile/pull/11057, 'close' event handling for iOS 13+ modal windows is already there . I have verified your test case. So we do not need this PR. It would be great, if you can test at your end. Thanks!

**Comment by hansemannn** [comment]
I don't see how this solves my issue. I want the window to be swipeable and without any other code changes for backwards compatibility. Explicitly disallowing modal states is different I think. But I will test your changes!

**Comment by hansemannn** [comment]
Not required anymore.

**Pull request closed without merging**
