### PR TITLE
[TIMOB-23901] Undo changes for running on main thread

### PR DESCRIPTION
**Pull request by ashcoding**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23901

This PR aims to undo changes done by https://github.com/appcelerator/titanium_mobile/pull/7332 for https://jira.appcelerator.org/browse/TIMOB-19765.
Please do not merge yet. This PR is up for discussion first.

### CODE REVIEW

**Comment by ashcoding** [comment]
@sgtcoolguy and @garymathews Please take a look.

**Comment by sgtcoolguy** [comment]
@ashcoding Is there a reason we need to roll it all back to not even allow running on main thread? I would think we'd want to still allow using main thread and simply fix the bug that stems from the combination of analytics, being on the main thread, and restarting the app.

**Comment by garymathews** [comment]
- Fixed by https://github.com/appcelerator/titanium_mobile/pull/8411

**Comment by ashcoding** [comment]
Closing this PR.

**Pull request closed without merging**
