### PR TITLE
[TIMOB-19919] separates event and callback for onBackPressed

### PR DESCRIPTION
**Pull request by manumaticx**
Test code in ticket description: [AC-96](https://jira.appcelerator.org/browse/AC-96)

This allows you to listen to the back button event without influencing the default behavior. Therefor, a new property was added (`Ti.UI.Window.onBack`) which lets you define a callback that explicitly overrides _onBackPressed_.

The existing `androidback` event fires without impact on the behavior. This allows you to execute additional code.

### CODE REVIEW

**Comment by hieupham007** [comment]
Code reviewed and functionally tested. Looks good

**Comment by hansemannn** [comment]
Would be great to have the `since` tag inside the docs.

**Comment by ashcoding** [comment]
As mentioned in https://jira.appcelerator.org/browse/TIMOB-19919
 Will get this out of 5.4.0 (aka current Master) and get it merged back when we do 6.0.0. Will be reverting it right now.

**Comment by ashcoding** [comment]
Revert button not able to create PR automatically, will be required to manually create a PR to revert the changes.

**Comment by ashcoding** [comment]
PR: https://github.com/appcelerator/titanium_mobile/pull/7780

**Pull request merged**
