### PR TITLE
[TIMOB-12848] Android: Improve TiCameraActivity.takePicture()

### PR DESCRIPTION
**Pull request by garymathews**
- Improve error handling and prevent simultaneous `takePicture()` calls

###### TEST CASE
**Requires camera permission**
```XML
<uses-permission android:name="android.permission.CAMERA" />
```
- Press `OPEN CAMERA` to open the custom camera-overlay
- Press `TAKE PICTURE` to take a picture and display it
- Attempt to repeately tap `OPEN CAMERA` and `TAKE PICTURE` in quick-succession, the app should not crash
```Javascript
var win = Titanium.UI.createWindow({layout: 'vertical'}),
    openCamera = Ti.UI.createButton({title: 'OPEN CAMERA', width: Ti.UI.FILL, height: '40dp'}),
    preview = Ti.UI.createImageView({backgroundColor: 'red', height: Ti.UI.FILL, width: Ti.UI.FILL}),
    
    overlay = Ti.UI.createView({backgroundColor: 'blue', width: Ti.UI.FILL, height: Ti.UI.FILL}),
    takePicture = Ti.UI.createButton({title: 'TAKE PICTURE', width: Ti.UI.FILL, height: '40dp', top: '80dp'});

function showCamera() {
    if (Ti.Media.hasCameraPermissions()) {
        Ti.Media.showCamera({
            success: function(e) {
                preview.image = e.media;
                Ti.Media.hideCamera();
            },
            cancel: function() {
                Ti.API.info('canceled');
            },
            error: function(e) {
                Ti.API.info('error: ' + JSON.stringify(e, null, ' '));
            },
            overlay: overlay,
            autohide: false,
            mediaTypes: [Ti.Media.MEDIA_TYPE_PHOTO]
        });
    } else {
        Ti.Media.requestCameraPermissions(function(e) {
            if (e.success) {
                showCamera();
            }
        });
    }
}

takePicture.addEventListener('click', function() {
    Ti.Media.takePicture();
});
overlay.add(takePicture);

openCamera.addEventListener('click', function() {
    showCamera();
});

win.add(openCamera);
win.add(preview);

win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-12848)

### CODE REVIEW

**Review by antw12 — APPROVED** [review]
Looks good 👍 
CR PASS
FT PASS

**Comment by hansemannn** [comment]
@garymathews Do we have the requirements clearly documented? Never heard of `<activity android:name="ti.modules.titanium.media.TiCameraActivity"/>` over the last 6 years :P

**Comment by antw12** [comment]
When i ran it, it said as a requirement or the app fails to run and it then worked when i added it

**Comment by garymathews** [comment]
@antw12 @hansemannn The CLI adds this to the `AndroidManifest.xml` automatically when `showCamera` is defined ([reference](https://github.com/appcelerator/titanium_mobile/blob/master/android/cli/commands/_build.js#L3512))

I'm guessing @antw12 was testing in IntelliJ :)

**Comment by antw12** [comment]
You are correct, apologies for making changes to the test code

**Review by mukherjee2 — APPROVED** [review]
Node Version: 6.10.3
NPM Version: 3.10.10
Mac OS: 10.12.4
Appc CLI: 6.2.3
Appc CLI NPM: 4.2.9
Titanium SDK version: 6.2.0.v20170829115147
Appcelerator Studio, build: 4.9.1.201707200100
Xcode 8.3.2
Android OS 5.1.1, 7.1.2, 4.4.4, 6.0.1
Android phones: Galaxy S4, Pixel, HTC One X, Nexus, Nexus 5

I tried testing for the crash with the above phones and OS with the SDK above, which as the fix. I found no crashes while going through the sequence (and looping  manually): Open Camera, Take Picture, Review Picture. I tried about 50 times, and no crashes occurred. I was not able to test with a Galaxy S6, as the device is not available in our lab.

**Pull request merged**
