### PR TITLE
fix(ios): restore correct Ti.Platform.id value

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27175

**Optional Description:**
The UUID returned by `Ti.Platform.id` changes when migrating to SDK 8.0.0. This fixes the issues and will return the expected identifier again.

### CODE REVIEW

**Comment by vijaysingh-axway** [comment]
@janvennemann  Can you explain reason of the issue? Is string 'appcelerator' is replaced with app name in SDK < 8.0.0?

**Comment by janvennemann** [comment]
@vijaysingh-axway We will scrub our iOS source files to replace strings like `Titanium` or `appcelerator` in our build [here](https://github.com/appcelerator/titanium_mobile/blob/e677dbe127c86248f5d37a028d6a85a3c80a549d/iphone/cli/commands/_build.js#L4448). To prevent possible app store rejections i guess. In this case the key `com.appcelerator.uuid` was replaced to be `com.<app-name>.uuid`.

Now, since 8.0.0 the `TiUtils.m` is part of TitaniumKit, so it gets pre compiled and the build won't replace the key that is used to store the unique app id. And since the key changes when migrating from 7.x to 8.x, the id changes. Moving the relevant code back to a category outside of TitaniumKit solves this issue as the build can now properly replace the key again.

**Review by vijaysingh-axway — APPROVED** [review]
CR passed.

**Review by ssjsamir — APPROVED** [review]
FR Passed: Correct Ti.Platform.id value is now restored to meet 7.5.2.GA, tested with the steps mentioned in: https://jira.appcelerator.org/browse/TIMOB-27175. 

**Test Environment**
```
iPhone 7 (12.2 Sim)
APPC CLI: 7.0.12-70X.4
Operating System Name: Mac OS Mojave
Operating System Version: 10.14.2
Node.js Version: 8.11.3
Xcode 8.9.1

**Pull request merged**
