### PR TITLE
Add support for HMS "Huawei Kit" Android

### PR DESCRIPTION
**Pull request by AbdullahFaqeir**
**JIRA:** https://jira.appcelerator.org/browse/[TICKET]

Provide a clear PR title prefixed with `[TICKET]`

**Optional Description:**

### CODE REVIEW

**Comment by hansemannn** [comment]
This can be done with a few module hacks. I just open sourced my Huawei module, have fun: https://github.com/hansemannn/titanium-huawei-analytics

**Comment by m1ga** [comment]
@hansemannn Those hooks are very interesting, especially the `appBuildGradleContents` part :+1:

**Comment by hansemannn** [comment]
Thx! Unfortunately really hacky. But it does the job :)

**Comment by hansemannn** [comment]
Let's go with standalone modules here for a more modular ecosystem! :)

**Pull request closed without merging**
