### PR TITLE
[TIMOB-20066] Android: Add support for style in Titanium.Android.Notification

### PR DESCRIPTION
**Pull request by falkolab**
JIRA: https://jira.appcelerator.org/browse/TIMOB-20066

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi @falkolab, please update your fork branch to the latest master to resolve merge conflicts. Thank you!

**Comment by falkolab** [comment]
updated

**Comment by ashcoding** [comment]
Thanks for the update! Will get this planned to be reviewed.

**Comment by ashcoding** [comment]
Functionally tested this. Working well. :+1:

**Comment by ashcoding** [comment]
@falkolab would you have time to resolve the merge conflict?
Alternatively, I can cherry-pick your commit into another PR that would contain your commit and changes.

**Comment by falkolab** [comment]
not ready yet

**Comment by falkolab** [comment]
ready now

**Comment by ashcoding** [comment]
Code reviewed and functionally tested. Excellent PR!
:+1:

**Comment by ashcoding** [comment]
**Approved**

**Pull request merged**
