### PR TITLE
[TIMOB-24446] Allow replacing bundled Android Support Libraries

### PR DESCRIPTION
**Pull request by janvennemann**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24446

**Optional Description:**
This allows a user to replace our bundled Android Support Libraries with one of their own choosing, either from a module or from the project's `platform/android` folder.

This relies on #8792 and #9027, so only merge after those two PRs.

### CODE REVIEW

**Comment by hansemannn** [comment]
@janvennemann Please document this new feature in our wikis, so developer know how to replace libraries. Maybe even an own guide on how to do it and some background on what is done internally to select and merge the libraries.

**Comment by janvennemann** [comment]
@hansemannn i was planning on doing exactly that. I will add a whole new section to the Android Module Development Guide explaining the .aar handling, including the Support Library override.

**Review by garymathews — APPROVED** [review]
CR: **PASS**

👍

**Comment by janvennemann** [comment]
@garymathews i just updated this PR to also allow the design support library to be replaced because they are now part of our bundled support libraries as of #9027

**Comment by sgtcoolguy** [comment]
Relates to #9258

**Comment by hansemannn** [comment]
I think this PR or one related causes linting issues:
```
/Users/build/jenkins/workspace/sdk_titanium_mobile_PR-9556-SYYMULLJBPTOYKQ4LBGV23OAGC75PMAHFNU4OMUO5E5XUVZIED7Q/android/cli/commands/_build.js
  1636:9  warning  Blocks are nested too deeply (6)  max-depth

✖ 1 problem (0 errors, 1 warning)
```
cc @janvennemann

**Comment by acaland** [comment]
It seems that this receipt does not work with the 28.0.0.

I am trying to build a module that uses a third party library that depends on Android Support Library 28.0.0. It seems that the current TiSDK 8.2.0.GA comes with 27.1.1. I am trying to bundle all the Android Support Library 28.0.0 into my module as described in the documentation but I am experiencing resource conflicts with the .aar appcompat-v7:28.0.0 depend on:

`[ERROR] An error occurred during build after 6s 703ms
[ERROR] Conflicting Android Libraries with package name "android.support.graphics.drawable" detected:
[ERROR]   /Users/tcaland/projects/tinamirialmodules/2019/tinamirialfeagui/android/lib/animated-vector-drawable-28.0.0.aar (hash: e2d41c2a032145313f42ab38a2d9757c5d1ebc19, origin: Module)
[ERROR]   /Users/tcaland/projects/tinamirialmodules/2019/tinamirialfeagui/android/lib/support-vector-drawable-28.0.0.aar (hash: 80387886ef55af284d8253e52d321f93b3f923dd, origin: Module)
[ERROR]   
[ERROR] Please either select a version of these modules where the conflicting .aar file is the same or you can try removing the .aar file from one module's "lib" folder.`

Any other way to include 28.0.0 ?
I have also tried to install 8.3.x builds, but they still provide 27.1.1.

**Pull request merged**
