### PR TITLE
fix(android): fix TabbedBar Click loop

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-27779

Test code:

```javascript
var window = Ti.UI.createWindow();
var tabbedBar = Ti.UI.createTabbedBar();
tabbedBar.labels = ["One", "Two", "Three"];
tabbedBar.addEventListener("click", function() {
	console.log(new Date() + " tbrSortTLby Click event triggerred");
	tabbedBar.labels = ['Three', 'Four', 'Five'];
})
window.add(tabbedBar);
window.open();
```

No endless loop when changing the labels inside the click event

### CODE REVIEW

**Review by jquick-axway — APPROVED** [review]
CR: Pass

Thanks Michael!

**Review by ssjsamir — DISMISSED** [review]
@m1ga The application no longer hangs but using the test case included I am unable to select other tabs after the initial tab has been clicked. 

**Environment**
```
MacOS Catalina: 10.15.1 beta
Xcode: 11.3
Java Version: 1.8.0_131
Android NDK: 21.1.6273396-beta2
Node.js: 10.16.3
""NPM":"5.0.0-1","CLI":"8.0.0-master.10""
Pixel Xl 7.1.1 Sim
```

**Comment by m1ga** [comment]
@ssjsamir this is correct. It will always reset it when you set new labels. Didn't want to add functionality but when you want to select something in the 2nd label group it would be something like:
```
var window = Ti.UI.createWindow();
var tabbedBar = Ti.UI.createTabbedBar();
var secondVersion = false;
tabbedBar.labels = ["One", "Two", "Three"];
tabbedBar.addEventListener("click", function() {
	console.log(new Date() + " tbrSortTLby Click event triggerred");
	if (!secondVersion) {
		tabbedBar.labels = ['Three', 'Four', 'Five'];
	}
	secondVersion = true;
})
window.add(tabbedBar);
window.open();
```

**Comment by ssjsamir** [comment]
@m1ga In that Case LGTM 👍. But I guess their is a Parity issue between iOS and Android and will write up a ticket as on iOS it still allows me to click on other tabs.

**Review by ssjsamir — APPROVED** [review]

**Comment by m1ga** [comment]
> @m1ga In that Case LGTM +1. But I guess their is a Parity issue between iOS and Android and will write up a ticket as on iOS it still allows me to click on other tabs.

ah ok. I didn't look at the iOS part! Maybe it keeps the index, have to check. Feel free to send me a link to the new ticket

**Comment by ssjsamir** [comment]
@m1ga Here is the ticket I created to follow the parity issue https://jira.appcelerator.org/browse/TIMOB-27826

**Pull request merged**
