### PR TITLE
[TIMOB-26314] Android: Add versionCode to tiapp.xml

### PR DESCRIPTION
**Pull request by m1ga**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-26314

### CODE REVIEW

**Review by garymathews — APPROVED** [review]
LGTM

**Comment by cb1kenobi** [comment]
Why do we need this? We already compute this when we write the AndroidManifest.xml: https://github.com/appcelerator/titanium_mobile/blob/82748c2cedaac99f9386a551c8b59b09322eb615/android/cli/commands/_build.js#L3721.

**Comment by m1ga** [comment]
@cb1kenobi oh ok. Didn't see that part cause the other "variables" had placeholders. I'll remove that part but the versionCode is still nice to have in the default tiapp.xml

**Comment by cb1kenobi** [comment]
Sure, but we already have support for that via a custom android manifest section in the `tiapp.xml`:

```xml
<?xml version="1.0" encoding="UTF-8"?>
<ti:app xmlns:ti="http://ti.appcelerator.org">
    <android xmlns:android="http://schemas.android.com/apk/res/android">
        <manifest android:versionCode="2"/>
    </android>
</ti:app>
```

**Comment by m1ga** [comment]
yes, but it is not exposed in the default (template) tiapp.xml. You have to look up the parameter name if you don't know it. In this PR I just add it since it is a very default value you always need to change in every project

**Review by cb1kenobi — APPROVED** [review]
This is a welcome addition! Thanks for the contribution! **APPROVED**!!!

**Review by jquick-axway — APPROVED** [review]

**Comment by lokeshchdhry** [comment]
FR Passed.

`tiapp.xml` is now by default populated with `android:versionCode="1"`.

Studio Ver:     5.1.1.201809051655
SDK Ver:        7.5.0 local build
OS Ver:         10.13.5
Xcode Ver:      Xcode 9.4.1
Appc NPM:       4.2.13
Appc CLI:       7.0.6
Daemon Ver:     1.1.3
Ti CLI Ver:     5.1.1
Alloy Ver:      1.13.2
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       10.0.2
Devices:        ⇨ google Nexus 5 (Android 6.0.1)
                ⇨ google Nexus 6P (Android 8.1.0)

**Comment by garymathews** [comment]
Humm... adding `versionCode` seems to cause the tests to consistently fail?

**Comment by cb1kenobi** [comment]
I don't get why the tests are failing. This PR is just adding a `versionCode` to the project templates.

What's more confusing is Jenkins says that this PR's "changes" are in `TCPProxy.java`, not in the project template. Jenkins has some wires crossed.

**Comment by sgtcoolguy** [comment]
The last build failed because of the test that opens a Ti.Map in a TabGroup. That also failed on another PR. Seems to be an unrelated issue entirely, but looks to be an Android regression that has started recently. cc @garymathews

**Pull request merged**
