### PR TITLE
[TIMOB-24898] Allow background transparency when borderRadius is set

### PR DESCRIPTION
**Pull request by garymathews**
- Disable canvas hardware-acceleration when a view has a border and background transparency set

###### TEST CASE
- Label should be visible before and after clicking the view
```JS
var win = Ti.UI.createWindow({title: 'TIMOB-24898', backgroundColor: 'gray'}),
    view = Ti.UI.createView({
        width: 300, height: 300,
        backgroundColor: '#00202020',
        borderRadius: 6, borderWidth: 2,
        borderColor: 'red'
    }),
    lbl = Ti.UI.createLabel({text: 'VISIBLE', color: 'white'});

view.addEventListener('click', function() {
    if (view.backgroundColor.startsWith('#00')) {
        view.backgroundColor = '#AA202020';
    } else {
        view.backgroundColor = '#00202020';
    }
});

win.add(lbl);
win.add(view);
win.open();
```

[JIRA Ticket](https://jira.appcelerator.org/browse/TIMOB-24898)

### CODE REVIEW

**Comment by jquick-axway** [comment]
**Question:**
If a border radius triggers this issue, then why does the following not fix this issue?
https://github.com/appcelerator/titanium_mobile/commit/40ff1da59740e53baa8f2b154a2627fb2f267329

**Comment by garymathews** [comment]
@jquick-axway Yes it would, but not in the case of Jellybean and higher. There's so many edge cases for HW acceleration..

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
FR Passed.

1. Checked it with different values of `borderRadius` 
2. With `borderRadius` disabled.
3. With both `borderRadius` & `borderWidth`.

Studio Ver:     4.9.0.201705302345
SDK Ver:        6.1.1.GA
OS Ver:         10.12.3
Xcode Ver:      Xcode 8.3.3
Appc NPM:       4.2.9
Appc CLI:       6.2.2
Ti CLI Ver:     5.0.14
Alloy Ver:      1.9.11
Node Ver:       6.10.1
Java Ver:       1.8.0_101
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Pixel --- Android 7.1.1

**Pull request merged**
