### PR TITLE
fix(ios16): fix navigation items in tab group layout

### LINKED ISSUE #13529: iOS 16: Navigation bar not properly aligned in regards to safe area
When adding the view of a UITabBarController to the current view controller view, the navigation bar is layouted incorrectly, ignoring the safe area of the view. This is a regression in iOS 16 and is always reproducible. Looking for related issues, it seems like quite a few developers have this issue: https://developer.apple.com/forums/thread/708156?login=true#reply-to-this-question.

In Titanium, this means that the navigation items in a `Ti.UI.TabGroup` (title, left nav button, right nav button) are not padded correctly. 

Native discussion: https://developer.apple.com/forums/thread/708156

### Expected Behavior

The navigation bar items are placed within the safe area.

### Actual behavior

The navigation bar items are placed outside the safe area.

### Reproducible sample

```js
const window = Ti.UI.createWindow({
   title: 'Window 1',
   leftNavButton: Ti.UI.createButton({ title: 'Left Button' })
});

const tab = Ti.UI.createTab({
    window,
    title: 'Tab 1'
});

const tabGroup = Ti.UI.createTabGroup({
    tabs: [tab]
});

tabGroup.open();
```

### Steps to reproduce

1. Compile the app with Xcode 13.x
2. Observe the navigation bar layout
3. Compile the app with Xcode 14 Beta (iOS 16 Simulator)
4. Observe the navigation bar layout

### Platform

iOS

### SDK version you are using

11.1.0

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes #13529

After some weeks of discussion with Apple, this solution will solve the outstanding layout issues on iOS and improve the general tab group layout behavior (for older iOS versions as well).

Test Case:
```js
const rootWindow = Ti.UI.createWindow({ backgroundColor: 'green' });
const btn = Ti.UI.createButton({ title: 'Open Tab Group' });

btn.addEventListener('click', () => {
	let tabGroup;

	const window = Ti.UI.createWindow({
		title: 'Window 1',
		backgroundColor: 'white',
		leftNavButton: Ti.UI.createButton({ title: 'Left Button' })
	});

	const btn2 = Ti.UI.createButton({ title: 'Close Tab Group' });

	btn2.addEventListener('click', () => {
		tabGroup.close();
	});

	window.add(btn2);

	const tab = Ti.UI.createTab({
		window,
		title: 'Tab 1'
	});

	tabGroup = Ti.UI.createTabGroup({
		tabs: [ tab ]
	});

	tabGroup.open();
});

rootWindow.add(btn);
rootWindow.open();
```

### CODE REVIEW

**Comment by janvennemann** [comment]
@hansemannn I guess we need some handling now to remove the UITabController again when it will be closed?

**Comment by caspahouzer** [comment]
I just tried the example and the bug as [mentioned](https://developer.apple.com/forums/thread/708156) seems not to exist anymore

**Comment by hansemannn** [comment]
@caspahouzer Thanks for the test!
@janvennemann Good catch - will add and test that

**Comment by hansemannn** [comment]
- [x] Updated the closing-behavior with view controller containment
- [x] Updated the sample code to test the open / close flow

Example video:

https://user-images.githubusercontent.com/10667698/183645184-0c18f089-da95-4f4f-88a2-8810f7ead701.mp4

.

**Review by caspahouzer — APPROVED** [review]
Test passed

LGTM

@hansemannn do you agree?

**Review by janvennemann — APPROVED** [review]

**Comment by hansemannn** [comment]
All approved, thanks guys!

**Pull request merged**
