### PR TITLE
[TIMOB-20294] Resolve Xcode compiler warnings

### PR DESCRIPTION
**Pull request by hansemannn**
JIRA: https://jira.appcelerator.org/browse/TIMOB-20294

### CODE REVIEW

**Comment by sriks** [comment]
@hansemannn Its good to see the warnings are addressed!
I understand most of them has to do with proper casting. But can I get some test cases to make sure we did not miss any edge cases ?

**Comment by hansemannn** [comment]
@sriks Unfortunetely, we would need to track it back to the proxies that call the methods. I can setup tests today and provide them. Since it's 6.0.0 timeline anyway, we have enough time!

**Comment by sriks** [comment]
@hansemannn Will kitchensink serve for now ?

**Comment by hansemannn** [comment]
@sriks I write test cases today to exactly trigger all methods being used there. Although I'm pretty sure everything works, that's the most save way to test it.

**Comment by hansemannn** [comment]
The test cases can be found in the JIRA ticket.

**Pull request merged**
