### PR TITLE
[TIMOB-23543] TiAPI: require implementation uses incorrect __filename values

### PR DESCRIPTION
**Pull request by sgtcoolguy**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-23543

**Description:**
__filename should now be exposed as the "absolute" path to the resolved file. In our case we define "absolute" as really being relative to the internal Resources directory in the app, since that's the base of any paths that the end-user/developer deals with.

This PR modifies the existing require tests to validate the value of __filename and __dirname under a number of use cases. I did not add support for _-filename and __dirname in JSON files, and haven't investigated if that's supported in Node or not.

### CODE REVIEW

**Comment by ashcoding** [comment]
Managed to run all the tests. The tests for the 2 following tests didn't pass for me
```it('loads file under Titanium CommonJS module containing moduleid.js file')``` and
```it('should load a node module by id in node_modules folder living at same level as requirer')```
I do have a folder ```modules/commonjs.legacy.package/1.0.0/main.js``` although it refers to ```commonjs.legacy.package/main.js``` which I assume should be fine. But it fails for me.

**Comment by ashcoding** [comment]
What I'm doing right now is trying to follow https://wiki.appcelerator.org/display/pe/Automated+Unit+Tests

I cloned https://github.com/appcelerator/titanium-mobile-mocha-suite copied over https://github.com/appcelerator/titanium_mobile/tree/master/ti_mocha_tests and then the new tests you wrote at tests/Resources/ti.require.test.js

**Comment by sgtcoolguy** [comment]
@ashcoding I added a new command to make it easier to run the tests locally. You should be able to check out this PR and then do:
```
cd build
npm install
node scons.js clean build ios android
node scons.js test android
node scons.js test ios
```

That would generate an SDK zip build for ios and android and then run the tests for each platform separately - though the PR build is doing exactly that anyways (and the tests are passing: https://jenkins.appcelerator.org/job/titanium_mobile_prs/291/ )

ti_mocha_tests is an old folder whose tests I need to fold into the common suite. It's unused for now and will be going away.

**Comment by sgtcoolguy** [comment]
I've updated that wiki page with the latest steps. This PR shows how to override/edit tests in a PR...

**Comment by ashcoding** [comment]
That test command is really handy 👍 
I tried and works like a charm.

Faced just this failed tests:-
```
requireJS
  ✓ should load a node module by id in node_modules folder living at same level as requirer 
  ✓ loads file under Titanium CommonJS module containing moduleid.js file 
  ✓ loads .json with matching file basename if no exact or .js match 
  1) loads .js with matching file basename if no exact match
    {"state":"failed","duration":0,"suite":"requireJS","title":"loads .js with matching file basename if no exact match","error":{"name":"AssertionError","actual":"with_index_js/index.js","expected":"/with_index_js/index.js","operator":"to equal","message":"expected 'with_index_js/index.js' to equal '/with_index_js/index.js'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  ✓ loads exact match JSON file 
  2) loads exact match JS file
    {"state":"failed","duration":2,"suite":"requireJS","title":"loads exact match JS file","error":{"name":"AssertionError","actual":"with_package/index.js","expected":"/with_package/index.js","operator":"to equal","message":"expected 'with_package/index.js' to equal '/with_package/index.js'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  ✓ falls back to index.json when requiring directory with no package.json or index.js 
  3) relative require() from sub directory
    {"state":"failed","duration":4,"suite":"requireJS","title":"relative require() from sub directory","error":{"name":"AssertionError","actual":"with_index_js/sub1.js","expected":"/with_index_js/sub1.js","operator":"to equal","message":"expected 'with_index_js/sub1.js' to equal '/with_index_js/sub1.js'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  4) falls back to index.js when requiring directory with no package.json
    {"state":"failed","duration":2,"suite":"requireJS","title":"falls back to index.js when requiring directory with no package.json","error":{"name":"AssertionError","actual":"with_index_js/index.js","expected":"/with_index_js/index.js","operator":"to equal","message":"expected 'with_index_js/index.js' to equal '/with_index_js/index.js'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  5) loads package.json main property when requiring directory
    {"state":"failed","duration":4,"suite":"requireJS","title":"loads package.json main property when requiring directory","error":{"name":"AssertionError","actual":"with_package/main.js","expected":"/with_package/main.js","operator":"to equal","message":"expected 'with_package/main.js' to equal '/with_package/main.js'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  6) requireJS.__dirname
    {"state":"failed","duration":5,"suite":"requireJS","title":"requireJS.__dirname","error":{"name":"AssertionError","actual":".","expected":"/","operator":"to equal","message":"expected '.' to equal '/'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  7) requireJS.__filename
    {"state":"failed","duration":2,"suite":"requireJS","title":"requireJS.__filename","error":{"name":"AssertionError","actual":"ti.require.test_test.js","expected":"/ti.require.test_test.js","operator":"to equal","message":"expected 'ti.require.test_test.js' to equal '/ti.require.test_test.js'","generatedMessage":true,"showDiff":true},"stdout":"","stderr":""}
  ✓ requireJS.PublicNullVar 
  ✓ requireJS.PublicBoolVar 
  ✓ requireJS.PublicNumVar 
  ✓ requireJS.PublicStrVar 
  ✓ requireJS.PublicFunc2 
  ✓ requireJS.PublicFunc1 
  ✓ requireJS.PublicFunc0 
  ✓ requireJS.LocalFunc 
  ✓ requireJS.ObjectCache 
  ✓ requireJS.NonObject 
  ✓ requireJS.Object 
  ✓ requireJS.Function 
```

But I believe this PR is okay and good to go as I've tested it manually. I'll try to see and figure out why I'm getting failures.

**Comment by ashcoding** [comment]
Although the tests seems to show difference in ```/``` in the path. What do you think?

**Comment by sgtcoolguy** [comment]
@ashcoding I get the feeling you're running tests on an older SDK zip (i.e. you didn't check out this PR and redo a cleanbuild). The tests are passing for me locally (just re-checked) and on the build agent...

The values you get look like the values we'd report pre-PR.

**Pull request merged**
