### PR TITLE
[TIMOB-25917] Android: Setting minDate/maxDate after creation doesn't work

### PR DESCRIPTION
**Pull request by ypbnv**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-25917

**Description:**
Fix `minDate` and `maxDate` properties for Android. Add unit tests for both platforms.

**Test case:**
```
var win = Ti.UI.createWindow(),
	dp = Ti.UI.createPicker({
		type: Ti.UI.PICKER_TYPE_DATE
	}),
	date = new Date(2018, 1, 1);

dp.setMinDate(date);
win.add(dp);
win.open();

```

Note: Yay, PR 10000!

### CODE REVIEW

**Comment by jquick-axway** [comment]
I just tested the below on iOS and we allow the min and max date to be set while the picker is being displayed onscreen...

```javascript
var window = Ti.UI.createWindow({ layout: "vertical" });
var picker = Ti.UI.createPicker({
	type: Ti.UI.PICKER_TYPE_DATE,
	top: "50dp",
});
window.add(picker);
var button = Ti.UI.createButton({ title: "Change Min/Max Date" });
button.addEventListener("click", function(e) {
	picker.minDate = new Date(2018, 1, 1);
	picker.maxDate = new Date(2018, 2, 1);
});
window.add(button);
window.open();
```

From looking at our Android code, I don't think the above will work with your changes either, right? It looks like we only read the min/max dates in the proxy's `handleShowDatePickerDialog()` method. Our `propertyChanged()` method doesn't check for these property changes after the fact.

Although we should double check if Android's native `DatePicker` actually supports min/max date changes at runtime too.

**Comment by ypbnv** [comment]
@jquick-axway I have missed that, thanks! Checked it on native Android - it is supported. I will add proper unit tests for that specific scenario once I finish the `postlayout` event fix.

**Review by jquick-axway — APPROVED** [review]
CR: Pass

**Comment by lokeshchdhry** [comment]
@ypbnv , When I run below code : 
```
var window = Ti.UI.createWindow({ layout: "vertical" });
var picker = Ti.UI.createPicker({
	type: Ti.UI.PICKER_TYPE_DATE,
	top: "50dp",
});
window.add(picker);
var button = Ti.UI.createButton({ title: "Change Min/Max Date" });
button.addEventListener("click", function(e) {
	picker.maxDate = new Date(2018, 2, 1);
});
window.add(button);
window.open();
```
The max date gets set to Mar 01 2018.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.2.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.13-2
Appc CLI:       7.0.3-master.39
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_131
Devices:        ⇨ google Nexus 5 --- Android 6.0.1
                ⇨ google Nexus 6P --- Android 8.0.0

**Comment by jquick-axway** [comment]
@lokeshchdhry, the JavaScript `Date` object's month field is zero based. So, a value of `2` should be March. (This is just to be extra clear about it.)
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Date

**Comment by lokeshchdhry** [comment]
@jquick-axway, Thanks !!

**Comment by lokeshchdhry** [comment]
FR Passed.

`minDate/maxDate` can be set after creation successfully.

Studio Ver:     5.0.0.201712081732
SDK Ver:        7.2.0 local build
OS Ver:         10.13.4
Xcode Ver:      Xcode 9.3
Appc NPM:       4.2.13-2
Appc CLI:       7.0.3-master.41
Daemon Ver:     1.1.1
Ti CLI Ver:     5.1.0
Alloy Ver:      1.12.0
Node Ver:       8.9.1
NPM Ver:        5.5.1
Java Ver:       1.8.0_131
Devices:        ⇨ google Nexus 6P --- Android 8.0.0
                ⇨ google Nexus 5 --- Android 6.0.1

**Pull request merged**
