### PR TITLE
[TIMOB-15424] iOS: adds support for pageIndicatorTintColor and currentPageInd...

### PR DESCRIPTION
**Pull request by manumaticx**
...icatorTintColor to ScrollableView

The credits for this code goes entirely to Samuele Coppede: https://github.com/boardmain/TitaniumMods

### CODE REVIEW

**Comment by hansemannn** [comment]
Hi @manumaticx, we'd welcome to get this merged. Can you please do the following things before:
- Resolve the merge conflicts with the latest master
- Ensure that the (new) default values for the colors don't break existing app designs.
- Create a JIRA-ticket [here](jira.appcelerator.org)

Thanks!

**Comment by manumaticx** [comment]
@hansemannn isn't this existing ticket the right one?: https://jira.appcelerator.org/browse/TIMOB-15424

**Comment by hansemannn** [comment]
Oh sure, didn't see in the first place. The docs need the `since: "6.0.0"` in it and for some reason travis CI failed a few months ago. Will retrigger it after the doc updates. Did  you ensure that the (new) default values for the colors don't break existing app designs?

**Comment by manumaticx** [comment]
Not yet. I'll update this PR asap after testing default colors.

**Comment by manumaticx** [comment]
@hansemannn That color issue was indeed a good pointer because gray is not the default color but a semi-transparent white (which looks gray on the default black background).
simulator screen shot 28 01 2016 14 27 03
_(for reference: this is how the paging control should look like on blue background)_

I've updated this PR with resolved conflicts and added the since property to the docs.

**Comment by hansemannn** [comment]
I thought more of nil'ing the value so iOS uses its own default values. Especially instead of creating an alpha channel manually.

**Comment by manumaticx** [comment]
Okay, I have to admit that I'm neither an iOS developer nor the author of that fix. I just took Samuels patch and created the PR since nobody else did. Because this solutions has worked for me since Titanium 3.0.2.GA and many Ti users used it too. 

However, we might should just close this, hoping @boardmain comes up with his own pull request ;)

**Comment by hansemannn** [comment]
All good! I'll take your PR and modify it in another commit to credit your work. Thank you!

**Comment by manumaticx** [comment]
I was hoping you'd say that! :) (I'm busy with other stuff atm) - Thanks! (and don't miss: credits goes to Samuele Coppede)

**Comment by hansemannn** [comment]
Hey there! Finally found the time to finish the PR (https://github.com/appcelerator/titanium_mobile/pull/7888). I did the following changes:
- Rename `pageIndicatorTintColor` to `pageIndicatorColor`
- Rename `currentPageIndicatorTintColor` to `currentPageIndicatorColor`
- Change default values to nil (which makes iOS to use the system-default - futureproof)
- Change the `since` key from 6.0.0 to 5.4.0

That's it. Thank you!

**Pull request closed without merging**
