### PR TITLE
[TIMOB-24288] iOS/Android: Deprecate "onStopBlacklistedUrl" WebView event in favor of cross-platform "blacklisturl" event

### PR DESCRIPTION
**Pull request by hansemannn**
**JIRA:** https://jira.appcelerator.org/browse/TIMOB-24288

### CODE REVIEW

**Review by vijaysingh-axway — COMMENTED** [review]
```
 +    since: 5.4.0
 +    properties:
 +      - name: url
 +        summary: The URL of the web document that is stopped.
 +    deprecated:
 +        since: "6.1.0"
 +        notes: Use the  cross-platform `blacklist` event instead.
```
'blacklist' should be 'blacklisturl' .

**Comment by hansemannn** [comment]
Good catch! Updated.

**Comment by garymathews** [comment]
LGTM 👍

**Comment by hansemannn** [comment]
@htbryant94 Ping!

**Comment by lokeshchdhry** [comment]
FR passed.
Works as expected on both android & IOS. The `blacklisturl` event is fired successfully when a url is blocked.

Appc Studio : 4.8.1.201612050850
SDK Version : Locally built 6.0.1
Mac OS Version : 10.12.2
Xcode Version : Xcode 8.2.1 Build version 8C1002
Appc CLI AND Appc NPM : {"NPM":"4.2.9-1","CLI":"6.1.0"}
Ti CLI : 5.0.11
Alloy : 1.9.5
Node : v4.6.0
Nexus 6 running 6.0.1

**Pull request merged**
