### PR TITLE
[TIMOB-16432] iOS: Fix missing bindId in itemclick event with active search

### PR DESCRIPTION
**Pull request by bduyng**
JIRA: https://jira.appcelerator.org/browse/TIMOB-16432

### CODE REVIEW

**Comment by hansemannn** [comment]
Functionality tested. Please fix the following issues:
- Indentation level (fix spaces with tabs to retain legacy code)
- Sign the CLA (Note: There are currently problems with the CLA server, so please try to run it using the private mode of your browser, e.g. CMD + Shift + N in Chrome) 
- Rename `indexPathInOrgTableView` to `realIndexPath` to match the rest of the code style

As we discussed this issue on Slack before, feel free to contact me there if you have further questions. Thank you!

**Comment by hansemannn** [comment]
CR + FT approved, will merge after the CLA server is back online. Thank you @bduyng, great work!

**Comment by bduyng** [comment]
thanks @hansemannn. the work can not be done without your help :)

**Comment by hansemannn** [comment]
CR + FT approved, thank you! :rocket:

**Pull request merged**
