### PR TITLE
fix(ios): fix layout issues and possible crash in Ti.UI.iPad.Popover API

### LINKED ISSUE #13915: Popover has glitch UI in iPadOS 17 and makes app freezing
### I have searched and made sure there are no existing issues for the issue I am filing

- [X] I have searched the existing issues

### Description

Popover has glitch UI in iOS 17 something like padding (top, bottom padding if arrow Up or down || left, right padding if arrow left  or right) and makes app freezing when trying to open and hide it repeatedly, you will think that's not right way to open and close it repeatedly but in real project i have a lot of buttons which open a popover so when click on one of it and close to open another that will show glitch UI or makes app freezing.

### For first time
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 35

### After closing and opening
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 26

### App freezing in opening popover
Simulator Screenshot - iPad Pro (12 9-inch) (6th generation) - 2023-09-20 at 23 29 05

### Reproducible sample

```
var popover;

const win = Ti.UI.createWindow();

const hidePopover = Ti.UI.createButton({
	title: 'Hide Popover',
	backgroundColor: 'orange',
	width: 160,
	height: 40
});
hidePopover.addEventListener("click", (e) => {
	popover.hide();
});

const showPopover = Ti.UI.createButton({
	title: "Show Popover",
	backgroundColor: 'red',
	width: 120,
	height: 40
});

showPopover.addEventListener("click", (e) => {
	const popoverWin = Ti.UI.createWindow({
		backgroundColor: 'red',
		title: 'Popover Window',
		rightNavButton: hidePopover
	});

	const listView = Ti.UI.createListView({
		backgroundColor: 'blue',
	});
	const sections = [];

	const fruitDataSet = [
		{ properties: { title: 'Apple' } },
		{ properties: { title: 'Banana' } },
	];
	const fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits', items: fruitDataSet });
	sections.push(fruitSection);

	const vegDataSet = [
		{ properties: { title: 'Carrots' } },
		{ properties: { title: 'Potatoes' } },
	];
	const vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables', items: vegDataSet });
	sections.push(vegSection);

	listView.sections = sections;

	popoverWin.add(listView);

	const fishDataSet = [
		{ properties: { title: 'Cod' } },
		{ properties: { title: 'Haddock' } },
	];
	const fishSection = Ti.UI.createListSection({ headerTitle: 'Fish', items: fishDataSet });
	listView.appendSection(fishSection);

	const popoverNav = Ti.UI.createNavigationWindow({
		window: popoverWin
	});

	popover = Ti.UI.iPad.createPopover({
		contentView: popoverNav
	});

	popover.show({ view: showPopover });
});

win.add(showPopover);

win.open();
```

### Steps to reproduce

1. create new classic app
2. add this sample code
3. click on showPopover button to show it
4. then click on hidePopover or outside the window
5. try to do this repeatedly

### Platform

iOS

### SDK version you are using

12.2.0

### Alloy version you are using

_No response_

### PR DESCRIPTION
**Pull request by hansemannn**
Fixes #13915 

Once approved to be working, I will do the 12_2_X backport.

### Sample 1

```js
var win = Ti.UI.createWindow({ backgroundColor: 'white' });
let popover;

var button = Ti.UI.createButton({ title: 'Open Popover!' });
button.addEventListener('click', function (e) {
	popover.show({ view: button });
});
win.add(button);

var rightButton = Ti.UI.createButton({ title: 'Robin' });
rightButton.addEventListener('click', function (e) {
	alert('But green\'s the color of spring.');
});

var contentWindow = Ti.UI.createWindow({
	rightNavButton: rightButton,
	title: 'Kermit'
});
contentWindow.add(Ti.UI.createLabel({ text: 'It\'s not easy being green.' }));

popover = Ti.UI.iPad.createPopover({
	backgroundColor: 'green',
	contentView: Ti.UI.createNavigationWindow({
		width: 250,
		height: 100,
		window: contentWindow
	})
});

win.open();
```

### Sample 2

```js
var popover;

const win = Ti.UI.createWindow();

const hidePopover = Ti.UI.createButton({
	title: 'Hide Popover',
	backgroundColor: 'orange',
	width: 160,
	height: 40
});
hidePopover.addEventListener("click", (e) => {
	popover.hide();
});

const showPopover = Ti.UI.createButton({
	title: "Show Popover",
	backgroundColor: 'red',
	width: 120,
	height: 40
});

showPopover.addEventListener("click", (e) => {
	const popoverWin = Ti.UI.createWindow({
		backgroundColor: 'red',
		title: 'Popover Window',
		rightNavButton: hidePopover
	});

	const listView = Ti.UI.createListView({
		backgroundColor: 'blue',
	});
	const sections = [];

	const fruitDataSet = [
		{ properties: { title: 'Apple' } },
		{ properties: { title: 'Banana' } },
	];
	const fruitSection = Ti.UI.createListSection({ headerTitle: 'Fruits', items: fruitDataSet });
	sections.push(fruitSection);

	const vegDataSet = [
		{ properties: { title: 'Carrots' } },
		{ properties: { title: 'Potatoes' } },
	];
	const vegSection = Ti.UI.createListSection({ headerTitle: 'Vegetables', items: vegDataSet });
	sections.push(vegSection);

	listView.sections = sections;

	popoverWin.add(listView);

	const fishDataSet = [
		{ properties: { title: 'Cod' } },
		{ properties: { title: 'Haddock' } },
	];
	const fishSection = Ti.UI.createListSection({ headerTitle: 'Fish', items: fishDataSet });
	listView.appendSection(fishSection);

	const popoverNav = Ti.UI.createNavigationWindow({
		window: popoverWin
	});

	popover = Ti.UI.iPad.createPopover({
		contentView: popoverNav
	});

	popover.show({ view: showPopover });
});

win.add(showPopover);

win.open();
```

### CODE REVIEW

**Comment by AhmedMSayed** [comment]
It works best than before, Glitches in UI is fixed but app still freezing when trying to hide & show popover repeatedly
Note: testing in simulators is works better than devices

**Comment by hansemannn** [comment]
Using the same sample code as shared?

**Comment by AhmedMSayed** [comment]
No i teated it with my project in production (iPadOS 17)
I sent video on slack thread please check it

**Comment by hansemannn** [comment]
Once you can send a reproducible snippet that this reproduces with this fix, I can continue debugging this

**Comment by taylor4502** [comment]
I've been testing this. Although the layout of the popover is much more consistent, it is not always correct. See code & attached screenshots. I got the different layouts by repeatedly opening and closing the popover.

I have also found that repeatedly opening and closing the popover can lead the app freezing, but this happens less frequently so is harder to produce. 

`
const win = Ti.UI.createWindow();

const textField = Ti.UI.createTextField({
	width: '90%',
	height: 40,
	top: 200,
	backgroundColor: 'red',
	editable: false
});

textField.addEventListener('click', () => {	

	const popover = buildPopover(textField);

	popover.show({
		view:textField,			
		animiated:false
	});

	

})

const buildPopover = () => {

	var popover =  Ti.UI.iPad.createPopover({
		height: Ti.UI.SIZE,
		//height: 600,
		backgroundColor: 'yellow',
	});



	var view = Ti.UI.createView({
		top:0,		// This doesn't seem to make any different to the layout or the consistency
		height: 600,
		width: 400,
		backgroundColor: 'red'
	});

	
	var selectButton = buildButton('Select');	
	selectButton.backgroundColor = 'green';
	selectButton.bottom = 30;
	selectButton.height = 60;

	var datePicker = Ti.UI.createPicker({
		//top:10,
		top:30,
		//bottom:300,
		width:400,
		height:200,
		selectionIndicator:true,		
		type: Ti.UI.PICKER_TYPE_DATE,
		datePickerStyle: Ti.UI.DATE_PICKER_STYLE_WHEELS,
	});

	for (var i = 0; i<=10; i++) {
		var line = Ti.UI.createView({
			height: i %2 == 0 ? 1 : 4,
			width: '100%',
			backgroundColor:'black',
			top:0 + (60*i),
			zIndex:999,
		});

		view.add(line);
	}

	var topview = Ti.UI.createView({
		top:30,
		height:60,
		backgroundColor:'green'
	});

	view.add(topview);
	

	//view.add(datePicker);	
	view.add(selectButton);	


	popover.contentView = view;

	
	return popover;
};

const buildButton = (title) => {
	
	var button = Ti.UI.createButton({
		title:title,
		height:50,
		width:150,
		bottom:10,		
	});	
	
	return button;
}


win.add(textField);

win.open()`

Screenshot 2023-09-25 at 16 15 27
Screenshot 2023-09-25 at 16 15 17

**Comment by AhmedMSayed** [comment]
I found when app freezing the hide method is called automatically and It stucks on this [line](https://github.com/tidev/titanium-sdk/blob/cdf7a673462a5aed72acf77f71c740c21f417d6b/iphone/Classes/TiUIiPadPopoverProxy.m#L208)

I think using NSCondition and dispatch_async leads the app to freezing sometimes

**Comment by AhmedMSayed** [comment]
Finally found the issue
This [line](https://github.com/tidev/titanium-sdk/blob/cdf7a673462a5aed72acf77f71c740c21f417d6b/iphone/Classes/TiUIiPadPopoverProxy.m#L182C31-L182C31) will force popover to hide if `currentlyDisplaying = YES`
That's fine but the real issue here is we didn't release the `popOverCondition` so it will be called in some cases 

The solution
- Adding `RELEASE_TO_NIL(popOverCondition);` in dealloc method
OR
- Removing `popOverCondition` because we already have `popoverInitialized` check [here](https://github.com/tidev/titanium-sdk/blob/cdf7a673462a5aed72acf77f71c740c21f417d6b/iphone/Classes/TiUIiPadPopoverProxy.m#L147C7-L147C25)

**Comment by AhmedMSayed** [comment]
BTW `currentPopover hide` not safe to call from NSCondition because it has NSCondition and dispatch_async inside it too (this is the freezing part)

**Comment by hansemannn** [comment]
Thanks for the feedback everyone! I can apply the patch over the weekend - alternatively, someone can do a PR that targets by branch (or cherry pick the existing fixes into it) if a sooner approach is needed.

**Comment by markive** [comment]
Thanks @hansemannn! I'll wait for the weekend update and test too.

**Comment by markive** [comment]
@hansemannn I can confirm that the layout issues are fixed with this PR, but the crashing is still possible if you quickly hide / create new popovers.

**Comment by AhmedMSayed** [comment]
@hansemannn  @markive @taylor4502 Please check this [PR](https://github.com/tidev/titanium-sdk/pull/13929)

**Comment by hansemannn** [comment]
Superseded by https://github.com/tidev/titanium-sdk/pull/13929

**Pull request closed without merging**
